//! Adversary cases for the rebinding of a settled output state (beyond10x/ess#306).
use super::{ownership, serial, Fixture};
use std::{fs, path::Path};

const OLD: &[(&str, &str)] = &[("same", "original"), ("retired/old", "withdrawn")];
const NEW: &[(&str, &str)] = &[("same", "replacement"), ("new/leaf", "introduced")];

fn copy_tree(from: &Path, to: &Path) {
    fs::create_dir(to).unwrap();
    for entry in fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let kind = entry.file_type().unwrap();
        assert!(!kind.is_symlink(), "{}", entry.path().display());
        let target = to.join(entry.file_name());
        if kind.is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), &target).unwrap();
        }
    }
    fs::set_permissions(to, fs::metadata(from).unwrap().permissions()).unwrap();
}

/// Copying `.ess-output` alone into a root whose files at the recorded owned paths are authored
/// is not an ownership transfer: adoption requires the exact generated bytes, and before ess#306
/// the binding refused the copied state outright. A rebind must not hand the copied ledger
/// authority over bytes it never recorded.
#[test]
fn a_state_copied_into_a_root_with_different_owned_bytes_does_not_replace_them() {
    let _serial = serial();
    let f = Fixture::new();
    let a = f.0.join("a");
    let b = f.0.join("b");
    ownership::probe::publish(&a, OLD, &mut |_| Ok(())).unwrap();
    fs::create_dir(&b).unwrap();
    fs::write(b.join("same"), "authored in b").unwrap();
    fs::create_dir(b.join("retired")).unwrap();
    fs::write(b.join("retired/old"), "also authored in b").unwrap();
    copy_tree(&a.join(".ess-output"), &b.join(".ess-output"));

    let result = ownership::probe::publish(&b, NEW, &mut |_| Ok(()));
    assert_eq!(
        fs::read_to_string(b.join("same")).unwrap(),
        "authored in b",
        "a copied ledger replaced an authored file it never recorded: {result:?}"
    );
    assert_eq!(
        fs::read_to_string(b.join("retired/old")).ok().as_deref(),
        Some("also authored in b"),
        "a copied ledger retired an authored file it never recorded: {result:?}"
    );
}

/// The non-Idle refusal tells the operator to run `recover --ownership-root <recorded>`. When the
/// checkout at that very path was replaced by a copy (a re-clone, a restore from backup, a
/// container that always mounts its source at one path), the named command must not fail with
/// the same refusal that named it.
#[test]
fn the_recovery_command_a_refusal_names_works_at_the_root_it_names() {
    let _serial = serial();
    let f = Fixture::new();
    let a = f.0.join("a");
    let copy = f.0.join("a.copy");
    ownership::probe::publish(&a, OLD, &mut |_| Ok(())).unwrap();
    let cut = ownership::probe::publish(&a, NEW, &mut |event| {
        if event == "after:rename:output-installation" {
            anyhow::bail!("cut at {event}")
        }
        Ok(())
    });
    assert!(cut.is_err());
    copy_tree(&a, &copy);
    fs::remove_dir_all(&a).unwrap();
    fs::rename(&copy, &a).unwrap();

    let refusal = format!(
        "{:#}",
        ownership::probe::publish(&a, NEW, &mut |_| Ok(())).unwrap_err()
    );
    let named = format!("--ownership-root {}", a.display());
    assert!(refusal.contains(&named), "{refusal}");
    // Coordinator decision (story:feature-request-306 correction 1): a transaction copied with
    // its root cannot be recovered at the same path, because its recorded inode identities are
    // gone. The refusal must not send the operator to `recover`, and `recover` must refuse
    // without deleting evidence.
    assert!(!refusal.contains("output recover"), "{refusal}");
    assert!(refusal.contains("output adopt"), "{refusal}");
    let before = tree(&a);
    let recovered = ownership::recover(&a);
    assert!(recovered.is_err(), "a copied transaction was recovered");
    assert_eq!(tree(&a), before, "a refused recovery deleted evidence");
}

fn tree(root: &std::path::Path) -> Vec<std::path::PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        for entry in fs::read_dir(&dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                stack.push(path.clone());
            }
            out.push(path);
        }
    }
    out.sort();
    out
}
