//! Deterministically project structural TypeScript declarations from JSON Schema.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::{Map, Value};

/// Why a JSON Schema cannot be projected without losing structural meaning.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum ProjectionError {
    /// The requested root type is not a TypeScript identifier.
    #[error("`{0}` is not a TypeScript type identifier")]
    InvalidRootName(String),
    /// The schema lacks the stable identity written into generated output.
    #[error("the schema must declare a non-empty absolute `$id`")]
    MissingSchemaId,
    /// A structural keyword is outside the deliberately small projection vocabulary.
    #[error("{pointer}: unsupported structural keyword `{keyword}`")]
    UnsupportedKeyword {
        /// JSON Pointer to the schema object carrying the keyword.
        pointer: String,
        /// The unsupported keyword.
        keyword: String,
    },
    /// A supported keyword has a shape this projection cannot interpret.
    #[error("{pointer}: {message}")]
    InvalidShape {
        /// JSON Pointer to the invalid value.
        pointer: String,
        /// The expected shape.
        message: String,
    },
    /// A `$ref` is not a local `$defs` reference.
    #[error("{pointer}: only local `#/$defs/...` references are projectable, found `{reference}`")]
    UnsupportedReference {
        /// JSON Pointer to the `$ref`.
        pointer: String,
        /// The reference that was refused.
        reference: String,
    },
    /// A local reference names no definition.
    #[error("{pointer}: `{reference}` names no definition")]
    UnknownReference {
        /// JSON Pointer to the `$ref`.
        pointer: String,
        /// The unresolved local reference.
        reference: String,
    },
    /// Two definition keys would produce the same TypeScript name.
    #[error("definitions `{first}` and `{second}` both project to `{projected}`")]
    NameCollision {
        /// The first JSON Schema definition name.
        first: String,
        /// The second JSON Schema definition name.
        second: String,
        /// Their colliding TypeScript name.
        projected: String,
    },
}

/// Projects one JSON Schema into a deterministic TypeScript module.
///
/// The output describes structural types only. JSON Schema remains authoritative for refinements
/// such as patterns, formats, numeric bounds and uniqueness, which TypeScript cannot enforce.
pub fn project(schema: &Value, root_name: &str) -> Result<String, ProjectionError> {
    if !typescript_type_identifier(root_name) {
        return Err(ProjectionError::InvalidRootName(root_name.to_owned()));
    }
    let identifier = schema
        .as_object()
        .and_then(|object| object.get("$id"))
        .and_then(Value::as_str)
        .filter(|value| absolute_identifier(value))
        .ok_or(ProjectionError::MissingSchemaId)?;
    let root = object(schema, "")?;
    let definitions = definitions(root)?;
    let names = definition_names(definitions, root_name)?;

    let mut output = format!(
        "// @generated by ESS schema-contract projection; do not edit.\n\
         // Source: {identifier}\n\
         // JSON Schema remains authoritative for runtime validation and refinements.\n\n"
    );
    for (key, definition) in definitions {
        let name = &names[key];
        let rendered = render_type(definition, &pointer("/$defs", key), 0, &names, root_name)?;
        writeln!(output, "export type {name} = {rendered};\n")
            .expect("writing to a String cannot fail");
    }
    let rendered = render_type(schema, "", 0, &names, root_name)?;
    writeln!(output, "export type {root_name} = {rendered};")
        .expect("writing to a String cannot fail");
    Ok(output)
}

fn render_type(
    schema: &Value,
    path: &str,
    depth: usize,
    names: &BTreeMap<String, String>,
    root_name: &str,
) -> Result<String, ProjectionError> {
    let object = object(schema, path)?;
    check_keywords(object, path)?;
    if let Some(reference) = object.get("$ref") {
        let reference = reference
            .as_str()
            .ok_or_else(|| invalid(path, "$ref must be a string"))?;
        return reference_type(reference, &pointer(path, "$ref"), names);
    }
    if let Some(value) = object.get("const") {
        return literal(value, &pointer(path, "const"));
    }
    if let Some(values) = object.get("enum") {
        let values = values
            .as_array()
            .filter(|values| !values.is_empty())
            .ok_or_else(|| invalid(&pointer(path, "enum"), "enum must be a non-empty array"))?;
        let mut variants = values
            .iter()
            .map(|value| literal(value, &pointer(path, "enum")))
            .collect::<Result<Vec<_>, _>>()?;
        variants.sort();
        variants.dedup();
        return Ok(variants.join(" | "));
    }

    let types = object
        .get("type")
        .ok_or_else(|| invalid(path, "expected one of `$ref`, `const`, `enum`, or `type`"))?;
    if let Some(types) = types.as_array() {
        let mut variants = types
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .ok_or_else(|| invalid(&pointer(path, "type"), "type entries must be strings"))
                    .and_then(|kind| render_kind(kind, object, path, depth, names, root_name))
            })
            .collect::<Result<Vec<_>, _>>()?;
        variants.sort();
        variants.dedup();
        return Ok(variants.join(" | "));
    }
    let kind = types.as_str().ok_or_else(|| {
        invalid(
            &pointer(path, "type"),
            "type must be a string or string array",
        )
    })?;
    render_kind(kind, object, path, depth, names, root_name)
}

fn render_kind(
    kind: &str,
    schema: &Map<String, Value>,
    path: &str,
    depth: usize,
    names: &BTreeMap<String, String>,
    root_name: &str,
) -> Result<String, ProjectionError> {
    match kind {
        "string" => Ok("string".to_owned()),
        "integer" | "number" => Ok("number".to_owned()),
        "boolean" => Ok("boolean".to_owned()),
        "null" => Ok("null".to_owned()),
        "array" => {
            // Reserve the global helper only where it is actually emitted. An alias named
            // Array remains valid in projections that do not use the helper.
            if root_name == "Array" || names.values().any(|name| name == "Array") {
                return Err(invalid(
                    path,
                    "a declaration shadows the required TypeScript `Array` helper",
                ));
            }
            let items = schema
                .get("items")
                .ok_or_else(|| invalid(path, "an array must declare `items`"))?;
            Ok(format!(
                "Array<{}>",
                render_type(items, &pointer(path, "items"), depth, names, root_name)?
            ))
        }
        "object" => render_object(schema, path, depth, names, root_name),
        other => Err(invalid(
            &pointer(path, "type"),
            format!("unsupported JSON Schema type `{other}`"),
        )),
    }
}

fn render_object(
    schema: &Map<String, Value>,
    path: &str,
    depth: usize,
    names: &BTreeMap<String, String>,
    root_name: &str,
) -> Result<String, ProjectionError> {
    if schema.get("additionalProperties") != Some(&Value::Bool(false)) {
        return Err(invalid(
            &pointer(path, "additionalProperties"),
            "projected objects must declare `additionalProperties: false`",
        ));
    }
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| {
            invalid(
                &pointer(path, "properties"),
                "object properties must be an object",
            )
        })?;
    let required = required(schema, path)?;
    let mut lines = Vec::new();
    for (name, property) in properties {
        let optional = if required.contains(name) { "" } else { "?" };
        let property_type = render_type(
            property,
            &pointer(&pointer(path, "properties"), name),
            depth + 1,
            names,
            root_name,
        )?;
        let property_name = if typescript_identifier(name) {
            name.clone()
        } else {
            serde_json::to_string(name).map_err(|error| invalid(path, error.to_string()))?
        };
        let indent = "  ".repeat(depth + 1);
        let continuation = "  ".repeat(depth + 1);
        let property_type = property_type.replace('\n', &format!("\n{continuation}"));
        lines.push(format!(
            "{indent}{property_name}{optional}: {property_type};"
        ));
    }
    let closing = "  ".repeat(depth);
    Ok(format!("{{\n{}\n{closing}}}", lines.join("\n")))
}

fn required(schema: &Map<String, Value>, path: &str) -> Result<BTreeSet<String>, ProjectionError> {
    schema.get("required").map_or_else(
        || Ok(BTreeSet::new()),
        |value| {
            value
                .as_array()
                .ok_or_else(|| invalid(&pointer(path, "required"), "required must be an array"))?
                .iter()
                .map(|entry| {
                    entry.as_str().map(ToOwned::to_owned).ok_or_else(|| {
                        invalid(
                            &pointer(path, "required"),
                            "required entries must be strings",
                        )
                    })
                })
                .collect()
        },
    )
}

fn definitions(root: &Map<String, Value>) -> Result<&Map<String, Value>, ProjectionError> {
    match root.get("$defs") {
        None => {
            static EMPTY: std::sync::OnceLock<Map<String, Value>> = std::sync::OnceLock::new();
            Ok(EMPTY.get_or_init(Map::new))
        }
        Some(value) => value
            .as_object()
            .ok_or_else(|| invalid("/$defs", "$defs must be an object")),
    }
}

fn definition_names(
    definitions: &Map<String, Value>,
    root_name: &str,
) -> Result<BTreeMap<String, String>, ProjectionError> {
    let mut names = BTreeMap::new();
    let mut reverse = BTreeMap::<String, String>::new();
    for key in definitions.keys() {
        let projected = pascal_case(key).ok_or_else(|| {
            invalid(
                &pointer("/$defs", key),
                "definition name cannot become a TypeScript identifier",
            )
        })?;
        if projected == root_name {
            return Err(invalid(
                &pointer("/$defs", key),
                format!("definition and root both project to `{root_name}`"),
            ));
        }
        if let Some(first) = reverse.insert(projected.clone(), key.clone()) {
            return Err(ProjectionError::NameCollision {
                first,
                second: key.clone(),
                projected,
            });
        }
        names.insert(key.clone(), projected);
    }
    Ok(names)
}

fn reference_type(
    reference: &str,
    path: &str,
    names: &BTreeMap<String, String>,
) -> Result<String, ProjectionError> {
    let Some(key) = reference.strip_prefix("#/$defs/") else {
        return Err(ProjectionError::UnsupportedReference {
            pointer: path.to_owned(),
            reference: reference.to_owned(),
        });
    };
    let key = key.replace("~1", "/").replace("~0", "~");
    names
        .get(&key)
        .cloned()
        .ok_or_else(|| ProjectionError::UnknownReference {
            pointer: path.to_owned(),
            reference: reference.to_owned(),
        })
}

fn check_keywords(object: &Map<String, Value>, path: &str) -> Result<(), ProjectionError> {
    const ALLOWED: &[&str] = &[
        "$comment",
        "$defs",
        "$id",
        "$ref",
        "$schema",
        "additionalProperties",
        "const",
        "default",
        "deprecated",
        "description",
        "enum",
        "examples",
        "exclusiveMaximum",
        "exclusiveMinimum",
        "format",
        "items",
        "maxItems",
        "maxLength",
        "maxProperties",
        "maximum",
        "minItems",
        "minLength",
        "minProperties",
        "minimum",
        "multipleOf",
        "pattern",
        "properties",
        "readOnly",
        "required",
        "title",
        "type",
        "uniqueItems",
        "writeOnly",
    ];
    for keyword in object.keys() {
        if !ALLOWED.contains(&keyword.as_str()) {
            return Err(ProjectionError::UnsupportedKeyword {
                pointer: path.to_owned(),
                keyword: keyword.clone(),
            });
        }
    }
    Ok(())
}

fn literal(value: &Value, path: &str) -> Result<String, ProjectionError> {
    match value {
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {
            serde_json::to_string(value).map_err(|error| invalid(path, error.to_string()))
        }
        Value::Array(_) | Value::Object(_) => Err(invalid(
            path,
            "only scalar const and enum values are projectable",
        )),
    }
}

fn object<'a>(value: &'a Value, path: &str) -> Result<&'a Map<String, Value>, ProjectionError> {
    value
        .as_object()
        .ok_or_else(|| invalid(path, "schema must be an object"))
}

fn invalid(pointer: &str, message: impl Into<String>) -> ProjectionError {
    ProjectionError::InvalidShape {
        pointer: if pointer.is_empty() {
            "/".to_owned()
        } else {
            pointer.to_owned()
        },
        message: message.into(),
    }
}

fn pointer(parent: &str, segment: &str) -> String {
    let escaped = segment.replace('~', "~0").replace('/', "~1");
    if parent.is_empty() {
        format!("/{escaped}")
    } else {
        format!("{parent}/{escaped}")
    }
}

fn typescript_identifier(value: &str) -> bool {
    let mut bytes = value.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    matches!(first, b'a'..=b'z' | b'A'..=b'Z' | b'_' | b'$')
        && bytes.all(|byte| matches!(byte, b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' | b'$'))
}

fn typescript_type_identifier(value: &str) -> bool {
    // Binding restrictions differ from property spelling: keywords are valid object keys.
    // These words cannot name an exported type alias in the supported TypeScript target.
    const RESERVED: &[&str] = &[
        "break",
        "case",
        "catch",
        "class",
        "const",
        "continue",
        "debugger",
        "default",
        "delete",
        "do",
        "else",
        "enum",
        "export",
        "extends",
        "false",
        "finally",
        "for",
        "function",
        "if",
        "import",
        "in",
        "instanceof",
        "new",
        "null",
        "return",
        "super",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "var",
        "void",
        "while",
        "with",
        "any",
        "unknown",
        "never",
        "number",
        "bigint",
        "boolean",
        "string",
        "symbol",
        "object",
        "undefined",
        "as",
        "implements",
        "interface",
        "let",
        "package",
        "private",
        "protected",
        "public",
        "static",
        "yield",
        "await",
    ];
    typescript_identifier(value) && !RESERVED.contains(&value)
}

fn pascal_case(value: &str) -> Option<String> {
    let mut output = String::new();
    for word in value.split(|character: char| !character.is_ascii_alphanumeric()) {
        if word.is_empty() {
            continue;
        }
        let mut characters = word.chars();
        output.extend(characters.next()?.to_uppercase());
        output.extend(characters);
    }
    typescript_identifier(&output).then_some(output)
}

fn absolute_identifier(value: &str) -> bool {
    let Some((scheme, rest)) = value.split_once(':') else {
        return false;
    };
    !rest.is_empty()
        && scheme.bytes().enumerate().all(|(index, byte)| {
            matches!(
                (index, byte),
                (0, b'a'..=b'z' | b'A'..=b'Z')
                    | (_, b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'+' | b'-' | b'.')
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn schema() -> Value {
        json!({
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "urn:example:registry:1",
            "type": "object",
            "required": ["schema", "items"],
            "properties": {
                "schema": {"const": "urn:example:registry:1"},
                "items": {"type": "array", "items": {"$ref": "#/$defs/item"}},
                "optional-label": {"type": ["string", "null"], "minLength": 1}
            },
            "additionalProperties": false,
            "$defs": {
                "item": {
                    "type": "object",
                    "required": ["id", "state"],
                    "properties": {
                        "id": {"type": "integer", "minimum": 1},
                        "state": {"enum": ["draft", "active"]},
                        "enabled": {"type": "boolean"}
                    },
                    "additionalProperties": false
                }
            }
        })
    }

    #[test]
    fn projects_the_supported_structural_vocabulary() {
        let output = project(&schema(), "Registry").expect("the schema is projectable");
        assert!(output.contains("export type Item = {"), "{output}");
        assert!(output.contains("id: number;"), "{output}");
        assert!(
            output.contains("state: \"active\" | \"draft\";"),
            "{output}"
        );
        assert!(output.contains("enabled?: boolean;"), "{output}");
        assert!(output.contains("items: Array<Item>;"), "{output}");
        assert!(
            output.contains("\"optional-label\"?: null | string;"),
            "{output}"
        );
        assert!(output.ends_with('\n'));
    }

    #[test]
    fn projection_is_deterministic_across_property_insertion_order() {
        let first = schema();
        let mut second = schema();
        let properties = second["properties"].as_object_mut().expect("properties");
        let schema_property = properties.remove("schema").expect("schema property");
        properties.insert("schema".to_owned(), schema_property);
        assert_eq!(
            project(&first, "Registry").expect("projectable"),
            project(&second, "Registry").expect("projectable")
        );
    }

    #[test]
    fn validation_refinements_do_not_become_a_second_runtime_contract() {
        let mut refined = schema();
        refined["properties"]["optional-label"]["format"] = json!("email");
        refined["properties"]["items"]["minItems"] = json!(1);
        let output = project(&refined, "Registry").expect("refinements stay in JSON Schema");
        assert!(
            output.contains("optional-label\"?: null | string"),
            "{output}"
        );
    }

    #[test]
    fn an_unsupported_structural_keyword_is_refused_at_its_pointer() {
        let mut conditional = schema();
        conditional["if"] = json!({"properties": {"schema": {"const": "x"}}});
        let error = project(&conditional, "Registry").expect_err("if changes shape semantics");
        assert!(
            error
                .to_string()
                .contains("unsupported structural keyword `if`"),
            "{error}"
        );
    }

    #[test]
    fn an_external_reference_is_refused_instead_of_becoming_unknown() {
        let mut external = schema();
        external["properties"]["items"]["items"] =
            json!({"$ref": "https://schemas.example.test/item.json"});
        let error = project(&external, "Registry").expect_err("external refs are not projected");
        assert!(error.to_string().contains("only local"), "{error}");
    }

    #[test]
    fn root_and_normalized_definitions_cannot_claim_the_same_binding() {
        for (key, root) in [
            ("item", "Item"),
            ("foo-bar", "FooBar"),
            ("foo_bar", "FooBar"),
            ("foo/bar", "FooBar"),
        ] {
            let reference = format!("#/$defs/{}", key.replace('/', "~1"));
            let source = json!({
                "$id": "urn:example:collision:1", "$ref": reference,
                "$defs": {key: {"type": "string"}}
            });
            let before = source.clone();
            let first = project(&source, root).expect_err("root/definition collision must refuse");
            assert_eq!(project(&source, root).expect_err("repeat refusal"), first);
            assert_eq!(
                source, before,
                "target refusal must not rewrite schema authority"
            );
        }
    }

    #[test]
    fn normalized_definition_collisions_keep_the_existing_deterministic_refusal() {
        let source = json!({
            "$id": "urn:example:collision:1", "$ref": "#/$defs/foo-bar",
            "$defs": {"foo_bar": {"type": "number"}, "foo-bar": {"type": "string"}}
        });
        assert_eq!(
            project(&source, "Root"),
            Err(ProjectionError::NameCollision {
                first: "foo-bar".to_owned(),
                second: "foo_bar".to_owned(),
                projected: "FooBar".to_owned()
            })
        );
    }

    #[test]
    fn reserved_words_and_primitive_type_aliases_are_refused() {
        let source = json!({"$id": "urn:example:names:1", "type": "string"});
        for name in [
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "new",
            "null",
            "return",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "any",
            "unknown",
            "never",
            "number",
            "bigint",
            "boolean",
            "string",
            "symbol",
            "object",
            "undefined",
        ] {
            assert_eq!(
                project(&source, name),
                Err(ProjectionError::InvalidRootName(name.to_owned())),
                "{name}"
            );
        }
    }

    #[test]
    fn emitted_array_helper_cannot_be_shadowed_by_root_or_definition() {
        for source in [
            json!({"$id": "urn:example:array:1", "type": "array", "items": {"type": "string"}}),
            json!({"$id": "urn:example:array:1", "type": "object", "additionalProperties": false,
                "properties": {"nested": {"type": "array", "items": {"type": "string"}}}}),
        ] {
            project(&source, "Array").expect_err("root must not shadow emitted Array helper");
            let mut with_definition = source;
            with_definition["$defs"] = json!({"array": {"type": "string"}});
            project(&with_definition, "Root")
                .expect_err("definition must not shadow emitted Array helper");
        }
    }

    #[test]
    fn module_reserved_aliases_are_refused() {
        let source = json!({"$id": "urn:example:names:1", "type": "string"});
        for name in [
            "as",
            "implements",
            "interface",
            "let",
            "package",
            "private",
            "protected",
            "public",
            "static",
            "yield",
            "await",
        ] {
            assert_eq!(
                project(&source, name),
                Err(ProjectionError::InvalidRootName(name.to_owned())),
                "{name}"
            );
        }
    }

    #[test]
    fn unused_array_name_and_keyword_properties_keep_their_valid_bytes() {
        let scalar = json!({"$id": "urn:example:names:1", "type": "string"});
        assert!(project(&scalar, "Array")
            .expect("unused helper name is valid")
            .ends_with("export type Array = string;\n"));
        let source = json!({"$id": "urn:example:names:1", "$ref": "#/$defs/array",
            "$defs": {"array": {"type": "string"}}});
        assert!(project(&source, "Root")
            .expect("Array definition without helper use")
            .ends_with("export type Root = Array;\n"));
        let source = json!({"$id": "urn:example:names:1", "type": "object", "additionalProperties": false,
            "properties": {"class": {"type": "string"}, "string": {"type": "string"},
                "Array": {"type": "string"}, "wire-key": {"type": "string"}},
            "examples": [{"type": "array"}]
        });
        let output =
            project(&source, "Array").expect("property and annotation words are not helper uses");
        assert!(output.ends_with("export type Array = {\n  Array?: string;\n  class?: string;\n  string?: string;\n  \"wire-key\"?: string;\n};\n"), "{output}");
    }

    #[test]
    fn noncolliding_projection_retains_the_complete_baseline_bytes() {
        assert_eq!(
            project(&schema(), "Registry").expect("noncollision control"),
            include_str!("../tests/fixtures/registry.ts")
        );
    }
}
