//! The generated React app bound to a served surface (beyond10x/ess#311, S2): with a binding from
//! `ess_ui_check::binding`, the project carries `src/binding.ts` and an `httpAdapter` that reads
//! and commands the paths the synthesized server answers, classifies every command answer with a
//! port of `ess_ui::binding::classify`, and shows a refusal on the form, confirm or action that
//! sent it. Without a binding the project is the plain one, byte for byte.
//!
//! Runtime cases compile the generated project to `CommonJS` with `tsc` and run it under `node`
//! against the stand-ins in `support`; the end-to-end case also builds it with esbuild and drives
//! it against the Rust gatepass server from `examples/gatepass-realization`.

mod support;

use std::io::BufRead as _;
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};

use ess_ui::binding::Binding;
use ess_ui::Document;
use ess_ui_react::GeneratedFiles;
use support::{compile, node, write};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..")
}

fn scratch(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join("ess-ui-react-live")
        .join(name);
    if dir.exists() {
        std::fs::remove_dir_all(&dir).expect("the old scratch project is removed");
    }
    dir
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|error| panic!("{}: {error}", path.display()))
}

/// A front desk over `examples/gatepass`: the expected list with an action, the registration
/// form, and a confirm.
const DESK: &str = "format: ess-ui/1
app: desk
model: gatepass
placement_profile: fat
shells: {app: {regions: {main: {kind: page_outlet}}}}
navigation: {home: desk, sections: [{name: all, pages: [desk]}]}
pages:
  desk:
    kind: detail_page
    title: Desk
    sections:
      - name: expected
        component: collection
        reads: visit.ExpectedVisits
        actions: [{name: admit, does: visit.AdmitVisitor, label: Admit}]
      - name: register
        component: form
        does: visit.RegisterVisit
        fields: [visitor, building, {field: expected_minutes, as: number}]
      - name: depart
        component: confirm
        does: visit.SignOutVisitor
        body: Sign the visitor out?
";

/// `examples/gatepass` as `(label, text)` sources, with `extra_views` appended to its one domain
/// (whose last key is `views:`).
fn gatepass_with(extra_views: &str) -> Vec<(String, String)> {
    let root = root().join("examples/gatepass");
    let mut visit = read(&root.join("domains/visit.yaml"));
    visit.push_str(extra_views);
    vec![
        ("system.yaml".to_owned(), read(&root.join("system.yaml"))),
        (
            "components.yaml".to_owned(),
            read(&root.join("components.yaml")),
        ),
        ("domains/visit.yaml".to_owned(), visit),
    ]
}

fn load(text: &str) -> Document {
    ess_ui::load_str(text).unwrap_or_else(|error| panic!("the document loads: {error}"))
}

fn bind(document: &Document, sources: &[(String, String)]) -> Binding {
    ess_ui_check::binding(document, sources)
        .unwrap_or_else(|error| panic!("the document binds: {error}"))
}

/// The desk, bound to gatepass, generated under `name`.
fn bound_desk(name: &str) -> (PathBuf, GeneratedFiles, Binding) {
    let document = load(DESK);
    let binding = bind(&document, &gatepass_with(""));
    let out = scratch(name);
    let files = ess_ui_react::generate_bound(&document, &root(), &out, Some(&binding))
        .unwrap_or_else(|error| panic!("{error}"));
    (out, files, binding)
}

fn file<'a>(files: &'a GeneratedFiles, path: &str) -> &'a str {
    files
        .files
        .get(path)
        .unwrap_or_else(|| panic!("`{path}` is generated; have {:?}", files.files.keys()))
}

/// FNV-1a, 64 bits: a digest of generated bytes that needs no dependency.
fn fnv(text: &str) -> u64 {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x0100_0000_01b3);
    }
    hash
}

/// The unbound desk after the consolidated UI fixes: confirm openers return their result and
/// run once, while the remaining live-binding template projections retain their plain bytes.
/// The whole-project digest also covers the shared expression, row and field fixes.
const PLAIN: [(&str, u64); 7] = [
    ("README.md", 0xdae6_c3b6_7e5c_2d28),
    ("src/main.tsx", 0x6fd5_ef21_0230_ebac),
    ("src/runtime/actions.tsx", 0x1440_0f25_3b4c_8e3b),
    ("src/runtime/composites/confirm.tsx", 0xbeef_774c_44b0_0be3),
    ("src/runtime/composites/form.tsx", 0x752b_3696_9db6_fbcc),
    ("src/runtime/data.ts", 0x27ef_3e5b_6f5b_b68c),
    ("www/index.html", 0x5972_6d4a_5ee2_5ce2),
];
const PLAIN_PROJECT: u64 = 0x6dae_633a_08fe_4f60;

#[test]
fn without_a_model_the_project_is_byte_identical() {
    let document = load(DESK);
    let plain = ess_ui_react::render(&document, &root()).unwrap_or_else(|error| panic!("{error}"));
    let unbound = ess_ui_react::render_bound(&document, &root(), None)
        .unwrap_or_else(|error| panic!("{error}"));
    assert_eq!(plain, unbound, "render is render_bound without a binding");
    for (path, digest) in PLAIN {
        assert_eq!(
            fnv(file(&plain, path)),
            digest,
            "{path} differs from the consolidated unbound projection:\n{}",
            file(&plain, path)
        );
    }
    let mut whole = String::new();
    for (path, text) in &plain.files {
        whole.push_str(path);
        whole.push('\0');
        whole.push_str(text);
        whole.push('\0');
    }
    assert_eq!(
        fnv(&whole),
        PLAIN_PROJECT,
        "the project differs from the consolidated unbound projection: {:?}",
        plain.files.keys()
    );
    for absent in ["src/binding.ts", "src/runtime/answer.ts"] {
        assert!(!plain.files.contains_key(absent), "{absent} is generated");
    }
}

#[test]
fn binding_ts_holds_the_served_paths_and_query_wire_names() {
    // A view whose parameter is carried under another query key than its name.
    let sources = gatepass_with(
        "\n  - name: gatepass.visit.InBuilding\n    source: gatepass.visit.Visit\n    \
         consistency: eventual\n    params:\n      - name: building\n        type: \
         gatepass.visit.Building\n        naming: {wire: site}\n    filter: building == \
         param.building\n    fields:\n      - name: visit_id\n        type: \
         gatepass.visit.VisitId\n",
    );
    let text = DESK.replace(
        "      - name: register\n",
        "      - name: here\n        component: collection\n        \
         reads: {view: visit.InBuilding, params: {building: \"'North'\"}}\n      \
         - name: register\n",
    );
    let document = load(&text);
    let binding = bind(&document, &sources);
    let files = ess_ui_react::render_bound(&document, &root(), Some(&binding))
        .unwrap_or_else(|error| panic!("{error}"));
    let ts = file(&files, "src/binding.ts");
    for wanted in [
        "\"/visits/views/expected\"",
        "\"/visits/commands/register-visit\"",
        "\"/visits/commands/admit-visitor\"",
        "\"/visits/commands/sign-out-visitor\"",
        "\"wire\": \"site\"",
        "\"visit.RegisterVisit\": \"gatepass.visit.RegisterVisit\"",
    ] {
        assert!(ts.contains(wanted), "binding.ts lacks {wanted}:\n{ts}");
    }
    // The binding as data: the object literal is the binding's JSON, member for member.
    let literal = ts
        .split_once("export const binding: Binding = ")
        .and_then(|(_, rest)| rest.trim_end().strip_suffix(';'))
        .unwrap_or_else(|| panic!("binding.ts exports no binding literal:\n{ts}"));
    let parsed: serde_json::Value =
        serde_json::from_str(literal).unwrap_or_else(|error| panic!("{error}:\n{literal}"));
    assert_eq!(
        parsed,
        serde_json::to_value(&binding).expect("the binding serialises")
    );
    // The adapter it drives, switched on before the app renders, and a base URL per component.
    let main = file(&files, "src/main.tsx");
    assert!(
        main.contains("setDataAdapter(httpAdapter(binding));"),
        "{main}"
    );
    let html = file(&files, "www/index.html");
    assert!(
        html.contains("<meta name=\"ess-base-url:pass-service\" content=\"\" />"),
        "{html}"
    );
    // Deterministic.
    let again = ess_ui_react::render_bound(&document, &root(), Some(&binding))
        .unwrap_or_else(|error| panic!("{error}"));
    assert_eq!(files, again);
}

#[test]
fn the_bound_project_type_checks_offline() {
    let (out, files, _) = bound_desk("typecheck");
    for path in [
        "src/binding.ts",
        "src/runtime/answer.ts",
        "src/runtime/data.ts",
        "src/main.tsx",
    ] {
        file(&files, path);
    }
    let output = Command::new("tsc")
        .args(["-p", "tsconfig.offline.json", "--noEmit"])
        .current_dir(&out)
        .output()
        .expect("tsc is on PATH");
    assert!(
        output.status.success(),
        "tsc --noEmit failed in {}:\n{}{}",
        out.display(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn the_typescript_classifier_agrees_with_every_answer_vector() {
    let (out, _, _) = bound_desk("classify");
    compile(&out, &["runtime/answer.ts"]);
    let vectors = root().join("crates/ui/ess-ui/tests/vectors/answers.json");
    let parsed: serde_json::Value =
        serde_json::from_str(&read(&vectors)).expect("answers.json parses");
    let count = parsed["vectors"].as_array().expect("vectors").len();
    assert!(count >= 12, "answers.json holds {count} vectors");
    node(
        &out,
        "classify",
        &format!(
            r#"
const {{ classify }} = out("runtime/answer");
const file = JSON.parse(require("fs").readFileSync({path}, "utf8"));
assert.strictEqual(file.format, "ess-ui-answers/1");
const wrong = [];
for (const vector of file.vectors) {{
  const answer = classify(vector.status, vector.body);
  try {{
    assert.deepStrictEqual(answer, vector.expected);
  }} catch (error) {{
    wrong.push(`${{vector.case}} (${{vector.source}}): ${{vector.status}} ${{vector.body}} -> ${{JSON.stringify(answer)}}, recorded ${{JSON.stringify(vector.expected)}}`);
  }}
}}
assert.deepStrictEqual(wrong, []);
assert.strictEqual(file.vectors.length, {count});
"#,
            path = serde_json::to_string(&vectors.display().to_string()).expect("a path"),
        ),
    );
}

/// Shared by the refusal cases: a stand-in `fetch` answering every `GET` with no rows and every
/// `POST` with `answer`, a stand-in page holding the base-URL meta tag, the adapter switched on
/// as `main.tsx` switches it, and helpers to settle the tree after the answer arrives.
const STAGE: &str = r#"
const { ScopeLayer } = out("runtime/core");
const { httpAdapter, setDataAdapter, setAuthorization, useRead } = out("runtime/data");
const { binding } = out("binding");
const sent = [];
let answer = { status: 500, body: "{}" };
globalThis.fetch = async (url, init) => {
  const method = (init && init.method) || "GET";
  sent.push({ url: String(url), method, headers: (init && init.headers) || {}, body: init && init.body });
  const reply = method === "GET" ? { status: 200, body: '{"rows":[]}' } : answer;
  return { status: reply.status, ok: reply.status < 300, statusText: "", text: async () => reply.body };
};
globalThis.document = {
  querySelector: (selector) =>
    selector === 'meta[name="ess-base-url:pass-service"]' ? { getAttribute: () => "http://desk.test" } : null,
};
setAuthorization("Actor gatepass.visit.Receptionist");
setDataAdapter(httpAdapter(binding));
const flush = async (root) => {
  for (let i = 0; i < 6; i += 1) {
    await new Promise((resolve) => setTimeout(resolve, 0));
    root.settle();
  }
};
const within = (node, predicate) => {
  const found = [];
  const visit = (nodes) => nodes.forEach((n) => {
    if (typeof n !== "object") return;
    if (predicate(n)) found.push(n);
    if (n.children) visit(n.children);
  });
  visit(node.children || []);
  return found;
};
const textOf = (node) => {
  const parts = [];
  const visit = (nodes) => nodes.forEach((n) => (typeof n === "string" ? parts.push(n) : n.children && visit(n.children)));
  visit(node.children || []);
  return parts.join(" ");
};
const posts = () => sent.filter((call) => call.method === "POST");
const reads = () => sent.filter((call) => call.method === "GET").length;
// A section reading the expected list, so a case can see whether reads were invalidated.
function Reader() {
  const read = useRead({ view: "visit.ExpectedVisits" }, {});
  return jsx("span", { "data-reader": read.status, children: read.status });
}
"#;

fn refusal_stage(name: &str) -> PathBuf {
    let (out, _, _) = bound_desk(name);
    compile(
        &out,
        &[
            "binding.ts",
            "runtime/composites/form.tsx",
            "runtime/composites/confirm.tsx",
            "runtime/actions.tsx",
        ],
    );
    out
}

#[test]
fn a_refused_command_renders_on_the_form_that_sent_it() {
    let out = refusal_stage("form");
    node(
        &out,
        "form",
        &format!(
            r#"{STAGE}
const {{ FormView }} = out("runtime/composites/form");
answer = {{ status: 422, body: '{{"outcome":"refused","published":[],"error":"gatepass.visit.InvalidVisitLength","payload":{{"submitted":0}}}}' }};
const initial = {{ visitor: "Ada", building: "North", expected_minutes: 0 }};
let draft = initial;
let closed = 0;
const notices = [];
function Host() {{
  const [value, setValue] = React.useState(initial);
  draft = value;
  return jsx(ScopeLayer, {{
    values: {{ draft: value }},
    setters: {{ draft: setValue }},
    actions: {{ close: () => {{ closed += 1; }}, notify: (message) => notices.push(message) }},
    children: [
      jsx(Reader, {{}}, "reader"),
      jsx(FormView, {{
        "data-ui-path": "pages/desk/sections/register",
        does: "visit.RegisterVisit",
        fields: [{{ "data-ui-path": "pages/desk/sections/register/fields/visitor", field: "visitor", name: "visitor" }}],
        groups: [{{
          "data-ui-path": "pages/desk/sections/register/groups/length",
          name: "length",
          save: "on_change",
          fields: [{{ "data-ui-path": "pages/desk/sections/register/groups/length/fields/expected_minutes", field: "expected_minutes", name: "expected_minutes", as: "number" }}],
        }}],
      }}, "form"),
    ],
  }});
}}
(async () => {{
  const root = React.__root(jsx(Host, {{}})).settle();
  await flush(root);
  const before = reads();
  const form = () => root.find((n) => n.tag === "form")[0];
  assert.strictEqual(within(form(), (n) => n.props && n.props["data-ui-refusal"] !== undefined).length, 0, "no refusal before sending");
  form().props.onSubmit({{ preventDefault() {{}} }});
  await flush(root);
  // Sent to the bound path, as the caller configured.
  assert.strictEqual(posts().length, 1);
  assert.strictEqual(posts()[0].url, "http://desk.test/visits/commands/register-visit");
  assert.strictEqual(posts()[0].headers.authorization, "Actor gatepass.visit.Receptionist");
  assert.deepStrictEqual(JSON.parse(posts()[0].body), initial);
  // Shown on the form: the error's display text and its payload.
  const shown = within(form(), (n) => n.props && n.props["data-ui-refusal"] !== undefined);
  assert.strictEqual(shown.length, 1, root.text());
  assert.strictEqual(shown[0].props["data-ui-refusal"], "refused");
  const text = textOf(shown[0]);
  assert.ok(text.includes("InvalidVisitLength"), text);
  assert.ok(text.includes("submitted"), text);
  assert.ok(text.includes("0"), text);
  // The draft is kept, the form stays open, nothing is toasted, and a 422 invalidates no read.
  assert.deepStrictEqual(draft, initial);
  assert.strictEqual(closed, 0);
  assert.deepStrictEqual(notices, []);
  assert.strictEqual(reads(), before);
  // An optimistic change (a group saved on change) is reverted when its command is refused.
  const input = within(form(), (n) => n.tag === "fieldset")[0];
  const field = within(input, (n) => n.tag === "input")[0];
  field.props.onChange({{ target: {{ value: "5" }} }});
  root.settle();
  assert.strictEqual(draft.expected_minutes, 5, "the change shows at once");
  await flush(root);
  assert.strictEqual(posts().length, 2);
  assert.deepStrictEqual(draft, initial, "the refused change is reverted");
  assert.strictEqual(within(form(), (n) => n.props && n.props["data-ui-refusal"] !== undefined).length, 1);
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

#[test]
fn a_refused_command_renders_on_the_confirm_that_sent_it() {
    let out = refusal_stage("confirm");
    node(
        &out,
        "confirm",
        &format!(
            r#"{STAGE}
const {{ ConfirmView }} = out("runtime/composites/confirm");
answer = {{ status: 409, body: '{{"outcome":"wrong-state","published":[],"error":"gatepass.visit.VisitStateConflict","payload":{{"state":"Departed"}}}}' }};
let closed = 0;
const notices = [];
const app = jsx(ScopeLayer, {{
  values: {{ row: {{ id: "v-1" }}, params: {{ visit_id: "v-1" }} }},
  actions: {{ close: () => {{ closed += 1; }}, notify: (message) => notices.push(message) }},
  children: [
    jsx(Reader, {{}}, "reader"),
    jsx(ConfirmView, {{ "data-ui-path": "pages/desk/sections/depart", does: "visit.SignOutVisitor", body: "Sign the visitor out?" }}, "confirm"),
  ],
}});
(async () => {{
  const root = React.__root(app).settle();
  await flush(root);
  const before = reads();
  const confirm = () => root.find((n) => n.props && n.props["data-ui-path"] === "pages/desk/sections/depart")[0];
  const button = within(confirm(), (n) => n.tag === "button" && textOf(n).includes("Confirm"))[0];
  button.props.onClick();
  await flush(root);
  assert.strictEqual(posts().length, 1);
  assert.strictEqual(posts()[0].url, "http://desk.test/visits/commands/sign-out-visitor");
  const shown = within(confirm(), (n) => n.props && n.props["data-ui-refusal"] !== undefined);
  assert.strictEqual(shown.length, 1, root.text());
  const text = textOf(shown[0]);
  assert.ok(text.includes("VisitStateConflict"), text);
  assert.ok(text.includes("Departed"), text);
  // The confirm stays open over what it refused, and a 409 invalidates the reads.
  assert.strictEqual(closed, 0);
  assert.deepStrictEqual(notices, []);
  assert.ok(reads() > before, `reads ${{before}} -> ${{reads()}}`);
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

#[test]
fn a_matching_confirm_retries_refusal_then_closes_without_resending_committed_work() {
    let document = load(&format!("{DESK}    overlays:\n      ask: {{kind: dialog, component: confirm, does: visit.AdmitVisitor}}\n"));
    let binding = bind(&document, &gatepass_with(""));
    let out = scratch("matching-confirm-retry");
    ess_ui_react::generate_bound(&document, &root(), &out, Some(&binding)).expect("bound app");
    compile(
        &out,
        &[
            "binding.ts",
            "runtime/actions.tsx",
            "runtime/overlays.tsx",
            "runtime/composites/confirm.tsx",
        ],
    );
    node(
        &out,
        "matching-confirm-retry",
        &format!(
            r#"{STAGE}
const {{ ActionControl }} = out("runtime/actions");
const {{ OverlayHost }} = out("runtime/overlays");
const {{ ConfirmView }} = out("runtime/composites/confirm");
answer = {{ status: 409, body: '{{"outcome":"wrong-state","published":[],"error":"gatepass.visit.VisitStateConflict","payload":{{"state":"Departed"}}}}' }};
const path = "pages/desk/sections/expected/actions/admit";
const root = React.__root(jsx(OverlayHost, {{ overlays: {{}}, children: jsx(ScopeLayer, {{
  values: {{ row: {{ visit_id: "v-1" }} }},
  children: jsx(ActionControl, {{ action: {{
    "data-ui-path": path, name: "admit", label: "Admit", does: "visit.AdmitVisitor",
    bind: {{ visit_id: "row.visit_id" }},
    confirm: jsx(ConfirmView, {{ "data-ui-path": `${{path}}/confirm/overlay`, does: "visit.AdmitVisitor" }}),
  }} }}),
}}) }})).settle();
(async () => {{
  await flush(root);
  root.find((n) => n.tag === "button" && n.props["data-ui-path"] === path)[0].props.onClick();
  await flush(root);
  const primary = () => root.find((n) => n.tag === "button" && String(n.props.className).includes("ui-tone-danger"));
  primary()[0].props.onClick();
  await flush(root);
  assert.strictEqual(posts().length, 1, "matching command is sent once");
  assert.strictEqual(primary().length, 1, "refusal leaves confirm open");
  assert.ok(root.text().includes("VisitStateConflict"), root.text());
  {COMMITTED}
  primary()[0].props.onClick();
  await flush(root);
  assert.strictEqual(posts().length, 2, "refused command is retryable");
  assert.strictEqual(primary().length, 0, "committed command closes confirm");
  await flush(root);
  assert.strictEqual(posts().length, 2, "committed action is never resent");
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

/// A `501` whose effect was committed (`ess_ui::binding::Answer::Unfinished { committed: true }`):
/// the command is done and must not be sent again, so the stage closes as after an accepted
/// command, reads are read again, and what failed after the effect is shown, not lost.
const COMMITTED: &str = r#"answer = { status: 501, body: '{"refused":"delivering what the command published: the binding refused the event","committed":true}' };"#;

#[test]
fn a_committed_unfinished_submit_is_not_sent_again() {
    let out = refusal_stage("unfinished-form");
    node(
        &out,
        "unfinished-form",
        &format!(
            r#"{STAGE}
const {{ FormView }} = out("runtime/composites/form");
{COMMITTED}
let closed = 0;
const notices = [];
const app = jsx(ScopeLayer, {{
  values: {{ draft: {{ visitor: "Ada", building: "North", expected_minutes: 30 }} }},
  setters: {{ draft: () => undefined }},
  actions: {{ close: () => {{ closed += 1; }}, notify: (message) => notices.push(message) }},
  children: [
    jsx(Reader, {{}}, "reader"),
    jsx(FormView, {{ "data-ui-path": "pages/desk/sections/register", does: "visit.RegisterVisit" }}, "form"),
  ],
}});
(async () => {{
  const root = React.__root(app).settle();
  await flush(root);
  const before = reads();
  const form = () => root.find((n) => n.tag === "form")[0];
  form().props.onSubmit({{ preventDefault() {{}} }});
  await flush(root);
  assert.strictEqual(posts().length, 1);
  // Done: the form closes, so it offers no second submit of a command whose effect stands.
  assert.strictEqual(closed, 1, "the form stays open over a committed command");
  assert.ok(reads() > before, `reads ${{before}} -> ${{reads()}}`);
  const shown = within(form(), (n) => n.props && n.props["data-ui-refusal"] !== undefined);
  assert.strictEqual(shown.length, 1, root.text());
  assert.strictEqual(shown[0].props["data-ui-refusal"], "unfinished");
  assert.ok(notices.some((message) => message.includes("do not send it again")), JSON.stringify(notices));
  await flush(root);
  assert.strictEqual(posts().length, 1, "the committed command was sent again");
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

#[test]
fn a_committed_unfinished_confirm_is_not_sent_again() {
    let out = refusal_stage("unfinished-confirm");
    node(
        &out,
        "unfinished-confirm",
        &format!(
            r#"{STAGE}
const {{ ConfirmView }} = out("runtime/composites/confirm");
{COMMITTED}
let closed = 0;
const notices = [];
const app = jsx(ScopeLayer, {{
  values: {{ row: {{ id: "v-1" }}, params: {{ visit_id: "v-1" }} }},
  actions: {{ close: () => {{ closed += 1; }}, notify: (message) => notices.push(message) }},
  children: [
    jsx(Reader, {{}}, "reader"),
    jsx(ConfirmView, {{ "data-ui-path": "pages/desk/sections/depart", does: "visit.SignOutVisitor", body: "Sign the visitor out?" }}, "confirm"),
  ],
}});
(async () => {{
  const root = React.__root(app).settle();
  await flush(root);
  const before = reads();
  const confirm = () => root.find((n) => n.props && n.props["data-ui-path"] === "pages/desk/sections/depart")[0];
  const button = () => within(confirm(), (n) => n.tag === "button" && textOf(n).includes("Confirm"))[0];
  button().props.onClick();
  await flush(root);
  assert.strictEqual(posts().length, 1);
  // Done: the confirm closes and its guard is released, as after an accepted command.
  assert.strictEqual(closed, 1, "the confirm stays open over a committed command");
  assert.ok(reads() > before, `reads ${{before}} -> ${{reads()}}`);
  assert.ok(notices.some((message) => message.includes("do not send it again")), JSON.stringify(notices));
  const shown = within(confirm(), (n) => n.props && n.props["data-ui-refusal"] !== undefined);
  assert.strictEqual(shown.length, 1, root.text());
  assert.strictEqual(shown[0].props["data-ui-refusal"], "unfinished");
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

#[test]
fn a_refused_command_renders_on_the_action_that_sent_it() {
    let out = refusal_stage("action");
    node(
        &out,
        "action",
        &format!(
            r#"{STAGE}
const {{ ActionControl }} = out("runtime/actions");
answer = {{ status: 409, body: '{{"outcome":"wrong-state","published":[],"error":"gatepass.visit.VisitStateConflict","payload":{{"state":"OnSite"}}}}' }};
const notices = [];
const path = "pages/desk/sections/expected/actions/admit";
const app = jsx(ScopeLayer, {{
  values: {{ row: {{ id: "v-1" }} }},
  actions: {{ notify: (message) => notices.push(message) }},
  children: [
    jsx(Reader, {{}}, "reader"),
    jsx("div", {{ className: "actions", children: jsx(ActionControl, {{ action: {{ "data-ui-path": path, name: "admit", does: "visit.AdmitVisitor", bind: {{ visit_id: "row.id", badge: "'B-1'" }} }} }}) }}, "actions"),
  ],
}});
(async () => {{
  const root = React.__root(app).settle();
  await flush(root);
  const before = reads();
  const control = () => root.find((n) => n.props && n.props["data-ui-path"] === path)[0];
  control().props.onClick();
  await flush(root);
  assert.strictEqual(posts().length, 1);
  assert.strictEqual(posts()[0].url, "http://desk.test/visits/commands/admit-visitor");
  assert.deepStrictEqual(JSON.parse(posts()[0].body), {{ visit_id: "v-1", badge: "B-1" }});
  // Beside the control that sent it, not in a notification.
  const holder = root.find((n) => n.props && n.props.className === "actions")[0];
  const shown = within(holder, (n) => n.props && n.props["data-ui-refusal"] !== undefined);
  assert.strictEqual(shown.length, 1, root.text());
  assert.strictEqual(shown[0].props["data-ui-refused-by"], path);
  const text = textOf(shown[0]);
  assert.ok(text.includes("VisitStateConflict"), text);
  assert.ok(text.includes("OnSite"), text);
  assert.deepStrictEqual(notices, []);
  assert.ok(reads() > before, `reads ${{before}} -> ${{reads()}}`);
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}

// ── end to end, against the Rust gatepass server ─────────────────────────────────────────────

/// Builds `examples/gatepass-realization`'s server into its own target directory: a nested
/// `cargo build` into the running test's target directory would wait on its lock.
fn gatepass_server() -> PathBuf {
    let target = Path::new(env!("CARGO_TARGET_TMPDIR")).join("gatepass-target");
    let built = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args([
            "build",
            "--offline",
            "--quiet",
            "--bin",
            "gatepass-server",
            "--manifest-path",
        ])
        .arg(root().join("examples/gatepass-realization/Cargo.toml"))
        .arg("--target-dir")
        .arg(&target)
        .env_remove("CARGO_TARGET_DIR")
        .env("CARGO_INCREMENTAL", "0")
        .output()
        .expect("cargo runs");
    assert!(
        built.status.success(),
        "the Rust gatepass server builds: {}",
        String::from_utf8_lossy(&built.stderr)
    );
    target.join("debug/gatepass-server")
}

/// Kills a child when the case ends, pass or fail.
struct Served(Child);

impl Drop for Served {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}

/// Starts the server on an ephemeral port and reads the port from its startup record.
fn serve(binary: &Path) -> (Served, u16) {
    let mut child = Command::new(binary)
        .env("PORT", "0")
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("the server starts");
    let stdout = child.stdout.take().expect("piped");
    let served = Served(child);
    let mut lines = std::io::BufReader::new(stdout).lines();
    let first = lines.next().expect("a startup record").expect("text");
    let record: serde_json::Value = serde_json::from_str(&first).expect("the record is JSON");
    let port = record["runtime"]["port"]
        .as_u64()
        .and_then(|port| u16::try_from(port).ok())
        .unwrap_or_else(|| panic!("the record names the port: {first}"));
    std::thread::spawn(move || lines.for_each(drop));
    (served, port)
}

const REACT: &str = r#""use strict";
exports.useState = (initial) => [typeof initial === "function" ? initial() : initial, () => undefined];
exports.useEffect = () => undefined;
exports.useLayoutEffect = () => undefined;
exports.useMemo = (factory) => factory();
exports.useCallback = (callback) => callback;
exports.useRef = (initial) => ({ current: initial });
exports.useContext = (context) => context._default;
exports.createContext = (value) => ({ _default: value, Provider: (props) => props.children });
exports.Fragment = (props) => props.children;
exports.StrictMode = (props) => props.children;
"#;

/// Runs the project's own `build` script (`tsc --noEmit && esbuild …`) against stand-in `react`
/// and `react-dom` packages typed by the project's offline declarations.
fn build(project: &Path) {
    let modules = project.join("node_modules");
    let types = |file: &str| read(&project.join("types").join(file));
    write(
        &modules.join("react/package.json"),
        r#"{"name":"react","main":"index.js","types":"index.d.ts"}"#,
    );
    write(&modules.join("react/index.js"), REACT);
    write(&modules.join("react/index.d.ts"), &types("react.d.ts"));
    write(
        &modules.join("react/jsx-runtime.js"),
        "\"use strict\";\nconst jsx = (type, props) => ({ type, props });\nmodule.exports = { jsx, jsxs: jsx };\n",
    );
    write(
        &modules.join("react/jsx-runtime.d.ts"),
        &types("react-jsx-runtime.d.ts"),
    );
    write(
        &modules.join("react-dom/package.json"),
        r#"{"name":"react-dom","main":"client.js"}"#,
    );
    write(
        &modules.join("react-dom/client.js"),
        "\"use strict\";\nexports.createRoot = () => ({ render() {}, unmount() {} });\n",
    );
    write(
        &modules.join("react-dom/client.d.ts"),
        &types("react-dom-client.d.ts"),
    );
    let package: serde_json::Value =
        serde_json::from_str(&read(&project.join("package.json"))).expect("package.json parses");
    let script = package["scripts"]["build"]
        .as_str()
        .expect("a build script");
    let output = Command::new("sh")
        .args(["-c", script])
        .current_dir(project)
        .output()
        .expect("sh runs");
    assert!(
        output.status.success(),
        "`{script}` failed:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let bundle = read(&project.join("www/assets/main.js"));
    assert!(
        bundle.contains("/visits/commands/register-visit"),
        "the bundle carries no binding"
    );
}

#[test]
fn the_built_app_reads_and_commands_a_synthesized_gatepass_server() {
    let (out, _, _) = bound_desk("gatepass");
    build(&out);
    // The node run replaces the build's stand-in `react` with `support`'s hook-level one.
    compile(&out, &["binding.ts", "runtime/composites/form.tsx"]);
    let binary = gatepass_server();
    let (_server, port) = serve(&binary);
    node(
        &out,
        "gatepass",
        &format!(
            r#"
const {{ ScopeLayer, useScope }} = out("runtime/core");
const {{ FormView }} = out("runtime/composites/form");
const {{ runCommand }} = out("runtime/actions");
const {{ httpAdapter, setDataAdapter, setAuthorization, useRead }} = out("runtime/data");
const {{ binding }} = out("binding");
globalThis.document = {{
  querySelector: (selector) =>
    selector === 'meta[name="ess-base-url:pass-service"]' ? {{ getAttribute: () => "http://127.0.0.1:{port}" }} : null,
}};
setAuthorization("Actor gatepass.visit.Receptionist");
setDataAdapter(httpAdapter(binding));
const register = {{ visitor: "Ada", building: "North", host: {{ kind: "employee", value: "E1" }}, expected_minutes: 30, expected_stay: "PT30M", deposit: {{ amount: "0", currency: "EUR" }}, escorts: [], notes: {{}}, on_watchlist: false }};
let read;
function Reader() {{
  read = useRead({{ view: "visit.ExpectedVisits" }}, {{}});
  return jsx("span", {{ children: read.status }});
}}
let scope;
function Grab() {{
  scope = useScope();
  return null;
}}
const notices = [];
const app = jsx(ScopeLayer, {{
  values: {{ draft: {{ ...register, expected_minutes: 0 }} }},
  setters: {{ draft: () => undefined }},
  actions: {{ notify: (message, tone) => notices.push([message, tone]) }},
  children: [
    jsx(Reader, {{}}, "reader"),
    jsx(Grab, {{}}, "grab"),
    jsx(FormView, {{ "data-ui-path": "pages/desk/sections/register", does: "visit.RegisterVisit" }}, "form"),
  ],
}});
const until = async (root, what, done) => {{
  const deadline = Date.now() + 15000;
  while (!done()) {{
    if (Date.now() > deadline) throw new Error(`timed out waiting for ${{what}}: ${{root.text()}}`);
    await new Promise((resolve) => setTimeout(resolve, 20));
    root.settle();
  }}
}};
(async () => {{
  const root = React.__root(app).settle();
  // ExpectedVisits reads ready, from the served path.
  await until(root, "the expected list", () => read.status === "ready");
  assert.deepStrictEqual(read.rows, []);
  // RegisterVisit is accepted, and the list reads again and shows the visit.
  const ok = await runCommand(scope, "visit.RegisterVisit", register);
  assert.strictEqual(ok, true, JSON.stringify(notices));
  await until(root, "the registered visit", () => read.status === "ready" && read.rows.length === 1);
  assert.strictEqual(read.rows[0].visitor, "Ada");
  // A zero-length visit is refused with InvalidVisitLength, on the form that sent it.
  const form = () => root.find((n) => n.tag === "form")[0];
  form().props.onSubmit({{ preventDefault() {{}} }});
  const refusal = () => root.find((n) => n.props && n.props["data-ui-refusal"] !== undefined);
  await until(root, "the refusal", () => refusal().length > 0);
  const inside = [];
  const visit = (nodes) => nodes.forEach((n) => {{ if (typeof n === "object") {{ if (n.props && n.props["data-ui-refusal"] !== undefined) inside.push(n); if (n.children) visit(n.children); }} }});
  visit(form().children);
  assert.strictEqual(inside.length, 1, "the refusal is inside the form");
  assert.strictEqual(inside[0].props["data-ui-refusal"], "refused");
  const parts = [];
  const text = (nodes) => nodes.forEach((n) => (typeof n === "string" ? parts.push(n) : n.children && text(n.children)));
  text(inside[0].children);
  assert.ok(parts.join(" ").includes("InvalidVisitLength"), parts.join(" "));
  assert.ok(parts.join(" ").includes("submitted"), parts.join(" "));
  // Still one visit: nothing was recorded.
  assert.strictEqual(read.rows.length, 1);
}})().catch((error) => {{ console.error(error); process.exit(1); }});
"#
        ),
    );
}
