//! Public CLI routes resolve first and obey existing generated-output ownership.

use std::{
    fs,
    path::Path,
    process::{Command, Output},
};

const MODEL: &str = include_str!("../../../specify/ess-cli-contract/tests/fixtures/model.yaml");
const BINDING: &str = include_str!("../../../specify/ess-cli-contract/tests/fixtures/cli.yaml");

fn fixture() -> tempfile::TempDir {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("model.yaml"), MODEL).unwrap();
    fs::write(temp.path().join("cli.yaml"), BINDING).unwrap();
    temp
}

fn ess(root: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_ess"))
        .current_dir(root)
        .args(args)
        .output()
        .unwrap()
}

fn generate(root: &Path, check: bool) -> Output {
    let mut args = vec![
        "generate",
        "cli",
        "--path",
        "model.yaml",
        "--binding",
        "cli.yaml",
        "--out",
        "generated",
    ];
    if check {
        args.push("--check");
    }
    ess(root, &args)
}

#[test]
fn binding_routes_validate_generate_compare_and_refuse_drift() {
    let temp = fixture();
    let valid = ess(
        temp.path(),
        &[
            "specify",
            "cli",
            "--path",
            "model.yaml",
            "--binding",
            "cli.yaml",
            "--format",
            "json",
        ],
    );
    assert!(
        valid.status.success(),
        "{}",
        String::from_utf8_lossy(&valid.stderr)
    );
    serde_json::from_slice::<serde_json::Value>(&valid.stdout).unwrap();
    let generated = generate(temp.path(), false);
    assert!(
        generated.status.success(),
        "{}",
        String::from_utf8_lossy(&generated.stderr)
    );
    let before = fs::read(temp.path().join("generated/src/lib.rs")).unwrap();
    assert!(generate(temp.path(), true).status.success());
    fs::write(temp.path().join("generated/src/lib.rs"), "changed").unwrap();
    assert!(!generate(temp.path(), true).status.success());
    assert_eq!(
        fs::read(temp.path().join("generated/src/lib.rs")).unwrap(),
        b"changed"
    );
    // The owning protocol explicitly lets regeneration repair its selected owned files.
    // Check above remains nonwriting; ordinary generation restores the generated bytes.
    assert!(generate(temp.path(), false).status.success());
    assert_eq!(
        fs::read(temp.path().join("generated/src/lib.rs")).unwrap(),
        before
    );
    fs::write(
        temp.path().join("generated/authored.txt"),
        "authored neighbour",
    )
    .unwrap();
    assert!(generate(temp.path(), false).status.success());
    assert_eq!(
        fs::read(temp.path().join("generated/authored.txt")).unwrap(),
        b"authored neighbour"
    );
}

#[test]
fn invalid_binding_leaves_both_absent_and_existing_destinations_untouched() {
    let temp = fixture();
    fs::write(
        temp.path().join("cli.yaml"),
        BINDING.replace("ess-cli/1", "ess-cli/999"),
    )
    .unwrap();
    assert!(!generate(temp.path(), false).status.success());
    assert!(!temp.path().join("generated").exists());
    fs::create_dir(temp.path().join("generated")).unwrap();
    fs::write(temp.path().join("generated/keep.txt"), "authored").unwrap();
    assert!(!generate(temp.path(), false).status.success());
    assert_eq!(
        fs::read_dir(temp.path().join("generated")).unwrap().count(),
        1
    );
    assert_eq!(
        fs::read(temp.path().join("generated/keep.txt")).unwrap(),
        b"authored"
    );
}

#[test]
fn generating_within_model_input_is_refused_without_mutation() {
    let temp = fixture();
    fs::create_dir(temp.path().join("model")).unwrap();
    fs::rename(
        temp.path().join("model.yaml"),
        temp.path().join("model/system.yaml"),
    )
    .unwrap();
    let output = ess(
        temp.path(),
        &[
            "generate",
            "cli",
            "--path",
            "model",
            "--binding",
            "cli.yaml",
            "--out",
            "model/generated",
        ],
    );
    assert!(!output.status.success());
    assert!(!temp.path().join("model/generated").exists());
}

#[cfg(unix)]
#[test]
fn drift_check_refuses_linked_generated_files() {
    let temp = fixture();
    assert!(generate(temp.path(), false).status.success());
    let output = temp.path().join("generated/src/lib.rs");
    let outside = temp.path().join("outside.rs");
    fs::rename(&output, &outside).unwrap();
    std::os::unix::fs::symlink(outside, output).unwrap();
    assert!(!generate(temp.path(), true).status.success());
}
