// Model-based exploration: seeded random command sequences, each step checked against a reference
// model interpreted from the compiled specification.
//
// Generated by `ess verify conform synthesize --target typescript`. Do not edit: change the
// specification and regenerate.
//
// # What this asks that the suite does not
//
// The suite asks one fixed question per scenario. This walks paths nobody wrote — a view that drops
// rows after the fifth, a refusal that still writes, an identity reused on the fourth create, a
// state that cannot be re-entered a third time — and checks after every step the outcome, the
// error, the direct events and their determined payload fields, every parameterless view over an
// entity (polling an `eventual` one), identity uniqueness and every invariant. A failure is shrunk
// to a shorter trace that still fails the same way.
//
// # A port, not a second opinion
//
// `src/go/explore.go` is this file in Go, function for function. The random draws, their order and
// every sorted enumeration are part of the contract, so one seed names one sequence in both
// languages and both report the same trace for it.
//
// # The model it reads
//
// `ir.json` beside `suite.json`: the compact IR, the exact bytes the suite's `spec_digest` is taken
// over. It is read only after that digest matches, so a package whose two files came from different
// specifications is refused rather than explored against the wrong model.

import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

import { facts, fromNode, TruthFalse, TruthTrue, TruthUnknown } from './predicate.js';
import type { Predicate } from './predicate.js';
import {
  asNumber,
  byteCompare,
  equal,
  errorText,
  goMarshal,
  isObject,
  isUnsupported,
  newHarness,
  ranked,
  sortStrings,
  strictJSON,
} from './runtime.js';
import type { Answer, CommandResult, Node, Row, Target } from './runtime.js';

/** What one exploration is asked to do. */
export interface ExploreOptions {
  /** Sequences to run, seeded `1…seeds`. Default 200. */
  seeds?: number;
  /** Commands per sequence. Default 60. */
  steps?: number;
  /** Run exactly this one sequence, overriding `seeds`: how a reported failure is replayed. */
  seed?: number;
}

/** One command or view left out of every sequence, and why. */
export interface Exclusion {
  subject: string;
  reason: string;
}

/** A disagreement: its seed, what disagreed, and the shortest trace found that still shows it. */
export interface ExploreFailure {
  seed: number;
  message: string;
  trace: string[];
  originalLength: number;
  shrinkComplete: boolean;
}

/** What an exploration found. Every list is sorted. */
export interface ExploreResult {
  sequences: number;
  steps: number;
  /** Commands actually run, across every sequence and none of the shrinking replays. */
  executed: number;
  /** `command/outcome` for every outcome a step took. */
  reached: string[];
  /** Declared outcomes of included commands that no step took. */
  unreached: string[];
  excluded: Exclusion[];
  /** Every declared outcome of an excluded command. */
  excludedOutcomes: string[];
  /** What the model could not place, such as a view filter over a field no command set. */
  undetermined: string[];
  /** Draws the specification does not decide, which were redrawn rather than executed. */
  ambiguous: string[];
  failure?: ExploreFailure;
}

/** What `assertExplored` accepts. */
export interface AssertOptions {
  /** Accept outcomes of excluded commands. An explicit, reviewable opt-out. */
  allowExcluded?: boolean;
}

export const DEFAULT_SEEDS = 200;
export const DEFAULT_STEPS = 60;
const ATTEMPTS_PER_STEP = 20;
const SHRINK_REPLAYS = 1000;
const INTEGERS = [-1, 0, 1, 2, 3, 100];
const TEXTS = ['', 'a', 'b'];

/** The refusal when `ir.json` is not the model `suite.json` was synthesized from. */
export const MODEL_MISMATCH =
  '`ir.json` and `suite.json` come from different specifications; regenerate the package';

// ---- randomness -------------------------------------------------------------------------------

/**
 * mulberry32 over a 32-bit state that starts at the seed.
 *
 * `next` is the 32-bit output divided by 2^32, which binary64 holds exactly, so the Go port draws
 * the same numbers.
 */
export class Mulberry32 {
  private state: number;

  constructor(seed: number) {
    this.state = seed >>> 0;
  }

  nextUint32(): number {
    this.state = (this.state + 0x6d2b79f5) >>> 0;
    let t = this.state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return (t ^ (t >>> 14)) >>> 0;
  }

  next(): number {
    return this.nextUint32() / 4294967296;
  }

  int(lo: number, hi: number): number {
    return lo + Math.floor(this.next() * (hi - lo + 1));
  }

  pick<T>(items: T[]): T {
    return items[Math.floor(this.next() * items.length)] as T;
  }

  chance(p: number): boolean {
    return this.next() < p;
  }
}

// ---- the model document -------------------------------------------------------------------------

function packageFile(name: string): string {
  try {
    return readFileSync(new URL(`../${name}`, import.meta.url), 'utf8');
  } catch (error) {
    throw new Error(`explore: cannot read \`${name}\`: ${errorText(error)}`);
  }
}

/**
 * The compiled model, after its digest has been checked against the suite's.
 *
 * Throws when either file is absent or unreadable, or when the two disagree.
 */
export function loadModel(
  irText: string = packageFile('ir.json'),
  suiteText: string = packageFile('suite.json'),
): Node {
  const body = irText.endsWith('\n') ? irText.slice(0, -1) : irText;
  const digest = createHash('sha256').update(body, 'utf8').digest('hex');
  const suite = strictJSON(suiteText);
  const declared =
    isObject(suite) && isObject(suite.provenance) ? suite.provenance.spec_digest : null;
  if (digest !== declared) {
    throw new Error(MODEL_MISMATCH);
  }
  return strictJSON(body);
}

/** An object's values in byte order of key. */
function sortedValues(value: Node): Node[] {
  if (!isObject(value)) return [];
  return sortStrings(Object.keys(value)).map((key) => value[key]);
}

function list(value: Node): Node[] {
  return Array.isArray(value) ? value : [];
}

function nonEmpty(value: Node): boolean {
  if (Array.isArray(value)) return value.length > 0;
  if (isObject(value)) return Object.keys(value).length > 0;
  return value !== null && value !== undefined;
}

// ---- input types --------------------------------------------------------------------------------

type Kind =
  | { kind: 'integer' | 'boolean' | 'string' | 'uuid' }
  | { kind: 'enum'; variants: string[] }
  | { kind: 'struct'; fields: [string, Kind][] }
  | { kind: 'identity'; entity: string; base: Kind }
  | { kind: 'unsupported'; why: string };

function identityOwner(ir: Node, type: string): string | null {
  for (const entity of sortedValues(ir.entities)) {
    const ref = entity?.identity?.type_ref;
    if (ref?.kind === 'declared' && ref.name === type) return entity.name;
  }
  return null;
}

function resolveKind(ir: Node, ref: Node, depth = 0): Kind {
  if (depth > 32) return { kind: 'unsupported', why: 'nested too deeply' };
  if (ref?.kind === 'primitive') {
    switch (ref.name) {
      case 'integer':
      case 'boolean':
      case 'string':
      case 'uuid':
        return { kind: ref.name };
      default:
        return { kind: 'unsupported', why: `a \`${ref.name}\`` };
    }
  }
  if (ref?.kind !== 'declared') return { kind: 'unsupported', why: `a \`${ref?.kind}\`` };
  const body = ir.types?.[ref.name]?.body;
  if (
    list(body?.invariants).length > 0 ||
    (body?.alphabet !== undefined && body?.alphabet !== null)
  ) {
    return { kind: 'unsupported', why: `\`${ref.name}\`, which constrains its values` };
  }
  if (body?.kind === 'newtype') {
    const base = resolveKind(ir, body.of, depth + 1);
    if (base.kind === 'unsupported') return base;
    const owner = identityOwner(ir, ref.name);
    return owner === null ? base : { kind: 'identity', entity: owner, base };
  }
  if (body?.kind === 'enum') {
    const variants = list(body.variants).map((variant: Node) =>
      typeof variant === 'string' ? variant : String(variant?.name),
    );
    if (variants.length === 0)
      return { kind: 'unsupported', why: `\`${ref.name}\`, which has no variants` };
    return { kind: 'enum', variants };
  }
  if (body?.kind === 'struct') {
    const fields: [string, Kind][] = [];
    for (const field of list(body.fields)) {
      const kind = resolveKind(ir, field.type_ref, depth + 1);
      if (kind.kind === 'unsupported') return kind;
      fields.push([field.name, kind]);
    }
    return { kind: 'struct', fields };
  }
  return { kind: 'unsupported', why: `\`${ref.name}\`, a \`${body?.kind}\`` };
}

// ---- predicates ---------------------------------------------------------------------------------

const TEXT_OPERATORS = ['starts_with', 'ends_with', 'contains'];

function walk(predicate: Predicate, visit: (node: Predicate) => void): void {
  visit(predicate);
  for (const child of predicate.children) walk(child, visit);
  if (predicate.body) walk(predicate.body, visit);
}

/** Every fact path a predicate reads, sorted. */
function paths(predicate: Predicate): string[] {
  const found = new Set<string>();
  walk(predicate, (node) => {
    if (node.kind === 'compare') {
      if (node.left.isFact) found.add(node.left.path);
      if (node.right.isFact) found.add(node.right.path);
    } else if (node.kind === 'forall' || node.kind === 'exists') {
      found.add(node.over);
    } else if (node.path !== '') {
      found.add(node.path);
    }
  });
  return sortStrings([...found]);
}

/** The first path a predicate reads that `row` does not hold. */
function missing(predicate: Predicate, row: Row): string {
  const source = facts(row);
  return paths(predicate).find((path) => !source.has(path)) ?? paths(predicate)[0] ?? '';
}

function parsed(node: Node): Predicate | string {
  try {
    const predicate = fromNode(node);
    let text: string | null = null;
    walk(predicate, (child) => {
      if (text === null && TEXT_OPERATORS.includes(child.kind)) text = child.kind;
    });
    if (text !== null) return `it uses \`${text}\`, which this explorer does not evaluate`;
    return predicate;
  } catch (error) {
    return `it cannot be read: ${errorText(error)}`;
  }
}

/** The literals a command's guards compare against, as draw pools. */
function pools(guards: Predicate[]): { integers: number[]; texts: string[] } {
  const integers = new Set<number>(INTEGERS);
  const texts = new Set<string>(TEXTS);
  const literal = (value: Node): void => {
    if (typeof value === 'string') {
      texts.add(value);
      return;
    }
    if (typeof value === 'boolean' || value === null || value === undefined) return;
    const [number, ok] = asNumber(value);
    if (ok && Number.isSafeInteger(number)) {
      integers.add(number - 1);
      integers.add(number);
      integers.add(number + 1);
    }
  };
  for (const guard of guards) {
    walk(guard, (node) => {
      if (node.kind === 'compare') {
        if (!node.left.isFact) literal(node.left.literal);
        if (!node.right.isFact) literal(node.right.literal);
      } else if (node.kind === 'any_of' || node.kind === 'none_of') {
        node.values.forEach(literal);
      }
    });
  }
  return {
    integers: [...integers].sort((left, right) => left - right),
    texts: sortStrings([...texts]),
  };
}

// ---- the plan: what is explored, and what is left out -------------------------------------------

interface Command {
  name: string;
  actor: string;
  node: Node;
  inputs: [string, Kind][];
  guards: Map<string, Predicate>;
  pools: { integers: number[]; texts: string[] };
}

interface Plan {
  ir: Node;
  system: string;
  commands: Command[];
  views: Node[];
  excluded: Exclusion[];
  excludedCommands: Set<string>;
  declared: Map<string, string[]>;
}

function effectRefusal(outcome: Node): string | null {
  const subject = outcome.subject;
  if (subject === null || subject === undefined) return null;
  const from = subject.instance?.from;
  const allowed =
    (subject.effect === 'creates' && from === 'observed') ||
    ((subject.effect === 'moves' || subject.effect === 'updates') && from === 'supplied');
  return allowed
    ? null
    : `outcome \`${outcome.name}\` ${subject.effect} its subject from \`${from}\``;
}

function plan(ir: Node): Plan {
  const excluded: Exclusion[] = [];
  const excludedCommands = new Set<string>();
  const declared = new Map<string, string[]>();
  const actorFor = new Map<string, string>();
  for (const actor of sortedValues(ir.actors)) {
    for (const command of list(actor.may)) {
      if (!actorFor.has(command)) actorFor.set(command, actor.name);
    }
  }

  const commands: Command[] = [];
  for (const node of sortedValues(ir.commands)) {
    const outcomes = list(node.outcomes);
    declared.set(
      node.name,
      outcomes.map((outcome: Node) => String(outcome.name)),
    );
    let reason: string | null = null;
    for (const outcome of outcomes) {
      const kind = outcome.condition?.kind;
      if (reason === null && kind !== 'when' && kind !== 'otherwise' && kind !== 'wrong_state') {
        reason = `outcome \`${outcome.name}\` has a \`${kind}\` condition`;
      }
    }
    for (const outcome of outcomes) reason ??= effectRefusal(outcome);
    for (const outcome of outcomes) {
      if (reason === null && outcome.replays !== undefined && outcome.replays !== null) {
        reason = `outcome \`${outcome.name}\` replays a retained result`;
      }
    }
    const inputs: [string, Kind][] = [];
    for (const field of list(node.input)) {
      const kind = resolveKind(ir, field.type_ref);
      if (reason === null && kind.kind === 'unsupported') {
        reason = `input \`${field.name}\` is ${kind.why}`;
      }
      inputs.push([field.name, kind]);
    }
    const guards = new Map<string, Predicate>();
    for (const outcome of outcomes) {
      if (reason !== null || outcome.condition?.kind !== 'when') continue;
      const guard = parsed(outcome.condition.predicate);
      if (typeof guard === 'string') reason = `the guard of \`${outcome.name}\`: ${guard}`;
      else guards.set(outcome.name, guard);
    }
    const actor = actorFor.get(node.name);
    if (reason === null && actor === undefined) reason = 'no actor may invoke it';
    if (reason !== null || actor === undefined) {
      excluded.push({ subject: node.name, reason: reason ?? 'no actor may invoke it' });
      excludedCommands.add(node.name);
      continue;
    }
    commands.push({
      name: node.name,
      actor,
      node,
      inputs,
      guards,
      pools: pools([...guards.values()]),
    });
  }

  const views: Node[] = [];
  for (const view of sortedValues(ir.views)) {
    let reason: string | null = null;
    if (nonEmpty(view.params)) reason = 'it declares parameters';
    else if (nonEmpty(view.group_by)) reason = 'it groups its rows';
    else if (list(view.fields).some((field: Node) => nonEmpty(field.aggregate)))
      reason = 'it aggregates';
    else if (!isObject(ir.entities?.[view.source]))
      reason = `its source \`${view.source}\` is not an entity`;
    else if (
      view.filter !== undefined &&
      view.filter !== null &&
      typeof parsed(view.filter) === 'string'
    ) {
      reason = `its filter: ${parsed(view.filter) as string}`;
    }
    if (reason !== null) excluded.push({ subject: view.name, reason });
    else views.push(view);
  }
  return { ir, system: String(ir.system), commands, views, excluded, excludedCommands, declared };
}

function exclude(p: Plan, subject: string, reason: string): void {
  p.excluded.push({ subject, reason });
  if (p.commands.some((command) => command.name === subject)) {
    p.commands = p.commands.filter((command) => command.name !== subject);
    p.excludedCommands.add(subject);
  }
  p.views = p.views.filter((view) => view.name !== subject);
}

// ---- the reference model ------------------------------------------------------------------------

interface Rec {
  id: Node;
  fields: Row;
}

class Model {
  readonly records = new Map<string, Rec[]>();

  of(entity: string): Rec[] {
    let found = this.records.get(entity);
    if (found === undefined) {
      found = [];
      this.records.set(entity, found);
    }
    return found;
  }

  find(entity: string, id: Node): Rec | undefined {
    return this.of(entity).find((record) => equal(record.id, id));
  }
}

/** A value an outcome gives a field, or `undefined` where the model does not know it. */
const CLEARED = Symbol('cleared');

function readPath(value: Node, path: string): Node {
  let current = value;
  for (const segment of path.split('.')) {
    if (!isObject(current) || !Object.prototype.hasOwnProperty.call(current, segment))
      return undefined;
    current = current[segment];
  }
  return current;
}

function setPath(value: Node, path: string, to: Node): void {
  const segments = path.split('.');
  let current = value;
  for (const segment of segments.slice(0, -1)) current = current[segment];
  current[segments[segments.length - 1] as string] = to;
}

function literalValue(ir: Node, text: Node, type: Node): Node {
  const kind = resolveKind(ir, type);
  const base = kind.kind === 'identity' ? kind.base : kind;
  if (typeof text !== 'string') return undefined;
  switch (base.kind) {
    case 'integer': {
      if (!/^-?[0-9]+$/.test(text)) return undefined;
      const number = Number(text);
      return Number.isSafeInteger(number) ? number : undefined;
    }
    case 'boolean':
      return text === 'true' ? true : text === 'false' ? false : undefined;
    case 'string':
    case 'uuid':
    case 'enum':
      return text;
    default:
      return undefined;
  }
}

function valueOf(ir: Node, value: Node, input: Row, type: Node): Node | typeof CLEARED {
  switch (value?.kind) {
    case 'input_field':
      return readPath(input, String(value.field));
    case 'literal':
      return literalValue(ir, value.value, type);
    case 'cleared':
      return CLEARED;
    default:
      return undefined;
  }
}

type Decision =
  | { kind: 'take'; outcome: Node }
  | { kind: 'ambiguous'; names: string[] }
  | { kind: 'unknown'; reason: string };

function suppliedOutcome(command: Command): Node | undefined {
  return list(command.node.outcomes).find(
    (outcome: Node) => outcome.subject?.instance?.from === 'supplied',
  );
}

function decide(command: Command, input: Row, model: Model): Decision {
  const outcomes = list(command.node.outcomes);
  const supplied = suppliedOutcome(command);
  const record =
    supplied === undefined
      ? undefined
      : model.find(supplied.subject.entity, readPath(input, supplied.subject.instance.field.name));
  const moves = outcomes.filter((outcome: Node) => outcome.subject?.effect === 'moves');
  const starts = new Set<string>(
    moves.flatMap((outcome: Node) => list(outcome.subject.transition.from)),
  );
  const wrong = outcomes.find((outcome: Node) => outcome.condition?.kind === 'wrong_state');
  if (supplied !== undefined && record === undefined) {
    return { kind: 'ambiguous', names: ['no record for the supplied instance'] };
  }
  if (record !== undefined && moves.length > 0 && !starts.has(record.fields.state)) {
    if (wrong !== undefined) return { kind: 'take', outcome: wrong };
    return { kind: 'ambiguous', names: [`no outcome for state ${record.fields.state}`] };
  }

  const source = facts(input);
  const holding: Node[] = [];
  for (const outcome of outcomes) {
    if (outcome.condition?.kind !== 'when') continue;
    const guard = command.guards.get(outcome.name) as Predicate;
    const truth = guard.evaluate(source);
    if (truth === TruthUnknown) {
      return {
        kind: 'unknown',
        reason: `the guard of \`${outcome.name}\` (${guard}) is unknown over a generated input`,
      };
    }
    if (truth === TruthTrue) holding.push(outcome);
  }
  let selected: Node;
  if (holding.length > 1) {
    return { kind: 'ambiguous', names: holding.map((outcome) => String(outcome.name)) };
  } else if (holding.length === 1) {
    selected = holding[0];
  } else {
    selected = outcomes.find((outcome: Node) => outcome.condition?.kind === 'otherwise');
    if (selected === undefined) return { kind: 'ambiguous', names: ['no outcome holds'] };
  }
  if (
    selected.subject?.effect === 'moves' &&
    record !== undefined &&
    !list(selected.subject.transition.from).includes(record.fields.state)
  ) {
    const names = [String(selected.name)];
    if (wrong !== undefined) names.push(String(wrong.name));
    return { kind: 'ambiguous', names };
  }
  return { kind: 'take', outcome: selected };
}

// ---- drawing inputs -----------------------------------------------------------------------------

/** One step of a trace. An input naming an existing record keeps it as (entity, creation index). */
interface Step {
  command: string;
  input: Row;
  refs: [string, string, number][];
}

const NO_RECORD = Symbol('no record');

function drawValue(
  kind: Kind,
  rng: Mulberry32,
  command: Command,
  model: Model,
  path: string,
  mustExist: boolean,
  refs: [string, string, number][],
): Node | typeof NO_RECORD {
  switch (kind.kind) {
    case 'identity': {
      const known = model.of(kind.entity);
      if (mustExist) {
        if (known.length === 0) return NO_RECORD;
        const index = rng.int(0, known.length - 1);
        refs.push([path, kind.entity, index]);
        return (known[index] as Rec).id;
      }
      if (known.length > 0 && rng.chance(0.8)) {
        const index = rng.int(0, known.length - 1);
        refs.push([path, kind.entity, index]);
        return (known[index] as Rec).id;
      }
      return drawValue(kind.base, rng, command, model, path, false, refs);
    }
    case 'integer':
      return rng.chance(0.7) ? rng.pick(command.pools.integers) : rng.int(-10, 10000);
    case 'boolean':
      return rng.chance(0.5);
    case 'string':
      return rng.pick(command.pools.texts);
    case 'uuid':
      return `00000000-0000-4000-8000-${String(rng.int(0, 999999)).padStart(12, '0')}`;
    case 'enum':
      return rng.pick(kind.variants);
    case 'struct': {
      const value: Row = {};
      for (const [name, field] of kind.fields) {
        const drawn = drawValue(field, rng, command, model, `${path}.${name}`, false, refs);
        if (drawn === NO_RECORD) return NO_RECORD;
        value[name] = drawn;
      }
      return value;
    }
    default:
      return null;
  }
}

function draw(command: Command, rng: Mulberry32, model: Model): Step | null {
  const supplied = suppliedOutcome(command);
  const instance = supplied?.subject?.instance?.field?.name;
  const input: Row = {};
  const refs: [string, string, number][] = [];
  for (const [name, declared] of command.inputs) {
    let kind = declared;
    if (name === instance && kind.kind !== 'identity') {
      kind = { kind: 'identity', entity: supplied.subject.entity, base: kind };
    }
    const value = drawValue(kind, rng, command, model, name, name === instance, refs);
    if (value === NO_RECORD) return null;
    input[name] = value;
  }
  return { command: command.name, input, refs };
}

// ---- one step against the target ----------------------------------------------------------------

interface Disagreement {
  kind: string;
  detail: string;
}

class Unsupported extends Error {}

interface Session {
  p: Plan;
  target: Target;
  model: Model;
  correlation: string;
  undetermined: Set<string>;
}

function render(value: Node): string {
  return value === undefined ? 'nothing' : goMarshal(value);
}

async function perform(
  s: Session,
  command: Command,
  step: Step,
  outcome: Node,
): Promise<Disagreement | null> {
  const ir = s.p.ir;
  let result: CommandResult;
  try {
    result = await s.target.executeCommand({
      command: command.name,
      actor: command.actor,
      input: step.input,
      correlation: s.correlation,
    });
  } catch (error) {
    if (isUnsupported(error)) throw new Unsupported(errorText(error));
    return { kind: 'target', detail: `the target threw ${errorText(error)}` };
  }
  const got = result.outcome ?? '';
  if (got !== outcome.name) {
    return {
      kind: 'outcome',
      detail: `the target answered \`${got}\`, the specification says \`${outcome.name}\``,
    };
  }
  const error = result.error ?? '';
  const wanted = typeof outcome.error === 'string' ? outcome.error : '';
  if (error !== wanted) {
    return {
      kind: 'error',
      detail: `the target refused with \`${error}\`, the specification says \`${wanted}\``,
    };
  }
  const events = result.directEvents ?? [];
  const names = events.map((event) => event.event).join(', ');
  const emits = list(outcome.emits).join(', ');
  if (names !== emits) {
    return {
      kind: 'events',
      detail: `the target emitted [${names}], the specification says [${emits}]`,
    };
  }
  for (const [index, event] of events.entries()) {
    const declared = list(outcome.payload).find((entry: Node) => entry.event === event.event);
    for (const field of list(declared?.fields)) {
      const expected = valueOf(ir, field.value, step.input, field.target_type);
      if (expected === undefined || expected === CLEARED) continue;
      const actual = (event.payload ?? {})[field.target];
      if (!equal(expected, actual)) {
        return {
          kind: 'payload',
          detail: `event ${index} \`${event.event}\`.${field.target} is ${render(actual)}, the specification says ${render(expected)}`,
        };
      }
    }
  }

  const subject = outcome.subject;
  if (subject !== null && subject !== undefined) {
    const entity = ir.entities[subject.entity];
    let record: Rec | undefined;
    if (subject.effect === 'creates') {
      const field = subject.instance.field.name;
      const carrier = events.find((event) => event.event === subject.instance.event);
      const id = carrier?.payload?.[field];
      if (id === undefined || id === null) {
        return {
          kind: 'identity',
          detail: `the target emitted no \`${subject.instance.event}\`.${field}`,
        };
      }
      if (s.model.find(subject.entity, id) !== undefined) {
        return {
          kind: 'identity',
          detail: `the target created ${render(id)} again, over an existing record`,
        };
      }
      record = { id, fields: { [entity.identity.name]: id, state: entity.lifecycle?.initial } };
      s.model.of(subject.entity).push(record);
    } else {
      record = s.model.find(subject.entity, readPath(step.input, subject.instance.field.name));
      if (record !== undefined && subject.effect === 'moves')
        record.fields.state = subject.transition.to;
    }
    if (record !== undefined) {
      for (const set of list(outcome.sets)) {
        const value = valueOf(ir, set.value, step.input, set.target_type);
        if (value === undefined || value === CLEARED) delete record.fields[set.target];
        else record.fields[set.target] = value;
      }
    }
  }

  const views = await checkViews(s, result.consistency ?? '');
  if (views !== null) return views;
  return checkInvariants(s);
}

function agree(view: Node, identity: string, rows: Row[], expected: Rec[]): Disagreement | null {
  if (rows.length !== expected.length) {
    return {
      kind: 'view-rows',
      detail: `\`${view.name}\` holds ${rows.length} row(s), the specification says ${expected.length}`,
    };
  }
  const fields = list(view.fields).map((field: Node) => String(field.name));
  if (fields.includes(identity)) {
    const seen = new Set<Rec>();
    for (const row of rows) {
      const record = expected.find((candidate) => equal(candidate.id, row[identity]));
      if (record === undefined || seen.has(record)) {
        return {
          kind: 'view-rows',
          detail: `\`${view.name}\` holds ${identity} ${render(row[identity])}, which the specification does not place there`,
        };
      }
      seen.add(record);
      for (const field of fields) {
        if (!Object.prototype.hasOwnProperty.call(record.fields, field)) continue;
        if (!equal(record.fields[field], row[field])) {
          return {
            kind: 'view-field',
            detail: `\`${view.name}\`.${field} of ${render(row[identity])} is ${render(row[field])}, the specification says ${render(record.fields[field])}`,
          };
        }
      }
    }
  }
  const orderBy = list(view.order_by).map(String);
  if (orderBy.length > 0) {
    const [ok, message] = ranked(view.name, orderBy, rows);
    if (!ok) return { kind: 'view-order', detail: message };
  }
  return null;
}

async function checkViews(s: Session, token: string): Promise<Disagreement | null> {
  const ir = s.p.ir;
  for (const view of [...s.p.views]) {
    const entity = ir.entities[view.source];
    const filter = view.filter === undefined || view.filter === null ? null : fromNode(view.filter);
    const expected: Rec[] = [];
    let placed = true;
    for (const record of s.model.of(entity.name)) {
      if (filter === null) {
        expected.push(record);
        continue;
      }
      const truth = filter.evaluate(facts(record.fields));
      if (truth === TruthUnknown) {
        s.undetermined.add(
          `${view.name} filter reads ${missing(filter, record.fields)}, which no command set`,
        );
        placed = false;
        break;
      }
      if (truth === TruthTrue) expected.push(record);
    }
    if (!placed) continue;

    const eventual = view.consistency !== 'read_your_writes';
    const attempts = eventual ? newHarness(s.p.system).deadline().attempts : 1;
    let problem: Disagreement | null = null;
    for (let attempt = 0; attempt < attempts; attempt += 1) {
      let rows: Row[];
      try {
        const answer = await s.target.queryView({
          view: view.name,
          params: {},
          atLeast: eventual ? '' : token,
          correlation: s.correlation,
          deadline: { attempts: attempts - attempt },
        });
        rows = answer.rows ?? [];
      } catch (error) {
        if (isUnsupported(error)) {
          exclude(s.p, view.name, `the target does not expose it: ${errorText(error)}`);
          problem = null;
          break;
        }
        return {
          kind: 'target',
          detail: `reading \`${view.name}\`, the target threw ${errorText(error)}`,
        };
      }
      problem = agree(view, String(entity.identity.name), rows, expected);
      if (problem === null) break;
    }
    if (problem !== null) return problem;
  }
  return null;
}

function checkInvariants(s: Session): Disagreement | null {
  for (const entity of sortedValues(s.p.ir.entities)) {
    for (const invariant of list(entity.invariants)) {
      const predicate = parsed(invariant);
      if (typeof predicate === 'string') continue;
      for (const record of s.model.of(entity.name)) {
        const truth = predicate.evaluate(facts(record.fields));
        if (truth === TruthFalse) {
          return {
            kind: 'specification',
            detail: `${entity.name} ${render(record.id)} breaks \`${predicate}\`: the guards allow a sequence the invariants forbid`,
          };
        }
        if (truth === TruthUnknown) {
          s.undetermined.add(
            `${entity.name} invariant \`${predicate}\` reads ${missing(predicate, record.fields)}, which no command set`,
          );
        }
      }
    }
  }
  return null;
}

// ---- sequences ----------------------------------------------------------------------------------

function line(step: Step): string {
  return `${step.command} ${goMarshal(step.input)}`;
}

interface Found {
  kind: string;
  message: string;
  executed: Step[];
}

function describe(found: Disagreement, index: number, step: Step): string {
  return `${found.kind}: ${found.detail} (step ${index + 1}: ${line(step)})`;
}

async function open(
  p: Plan,
  newTarget: () => Answer<Target>,
  scenario: string,
): Promise<Session & { scenario: string }> {
  const target = await newTarget();
  const correlation = newHarness(p.system).correlation();
  await target.beginScenario({ scenario, correlation });
  return { p, target, model: new Model(), correlation, undetermined: new Set(), scenario };
}

/** Replays `trace` on a fresh target: the disagreement it ends in, or null when it passes. */
async function replay(
  p: Plan,
  newTarget: () => Answer<Target>,
  trace: Step[],
  scenario: string,
): Promise<Found | null> {
  const s = await open(p, newTarget, scenario);
  const executed: Step[] = [];
  try {
    for (const recorded of trace) {
      const command = p.commands.find((candidate) => candidate.name === recorded.command);
      if (command === undefined) continue;
      const input = JSON.parse(JSON.stringify(recorded.input)) as Row;
      let resolvable = true;
      for (const [path, entity, index] of recorded.refs) {
        const known = s.model.of(entity);
        if (index >= known.length) resolvable = false;
        else setPath(input, path, (known[index] as Rec).id);
      }
      if (!resolvable) continue;
      const step: Step = { command: recorded.command, input, refs: recorded.refs };
      const decision = decide(command, input, s.model);
      if (decision.kind !== 'take') continue;
      let found: Disagreement | null;
      try {
        found = await perform(s, command, step, decision.outcome);
      } catch (error) {
        if (error instanceof Unsupported) continue;
        throw error;
      }
      executed.push(step);
      if (found !== null) {
        return { kind: found.kind, message: describe(found, executed.length - 1, step), executed };
      }
    }
    return null;
  } finally {
    await s.target.endScenario({ scenario: s.scenario, correlation: s.correlation });
  }
}

/**
 * explore runs `seeds` sequences of `steps` random commands, each on a fresh target, and checks
 * every step against the model interpreted from `ir.json`. It stops at the first disagreement and
 * shrinks it.
 *
 * Throws only when the model cannot be used: an absent or unreadable `ir.json`, or one that is not
 * the model `suite.json` was synthesized from. A disagreement is the result's `failure`.
 */
export async function explore(
  newTarget: () => Answer<Target>,
  options: ExploreOptions = {},
): Promise<ExploreResult> {
  const p = plan(loadModel());
  const steps = options.steps ?? DEFAULT_STEPS;
  const seeds: number[] = [];
  if (options.seed !== undefined) seeds.push(options.seed);
  else for (let seed = 1; seed <= (options.seeds ?? DEFAULT_SEEDS); seed += 1) seeds.push(seed);

  const reached = new Set<string>();
  const ambiguous = new Set<string>();
  const undetermined = new Set<string>();
  let executed = 0;
  let sequences = 0;
  let failure: ExploreFailure | undefined;

  for (const seed of seeds) {
    if (p.commands.length === 0 || failure !== undefined) break;
    sequences += 1;
    const rng = new Mulberry32(seed);
    const s = await open(p, newTarget, `explore/seed-${seed}`);
    s.undetermined = undetermined;
    const trace: Step[] = [];
    let found: Found | null = null;
    try {
      for (
        let attempts = 0;
        trace.length < steps && attempts < steps * ATTEMPTS_PER_STEP;
        attempts += 1
      ) {
        if (p.commands.length === 0) break;
        const command = rng.pick(p.commands);
        const step = draw(command, rng, s.model);
        if (step === null) continue;
        const decision = decide(command, step.input, s.model);
        if (decision.kind === 'ambiguous') {
          ambiguous.add(`${command.name}: ${decision.names.join(', ')}`);
          continue;
        }
        if (decision.kind === 'unknown') {
          exclude(p, command.name, decision.reason);
          continue;
        }
        let disagreement: Disagreement | null;
        try {
          disagreement = await perform(s, command, step, decision.outcome);
        } catch (error) {
          if (error instanceof Unsupported) {
            exclude(p, command.name, `the target does not expose it: ${error.message}`);
            continue;
          }
          throw error;
        }
        executed += 1;
        trace.push(step);
        reached.add(`${command.name}/${decision.outcome.name}`);
        if (disagreement !== null) {
          found = {
            kind: disagreement.kind,
            message: describe(disagreement, trace.length - 1, step),
            executed: [...trace],
          };
          break;
        }
      }
    } finally {
      await s.target.endScenario({ scenario: s.scenario, correlation: s.correlation });
    }
    if (found !== null) failure = await shrink(p, newTarget, seed, trace, found);
  }

  const unreached: string[] = [];
  const excludedOutcomes: string[] = [];
  for (const [command, outcomes] of p.declared) {
    for (const outcome of outcomes) {
      const id = `${command}/${outcome}`;
      if (p.excludedCommands.has(command)) excludedOutcomes.push(id);
      else if (!reached.has(id)) unreached.push(id);
    }
  }
  const result: ExploreResult = {
    sequences,
    steps,
    executed,
    reached: sortStrings([...reached]),
    unreached: sortStrings(unreached),
    excluded: [...p.excluded].sort(
      (left, right) =>
        byteCompare(left.subject, right.subject) || byteCompare(left.reason, right.reason),
    ),
    excludedOutcomes: sortStrings(excludedOutcomes),
    undetermined: sortStrings([...undetermined]),
    ambiguous: sortStrings([...ambiguous]),
  };
  if (failure !== undefined) result.failure = failure;
  return result;
}

/** Removes one step at a time, last to first, while the shorter trace still fails the same way. */
async function shrink(
  p: Plan,
  newTarget: () => Answer<Target>,
  seed: number,
  trace: Step[],
  found: Found,
): Promise<ExploreFailure> {
  let current = trace;
  let shortest = found;
  let replays = 0;
  let complete = true;
  for (let removed = true; removed; ) {
    removed = false;
    for (let index = current.length - 1; index >= 0; index -= 1) {
      if (replays >= SHRINK_REPLAYS) {
        complete = false;
        break;
      }
      const candidate = current.filter((_, position) => position !== index);
      replays += 1;
      const again = await replay(p, newTarget, candidate, `explore/seed-${seed}/shrink-${replays}`);
      if (again !== null && again.kind === found.kind) {
        current = candidate;
        shortest = again;
        removed = true;
      }
    }
    if (!complete) break;
  }
  return {
    seed,
    message: shortest.message,
    trace: shortest.executed.map(line),
    originalLength: trace.length,
    shrinkComplete: complete,
  };
}

/** What `assertExplored` would fail with, or null when it passes. */
export function exploreProblem(result: ExploreResult, options: AssertOptions = {}): string | null {
  const problems: string[] = [];
  if (result.failure !== undefined) {
    const failure = result.failure;
    problems.push(
      `explore: seed ${failure.seed}: ${failure.message}\n` +
        `shrunk trace (${failure.trace.length} of ${failure.originalLength} step(s)${failure.shrinkComplete ? '' : ', not minimal'}):\n` +
        failure.trace.map((step) => `  ${step}`).join('\n'),
    );
  }
  if (result.unreached.length > 0) {
    problems.push(
      `explore: ${result.unreached.length} declared outcome(s) no sequence reached:\n` +
        result.unreached.map((outcome) => `  ${outcome}`).join('\n'),
    );
  }
  if (result.excludedOutcomes.length > 0 && options.allowExcluded !== true) {
    problems.push(
      `explore: ${result.excludedOutcomes.length} declared outcome(s) of excluded commands were never tried:\n` +
        result.excludedOutcomes.map((outcome) => `  ${outcome}`).join('\n') +
        '\nexcluded:\n' +
        result.excluded
          .map((exclusion) => `  ${exclusion.subject}: ${exclusion.reason}`)
          .join('\n') +
        '\naccept them explicitly with { allowExcluded: true }',
    );
  }
  return problems.length === 0 ? null : problems.join('\n');
}

/**
 * assertExplored throws when an exploration failed, when a declared outcome went unreached, or
 * when an excluded command's outcomes were never tried and `allowExcluded` is not set. What the
 * model could not place, and the draws it would not decide, are printed and do not fail.
 */
export function assertExplored(result: ExploreResult, options: AssertOptions = {}): void {
  for (const note of result.undetermined) console.log(`explore: undetermined: ${note}`);
  for (const note of result.ambiguous) console.log(`explore: ambiguous: ${note}`);
  const problem = exploreProblem(result, options);
  if (problem !== null) throw new Error(problem);
}
