//! Filesystem and process boundary for additive CLI presentation bindings.

use std::{fs, path::PathBuf, process::ExitCode};

use anyhow::{bail, Context, Result};

#[derive(Debug, clap::Args)]
pub(crate) struct Input {
    #[command(flatten)]
    model: crate::SpecPath,
    /// An independently authored ess-cli/1 presentation document.
    #[arg(long)]
    binding: PathBuf,
}

#[derive(Debug, clap::Args)]
pub(crate) struct Generate {
    #[command(flatten)]
    input: Input,
    /// Generated package destination, outside the specification inputs.
    #[arg(long)]
    out: PathBuf,
    /// Compare generated bytes without changing output files.
    #[arg(long)]
    check: bool,
}

fn compile(input: &Input) -> Result<Option<ess_cli_contract::CompiledBinding>> {
    let Ok((ir, _)) = crate::resolved(&input.model.path, input.model.format)? else {
        return Ok(None);
    };
    let text = fs::read_to_string(&input.binding)
        .with_context(|| format!("reading {}", input.binding.display()))?;
    let binding = ess_cli_contract::Binding::from_yaml(&text)?;
    Ok(Some(ess_cli_contract::compile(&ir, &binding)?))
}

pub(crate) fn validate(input: &Input) -> Result<ExitCode> {
    let Some(binding) = compile(input)? else {
        return Ok(ExitCode::from(1));
    };
    match input.model.format {
        crate::Format::Json => println!("{}", binding.to_canonical_json()),
        crate::Format::Yaml => {
            let value: serde_json::Value = serde_json::from_str(&binding.to_canonical_json())?;
            crate::render(&value, crate::Format::Yaml)?;
        }
        crate::Format::Text => println!(
            "{} — valid CLI presentation binding",
            input.binding.display()
        ),
    }
    Ok(ExitCode::SUCCESS)
}

pub(crate) fn generate(args: &Generate) -> Result<ExitCode> {
    // Resolve every type, callable and projection before admitting any output mutation.
    let Some(binding) = compile(&args.input)? else {
        return Ok(ExitCode::from(1));
    };
    let files = ess_cli_project::project(&binding);
    let destination = crate::resolve_output_directory(&args.out)?;
    for input in [&args.input.model.path, &args.input.binding] {
        let source = fs::canonicalize(input)?;
        if (source.is_dir() && destination.starts_with(&source))
            || files.keys().any(|name| destination.join(name) == source)
        {
            bail!("CLI output must not replace or reside within its specification inputs");
        }
    }
    if args.check {
        let _guard = crate::output_ownership::check(&destination)?;
        let paths: Vec<_> = files.keys().map(String::as_str).collect();
        crate::preflight_generated_files(&destination, &paths)?;
        for (path, expected) in &files {
            let path = destination.join(path);
            let actual = fs::read(&path)
                .with_context(|| format!("reading {} for CLI drift check", path.display()))?;
            if actual != expected.as_bytes() {
                bail!(
                    "{} is stale; regenerate it with `ess generate cli`",
                    path.display()
                );
            }
        }
    } else {
        crate::write_owned_files(
            &destination,
            "cli-binding",
            files
                .iter()
                .map(|(name, bytes)| (name.as_str(), bytes.as_str())),
        )?;
    }
    let report = serde_json::json!({
        "format": "ess-cli-generation/1",
        "files": files.keys().collect::<Vec<_>>(),
        "checked": args.check,
    });
    match args.input.model.format {
        crate::Format::Text => println!(
            "{} CLI artifact(s), {} {}",
            files.len(),
            if args.check {
                "current in"
            } else {
                "generated in"
            },
            args.out.display()
        ),
        format => crate::render(&report, format)?,
    }
    Ok(ExitCode::SUCCESS)
}
