//! `ess generate ui --target tui`: an `ess-ui/1` document, bound to the served surface of its
//! model, becomes a Rust terminal application crate.
//!
//! The crate is four files and holds no renderer code:
//!
//! - `Cargo.toml`: its own workspace, depending on `clap` and on this crate by the Git tag of the
//!   ESS version that generated it.
//! - `src/main.rs`: a clap-derived command line (`--base-url`, `--screen-once`) calling
//!   [`crate::run_embedded`]; the `Authorization` header comes from `ESS_UI_AUTHORIZATION`.
//! - `src/ui.yaml`: the document, compiled in with `include_str!`.
//! - `src/binding.rs`: the route table the caller computed, as JSON.
//!
//! Each file opens with a [`MARK`] line, and a file already at one of these paths is replaced only
//! when it opens with that line too, and every path under `--out` the crate goes to is a plain
//! directory or file, never a symbolic link: an `--out` holding anything else is refused before
//! the first write, writing nothing.
//!
//! Nothing of the document reaches Rust source raw: no comment carries its text, and a string
//! literal holds a `rust_string` of it. A document that opens with the mark line (the crate's
//! own `src/ui.yaml`) is embedded without it, so generating from it again writes the same bytes;
//! so does the same document and binding wherever they are written.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use ess_ui::binding::Binding;

use crate::{profile, TuiError, AUTHORIZATION_VAR, TUI};

/// The repository the generated crate fetches `ess-ui-tui` from.
pub const REPOSITORY: &str = "https://github.com/beyond10x/ess";

/// The ESS version whose tag the generated crate depends on: the version of this crate.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The text after the comment marker on the first line of every generated file.
pub const MARK: &str = "generated by ess generate ui --target tui";

/// The names Cargo refuses as a binary target, in any casing: its build directory's own.
const RESERVED: [&str; 4] = ["build", "deps", "examples", "incremental"];

/// The files of the crate for `document` (its text) bound by `binding`, by path relative to the
/// crate root. The document is refused here, before anything is written, when it does not load
/// or the terminal cannot draw it.
pub fn render(document: &str, binding: &Binding) -> Result<BTreeMap<String, String>, TuiError> {
    let document = unmarked(document);
    let loaded = ess_ui::load_str_with(document, binding).map_err(TuiError::Load)?;
    profile::check(&loaded, &TUI).map_err(TuiError::Refused)?;
    let name = crate_name(&loaded.app);
    let json = serde_json::to_string_pretty(binding)
        .map_err(|error| TuiError::Binding(format!("the binding does not serialise: {error}")))?;
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".to_owned(), manifest(&name));
    files.insert("src/main.rs".to_owned(), main_rs(&name));
    files.insert("src/binding.rs".to_owned(), binding_rs(&json));
    files.insert("src/ui.yaml".to_owned(), format!("# {MARK}\n{document}"));
    Ok(files)
}

/// Reads the document at `path`, renders its crate with [`render`] and writes it under `out`;
/// returns a one-line summary. Nothing is written when the document is refused, or when a file
/// the crate would replace does not open with the [`MARK`] line of its kind.
pub fn generate(path: &Path, binding: &Binding, out: &Path) -> Result<String, TuiError> {
    let document = std::fs::read_to_string(path)
        .map_err(|error| TuiError::Io(format!("cannot read {}: {error}", path.display())))?;
    let files = render(&document, binding)?;
    if out.exists() && !out.is_dir() {
        return Err(TuiError::Io(format!(
            "--out {} is not a directory; nothing was written",
            out.display()
        )));
    }
    for (relative, text) in &files {
        admit(out, relative, text)?;
    }
    for (relative, text) in &files {
        let target = out.join(relative);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(|error| {
                TuiError::Io(format!("cannot create {}: {error}", parent.display()))
            })?;
        }
        std::fs::write(&target, text)
            .map_err(|error| TuiError::Io(format!("cannot write {}: {error}", target.display())))?;
    }
    Ok(format!(
        "{} files written to {}",
        files.len(),
        out.display()
    ))
}

/// `document` without a leading `# <MARK>` line: the crate's own `src/ui.yaml` is the document it
/// was generated from.
fn unmarked(document: &str) -> &str {
    document
        .strip_prefix("# ")
        .and_then(|rest| rest.strip_prefix(MARK))
        .and_then(|rest| {
            rest.strip_prefix("\r\n")
                .or_else(|| rest.strip_prefix('\n'))
        })
        .unwrap_or(document)
}

/// Whether `relative` (a `/`-separated path) may be written under `out` with `text`: each
/// directory on the way is absent or a directory, and the file absent or a file opening with the
/// first line of `text`; none of them a symbolic link. Nothing is read through a link.
fn admit(out: &Path, relative: &str, text: &str) -> Result<(), TuiError> {
    let refused = |why: String| {
        TuiError::Io(format!(
            "--out {}: {why}; nothing was written",
            out.display()
        ))
    };
    let parts: Vec<&str> = relative.split('/').collect();
    let mut path = out.to_path_buf();
    for (at, part) in parts.iter().enumerate() {
        path.push(part);
        let shown = parts[..=at].join("/");
        let Ok(metadata) = std::fs::symlink_metadata(&path) else {
            return Ok(());
        };
        if metadata.file_type().is_symlink() {
            return Err(refused(format!("{shown} is a symbolic link")));
        }
        if at + 1 < parts.len() {
            if !metadata.is_dir() {
                return Err(refused(format!("{shown} is not a directory")));
            }
            continue;
        }
        let first = text.lines().next().unwrap_or_default();
        let ours = metadata.is_file()
            && std::fs::read_to_string(&path)
                .is_ok_and(|existing| existing.lines().next() == Some(first));
        if !ours {
            return Err(refused(format!(
                "{shown} is already there and was not written by `ess generate ui --target tui` \
                 (its first line is not `{first}`)"
            )));
        }
    }
    Ok(())
}

/// The package and binary name for the document's `app`: lowercase ASCII letters, digits, `-`
/// and `_`, every other character as `-`; `app-` before one that does not start with a letter,
/// and `-tui` after one Cargo reserves ([`RESERVED`]).
fn crate_name(app: &str) -> String {
    let name: String = app
        .chars()
        .map(|character| match character {
            'a'..='z' | '0'..='9' | '-' | '_' => character,
            'A'..='Z' => character.to_ascii_lowercase(),
            _ => '-',
        })
        .collect();
    if !name.starts_with(|first: char| first.is_ascii_lowercase()) {
        format!("app-{name}")
    } else if RESERVED.contains(&name.as_str()) {
        format!("{name}-tui")
    } else {
        name
    }
}

/// `text` as a Rust string literal, quotes included: `\`, `"` and every character that is not
/// printable ASCII or a line break escaped, so no codepoint rustc refuses in a literal is there.
fn rust_string(text: &str) -> String {
    let mut literal = String::with_capacity(text.len() + 2);
    literal.push('"');
    for character in text.chars() {
        match character {
            '\\' => literal.push_str("\\\\"),
            '"' => literal.push_str("\\\""),
            ' '..='~' | '\n' => literal.push(character),
            other => {
                let _ = write!(literal, "\\u{{{:x}}}", u32::from(other));
            }
        }
    }
    literal.push('"');
    literal
}

fn manifest(name: &str) -> String {
    format!(
        "# {MARK}\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         [[bin]]\n\
         name = \"{name}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         clap = {{ version = \"4\", features = [\"derive\"] }}\n\
         ess-ui-tui = {{ git = \"{REPOSITORY}\", tag = \"{VERSION}\" }}\n\
         \n\
         [workspace]\n"
    )
}

/// `src/main.rs`. The document's own text reaches no comment: the doc comments name the crate by
/// [`crate_name`], whose characters Markdown and rustc take literally, and the command line's
/// name is a [`rust_string`].
fn main_rs(name: &str) -> String {
    let literal = rust_string(name);
    format!(
        r#"// {MARK}
//! The `{name}` terminal application, generated by `ess generate ui --target tui` (ESS
//! {VERSION}) from its `ess-ui/1` document. Generate it again rather than editing it.

mod binding;

use std::process::ExitCode;

use clap::Parser;

/// Runs the `{name}` ess-ui/1 document in the terminal against the HTTP surface it is bound to;
/// the Authorization header of every request is read from {AUTHORIZATION_VAR}, never from the
/// command line.
#[derive(Debug, Parser)]
#[command(name = {literal}, version)]
struct Cli {{
    /// Where a served component is reached, http:// only: <url> when the document binds one
    /// component, else <component>=<url>, once per component.
    #[arg(long = "base-url", value_name = "URL")]
    base_url: Vec<String>,
    /// Print one rendered frame of this size, such as 120x40 (at most 1000x1000), after the home
    /// page has read once, and exit without touching the terminal: 3 when a read of the page
    /// failed, the frame printed all the same.
    #[arg(long = "screen-once", value_name = "WIDTHxHEIGHT")]
    screen_once: Option<ess_ui_tui::ScreenSize>,
}}

const APP: ess_ui_tui::Embedded = ess_ui_tui::Embedded {{
    document: include_str!("ui.yaml"),
    binding: binding::BINDING,
}};

fn main() -> ExitCode {{
    let cli = Cli::parse();
    match ess_ui_tui::run_embedded(&APP, &cli.base_url, cli.screen_once) {{
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {{
            eprintln!("{{error}}");
            ExitCode::from(error.exit_code())
        }}
    }}
}}
"#
    )
}

fn binding_rs(json: &str) -> String {
    format!(
        "// {MARK}\n\
         //! The route table the document binds to, computed by `ess_ui_check::binding` when the\n\
         //! crate was generated.\n\
         \n\
         /// The `ess_ui::binding::Binding`, as JSON.\n\
         pub(crate) const BINDING: &str = {};\n",
        rust_string(json)
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn a_string_literal_escapes_what_rustc_would_refuse() {
        assert_eq!(super::rust_string("a\"b\\c"), r#""a\"b\\c""#);
        assert_eq!(super::rust_string("x\ny"), "\"x\ny\"");
        assert_eq!(
            super::rust_string("\r\t\u{202E}é"),
            r#""\u{d}\u{9}\u{202e}\u{e9}""#
        );
    }

    #[test]
    fn only_a_leading_mark_line_is_taken_off_the_document() {
        let mark = format!("# {}", super::MARK);
        assert_eq!(
            super::unmarked(&format!("{mark}\nformat: x\n")),
            "format: x\n"
        );
        assert_eq!(
            super::unmarked(&format!("{mark}\r\nformat: x\n")),
            "format: x\n"
        );
        let inner = format!("format: x\n{mark}\n");
        assert_eq!(super::unmarked(&inner), inner);
        let longer = format!("{mark} again\nformat: x\n");
        assert_eq!(super::unmarked(&longer), longer);
    }

    #[test]
    fn the_crate_name_is_a_valid_package_name() {
        assert_eq!(super::crate_name("desk"), "desk");
        assert_eq!(super::crate_name("front_desk"), "front_desk");
        assert_eq!(super::crate_name("9lives"), "app-9lives");
        assert_eq!(super::crate_name("Desk.v2"), "desk-v2");
        assert_eq!(super::crate_name("front\ndesk"), "front-desk");
        for reserved in ["build", "Deps", "EXAMPLES", "incremental"] {
            let name = super::crate_name(reserved);
            assert_eq!(name, format!("{}-tui", reserved.to_ascii_lowercase()));
        }
    }
}
