//! `ess generate ui --target tui`: an `ess-ui/1` document, bound to the served surface of its
//! model, becomes a Rust terminal application crate.
//!
//! The crate is four files and holds no renderer code:
//!
//! - `Cargo.toml`: its own workspace, depending on `clap` and on this crate by the Git tag of the
//!   ESS version that generated it.
//! - `src/main.rs`: a clap-derived command line (`--base-url`, `--screen-once`) calling
//!   [`crate::run_embedded`]; the `Authorization` header comes from `ESS_UI_AUTHORIZATION`.
//! - `src/ui.yaml`: the document, compiled in with `include_str!`.
//! - `src/binding.rs`: the route table the caller computed, as JSON.
//!
//! The same document and binding generate the same bytes wherever they are written.

use std::collections::BTreeMap;
use std::path::Path;

use ess_ui::binding::Binding;

use crate::{profile, TuiError, AUTHORIZATION_VAR, TUI};

/// The repository the generated crate fetches `ess-ui-tui` from.
pub const REPOSITORY: &str = "https://github.com/beyond10x/ess";

/// The ESS version whose tag the generated crate depends on: the version of this crate.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The files of the crate for `document` (its text) bound by `binding`, by path relative to the
/// crate root. The document is refused here, before anything is written, when it does not load
/// or the terminal cannot draw it.
pub fn render(document: &str, binding: &Binding) -> Result<BTreeMap<String, String>, TuiError> {
    let loaded = ess_ui::load_str(document).map_err(TuiError::Load)?;
    profile::check(&loaded, &TUI).map_err(TuiError::Refused)?;
    let name = crate_name(&loaded.app);
    let json = serde_json::to_string_pretty(binding)
        .map_err(|error| TuiError::Binding(format!("the binding does not serialise: {error}")))?;
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".to_owned(), manifest(&name));
    files.insert("src/main.rs".to_owned(), main_rs(&name, &loaded.app));
    files.insert("src/binding.rs".to_owned(), binding_rs(&json));
    files.insert("src/ui.yaml".to_owned(), document.to_owned());
    Ok(files)
}

/// Reads the document at `path`, renders its crate with [`render`] and writes it under `out`;
/// returns a one-line summary. Nothing is written when the document is refused.
pub fn generate(path: &Path, binding: &Binding, out: &Path) -> Result<String, TuiError> {
    let document = std::fs::read_to_string(path)
        .map_err(|error| TuiError::Io(format!("cannot read {}: {error}", path.display())))?;
    let files = render(&document, binding)?;
    for (relative, text) in &files {
        let target = out.join(relative);
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).map_err(|error| {
                TuiError::Io(format!("cannot create {}: {error}", parent.display()))
            })?;
        }
        std::fs::write(&target, text)
            .map_err(|error| TuiError::Io(format!("cannot write {}: {error}", target.display())))?;
    }
    Ok(format!(
        "{} files written to {}",
        files.len(),
        out.display()
    ))
}

/// The package and binary name for the document's `app`: lowercase ASCII letters, digits, `-`
/// and `_`, every other character as `-`, starting with a letter.
fn crate_name(app: &str) -> String {
    let name: String = app
        .chars()
        .map(|character| match character {
            'a'..='z' | '0'..='9' | '-' | '_' => character,
            'A'..='Z' => character.to_ascii_lowercase(),
            _ => '-',
        })
        .collect();
    if name.starts_with(|first: char| first.is_ascii_lowercase()) {
        name
    } else {
        format!("app-{name}")
    }
}

fn manifest(name: &str) -> String {
    format!(
        "[package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\
         \n\
         [[bin]]\n\
         name = \"{name}\"\n\
         path = \"src/main.rs\"\n\
         \n\
         [dependencies]\n\
         clap = {{ version = \"4\", features = [\"derive\"] }}\n\
         ess-ui-tui = {{ git = \"{REPOSITORY}\", tag = \"{VERSION}\" }}\n\
         \n\
         [workspace]\n"
    )
}

fn main_rs(name: &str, app: &str) -> String {
    format!(
        r#"//! The `{app}` terminal application, generated by `ess generate ui --target tui` (ESS
//! {VERSION}) from its `ess-ui/1` document. Generate it again rather than editing it.

mod binding;

use std::process::ExitCode;

use clap::Parser;

/// Runs the `{app}` ess-ui/1 document in the terminal against the HTTP surface it is bound to.
///
/// The Authorization header of every request is read from {AUTHORIZATION_VAR}, never from the
/// command line.
#[derive(Debug, Parser)]
#[command(name = "{name}", version)]
struct Cli {{
    /// Where a served component is reached, http:// only: <url> when the document binds one
    /// component, else <component>=<url>, once per component.
    #[arg(long = "base-url", value_name = "URL")]
    base_url: Vec<String>,
    /// Print one rendered frame of this size, such as 120x40, after the home page has read once,
    /// and exit without touching the terminal.
    #[arg(long = "screen-once", value_name = "WIDTHxHEIGHT")]
    screen_once: Option<ess_ui_tui::ScreenSize>,
}}

const APP: ess_ui_tui::Embedded = ess_ui_tui::Embedded {{
    document: include_str!("ui.yaml"),
    binding: binding::BINDING,
}};

fn main() -> ExitCode {{
    let cli = Cli::parse();
    match ess_ui_tui::run_embedded(&APP, &cli.base_url, cli.screen_once) {{
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {{
            eprintln!("{{error}}");
            ExitCode::from(1)
        }}
    }}
}}
"#
    )
}

fn binding_rs(json: &str) -> String {
    let hashes = "#".repeat(longest_hash_run(json) + 1);
    format!(
        "//! The route table the document binds to, computed by `ess_ui_check::binding` when the\n\
         //! crate was generated.\n\
         \n\
         /// The `ess_ui::binding::Binding`, as JSON.\n\
         pub(crate) const BINDING: &str = r{hashes}\"{json}\"{hashes};\n"
    )
}

/// The longest run of `#` directly after a `"` in `text`, so a raw string can hold it.
fn longest_hash_run(text: &str) -> usize {
    text.split('"')
        .skip(1)
        .map(|after| {
            after
                .chars()
                .take_while(|character| *character == '#')
                .count()
        })
        .max()
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    #[test]
    fn a_raw_string_outlasts_every_hash_run() {
        assert_eq!(super::longest_hash_run(r#"{"a":"b"}"#), 0);
        assert_eq!(super::longest_hash_run(r###"{"a":"b"##"}"###), 2);
        assert!(super::binding_rs(r##"{"a":"x"#"}"##).contains(r###"r##"{"a":"x"#"}"##;"###));
    }

    #[test]
    fn the_crate_name_is_a_valid_package_name() {
        assert_eq!(super::crate_name("desk"), "desk");
        assert_eq!(super::crate_name("front_desk"), "front_desk");
        assert_eq!(super::crate_name("9lives"), "app-9lives");
        assert_eq!(super::crate_name("Desk.v2"), "desk-v2");
    }
}
