//! Actor grants as generated data (story `actor-grants-as-data`).
//!
//! Generated code still enforces no grant: who is calling is a fact the caller holds. What the
//! specification does determine — which actors exist and which commands each may invoke — is
//! emitted into the types crate, so a caller enforces a generated table instead of a hand-copied
//! one. The harness below lives outside the generated bytes, builds against the types crate with
//! every warning an error, and prints the table it reads back.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use ess_compiler::{resolve::compile, source::SourceMap, EssIr};
use ess_domain::{spec::RawSpecFile, system::Source, Specification};
use ess_synth::{
    synthesize_for, CapabilityKind, RefusalReason, RefusalStage, Synthesis, SynthesisDisposition,
    Target,
};

const SYSTEM: &str = "format: ess/1
system: desk
version: v1
domains:
  - desk.tickets
  - desk.audit
";

/// Three actors in one domain and one in another: several grants (one of them across domains,
/// written out of name order), a single grant, and none at all. `Clerk` is declared in both
/// domains, so the variant names have to be repaired rather than collide.
const TICKETS: &str = "domain: desk.tickets
events:
  - name: desk.tickets.Opened
    fields:
      - {name: id, type: String}
  - name: desk.tickets.Closed
    fields:
      - {name: id, type: String}
commands:
  - name: desk.tickets.OpenTicket
    input:
      - {name: id, type: String}
    outcomes:
      - name: opened
        emits: [desk.tickets.Opened]
        payload:
          desk.tickets.Opened: {id: input.id}
  - name: desk.tickets.CloseTicket
    input:
      - {name: id, type: String}
    outcomes:
      - name: closed
        emits: [desk.tickets.Closed]
        payload:
          desk.tickets.Closed: {id: input.id}
actors:
  - name: desk.tickets.Clerk
    may:
      - desk.tickets.OpenTicket
      - desk.tickets.CloseTicket
      - desk.audit.Review
  - name: desk.tickets.Watcher
";

const AUDIT: &str = "domain: desk.audit
events:
  - name: desk.audit.Reviewed
    fields:
      - {name: id, type: String}
commands:
  - name: desk.audit.Review
    input:
      - {name: id, type: String}
    outcomes:
      - name: reviewed
        emits: [desk.audit.Reviewed]
        payload:
          desk.audit.Reviewed: {id: input.id}
actors:
  - name: desk.audit.Clerk
    may:
      - desk.audit.Review
";

/// Reads the generated table back through its public surface only, and prints it.
const HARNESS: &str = r#"use desk_types::actor::{may, Actor};

fn main() {
    assert_eq!(Actor::ALL.len(), 3);
    for actor in Actor::ALL {
        let actor: Actor = *actor;
        println!("{} {:?} -> [{}]", actor.name(), actor, may(actor).join(", "));
    }
    assert_eq!(may(Actor::TicketsWatcher), &[] as &[&str]);
}
"#;

const EXPECTED: &str = concat!(
    "desk.audit.Clerk AuditClerk -> [desk.audit.Review]\n",
    "desk.tickets.Clerk TicketsClerk -> [desk.audit.Review, desk.tickets.CloseTicket, \
     desk.tickets.OpenTicket]\n",
    "desk.tickets.Watcher TicketsWatcher -> []\n",
);

fn ir(files: &[(&str, &str)]) -> EssIr {
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for (label, text) in files {
        sources.insert(*label, *text);
        parsed.push((
            Source::new(*label),
            RawSpecFile::parse(text).unwrap_or_else(|error| panic!("{label}: {error}")),
        ));
    }
    let spec =
        Specification::assemble(parsed).unwrap_or_else(|errors| panic!("validates: {errors}"));
    compile(&spec, &sources).unwrap_or_else(|errors| panic!("compiles: {errors}"))
}

fn desk() -> EssIr {
    ir(&[
        ("system.yaml", SYSTEM),
        ("tickets.yaml", TICKETS),
        ("audit.yaml", AUDIT),
    ])
}

fn scratch(label: &str) -> PathBuf {
    Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!("actor-grants-{label}"))
}

fn write(synthesis: &Synthesis, directory: &Path) {
    let _ = std::fs::remove_dir_all(directory);
    for (relative, artifact) in &synthesis.artifacts {
        let destination = directory.join(relative);
        std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
        std::fs::write(&destination, &artifact.contents).unwrap();
    }
}

/// Cargo inside the harness, with every warning an error: generated code that warns is an emitter
/// defect a consumer's own `-D warnings` build would inherit.
fn cargo(directory: &Path, arguments: &[&str]) -> Output {
    let output = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args(arguments)
        .current_dir(directory)
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env("RUSTFLAGS", "-D warnings")
        .output()
        .expect("cargo runs");
    eprintln!(
        "cargo {arguments:?} in {}\n{}{}",
        directory.display(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

#[test]
fn the_types_crate_carries_every_actor_and_its_grants_as_data() {
    let synthesis = synthesize_for(&desk(), Target::Rust).expect("the fixture synthesizes");
    let root = scratch("harness");
    let generated = root.join("generated");
    write(&synthesis, &generated);
    let harness = root.join("harness");
    std::fs::create_dir_all(harness.join("src")).unwrap();
    std::fs::write(
        harness.join("Cargo.toml"),
        "[package]\nname = \"grants-harness\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n\
         [dependencies]\ndesk-types = { path = \"../generated/crates/desk-types\" }\n\n\
         [workspace]\n",
    )
    .unwrap();
    std::fs::write(harness.join("src/main.rs"), HARNESS).unwrap();
    let target = root.join("target");
    let run = cargo(
        &harness,
        &[
            "run",
            "--offline",
            "--quiet",
            "--target-dir",
            target.to_str().unwrap(),
        ],
    );
    let stdout = String::from_utf8_lossy(&run.stdout).into_owned();
    let _ = std::fs::remove_dir_all(&root);
    assert!(
        run.status.success(),
        "the harness reads the generated table"
    );
    assert_eq!(stdout, EXPECTED);
}

#[test]
fn every_actor_grants_row_says_the_grant_is_data_and_enforcement_is_the_callers() {
    let synthesis = synthesize_for(&desk(), Target::Rust).expect("the fixture synthesizes");
    for (actor, grants) in [
        ("desk.audit.Clerk", "may invoke `desk.audit.Review`"),
        (
            "desk.tickets.Clerk",
            "may invoke `desk.audit.Review`, `desk.tickets.CloseTicket`, \
             `desk.tickets.OpenTicket`",
        ),
        (
            "desk.tickets.Watcher",
            "observes only; it may invoke no command",
        ),
    ] {
        let disposition = synthesis
            .plan
            .disposition_of(CapabilityKind::ActorGrants, actor)
            .expect("every actor is planned");
        let SynthesisDisposition::Refused(refusal) = disposition else {
            panic!("enforcing `{actor}`'s grant stays refused, not {disposition:?}");
        };
        assert_eq!(refusal.reason, RefusalReason::NeedsCallerIdentity);
        assert_eq!(refusal.stage, RefusalStage::Planning);
        assert_eq!(
            refusal.detail,
            format!(
                "{grants}; generated as data, not enforced: the grant is available as the \
                 declared actors and the qualified commands each may invoke, and enforcement \
                 stays with the caller, because a grant is checked against a caller identity, \
                 which types do not carry"
            )
        );
        let markdown = &synthesis.artifacts["PLAN.md"].contents;
        assert!(
            markdown.contains(&format!(
                "| actor grants | `{actor}` | planning | {} |",
                refusal.detail
            )),
            "PLAN.md carries `{actor}`'s row:\n{markdown}"
        );
    }
}

#[test]
fn a_model_without_actors_emits_no_grant_table() {
    let lone = ir(&[
        (
            "system.yaml",
            SYSTEM.replace("  - desk.audit\n", "").as_str(),
        ),
        (
            "tickets.yaml",
            TICKETS
                .split("actors:")
                .next()
                .expect("the fixture has a head"),
        ),
    ]);
    assert!(lone.actors().is_empty());
    let synthesis = synthesize_for(&lone, Target::Rust).expect("the model synthesizes");
    assert!(!synthesis
        .artifacts
        .keys()
        .any(|path| path.ends_with("/actor.rs")));
    let lib = &synthesis.artifacts["crates/desk-types/src/lib.rs"].contents;
    assert!(!lib.contains("actor"), "{lib}");
}
