//! Actor grants as generated data (story `actor-grants-as-data`), and enforced by a served surface
//! (beyond10x/ess#265).
//!
//! What the specification determines — which actors exist and which commands each may invoke — is
//! emitted into the types crate, so a caller enforces a generated table instead of a hand-copied
//! one. The harness below lives outside the generated bytes, builds against the types crate with
//! every warning an error, and prints the table it reads back.
//!
//! Where the specification serves a component, the generated Rust and Go servers are handed the
//! caller the realization authenticated a request as, and check its grant before the port runs:
//! no caller, or an actor without the grant, is the standard refusal, `403` `{"refused": "not
//! granted", "actor": …}`. A server with the check taken out fails the synthesized suite.

use std::fmt::Write as _;
use std::io::{BufRead as _, BufReader, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Output, Stdio};

use ess_compiler::{resolve::compile, source::SourceMap, EssIr};
use ess_domain::{spec::RawSpecFile, system::Source, Specification};
use ess_synth::{
    synthesize_for, CapabilityKind, RefusalReason, RefusalStage, Synthesis, SynthesisDisposition,
    Target,
};

const SYSTEM: &str = "format: ess/1
system: desk
version: v1
domains:
  - desk.tickets
  - desk.audit
";

/// Three actors in one domain and one in another: several grants (one of them across domains,
/// written out of name order), a single grant, and none at all. `Clerk` is declared in both
/// domains, so the variant names have to be repaired rather than collide.
const TICKETS: &str = "domain: desk.tickets
events:
  - name: desk.tickets.Opened
    fields:
      - {name: id, type: String}
  - name: desk.tickets.Closed
    fields:
      - {name: id, type: String}
commands:
  - name: desk.tickets.OpenTicket
    input:
      - {name: id, type: String}
    outcomes:
      - name: opened
        emits: [desk.tickets.Opened]
        payload:
          desk.tickets.Opened: {id: input.id}
  - name: desk.tickets.CloseTicket
    input:
      - {name: id, type: String}
    outcomes:
      - name: closed
        emits: [desk.tickets.Closed]
        payload:
          desk.tickets.Closed: {id: input.id}
actors:
  - name: desk.tickets.Clerk
    may:
      - desk.tickets.OpenTicket
      - desk.tickets.CloseTicket
      - desk.audit.Review
  - name: desk.tickets.Watcher
";

const AUDIT: &str = "domain: desk.audit
events:
  - name: desk.audit.Reviewed
    fields:
      - {name: id, type: String}
commands:
  - name: desk.audit.Review
    input:
      - {name: id, type: String}
    outcomes:
      - name: reviewed
        emits: [desk.audit.Reviewed]
        payload:
          desk.audit.Reviewed: {id: input.id}
actors:
  - name: desk.audit.Clerk
    may:
      - desk.audit.Review
";

/// Reads the generated table back through its public surface only, and prints it.
const HARNESS: &str = r#"use desk_types::actor::{may, Actor};

fn main() {
    assert_eq!(Actor::ALL.len(), 3);
    for actor in Actor::ALL {
        let actor: Actor = *actor;
        println!("{} {:?} -> [{}]", actor.name(), actor, may(actor).join(", "));
    }
    assert_eq!(may(Actor::TicketsWatcher), &[] as &[&str]);
}
"#;

const EXPECTED: &str = concat!(
    "desk.audit.Clerk AuditClerk -> [desk.audit.Review]\n",
    "desk.tickets.Clerk TicketsClerk -> [desk.audit.Review, desk.tickets.CloseTicket, \
     desk.tickets.OpenTicket]\n",
    "desk.tickets.Watcher TicketsWatcher -> []\n",
);

fn ir(files: &[(&str, &str)]) -> EssIr {
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for (label, text) in files {
        sources.insert(*label, *text);
        parsed.push((
            Source::new(*label),
            RawSpecFile::parse(text).unwrap_or_else(|error| panic!("{label}: {error}")),
        ));
    }
    let spec =
        Specification::assemble(parsed).unwrap_or_else(|errors| panic!("validates: {errors}"));
    compile(&spec, &sources).unwrap_or_else(|errors| panic!("compiles: {errors}"))
}

fn desk() -> EssIr {
    ir(&[
        ("system.yaml", SYSTEM),
        ("tickets.yaml", TICKETS),
        ("audit.yaml", AUDIT),
    ])
}

fn scratch(label: &str) -> PathBuf {
    // One directory per test process: nextest runs each test in its own process, and the
    // served build rewrites its generated surface in place to make the mutant.
    Path::new(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("actor-grants-{label}-{}", std::process::id()))
}

fn write(synthesis: &Synthesis, directory: &Path) {
    let _ = std::fs::remove_dir_all(directory);
    for (relative, artifact) in &synthesis.artifacts {
        let destination = directory.join(relative);
        std::fs::create_dir_all(destination.parent().unwrap()).unwrap();
        std::fs::write(&destination, &artifact.contents).unwrap();
    }
}

/// Cargo inside the harness, with every warning an error: generated code that warns is an emitter
/// defect a consumer's own `-D warnings` build would inherit.
fn cargo(directory: &Path, arguments: &[&str]) -> Output {
    let output = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args(arguments)
        .current_dir(directory)
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env("RUSTFLAGS", "-D warnings")
        .output()
        .expect("cargo runs");
    eprintln!(
        "cargo {arguments:?} in {}\n{}{}",
        directory.display(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

#[test]
fn the_types_crate_carries_every_actor_and_its_grants_as_data() {
    let synthesis = synthesize_for(&desk(), Target::Rust).expect("the fixture synthesizes");
    let root = scratch("harness");
    let generated = root.join("generated");
    write(&synthesis, &generated);
    let harness = root.join("harness");
    std::fs::create_dir_all(harness.join("src")).unwrap();
    std::fs::write(
        harness.join("Cargo.toml"),
        "[package]\nname = \"grants-harness\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n\
         [dependencies]\ndesk-types = { path = \"../generated/crates/desk-types\" }\n\n\
         [workspace]\n",
    )
    .unwrap();
    std::fs::write(harness.join("src/main.rs"), HARNESS).unwrap();
    let target = root.join("target");
    let run = cargo(
        &harness,
        &[
            "run",
            "--offline",
            "--quiet",
            "--target-dir",
            target.to_str().unwrap(),
        ],
    );
    let stdout = String::from_utf8_lossy(&run.stdout).into_owned();
    let _ = std::fs::remove_dir_all(&root);
    assert!(
        run.status.success(),
        "the harness reads the generated table"
    );
    assert_eq!(stdout, EXPECTED);
}

#[test]
fn every_actor_grants_row_says_the_grant_is_data_and_enforcement_is_the_callers() {
    let synthesis = synthesize_for(&desk(), Target::Rust).expect("the fixture synthesizes");
    for (actor, grants) in [
        ("desk.audit.Clerk", "may invoke `desk.audit.Review`"),
        (
            "desk.tickets.Clerk",
            "may invoke `desk.audit.Review`, `desk.tickets.CloseTicket`, \
             `desk.tickets.OpenTicket`",
        ),
        (
            "desk.tickets.Watcher",
            "observes only; it may invoke no command",
        ),
    ] {
        let disposition = synthesis
            .plan
            .disposition_of(CapabilityKind::ActorGrants, actor)
            .expect("every actor is planned");
        let SynthesisDisposition::Refused(refusal) = disposition else {
            panic!("enforcing `{actor}`'s grant stays refused, not {disposition:?}");
        };
        assert_eq!(refusal.reason, RefusalReason::NeedsCallerIdentity);
        assert_eq!(refusal.stage, RefusalStage::Planning);
        assert_eq!(
            refusal.detail,
            format!(
                "{grants}; generated as data, not enforced: the grant is available as the \
                 declared actors and the qualified commands each may invoke, and enforcement \
                 stays with the caller, because a grant is checked against a caller identity, \
                 which types do not carry"
            )
        );
        let markdown = &synthesis.artifacts["PLAN.md"].contents;
        assert!(
            markdown.contains(&format!(
                "| actor grants | `{actor}` | planning | {} |",
                refusal.detail
            )),
            "PLAN.md carries `{actor}`'s row:\n{markdown}"
        );
    }
}

#[test]
fn a_model_without_actors_emits_no_grant_table() {
    let lone = ir(&[
        (
            "system.yaml",
            SYSTEM.replace("  - desk.audit\n", "").as_str(),
        ),
        (
            "tickets.yaml",
            TICKETS
                .split("actors:")
                .next()
                .expect("the fixture has a head"),
        ),
    ]);
    assert!(lone.actors().is_empty());
    let synthesis = synthesize_for(&lone, Target::Rust).expect("the model synthesizes");
    assert!(!synthesis
        .artifacts
        .keys()
        .any(|path| path.ends_with("/actor.rs")));
    let lib = &synthesis.artifacts["crates/desk-types/src/lib.rs"].contents;
    assert!(!lib.contains("actor"), "{lib}");
}

// ---- a served surface enforces the grant (beyond10x/ess#265) -----------------------------------

/// `served_unfinished_committed`'s model, with two actors: `Operator` may invoke every command,
/// `Watcher` only `Open`. `Ping`'s behaviour answers an unmet obligation, so a granted caller that
/// reaches the port gets `501`, and one refused before it gets `403`.
const SERVED: &str = "format: ess/15
system: ops
version: v1
domain: ops.core
events:
  - name: ops.core.Opened
    fields:
      - {name: id, type: String}
  - name: ops.core.Noted
    fields:
      - {name: id, type: String}
  - name: ops.core.Pinged
    fields: []
commands:
  - name: ops.core.Open
    input:
      - {name: id, type: String}
      - {name: count, type: Integer}
    outcomes:
      - name: opened
        when: count > 0
        emits: [ops.core.Opened]
        payload:
          ops.core.Opened: {id: input.id}
      - name: refused
        error: ops.core.Bad
  - name: ops.core.Note
    input:
      - {name: id, type: String}
    outcomes:
      - name: noted
        emits: [ops.core.Noted]
        payload:
          ops.core.Noted: {id: input.id}
  - name: ops.core.Ping
    outcomes:
      - name: pinged
        emits: [ops.core.Pinged]
errors:
  - name: ops.core.Bad
actors:
  - name: ops.core.Operator
    may: [ops.core.Open, ops.core.Note, ops.core.Ping]
  - name: ops.core.Watcher
    may: [ops.core.Open]
components:
  - component: ops-service
    owns: {domains: [ops.core]}
    accepts: {commands: [ops.core.Open, ops.core.Note, ops.core.Ping]}
    publishes: {events: [ops.core.Opened, ops.core.Noted, ops.core.Pinged]}
    reached_by: network
";

/// The generated behaviours, except `Ping`, whose behaviour answers an unmet obligation.
const REALIZATION: &str = r#"use ops_types::behaviour::Generated;
use ops_types::core;
use ops_types::core::obligations::{NoteBehavior, OpenBehavior, PingBehavior};
use ops_types::obligation::UnmetObligation;

#[derive(Clone, Default)]
pub struct Desk;

pub struct Partly(pub Generated<Desk>);

impl OpenBehavior for Partly {
    fn open(&mut self, input: core::Open) -> Result<core::OpenOutcome, UnmetObligation> {
        self.0.open(input)
    }
}

impl NoteBehavior for Partly {
    fn note(&mut self, input: core::Note) -> Result<core::NoteOutcome, UnmetObligation> {
        self.0.note(input)
    }
}

impl PingBehavior for Partly {
    fn ping(&mut self, _input: core::Ping) -> Result<core::PingOutcome, UnmetObligation> {
        Err(UnmetObligation { capability: "command_behavior", source: "ops.core.Ping" })
    }
}

pub type System = ops_system::System<Partly>;

pub fn system() -> System {
    ops_system::System::new(ops_service::OpsService::new(Partly(Generated::new(Desk))))
}
"#;

/// One request per line on standard input — `command<TAB>actor or -<TAB>body`, or `reset` — and
/// one answer per line on standard output, `status<TAB>body`. The actor is turned into the
/// generated `Caller` here, where the realization would authenticate it; the request itself
/// carries none.
const SERVE_LINES: &str = r#"use std::io::{BufRead, Write};

use ops_server::http;
use ops_server::ops_service as surface;
use ops_types::actor::{Actor, Caller};

#[path = "../realization.rs"]
mod realization;

fn main() {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    let routes: Vec<(String, String, String)> = arguments
        .chunks(3)
        .map(|row| (row[0].clone(), row[1].clone(), row[2].clone()))
        .collect();
    let mut system = realization::system();
    let stdin = std::io::stdin();
    let mut stdout = std::io::stdout();
    for line in stdin.lock().lines() {
        let line = line.expect("a line");
        if line == "reset" {
            system = realization::system();
            writeln!(stdout, "ok").expect("written");
            stdout.flush().expect("flushed");
            continue;
        }
        let mut parts = line.splitn(3, '\t');
        let name = parts.next().expect("a command");
        let actor = parts.next().expect("an actor");
        let body = parts.next().unwrap_or("");
        let caller = Actor::ALL
            .iter()
            .find(|declared| declared.name() == actor)
            .map(|declared| Caller { actor: *declared });
        let (_, method, path) = routes
            .iter()
            .find(|(declared, _, _)| declared == name)
            .unwrap_or_else(|| panic!("`{name}` is a route"));
        let request = http::Request {
            method: method.clone(),
            path: path.clone(),
            query: String::new(),
            headers: Vec::new(),
            body: body.as_bytes().to_vec(),
        };
        let answered = surface::dispatch(&mut system, caller.as_ref(), &request);
        writeln!(stdout, "{}\t{}", answered.status, answered.body.replace('\t', " ")).expect("written");
        stdout.flush().expect("flushed");
    }
}
"#;

/// The transport-free entry point refuses the same callers, as a value.
const TYPED: &str = r#"use ops_server::entry::Refused;
use ops_server::json;
use ops_server::ops_service as surface;
use ops_types::actor::{Actor, Caller};

#[path = "../realization.rs"]
mod realization;

fn main() {
    let mut system = realization::system();
    let watcher = Caller { actor: Actor::Watcher };
    let operator = Caller { actor: Actor::Operator };
    for (label, caller) in [("absent", None), ("ungranted", Some(&watcher)), ("granted", Some(&operator))] {
        let refused = surface::handle(&mut system, caller, "ops.core.Ping", json::parse("{}").expect("JSON"))
            .expect_err("each case is refused");
        let variant = match &refused {
            Refused::NotGranted(Some(actor)) => format!("not-granted {actor}"),
            Refused::NotGranted(None) => "not-granted none".to_owned(),
            Refused::Unmet(_) => "unmet".to_owned(),
            other => format!("{other:?}"),
        };
        println!("{label}\t{}\t{variant}", refused.status());
    }
}
"#;

fn served_ir() -> EssIr {
    ir(&[("spec.yaml", SERVED)])
}

/// Every route, as `name method path` triples a harness takes on its command line.
fn route_arguments(ir: &EssIr) -> Vec<String> {
    let component = ir.components().values().next().expect("one component");
    let mut table = Vec::new();
    for route in ess_gen::http::routes(ir, component) {
        let name = match route.serves {
            ess_gen::http::Served::Command(handle) => ir.command(handle).name.to_string(),
            ess_gen::http::Served::View(handle) => ir.view(handle).name.to_string(),
        };
        table.extend([name, route.method.as_str().to_owned(), route.path]);
    }
    table
}

/// The two harness binaries, built against the generated server, and against the same server with
/// the grant check taken out: `(served, typed, mutant)`.
struct Built {
    served: PathBuf,
    typed: PathBuf,
    mutant: PathBuf,
}

/// The grant check the generated server runs before every command, as it is emitted.
const ADMIT: &str =
    "    match caller {\n        Some(caller) if caller.may(command) => Ok(()),\n        \
                     Some(caller) => Err(Some(caller.actor.name())),\n        None => \
                     Err(None),\n    }\n";

/// The mutant: the same function admitting every caller, so every command reaches the port.
const SKIPPED: &str = "    let _ = (caller, command);\n    Ok(())\n";

fn built() -> &'static Built {
    static BUILT: std::sync::OnceLock<Built> = std::sync::OnceLock::new();
    BUILT.get_or_init(|| {
        let synthesis = ess_synth::synthesize_laid_out(
            &served_ir(),
            Target::Rust,
            ess_synth::OutputLayout::Workspace,
        )
        .expect("the model synthesizes");
        let root = scratch("served");
        write(&synthesis, &root.join("ops"));
        let harness = root.join("harness");
        std::fs::create_dir_all(harness.join("src/bin")).unwrap();
        let dependencies = ["ops-server", "ops-system", "ops-service", "ops-types"]
            .iter()
            .fold(String::new(), |mut out, name| {
                let _ = writeln!(out, "{name} = {{ path = \"../ops/crates/{name}\" }}");
                out
            });
        std::fs::write(
            harness.join("Cargo.toml"),
            format!(
                "[package]\nname = \"grant-harness\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\
                 autobins = false\n\n[[bin]]\nname = \"served\"\npath = \"src/bin/served.rs\"\n\n\
                 [[bin]]\nname = \"typed\"\npath = \"src/bin/typed.rs\"\n\n[dependencies]\n\
                 {dependencies}\n[workspace]\n"
            ),
        )
        .unwrap();
        std::fs::write(harness.join("src/realization.rs"), REALIZATION).unwrap();
        std::fs::write(harness.join("src/bin/served.rs"), SERVE_LINES).unwrap();
        std::fs::write(harness.join("src/bin/typed.rs"), TYPED).unwrap();
        let target = root.join("target");
        let build = || {
            let built = cargo(
                &harness,
                &[
                    "build",
                    "--offline",
                    "--quiet",
                    "--target-dir",
                    target.to_str().unwrap(),
                ],
            );
            assert!(built.status.success(), "the harness builds");
        };
        build();
        let kept = root.join("kept");
        std::fs::create_dir_all(&kept).unwrap();
        for bin in ["served", "typed"] {
            std::fs::copy(target.join("debug").join(bin), kept.join(bin)).unwrap();
        }
        // The mutant: the grant check admits every caller, so every command reaches the port.
        let surface = root.join("ops/crates/ops-server/src/ops_service.rs");
        let source = std::fs::read_to_string(&surface).unwrap();
        assert_eq!(
            source.matches(ADMIT).count(),
            1,
            "one grant check:\n{source}"
        );
        std::fs::write(&surface, source.replace(ADMIT, SKIPPED)).unwrap();
        build();
        std::fs::copy(target.join("debug/served"), kept.join("mutant")).unwrap();
        Built {
            served: kept.join("served"),
            typed: kept.join("typed"),
            mutant: kept.join("mutant"),
        }
    })
}

/// The served harness's answers to a fixed list of requests: `label<TAB>status<TAB>body`.
fn answers(
    binary: &Path,
    requests: &[(&str, &str, &str, &str)],
) -> Vec<(String, u16, serde_json::Value)> {
    let mut served = Served::start(binary);
    requests
        .iter()
        .map(|(label, command, actor, body)| {
            let (status, body) = served.send(command, actor, body);
            ((*label).to_owned(), status, body)
        })
        .collect()
}

#[test]
fn a_served_model_plans_the_grant_as_generated() {
    let synthesis = synthesize_for(&served_ir(), Target::Rust).expect("synthesizes");
    for actor in ["ops.core.Operator", "ops.core.Watcher"] {
        assert_eq!(
            synthesis
                .plan
                .disposition_of(CapabilityKind::ActorGrants, actor),
            Some(&SynthesisDisposition::Generated),
            "{actor}"
        );
    }
    let go = synthesize_for(&served_ir(), Target::Go).expect("synthesizes for Go");
    let target = &go.artifacts["TARGET.md"].contents;
    assert!(!target.contains("emits no grant table"), "{target}");
}

#[test]
fn the_rust_server_refuses_a_caller_no_grant_admits_before_the_port_runs() {
    let answered = answers(
        &built().served,
        &[
            ("absent", "ops.core.Ping", "-", "{}"),
            ("undeclared", "ops.core.Ping", "ops.core.Nobody", "{}"),
            ("ungranted", "ops.core.Ping", "ops.core.Watcher", "{}"),
            ("granted", "ops.core.Ping", "ops.core.Operator", "{}"),
            (
                "granted-elsewhere",
                "ops.core.Open",
                "ops.core.Watcher",
                r#"{"id":"e","count":0}"#,
            ),
        ],
    );
    let expected = [
        (
            "absent",
            403,
            Some(serde_json::json!({"refused": "not granted", "actor": null})),
        ),
        (
            "undeclared",
            403,
            Some(serde_json::json!({"refused": "not granted", "actor": null})),
        ),
        (
            "ungranted",
            403,
            Some(serde_json::json!({"refused": "not granted", "actor": "ops.core.Watcher"})),
        ),
        // The port ran: `Ping`'s behaviour is unmet.
        ("granted", 501, None),
        // The port ran, and `Open` decided: `count` is not above zero.
        ("granted-elsewhere", 422, None),
    ];
    for ((label, status, body), (want_label, want_status, want_body)) in
        answered.iter().zip(expected)
    {
        assert_eq!(label, want_label);
        assert_eq!(*status, want_status, "`{label}`: {body}");
        if let Some(want) = want_body {
            assert_eq!(body, &want, "`{label}`");
        } else {
            assert!(
                body.get("refused") != Some(&serde_json::json!("not granted")),
                "`{label}`: {body}"
            );
        }
    }
}

#[test]
fn the_rust_entry_point_refuses_the_same_callers_as_a_value() {
    let output = Command::new(&built().typed)
        .output()
        .expect("the typed harness runs");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(
        String::from_utf8_lossy(&output.stdout),
        "absent\t403\tnot-granted none\nungranted\t403\tnot-granted ops.core.Watcher\n\
         granted\t501\tunmet\n"
    );
}

/// The synthesized suite's `…/grant/denied` scenarios, run through the served surface: the
/// generated server passes every one, and the same server with the check taken out fails every one.
#[test]
fn a_server_that_skips_the_grant_check_fails_the_synthesized_suite() {
    use ess_conformance::report::Status;
    let ir = served_ir();
    let mut suite = ess_conformance::synthesize(&ir).suite;
    suite
        .scenarios
        .retain(|id, _| matches!(id, ess_conformance::ScenarioId::Grant { .. }));
    let ids: Vec<String> = suite.scenarios.keys().map(ToString::to_string).collect();
    assert_eq!(
        ids,
        ["ops.core.Note/grant/denied", "ops.core.Ping/grant/denied"],
        "`Open` is every actor's, so it owes none"
    );
    let admitted = ess_conformance::AdmittedSuite::from_suite(&suite).expect("admits");
    let run = |binary: &Path| {
        let target = ServedTarget(std::cell::RefCell::new(Served::start(binary)));
        ess_conformance::Runner::for_suite(&suite)
            .run_admitted(&admitted, &target)
            .into_report()
            .scenarios
            .into_iter()
            .map(|scenario| (scenario.scenario.to_string(), scenario.status))
            .collect::<Vec<_>>()
    };
    assert_eq!(
        run(&built().served),
        [
            ("ops.core.Note/grant/denied".to_owned(), Status::Passed),
            ("ops.core.Ping/grant/denied".to_owned(), Status::Passed),
        ]
    );
    assert_eq!(
        run(&built().mutant),
        [
            ("ops.core.Note/grant/denied".to_owned(), Status::Failed),
            ("ops.core.Ping/grant/denied".to_owned(), Status::Failed),
        ]
    );
}

/// One running served harness.
struct Served {
    child: Child,
    stdin: ChildStdin,
    stdout: BufReader<ChildStdout>,
}

impl Served {
    fn start(binary: &Path) -> Self {
        let mut child = Command::new(binary)
            .args(route_arguments(&served_ir()))
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("the harness starts");
        let stdin = child.stdin.take().expect("piped");
        let stdout = BufReader::new(child.stdout.take().expect("piped"));
        Self {
            child,
            stdin,
            stdout,
        }
    }

    fn line(&mut self, line: &str) -> String {
        writeln!(self.stdin, "{line}").expect("the harness reads");
        self.stdin.flush().expect("the harness reads");
        let mut answer = String::new();
        self.stdout
            .read_line(&mut answer)
            .expect("the harness answers");
        answer.trim_end().to_owned()
    }

    fn send(&mut self, command: &str, actor: &str, body: &str) -> (u16, serde_json::Value) {
        let answer = self.line(&format!("{command}\t{actor}\t{body}"));
        let (status, body) = answer.split_once('\t').expect("status and body");
        (
            status.parse().expect("a status"),
            serde_json::from_str(body).unwrap_or_else(|error| panic!("`{body}`: {error}")),
        )
    }
}

impl Drop for Served {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

/// The suite's requests, over the served harness: the actor a step names is the caller the
/// harness authenticates the request as.
struct ServedTarget(std::cell::RefCell<Served>);

/// A suite value as JSON, a number in its exact spelling.
fn json_of(node: &ess_primitives::node::Node) -> serde_json::Value {
    use ess_primitives::node::Node;
    match node {
        Node::Null => serde_json::Value::Null,
        Node::Bool(value) => serde_json::Value::Bool(*value),
        Node::Number(number) => {
            serde_json::from_str(&number.to_string()).expect("a number's spelling is JSON")
        }
        Node::Text(text) => serde_json::Value::String(text.clone()),
        Node::Seq(items) => serde_json::Value::Array(items.iter().map(json_of).collect()),
        Node::Map(members) => serde_json::Value::Object(
            members
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect(),
        ),
    }
}

impl ess_conformance::ConformanceTarget for ServedTarget {
    fn identity(
        &self,
    ) -> Result<ess_conformance::ImplementationIdentity, ess_conformance::TargetError> {
        Ok(ess_conformance::ImplementationIdentity::new(
            "served-grants",
            "1",
        ))
    }
    fn begin_scenario(
        &self,
        _: &ess_conformance::ScenarioContext,
    ) -> Result<(), ess_conformance::TargetError> {
        assert_eq!(self.0.borrow_mut().line("reset"), "ok");
        Ok(())
    }
    fn end_scenario(
        &self,
        _: &ess_conformance::ScenarioContext,
    ) -> Result<(), ess_conformance::TargetError> {
        Ok(())
    }
    fn execute_command(
        &self,
        request: ess_conformance::SemanticCommandRequest,
    ) -> Result<ess_conformance::SemanticCommandResult, ess_conformance::TargetError> {
        let body = serde_json::Value::Object(
            request
                .input
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect(),
        );
        let actor = request
            .actor
            .as_ref()
            .map_or_else(|| "-".to_owned(), ToString::to_string);
        let (status, answer) =
            self.0
                .borrow_mut()
                .send(&request.command.to_string(), &actor, &body.to_string());
        if status == 403 && answer["refused"] == "not granted" {
            return Err(ess_conformance::TargetError::not_granted(
                answer["actor"].as_str(),
            ));
        }
        Ok(match answer["outcome"].as_str() {
            Some(outcome) => {
                ess_conformance::SemanticCommandResult::took(ess_compiler::refs::OutcomeRef::new(
                    request.command.clone(),
                    outcome.parse().expect("a branch name"),
                ))
            }
            None => ess_conformance::SemanticCommandResult::undeclared(),
        })
    }
    fn query_view(
        &self,
        request: ess_conformance::SemanticViewRequest,
    ) -> Result<ess_conformance::SemanticViewResult, ess_conformance::TargetError> {
        Err(ess_conformance::TargetError::unsupported(
            format!("reading `{}`", request.view),
            "only commands are sent",
        ))
    }
    fn observe_events(
        &self,
        _: ess_conformance::EventObservationRequest,
    ) -> Result<Vec<ess_conformance::ObservedEvent>, ess_conformance::TargetError> {
        Ok(Vec::new())
    }
    fn configure_external_outcome(
        &self,
        _: ess_conformance::ExternalOutcomeControl,
    ) -> Result<(), ess_conformance::TargetError> {
        Err(ess_conformance::TargetError::unsupported(
            "forcing an outcome",
            "none is external",
        ))
    }
    fn redeliver_event(
        &self,
        _: ess_conformance::RedeliveryRequest,
    ) -> Result<(), ess_conformance::TargetError> {
        Err(ess_conformance::TargetError::unsupported(
            "redelivering",
            "not needed",
        ))
    }
}

/// The Go server: an in-package test of the generated `server` package, as
/// `served_unfinished_committed` drives it. Every line is `step<TAB>label<TAB>status<TAB>body`.
const GO_HARNESS: &str = r#"package server

import (
	"fmt"
	"net/http/httptest"
	"strings"
	"testing"

	"example.invalid/ops/components/opsservice"
	"example.invalid/ops/system"
	"example.invalid/ops/types/core"
	"example.invalid/ops/types/obligation"
)

type desk struct{}

func (d *desk) Open(input core.Open) (core.OpenOutcome, *obligation.UnmetObligation) {
	if input.Count > 0 {
		return core.OpenOutcomeOpened{Opened: core.Opened{Id: input.Id}}, nil
	}
	return core.OpenOutcomeRefused{}, nil
}

func (d *desk) Note(input core.Note) (core.NoteOutcome, *obligation.UnmetObligation) {
	return core.NoteOutcomeNoted{Noted: core.Noted{Id: input.Id}}, nil
}

// Ping's behaviour is not realized.
func (d *desk) Ping(input core.Ping) (core.PingOutcome, *obligation.UnmetObligation) {
	return nil, &obligation.UnmetObligation{Capability: "command_behavior", Source: "ops.core.Ping"}
}

func TestServedGrants(t *testing.T) {
	s := system.NewSystem(opsservice.New(&desk{}))
	step := func(label string, caller *Caller, path, body string) {
		request := httptest.NewRequest("POST", path, strings.NewReader(body))
		answer := dispatchOpsService(s, caller, request)
		fmt.Printf("step\t%s\t%d\t%s\n", label, answer.status, strings.ReplaceAll(answer.body, "\n", " "))
	}
	step("absent", nil, "/core/commands/Ping", "{}")
	step("ungranted", &Caller{Actor: ActorOpsCoreWatcher}, "/core/commands/Ping", "{}")
	step("granted", &Caller{Actor: ActorOpsCoreOperator}, "/core/commands/Ping", "{}")
	step("granted-elsewhere", &Caller{Actor: ActorOpsCoreWatcher}, "/core/commands/Open", `{"id":"e","count":0}`)
}
"#;

fn go_output() -> String {
    let synthesis = ess_synth::synthesize_laid_out(
        &served_ir(),
        Target::Go,
        ess_synth::OutputLayout::Workspace,
    )
    .expect("the model synthesizes for Go");
    let directory = scratch("go");
    write(&synthesis, &directory);
    std::fs::write(directory.join("server/served_grants_test.go"), GO_HARNESS).unwrap();
    let cache = scratch("gocache");
    let ran = Command::new("go")
        .args([
            "test",
            "-count=1",
            "-timeout",
            "60s",
            "-v",
            "-run",
            "TestServedGrants",
            "./server/",
        ])
        .current_dir(&directory)
        .env("GOCACHE", &cache)
        .env("GOFLAGS", "-mod=mod")
        .env("GOPROXY", "off")
        .env("GOTOOLCHAIN", "local")
        .output()
        .unwrap_or_else(|error| panic!("`go` runs: {error}"));
    let stdout = String::from_utf8_lossy(&ran.stdout).into_owned();
    eprintln!("{stdout}{}", String::from_utf8_lossy(&ran.stderr));
    let _ = std::fs::remove_dir_all(&directory);
    let _ = std::fs::remove_dir_all(&cache);
    assert!(ran.status.success(), "the Go harness builds and runs");
    stdout
        .lines()
        .filter_map(|line| line.strip_prefix("step\t"))
        .fold(String::new(), |mut out, line| {
            let _ = writeln!(out, "{line}");
            out
        })
}

#[test]
fn the_go_server_refuses_a_caller_no_grant_admits_before_the_port_runs() {
    let output = go_output();
    let answer = |label: &str| -> (u16, serde_json::Value) {
        let line = output
            .lines()
            .find(|line| line.split('\t').next() == Some(label))
            .unwrap_or_else(|| panic!("`{label}`:\n{output}"));
        let fields: Vec<&str> = line.splitn(3, '\t').collect();
        (
            fields[1].parse().expect("a status"),
            serde_json::from_str(fields[2]).expect("JSON"),
        )
    };
    assert_eq!(
        answer("absent"),
        (
            403,
            serde_json::json!({"refused": "not granted", "actor": null})
        )
    );
    assert_eq!(
        answer("ungranted"),
        (
            403,
            serde_json::json!({"refused": "not granted", "actor": "ops.core.Watcher"})
        )
    );
    assert_eq!(answer("granted").0, 501);
    assert_eq!(answer("granted-elsewhere").0, 422);
}
