//! A fully declared command's behaviour is generated over storage and context ports
//! (`story:generated-behaviour-for-declared-commands`).
//!
//! The fixture under `tests/fixtures/declared-behaviour/` declares every construct the story names
//! as expressible: `when:`, `when_subject:`, `when_subject_state:`, `unknown_instance:`,
//! `wrong_state:`, a default, `external:` with and without an input guard; `creates:`, `moves:`,
//! `updates:`, `deletes:`; `sets:` from input, a literal, `{increment:}`, `{cleared}`, the caller and
//! `{generated: true}`; payloads from input, subject fields, the caller and generated values. Its
//! Rust workspace is synthesized, the in-memory port implementation in
//! `tests/fixtures/declared-behaviour-harness/` is placed beside it (outside the generated bytes,
//! holding no command behaviour), and the suite the same specification synthesizes runs against
//! the generated behaviours through that harness.

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};

use ess_compiler::ir::EssIr;
use ess_compiler::resolve::compile_locating;
use ess_compiler::source::SourceMap;
use ess_conformance::report::Status;
use ess_conformance::scenario::{CommandRef, ErrorRef, EventRef, OutcomeRef, ScenarioStep};
use ess_conformance::target::{
    ConformanceTarget, DeclaredErrorValue, EventObservationRequest, ExternalOutcomeControl,
    ImplementationIdentity, ObservedEvent, RedeliveryRequest, ScenarioContext,
    SemanticCommandRequest, SemanticCommandResult, SemanticViewRequest, SemanticViewResult,
    TargetError, ViewRow,
};
use ess_conformance::{AdmittedSuite, Runner};
use ess_domain::spec::{RawSpecFile, Specification};
use ess_domain::system::Source;
use ess_primitives::consistency::ConsistencyToken;
use ess_primitives::node::Node;
use ess_synth::{
    synthesize_for, synthesize_laid_out, CapabilityKind, OutputLayout, SynthesisDisposition,
    SynthesisPlan, Target,
};

/// The fixture directory.
fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/declared-behaviour")
}

/// A specification directory, compiled where it lives.
fn compile_directory(base: &Path) -> EssIr {
    let mut labels = Vec::new();
    let mut pending = vec![base.to_path_buf()];
    while let Some(directory) = pending.pop() {
        for entry in std::fs::read_dir(&directory).expect("the fixture is readable") {
            let path = entry.expect("an entry").path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|it| it == "yaml") {
                labels.push(
                    path.strip_prefix(base)
                        .expect("inside the fixture")
                        .display()
                        .to_string(),
                );
            }
        }
    }
    labels.sort();
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for label in &labels {
        let text = std::fs::read_to_string(base.join(label)).expect("readable");
        let raw = RawSpecFile::parse(&text)
            .unwrap_or_else(|error| panic!("{label} is well formed: {error}"));
        sources.insert(label.clone(), text);
        parsed.push((Source::new(label.clone()), raw));
    }
    let specification = Specification::assemble(parsed)
        .unwrap_or_else(|errors| panic!("the fixture validates:\n{errors}"));
    compile_locating(&specification, &sources, &labels)
        .unwrap_or_else(|diagnostics| panic!("the fixture resolves:\n{diagnostics}"))
}

/// One YAML document, compiled.
fn compile_text(text: &str) -> EssIr {
    let raw = RawSpecFile::parse(text).unwrap_or_else(|error| panic!("well formed: {error}"));
    let specification = Specification::assemble([(Source::new("model.yaml"), raw)])
        .unwrap_or_else(|errors| panic!("validates:\n{errors}"));
    let mut sources = SourceMap::new();
    sources.insert("model.yaml".to_owned(), text.to_owned());
    compile_locating(&specification, &sources, &["model.yaml".to_owned()])
        .unwrap_or_else(|diagnostics| panic!("resolves:\n{diagnostics}"))
}

#[test]
fn the_plan_generates_every_fully_declared_command_and_the_view_query() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes");
    for command in ir.commands().keys() {
        assert_eq!(
            synthesis
                .plan
                .disposition_of(CapabilityKind::CommandBehavior, &command.to_string()),
            Some(&SynthesisDisposition::Generated),
            "`{command}` is fully declared, so its behaviour is generated"
        );
    }
    // The view projects the ticket's own fields and `state`, so its query is generated too
    // (`story:generated-view-queries`).
    assert_eq!(
        synthesis
            .plan
            .disposition_of(CapabilityKind::ViewQuery, "desk.ticket.Tickets"),
        Some(&SynthesisDisposition::Generated)
    );
    let behaviour = synthesis
        .artifacts
        .get("crates/desk-types/src/behaviour.rs")
        .expect("the types crate carries the generated behaviours");
    for port in [
        "pub trait TicketStorage",
        "pub trait Context",
        "pub struct Generated<P>",
        "fn external(&mut self, command: &'static str, outcome: &'static str) -> bool;",
        "fn caller_agent_id(&self) -> Option<crate::ticket::AgentId>;",
        "fn generate_desk_ticket_ticket_id(&mut self) -> crate::ticket::TicketId;",
    ] {
        assert!(
            behaviour.contents.contains(port),
            "`{port}` missing:\n{}",
            behaviour.contents
        );
    }
    assert!(
        !behaviour.contents.contains("impl Unimplemented")
            && !synthesis
                .artifacts
                .values()
                .any(|artifact| artifact.contents.contains("impl TicketStorage for")),
        "ess generates the storage trait, never a store"
    );
    let domain = &synthesis.artifacts["crates/desk-types/src/ticket.rs"].contents;
    assert!(
        !domain.contains("impl OpenTicketBehavior for Unimplemented"),
        "a generated behaviour is not stubbed as owed"
    );
    assert!(domain.contains("pub trait OpenTicketBehavior"), "{domain}");
}

#[test]
fn generated_nested_increment_behaves_in_rust_and_go() {
    let ir = compile_directory(&fixture_root());
    let rust = synthesize_for(&ir, Target::Rust).expect("the nested fixture synthesizes to Rust");
    let go = synthesize_for(&ir, Target::Go).expect("the nested fixture synthesizes to Go");
    let rust = &rust.artifacts["crates/desk-types/src/behaviour.rs"].contents;
    let go = &go.artifacts["types/behaviour/behaviour.go"].contents;

    for location in [
        "before.stats.amount",
        "before.stats.deeper.amount",
        "before.maybe_stats.as_ref()",
    ] {
        assert!(rust.contains(location), "`{location}` missing:\n{rust}");
    }
    for location in [
        "before.Stats.Amount",
        "before.Stats.Deeper.Amount",
        "before.MaybeStats == nil",
        "before.MaybeStats.Amount",
    ] {
        assert!(go.contains(location), "`{location}` missing:\n{go}");
    }

    let decimal = compile_text(NESTED_DECIMAL_INCREMENT);
    for target in [Target::Rust, Target::Go] {
        let synthesis = synthesize_for(&decimal, target).expect("the Decimal model plans");
        match synthesis
            .plan
            .disposition_of(CapabilityKind::CommandBehavior, "decimal.counter.Advance")
        {
            Some(SynthesisDisposition::Obligation(obligation)) => assert!(
                obligation.reason.describes().contains("Integer"),
                "the nested Decimal refusal names the generated target's Integer boundary: \
                 {obligation:#?}"
            ),
            other => panic!("a nested Decimal increment is owed for {target:?}: {other:#?}"),
        }
    }
}

#[test]
fn an_optional_struct_event_payload_does_not_read_a_non_stored_root() {
    let ir = compile_text(OPTIONAL_STRUCT_EVENT_PAYLOAD);
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the payload behavior plans");
    assert_eq!(
        synthesis
            .plan
            .disposition_of(CapabilityKind::CommandBehavior, "payload.counter.Advance"),
        Some(&SynthesisDisposition::Generated),
        "a fully determined nested payload remains generated"
    );
    let behaviour = synthesis
        .artifacts
        .values()
        .find(|artifact| artifact.path.ends_with("src/behaviour.rs"))
        .expect("the generated behavior source")
        .contents
        .as_str();
    assert!(
        !behaviour.contains("before.snapshot"),
        "an event payload root is not a stored entity field:\n{behaviour}"
    );
}

#[test]
fn a_same_named_optional_stored_field_does_not_gate_an_event_payload() {
    let source = OPTIONAL_STRUCT_EVENT_PAYLOAD.replace(
        "fields: [{name: amount, type: Integer}]\n    lifecycle:",
        "fields:\n      - {name: amount, type: Integer}\n      - {name: snapshot, type: 'Optional<payload.counter.Packet>'}\n    lifecycle:",
    );
    let ir = compile_text(&source);
    for (target, forbidden) in [
        (Target::Rust, "before.snapshot.as_ref()"),
        (Target::Go, "before.Snapshot == nil"),
    ] {
        let synthesis = synthesize_for(&ir, target).expect("the payload behavior plans");
        assert_eq!(
            synthesis
                .plan
                .disposition_of(CapabilityKind::CommandBehavior, "payload.counter.Advance"),
            Some(&SynthesisDisposition::Generated),
            "a fully determined nested payload remains generated for {target:?}"
        );
        let scratch = Scratch(Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!(
            "declared-behaviour-{target:?}-payload-{}",
            std::process::id()
        )));
        let _ = std::fs::remove_dir_all(&scratch.0);
        write_tree(&scratch.0, &synthesis);
        match target {
            Target::Rust => {
                let target_dir = scratch.0.join("target");
                let (built, log) = cargo(
                    &scratch.0,
                    &target_dir,
                    &["check", "--workspace", "--all-targets"],
                );
                assert!(built, "the generated Rust payload behavior builds:\n{log}");
            }
            Target::Go => {
                let go = go().expect("Go is required to compile the prospective generated target");
                let (built, log) = go_tool(&scratch.0, &go, &["build", "./..."]);
                assert!(built, "the generated Go payload behavior builds:\n{log}");
            }
            _ => unreachable!("the test covers the generated Rust and Go targets"),
        }
        let behaviour = synthesis
            .artifacts
            .values()
            .find(|artifact| {
                artifact.path.ends_with("behaviour.rs") || artifact.path.ends_with("behaviour.go")
            })
            .expect("the generated behavior source")
            .contents
            .as_str();
        assert!(
            !behaviour.contains(forbidden),
            "an output-only payload does not depend on the same-named stored value for {target:?}:\n{behaviour}"
        );
    }
}

#[test]
fn required_and_creation_struct_payloads_still_build_in_rust_and_go() {
    let required = OPTIONAL_STRUCT_EVENT_PAYLOAD.replace(
        "type: 'Optional<payload.counter.Packet>'",
        "type: payload.counter.Packet",
    );
    for (label, source) in [
        ("required", required.as_str()),
        ("creation", STRUCT_PAYLOAD_CREATION),
    ] {
        let ir = compile_text(source);
        for target in [Target::Rust, Target::Go] {
            let synthesis = synthesize_for(&ir, target).expect("the payload behavior plans");
            let scratch = Scratch(Path::new(env!("CARGO_TARGET_TMPDIR")).join(format!(
                "declared-behaviour-{target:?}-{label}-payload-{}",
                std::process::id()
            )));
            let _ = std::fs::remove_dir_all(&scratch.0);
            write_tree(&scratch.0, &synthesis);
            match target {
                Target::Rust => {
                    let target_dir = scratch.0.join("target");
                    let (built, log) = cargo(
                        &scratch.0,
                        &target_dir,
                        &["check", "--workspace", "--all-targets"],
                    );
                    assert!(built, "the generated Rust {label} payload builds:\n{log}");
                }
                Target::Go => {
                    let go =
                        go().expect("Go is required to compile the prospective generated target");
                    let (built, log) = go_tool(&scratch.0, &go, &["build", "./..."]);
                    assert!(built, "the generated Go {label} payload builds:\n{log}");
                }
                _ => unreachable!("the test covers the generated Rust and Go targets"),
            }
        }
    }
}

const OPTIONAL_STRUCT_EVENT_PAYLOAD: &str = "format: ess/20
system: payload
version: v1
domain: payload.counter
types:
  - name: payload.counter.Packet
    kind: struct
    fields: [{name: amount, type: Integer}]
entities:
  - name: payload.counter.Counter
    identity: {name: counter_id, type: Uuid}
    fields: [{name: amount, type: Integer}]
    lifecycle: {initial: Active, states: [Active], terminal: [Active]}
errors:
  - name: payload.counter.Missing
    fields: [{name: counter_id, type: Uuid}]
events:
  - name: payload.counter.Advanced
    fields: [{name: snapshot, type: 'Optional<payload.counter.Packet>'}]
commands:
  - name: payload.counter.Advance
    input:
      - {name: counter_id, type: Uuid}
      - {name: amount, type: Integer}
    outcomes:
      - name: advanced
        updates: payload.counter.Counter
        instance: counter_id
        sets: {amount: input.amount}
        emits: [payload.counter.Advanced]
        payload:
          payload.counter.Advanced:
            snapshot: {amount: input.amount}
      - name: missing
        unknown_instance: true
        error: payload.counter.Missing
        payload:
          payload.counter.Missing: {counter_id: input.counter_id}
components:
  - component: counter-service
    owns: {domains: [payload.counter]}
    accepts: {commands: [payload.counter.Advance]}
    publishes: {events: [payload.counter.Advanced]}
    reached_by: network
";

const STRUCT_PAYLOAD_CREATION: &str = "format: ess/20
system: payload
version: v1
domain: payload.counter
types:
  - name: payload.counter.Packet
    kind: struct
    fields: [{name: amount, type: Integer}]
entities:
  - name: payload.counter.Counter
    identity: {name: counter_id, type: Uuid}
    fields: [{name: amount, type: Integer}]
    lifecycle: {initial: Active, states: [Active], terminal: [Active]}
events:
  - name: payload.counter.Created
    fields:
      - {name: counter_id, type: Uuid}
      - {name: snapshot, type: 'Optional<payload.counter.Packet>'}
commands:
  - name: payload.counter.Create
    input: [{name: amount, type: Integer}]
    outcomes:
      - name: created
        creates: payload.counter.Counter
        instance: counter_id
        sets: {amount: input.amount}
        emits: [payload.counter.Created]
        payload:
          payload.counter.Created:
            counter_id: {generated: true}
            snapshot: {amount: input.amount}
components:
  - component: counter-service
    owns: {domains: [payload.counter]}
    accepts: {commands: [payload.counter.Create]}
    publishes: {events: [payload.counter.Created]}
    reached_by: network
";

const NESTED_DECIMAL_INCREMENT: &str = "format: ess/20
system: decimal
version: v1
domain: decimal.counter
types:
  - name: decimal.counter.Packet
    kind: struct
    fields: [{name: amount, type: Decimal}]
entities:
  - name: decimal.counter.Counter
    identity: {name: counter_id, type: Uuid}
    fields: [{name: packet, type: decimal.counter.Packet}]
    lifecycle: {initial: Active, states: [Active], terminal: [Active]}
errors:
  - name: decimal.counter.Missing
    fields: [{name: counter_id, type: Uuid}]
events:
  - {name: decimal.counter.Advanced, fields: []}
commands:
  - name: decimal.counter.Advance
    input: [{name: counter_id, type: Uuid}]
    outcomes:
      - name: advanced
        updates: decimal.counter.Counter
        instance: counter_id
        sets: {packet: {amount: {increment: 1}}}
        emits: [decimal.counter.Advanced]
      - name: missing
        unknown_instance: true
        error: decimal.counter.Missing
        payload:
          decimal.counter.Missing: {counter_id: input.counter_id}
";

#[test]
fn a_moved_or_written_entity_is_checked_against_its_invariants_before_it_is_stored() {
    let ir = compile_directory(&fixture_root());
    let with_invariant = fixture_with_invariant();
    let plain = synthesize_for(&ir, Target::Rust).expect("synthesizes");
    let checked = synthesize_for(&with_invariant, Target::Rust).expect("synthesizes");
    let behaviour = |synthesis: &ess_synth::Synthesis| {
        synthesis.artifacts["crates/desk-types/src/behaviour.rs"]
            .contents
            .clone()
    };
    assert!(
        !behaviour(&plain).contains("broken_invariant"),
        "an entity declaring no invariant has no check to call"
    );
    let text = behaviour(&checked);
    // Every write of the entity — the create, both moves, the four updates — is preceded by the
    // check.
    let puts = text.matches("TicketStorage::put(").count();
    let checks = text.matches(".broken_invariant()").count();
    assert_eq!(puts, 7, "{text}");
    assert_eq!(checks, puts, "{text}");
    for (position, _) in text.match_indices("TicketStorage::put(") {
        let before = &text[..position];
        let check = before
            .rfind(".broken_invariant()")
            .expect("a check before the write");
        let previous_put = before.rfind("TicketStorage::put(").unwrap_or(0);
        assert!(
            check > previous_put,
            "the check precedes its own write:\n{text}"
        );
    }
}

/// The fixture with `estimate >= 0` declared on the ticket.
fn fixture_with_invariant() -> EssIr {
    let base = fixture_root();
    let mut labels = vec![
        "components.yaml".to_owned(),
        "domains/ticket.yaml".to_owned(),
        "system.yaml".to_owned(),
    ];
    labels.sort();
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for label in &labels {
        let mut text = std::fs::read_to_string(base.join(label)).expect("readable");
        if label == "domains/ticket.yaml" {
            text = text.replace(
                "      - {name: maybe_stats, type: 'Optional<desk.ticket.Counter>'}\n    lifecycle:",
                "      - {name: maybe_stats, type: 'Optional<desk.ticket.Counter>'}\n    invariants:\n      - estimate >= 0\n    lifecycle:",
            );
        }
        let raw = RawSpecFile::parse(&text).expect("well formed");
        sources.insert(label.clone(), text);
        parsed.push((Source::new(label.clone()), raw));
    }
    let specification = Specification::assemble(parsed).expect("validates");
    compile_locating(&specification, &sources, &labels).expect("resolves")
}

/// A command that uses one construct the story keeps an obligation, beside a sibling that is fully
/// declared, and the phrase its obligation must name.
struct Kept {
    model: &'static str,
    command: &'static str,
    names: &'static str,
}

#[test]
fn every_construct_the_story_keeps_owed_keeps_its_whole_command_an_obligation() {
    let cases = [
        Kept {
            model: RELATED_GUARD,
            command: "kept.shop.PlaceOrder",
            names: "`when_related:`",
        },
        Kept {
            model: RELATED_SET,
            command: "kept.shop.PlaceOrder",
            names: "`{related:}`",
        },
        Kept {
            model: STATE_AND_EXTERNAL,
            command: "kept.shop.Ship",
            names: "`when_subject_state:` beside `external:`",
        },
        Kept {
            model: MOVE_OR_UPDATE,
            command: "kept.shop.Ship",
            names: "a subject predicate choosing between a move and an update",
        },
        Kept {
            model: NO_UNKNOWN_ANSWER,
            command: "kept.shop.Ship",
            names: "an unknown identity",
        },
        Kept {
            model: SET_OUTCOME,
            command: "kept.shop.ShipAll",
            names: "`instances:`",
        },
        Kept {
            model: AFFECTS,
            command: "kept.shop.Ship",
            names: "`affects:`",
        },
        Kept {
            model: UNDETERMINED_ERROR,
            command: "kept.shop.PlaceOrder",
            names: "the fields of error `kept.shop.TooMany`",
        },
        Kept {
            model: UNDETERMINED_FIELD,
            command: "kept.shop.PlaceOrder",
            names: "`creates:` leaving the required field `quantity`",
        },
    ];
    for case in cases {
        let ir = compile_text(case.model);
        // The plan, not a target: `instances:` and `affects:` are refused by the Rust target as a
        // whole, and the plan still names the construct that keeps the command owed.
        let plan = SynthesisPlan::of(&ir);
        match plan.disposition_of(CapabilityKind::CommandBehavior, case.command) {
            Some(SynthesisDisposition::Obligation(obligation)) => {
                let why = obligation.reason.describes();
                assert!(
                    why.contains(case.names),
                    "`{}` names `{}` as what kept it owed, not: {why}",
                    case.command,
                    case.names
                );
            }
            other => panic!("`{}` stays an obligation, not {other:?}", case.command),
        }
        let markdown = plan.to_markdown();
        assert!(markdown.contains(case.names), "{markdown}");
        // The sibling in each model is fully declared and generated: the line is per command.
        assert_eq!(
            plan.disposition_of(CapabilityKind::CommandBehavior, "kept.shop.OpenShop"),
            Some(&SynthesisDisposition::Generated),
            "{}",
            case.command
        );
    }
}

const RELATED_GUARD: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: no-shop
        when_related: {via: input.shop_id, exists: false}
        error: kept.shop.NoShop
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id, quantity: input.quantity}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

/// Declaration order deliberately disagrees with selection: input refusal, absence, presence,
/// creation, then existing-instance refusal. Presence must not inherit absence's priority.
fn related_precedence_model() -> EssIr {
    let (head, command) = RELATED_GUARD
        .split_once("  - name: kept.shop.PlaceOrder")
        .unwrap();
    let command = command
        .replace(
            "    input:",
            "    input:\n      - {name: order_id, type: kept.shop.OrderId}",
        )
        .replace(
            "      - name: no-shop",
            "      - {name: invalid-quantity, when: 'quantity < 0', error: kept.shop.Refused}\n      - name: no-shop",
        )
        .replace(
            "      - name: placed",
            "      - name: wrong-region\n        when_related: {via: input.shop_id, predicate: 'region != \"EU\"'}\n        error: kept.shop.Refused\n      - name: placed",
        )
        .replace(
            "          kept.shop.OrderPlaced: {order_id: {generated: true}}\n",
            "          kept.shop.OrderPlaced: {order_id: input.order_id}\n      - {name: already-placed, existing_instance: true, error: kept.shop.Conflict}\n",
        );
    compile_text(&format!("{head}  - name: kept.shop.PlaceOrder{command}"))
}

fn related_precedence_contract() -> String {
    let plan = SynthesisPlan::of(&related_precedence_model());
    match plan.disposition_of(CapabilityKind::CommandBehavior, "kept.shop.PlaceOrder") {
        Some(SynthesisDisposition::Obligation(obligation)) => {
            assert!(obligation.reason.describes().contains("`when_related:`"));
            obligation.contract.clone()
        }
        other => panic!("related guards still owe their behavior: {other:?}"),
    }
}

#[test]
fn plan_contract_states_related_absence_before_input_refusal() {
    let contract = related_precedence_contract();
    assert!(
        contract.contains("`exists: false` before input-guarded refusals"),
        "{contract}"
    );
    let (_, inventory) = contract
        .split_once("Declared outcomes (declaration order, not selection precedence):")
        .expect("the inventory does not pretend to be the decision order");
    assert!(inventory.find("`invalid-quantity`").unwrap() < inventory.find("`no-shop`").unwrap());
}

#[test]
fn plan_contract_distinguishes_related_presence_from_absence() {
    let contract = related_precedence_contract();
    assert!(
        contract.contains("Related-presence predicates do not precede input-guarded refusals"),
        "{contract}"
    );
    assert!(
        contract.contains("accepting and external branches in declaration order"),
        "{contract}"
    );
    assert!(
        contract.contains("`wrong-region` when the `kept.shop.Shop`"),
        "{contract}"
    );
}

#[test]
fn plan_contract_states_existing_instance_exception_for_related_commands() {
    let contract = related_precedence_contract();
    assert!(
        contract.contains(
            "on commands with `when_related:`, check `existing_instance` then `exists: false`"
        ),
        "{contract}"
    );
    assert!(
        contract.contains("`existing_instance` on commands without `when_related:`"),
        "{contract}"
    );
    assert!(
        contract.contains(
            "`wrong_state` only if the selected branch moves from a state the row does not hold"
        ),
        "{contract}"
    );
}

#[test]
fn generated_refusal_comments_do_not_claim_universal_read_precedence() {
    let ir = compile_directory(&fixture_root());
    for (target, path) in [
        (Target::Rust, "crates/desk-types/src/behaviour.rs"),
        (Target::Go, "types/behaviour/behaviour.go"),
    ] {
        let synthesis = synthesize_for(&ir, target).expect("supported behavior");
        let source = &synthesis.artifacts[path].contents;
        assert!(
            source.contains("an input-guarded refusal, before the addressed subject is loaded."),
            "{target:?}: scoped precedence comment missing"
        );
        assert!(
            !source.contains("before anything else is read"),
            "{target:?}"
        );
    }
}

#[test]
fn related_precedence_plan_projections_remain_target_independent() {
    let ir = related_precedence_model();
    let rust = synthesize_for(&ir, Target::Rust).expect("Rust carries obligations");
    for target in [Target::Go, Target::Web, Target::Clap] {
        let synthesis = synthesize_for(&ir, target).expect("targets carry obligations");
        for path in ["PLAN.md", "plan.json"] {
            assert_eq!(
                synthesis.artifacts[path].contents, rust.artifacts[path].contents,
                "{target:?}: {path}"
            );
        }
    }
    let json: serde_json::Value =
        serde_json::from_str(&rust.artifacts["plan.json"].contents).expect("valid plan JSON");
    let contract = related_precedence_contract();
    assert!(
        json.to_string()
            .contains(&serde_json::to_string(&contract).unwrap()),
        "JSON carries the same contract"
    );
    assert!(rust.artifacts["PLAN.md"].contents.contains(&contract));
}

const RELATED_SET: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets:
          shop_id: input.shop_id
          quantity: input.quantity
          region: {related: {via: input.shop_id, field: region}}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

const STATE_AND_EXTERNAL: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: already-shipped
        when_subject_state: Shipped
        error: kept.shop.Conflict
      - name: carrier-refused
        external: the carrier refuses the parcel
        error: kept.shop.Refused
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
"
);

const MOVE_OR_UPDATE: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: shipped
        when_subject: {predicate: quantity > 0}
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - name: topped-up
        updates: kept.shop.Order
        instance: order_id
        sets: {quantity: \"1\"}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
      - {name: already-shipped, wrong_state: true, error: kept.shop.Conflict}
"
);

const NO_UNKNOWN_ANSWER: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: already-shipped
        when_subject_state: Shipped
        error: kept.shop.Conflict
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
"
);

const SET_OUTCOME: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.ShipAll
    input: [{name: shop_id, type: kept.shop.ShopId}]
    outcomes:
      - name: shipped
        moves: kept.shop.Order.ship
        instances: {where: shop_id == input.shop_id}
        emits: [kept.shop.ShopOpened]
        payload:
          kept.shop.ShopOpened: {shop_id: input.shop_id}
"
);

const AFFECTS: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        affects:
          - entity: kept.shop.Order
            where: shop_id == subject.shop_id
            sets: {region: {cleared: true}}
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
      - {name: already-shipped, wrong_state: true, error: kept.shop.Conflict}
"
);

const UNDETERMINED_ERROR: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: too-many
        when: quantity > 10
        error: kept.shop.TooMany
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id, quantity: input.quantity}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

const UNDETERMINED_FIELD: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
    outcomes:
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

/// `story:error-payload-sources`: [`UNDETERMINED_ERROR`] with a source for its one error field is
/// fully determined, and its behaviour is generated.
#[test]
fn an_error_whose_every_field_has_a_declared_source_is_determined() {
    let model = UNDETERMINED_ERROR
        .replace("format: ess/18\n", "format: ess/19\n")
        .replace(
            "        error: kept.shop.TooMany\n",
            "        error: kept.shop.TooMany\n        payload:\n          kept.shop.TooMany: {limit: 10}\n",
        );
    assert_ne!(model, UNDETERMINED_ERROR);
    let plan = SynthesisPlan::of(&compile_text(&model));
    assert_eq!(
        plan.disposition_of(CapabilityKind::CommandBehavior, "kept.shop.PlaceOrder"),
        Some(&SynthesisDisposition::Generated),
        "{}",
        plan.to_markdown()
    );
}

/// Each refusal of the fixture fills its error from its declared sources: the input, a literal,
/// the caller, the row it is answered for and a generated value; `TicketStateConflict.state` is
/// still read from the held row, beside its declared `ticket_id`.
#[test]
fn a_generated_refusal_fills_its_error_from_the_declared_sources() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes");
    let behaviour = &synthesis.artifacts["crates/desk-types/src/behaviour.rs"].contents;
    for filled in [
        "NegativeEstimate { estimate: input.estimate.clone(), minimum: 0 }",
        "TicketNotFound { ticket_id: input.ticket_id.clone() }",
        "TicketStateConflict { state: held_state, ticket_id: input.ticket_id.clone() }",
        "NotYours { caller: self.ports.try_caller_agent_id()?.ok_or_else(|| undeclared(\"desk.ticket.Reprioritize\"))?",
        "opened_by: held.data.opened_by.clone() }",
        "TicketIsClosed { title: held.data.title.clone(), priority: held.data.priority.clone() }",
        "PagerRefused { reason: input.reason.clone() }",
        "Throttled { page_id: self.ports.try_generate_desk_ticket_escalation_id()? }",
    ] {
        assert!(
            behaviour.contains(filled),
            "`{filled}` missing:\n{behaviour}"
        );
    }
}

/// The suite the generated behaviours pass compares those fields, so passing it says they are
/// filled as declared: every field whose value a scenario determines, by error. A generated
/// value is the implementation's and is not compared; an identity the suite binds is known only
/// as a reference.
#[test]
fn the_fixture_suite_compares_the_declared_error_fields() {
    use ess_conformance::scenario::ScenarioStep;
    let ir = compile_directory(&fixture_root());
    let suite = ess_conformance::synthesize(&ir).suite;
    let mut compared: BTreeMap<String, std::collections::BTreeSet<String>> = BTreeMap::new();
    for step in suite
        .scenarios
        .values()
        .flat_map(|scenario| &scenario.steps)
    {
        if let ScenarioStep::ExpectError { error, fields } = step {
            compared
                .entry(error.to_string())
                .or_default()
                .extend(fields.keys().cloned());
        }
    }
    let keys = |error: &str| -> Vec<String> {
        compared
            .get(error)
            .map(|keys| keys.iter().cloned().collect())
            .unwrap_or_default()
    };
    assert_eq!(
        keys("desk.ticket.NegativeEstimate"),
        ["estimate", "minimum"]
    );
    assert_eq!(keys("desk.ticket.NotYours"), ["caller", "opened_by"]);
    assert_eq!(keys("desk.ticket.TicketIsClosed"), ["priority", "title"]);
    assert_eq!(keys("desk.ticket.PagerRefused"), ["reason"]);
    assert_eq!(keys("desk.ticket.TicketNotFound"), ["ticket_id"]);
    assert!(keys("desk.ticket.Throttled").is_empty(), "{compared:#?}");
}

/// `story:go-generated-behaviour`: the Go target generates every behaviour and query the plan marks
/// generated, over the same storage and context ports, and owes nothing the plan does not.
#[test]
fn the_go_target_generates_every_behaviour_the_plan_marks_generated() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Go).expect("the fixture synthesizes to Go");
    let rust = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes to Rust");
    assert_eq!(
        synthesis.artifacts["PLAN.md"].contents, rust.artifacts["PLAN.md"].contents,
        "the plan is one document in both targets"
    );
    let report = synthesis
        .target
        .as_ref()
        .expect("Go reports what it weakens");
    assert!(
        report
            .weakenings
            .iter()
            .all(|weakening| !weakening.affects.iter().any(|kind| matches!(
                kind,
                CapabilityKind::CommandBehavior | CapabilityKind::ViewQuery
            ))),
        "no behaviour or query is weakened: {report:#?}"
    );
    let behaviour = &synthesis
        .artifacts
        .get("types/behaviour/behaviour.go")
        .expect("the module carries the generated behaviours")
        .contents;
    for port in [
        "package behaviour",
        "type TicketStorage interface {",
        "\tGet(identity ticket.TicketId) (ticket.TicketSnapshot, bool)",
        "\tPut(snapshot ticket.TicketSnapshot)",
        "\tDelete(identity ticket.TicketId)",
        "\tList() []ticket.TicketSnapshot",
        "type Context interface {",
        "\tCallerAgentId() (ticket.AgentId, bool)",
        "\tGenerateDeskTicketTicketId() ticket.TicketId",
        "\tExternal(command string, outcome string) bool",
        "type Ports struct {",
        "func New(ports Ports) *Generated {",
    ] {
        assert!(behaviour.contains(port), "`{port}` missing:\n{behaviour}");
    }
    for command in ir.commands().values() {
        assert_eq!(
            synthesis
                .plan
                .disposition_of(CapabilityKind::CommandBehavior, &command.name.to_string()),
            Some(&SynthesisDisposition::Generated)
        );
        let qualified = command.name.to_string();
        let method = qualified.rsplit('.').next().unwrap_or_default();
        let signature = format!("func (b *Generated) {method}(input ticket.{method}) (ticket.{method}Outcome, *obligation.UnmetObligation) {{");
        assert!(
            behaviour.contains(&signature),
            "`{signature}` missing:\n{behaviour}"
        );
    }
    assert!(
        behaviour.contains(
            "func (b *Generated) Tickets() ([]ticket.Tickets, *obligation.UnmetObligation) {"
        ),
        "the view query is generated:\n{behaviour}"
    );
    assert!(
        !behaviour.contains("type Owed interface") && !behaviour.contains("ports.Owed."),
        "nothing is owed, so nothing is forwarded:\n{behaviour}"
    );
    assert!(
        !synthesis.artifacts.values().any(|artifact| artifact
            .contents
            .contains("TicketStorage = ")
            || artifact
                .contents
                .contains(") Put(snapshot ticket.TicketSnapshot) {")),
        "ess generates the storage interface, never a store"
    );
    let domain = &synthesis.artifacts["types/ticket/ticket.go"].contents;
    assert!(
        !domain.contains("func (Unimplemented) OpenTicket(")
            && !domain.contains("type Unimplemented struct"),
        "a generated behaviour is not stubbed as owed, and nothing else is owed:\n{domain}"
    );
    assert!(
        domain.contains("type OpenTicketBehavior interface {"),
        "{domain}"
    );
    let target = &synthesis.artifacts["TARGET.md"].contents;
    assert!(
        !target.contains("does not generate command behaviour")
            && !target.contains("does not generate view queries"),
        "{target}"
    );
}

/// `story:go-generated-behaviour`: the generated Go behaviours, over in-memory ports that hold no
/// behaviour (`tests/fixtures/declared-behaviour-go-harness/main.go`), are gofmt-clean, vet clean
/// and build, and pass the suite the specification synthesizes — through the component's port, and
/// through the generated HTTP surface over a real socket.
#[test]
fn the_go_behaviours_build_vet_clean_and_pass_their_own_suite() {
    let Some(go) = go() else {
        eprintln!(
            "no Go toolchain on this machine; the generated Go behaviours are unchecked here"
        );
        return;
    };
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Go).expect("the fixture synthesizes to Go");
    let scratch = Scratch(
        Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join(format!("declared-behaviour-go-{}", std::process::id())),
    );
    let _ = std::fs::remove_dir_all(&scratch.0);
    let tree = scratch.0.join("desk");
    write_tree(&tree, &synthesis);
    let harness = scratch.0.join("harness");
    std::fs::create_dir_all(&harness).expect("mkdir");
    std::fs::write(
        harness.join("go.mod"),
        "module deskharness\n\ngo 1.21\n\nrequire example.invalid/desk v0.0.0\n\nreplace \
         example.invalid/desk => ../desk\n",
    )
    .expect("write");
    std::fs::copy(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/declared-behaviour-go-harness/main.go"),
        harness.join("main.go"),
    )
    .expect("the harness copies");

    let (formatted, unformatted) = go_tool(&tree, "gofmt", &["-d", "."]);
    assert!(
        formatted && unformatted.trim().is_empty(),
        "the generated Go is gofmt-clean:\n{unformatted}"
    );
    let (vetted, log) = go_tool(&tree, &go, &["vet", "./..."]);
    assert!(vetted, "the generated Go is vet clean:\n{log}");
    let binary = scratch.0.join("harness-bin");
    let (built, log) = go_tool(
        &harness,
        &go,
        &["build", "-o", binary.to_str().expect("a UTF-8 path"), "."],
    );
    assert!(
        built,
        "the harness builds against the generated ports:\n{log}"
    );
    let (vetted, log) = go_tool(&harness, &go, &["vet", "."]);
    assert!(vetted, "the harness is vet clean:\n{log}");

    let through_port = run_through(
        &ir,
        &binary,
        &["port".to_owned()],
        "the Go component's port",
    );
    assert_every_event_named_and_encoded(&ir, &through_port);
    assert_absent_optional_increment_is_atomic(&through_port);
    drop(through_port);
    let mut served = vec!["served".to_owned()];
    served.extend(route_table(&ir));
    let through_server = run_through(&ir, &binary, &served, "the generated Go HTTP surface");
    drop(through_server);
    drop(scratch);
}

/// Where Go is, or `None` when this machine has none — said out loud, never passed silently.
fn go() -> Option<String> {
    let output = Command::new("go").arg("version").output().ok()?;
    output.status.success().then(|| "go".to_owned())
}

/// Runs a Go tool in `directory` with nothing fetched from a network, returning its output.
fn go_tool(directory: &Path, tool: &str, arguments: &[&str]) -> (bool, String) {
    let output = Command::new(tool)
        .args(arguments)
        .current_dir(directory)
        .env("GOFLAGS", "-mod=mod")
        .env("GOPROXY", "off")
        .env("GOWORK", "off")
        .output()
        .expect("the Go tool runs");
    (
        output.status.success(),
        format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ),
    )
}

/// A model whose plan generates no command behaviour and no view query: it declares neither.
const PORTLESS: &str = "format: ess/18
system: portless
version: v1
domain: portless.shop
types:
  - {name: portless.shop.ShopId, kind: newtype, of: Uuid}
";

#[test]
fn the_plan_names_the_storage_and_context_ports_as_the_implementors_to_provide() {
    let heading = "\n## Ports — yours to provide\n";
    for target in [Target::Rust, Target::Go] {
        let synthesis = synthesize_for(&compile_directory(&fixture_root()), target)
            .expect("the fixture synthesizes");
        let markdown = &synthesis.artifacts["PLAN.md"].contents;
        let section = markdown
            .split(heading)
            .nth(1)
            .and_then(|rest| rest.split("\n## ").next())
            .unwrap_or_else(|| panic!("PLAN.md has a ports section:\n{markdown}"));
        for named in [
            "| storage |",
            "| context |",
            "never an implementation of one",
            "`external:`",
        ] {
            assert!(section.contains(named), "`{named}` missing:\n{section}");
        }
        let generated = markdown
            .find("\n## Generated\n")
            .expect("a generated table");
        let owed = markdown
            .find("\n## Obligations")
            .expect("an obligations table");
        let ports = markdown.find(heading).expect("the ports section");
        assert!(generated < ports && ports < owed, "{markdown}");
    }
    let portless = SynthesisPlan::of(&compile_text(PORTLESS)).to_markdown();
    assert!(
        !portless.contains("## Ports"),
        "a plan generating nothing that reads a port names none:\n{portless}"
    );
}

// ---- the generated workspace, built and run against its own suite ------------------------------

/// A scratch directory under this test binary's target, removed when dropped.
struct Scratch(PathBuf);

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Writes every artifact of a synthesis under `root`.
fn write_tree(root: &Path, synthesis: &ess_synth::Synthesis) {
    for artifact in synthesis.artifacts.values() {
        let path = root.join(&artifact.path);
        std::fs::create_dir_all(path.parent().expect("a file has a parent")).expect("mkdir");
        std::fs::write(&path, &artifact.contents).expect("write");
    }
}

/// Runs cargo offline in `directory`, with warnings denied, returning its combined output.
fn cargo(directory: &Path, target: &Path, arguments: &[&str]) -> (bool, String) {
    let output = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args(arguments)
        .arg("--offline")
        .current_dir(directory)
        .env("CARGO_TARGET_DIR", target)
        .env("RUSTFLAGS", "-D warnings")
        .env("CARGO_INCREMENTAL", "0")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .expect("cargo runs");
    (
        output.status.success(),
        format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ),
    )
}

/// The harness crate's manifest, without its dependencies: those depend on the layout.
const HARNESS_MANIFEST: &str = "[package]
name = \"declared-behaviour-harness\"
version = \"0.0.0\"
edition = \"2021\"
publish = false

[workspace]

[[bin]]
name = \"harness\"
path = \"src/main.rs\"

[dependencies]
";

/// The workspace layout's dependencies: four of its crates, by path.
const WORKSPACE_DEPENDENCIES: &str = "desk-types = { path = \"../desk/crates/desk-types\" }
desk-server = { path = \"../desk/crates/desk-server\" }
desk-service = { path = \"../desk/crates/desk-service\" }
desk-system = { path = \"../desk/crates/desk-system\" }
";

/// The single-crate layout's one dependency, with its HTTP surface switched on.
const CRATE_DEPENDENCIES: &str = "desk = { path = \"../desk\", features = [\"server\"] }\n";

/// The harness source, as committed.
fn harness_source() -> String {
    std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/declared-behaviour-harness/main.rs"),
    )
    .expect("the harness is readable")
}

#[test]
fn the_generated_behaviours_build_with_warnings_denied_and_pass_their_own_suite() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes");
    run_suite(
        &ir,
        &synthesis,
        "workspace",
        WORKSPACE_DEPENDENCIES,
        &harness_source(),
        &["check", "--workspace", "--all-targets"],
    );
}

/// `story:single-crate-rust-layout`: the same fixture, laid out as one crate, passes the same
/// suite through the same harness once its `server` feature is on. Only the harness's paths into
/// the generated code differ: `desk_types::` is the crate root, the component's port is under
/// `ports::`, the system under `system::`, and the HTTP surface under `server::`.
#[test]
fn the_single_crate_layout_passes_the_same_suite_with_its_server_feature() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_laid_out(&ir, Target::Rust, OutputLayout::Crate)
        .expect("the fixture synthesizes as one crate");
    let harness = harness_source()
        .replace("desk_server::", "desk::server::")
        .replace("desk_system::", "desk::system::")
        .replace("desk_service::", "desk::ports::desk_service::")
        .replace("desk_types::", "desk::");
    run_suite(
        &ir,
        &synthesis,
        "crate",
        CRATE_DEPENDENCIES,
        &harness,
        &["check", "--all-targets", "--features", "server"],
    );
}

/// Writes the synthesis and the harness beside it, builds both with warnings denied, and runs
/// the suite the specification synthesizes against the harness.
fn run_suite(
    ir: &EssIr,
    synthesis: &ess_synth::Synthesis,
    label: &str,
    dependencies: &str,
    harness_source: &str,
    check: &[&str],
) {
    let scratch = Scratch(
        Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join(format!("declared-behaviour-{label}-{}", std::process::id())),
    );
    let _ = std::fs::remove_dir_all(&scratch.0);
    let tree = scratch.0.join("desk");
    write_tree(&tree, synthesis);
    let harness = scratch.0.join("harness");
    std::fs::create_dir_all(harness.join("src")).expect("mkdir");
    std::fs::write(
        harness.join("Cargo.toml"),
        format!("{HARNESS_MANIFEST}{dependencies}"),
    )
    .expect("write");
    std::fs::write(harness.join("src/main.rs"), harness_source).expect("write the harness");
    let target = scratch.0.join("target");

    let (built, log) = cargo(&tree, &target, check);
    assert!(
        built,
        "the generated {label} builds with -D warnings:\n{log}"
    );
    let (built, log) = cargo(&harness, &target, &["build"]);
    assert!(
        built,
        "the harness builds against the generated ports:\n{log}"
    );

    let binary = target.join("debug/harness");
    let through_port = run_through(ir, &binary, &["port".to_owned()], "the component's port");
    assert_every_event_named_and_encoded(ir, &through_port);
    assert_absent_optional_increment_is_atomic(&through_port);
    drop(through_port);
    // `story:generated-server-publishes-and-reads-headers`: the same suite through the generated
    // HTTP dispatcher, reading what each command published from the served answer alone, with
    // nothing left on the log or in an outbox after any answer.
    let mut served = vec!["served".to_owned()];
    served.extend(route_table(ir));
    let through_server = run_through(ir, &binary, &served, "the generated HTTP surface");
    assert_headers_read(&through_server);
    drop(through_server);
    drop(scratch);
}

/// Makes the optional parent absent through another generated behaviour, then proves the nested
/// increment returns its existing unmet obligation without moving or rewriting the stored row.
fn assert_absent_optional_increment_is_atomic(target: &Harnessed) {
    assert_eq!(
        target.ask(&serde_json::json!({"op": "reset"}))["ok"],
        serde_json::json!(true)
    );
    let caller = "00000000-0000-4000-8000-000000000777";
    let opened = target.ask(&serde_json::json!({
        "op": "command",
        "command": "desk.ticket.OpenTicket",
        "input": {"title": "nested", "priority": "Low", "estimate": 1, "note": null},
        "caller": {"agent_id": caller},
    }));
    let ticket_id = opened["answer"]["published"][0]["payload"]["ticket_id"]
        .as_str()
        .unwrap_or_else(|| panic!("the opening event carries its ticket identity: {opened}"));
    for command in ["desk.ticket.ForgetStats", "desk.ticket.CloseTicket"] {
        let answer = target.ask(&serde_json::json!({
            "op": "command",
            "command": command,
            "input": {"ticket_id": ticket_id},
            "caller": {"agent_id": caller},
        }));
        assert!(
            answer["answer"].get("outcome").is_some(),
            "{command} prepares the absent-parent case: {answer}"
        );
    }
    let before = target.ask(&serde_json::json!({
        "op": "view",
        "view": "desk.ticket.Tickets",
    }));
    let reopened = target.ask(&serde_json::json!({
        "op": "command",
        "command": "desk.ticket.ReopenTicket",
        "input": {"ticket_id": ticket_id},
        "caller": {"agent_id": caller},
    }));
    assert!(
        reopened["answer"]["undeclared"]
            .as_str()
            .is_some_and(|reason| reason.contains("desk.ticket.ReopenTicket")),
        "the absent Optional parent returns the existing unmet obligation: {reopened}"
    );
    let after = target.ask(&serde_json::json!({
        "op": "view",
        "view": "desk.ticket.Tickets",
    }));
    assert_eq!(
        after, before,
        "the unmet increment stores no partial mutation"
    );
}

/// The route table as `name method path` triples, from the mapping the server's routes come from.
fn route_table(ir: &EssIr) -> Vec<String> {
    let mut table = Vec::new();
    for component in ir.components().values() {
        for route in ess_gen::http::routes(ir, component) {
            let name = match route.serves {
                ess_gen::http::Served::Command(handle) => ir.command(handle).name.to_string(),
                ess_gen::http::Served::View(handle) => ir.view(handle).name.to_string(),
            };
            table.extend([name, route.method.as_str().to_owned(), route.path]);
        }
    }
    table
}

/// Every event the system took off its log over the port run was named by `SystemEvent::name` and
/// encoded by `wire::encode_system_event`; together they cover every event the model publishes.
fn assert_every_event_named_and_encoded(ir: &EssIr, target: &Harnessed) {
    let declared: std::collections::BTreeSet<String> = ir
        .components()
        .values()
        .flat_map(|component| component.publishes.iter())
        .map(|event| event.name().to_string())
        .collect();
    let seen = target.logged.borrow().clone();
    assert_eq!(
        seen, declared,
        "every `SystemEvent` variant was named and encoded"
    );
    let suite = ess_conformance::synthesize(ir).suite;
    let steps = || {
        suite
            .scenarios
            .values()
            .flat_map(|scenario| &scenario.steps)
    };
    let captures = steps()
        .filter(|step| matches!(step, ScenarioStep::CaptureInstance { .. }))
        .count();
    let expectations = steps()
        .filter(|step| matches!(step, ScenarioStep::ExpectEvent { .. }))
        .count();
    assert!(
        captures > 0 && expectations > 0,
        "the suite holds a created identity and an expected event: {captures} captures, \
         {expectations} event expectations"
    );
    eprintln!("the suite: {captures} captured identities, {expectations} expected events");
}

/// `server::http::Request` keeps the headers a real socket delivered, in arrival order, names
/// lower-cased and values trimmed; the query string still leaves the path.
fn assert_headers_read(target: &Harnessed) {
    let answer = target.ask(&serde_json::json!({"op": "headers"}));
    assert_eq!(
        answer,
        serde_json::json!({
            "method": "POST",
            "path": "/tickets/commands/open-ticket",
            "headers": [
                ["host", "desk.example"],
                ["authorization", "Bearer token-1"],
                ["x-request-id", "abc-123"],
                ["content-length", "2"],
            ],
            "bounded": 431,
        })
    );
}

/// Runs the suite the specification synthesizes against one harness process.
fn run_through(ir: &EssIr, binary: &Path, arguments: &[String], through: &str) -> Harnessed {
    let suite = ess_conformance::synthesize(ir).suite;
    let admitted = AdmittedSuite::from_suite(&suite).unwrap_or_else(|error| panic!("{error}"));
    let target = Harnessed::start(binary, arguments, ir);
    let report = Runner::for_suite(&suite)
        .run_admitted(&admitted, &target)
        .into_report();
    let failed: Vec<String> = report
        .scenarios
        .iter()
        .filter(|scenario| scenario.status != Status::Passed)
        .map(|scenario| format!("{scenario:#?}"))
        .collect();
    assert!(
        failed.is_empty(),
        "{} of {} scenarios did not pass through {through}:\n{}",
        failed.len(),
        report.scenarios.len(),
        failed.join("\n")
    );
    eprintln!(
        "{} of {} scenarios passed against the generated behaviours, through {through}",
        report.scenarios.len(),
        suite.scenarios.len()
    );
    assert_eq!(report.scenarios.len(), suite.scenarios.len());
    assert!(report.scenarios.len() >= 21, "{}", report.scenarios.len());
    target
}

// ---- the adapter: the suite's requests, over the harness's line protocol ----------------------

/// The harness process, one scenario's published events, and the pending forced branch.
struct Harnessed {
    child: RefCell<Child>,
    stdin: RefCell<ChildStdin>,
    stdout: RefCell<BufReader<ChildStdout>>,
    published: RefCell<Vec<ObservedEvent>>,
    forced: RefCell<Option<OutcomeRef>>,
    sequence: RefCell<u64>,
    optional_fields: BTreeMap<String, Vec<String>>,
    /// Every event name the system log carried on a served run.
    logged: RefCell<std::collections::BTreeSet<String>>,
}

impl Harnessed {
    fn start(binary: &Path, arguments: &[String], ir: &EssIr) -> Self {
        let mut child = Command::new(binary)
            .args(arguments)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("the harness starts");
        let stdin = child.stdin.take().expect("piped");
        let stdout = BufReader::new(child.stdout.take().expect("piped"));
        let optional = |fields: &[ess_compiler::ir::ResolvedField]| -> Vec<String> {
            fields
                .iter()
                .filter(|field| field.type_ref.is_optional())
                .map(|field| field.name.clone())
                .collect()
        };
        let optional_fields = ir
            .events()
            .values()
            .map(|event| (event.name.to_string(), optional(&event.fields)))
            .chain(
                ir.views()
                    .values()
                    .map(|view| (view.name.to_string(), optional(&view.fields))),
            )
            .collect();
        Self {
            child: RefCell::new(child),
            stdin: RefCell::new(stdin),
            stdout: RefCell::new(stdout),
            published: RefCell::default(),
            forced: RefCell::default(),
            sequence: RefCell::new(0),
            optional_fields,
            logged: RefCell::default(),
        }
    }

    /// One request line out, one answer line back.
    fn ask(&self, request: &serde_json::Value) -> serde_json::Value {
        let mut stdin = self.stdin.borrow_mut();
        writeln!(stdin, "{request}").expect("the harness reads");
        stdin.flush().expect("the harness reads");
        let mut line = String::new();
        self.stdout
            .borrow_mut()
            .read_line(&mut line)
            .expect("the harness answers");
        if std::env::var_os("DECLARED_BEHAVIOUR_TRACE").is_some() {
            eprintln!("> {request}\n< {}", line.trim_end());
        }
        serde_json::from_str(&line).unwrap_or_else(|error| panic!("`{line}`: {error}"))
    }

    /// A harness answer, held to what each path promises and read back as the port path words it.
    ///
    /// The port path answers the outcome beside `log`: every event the system pumped and took off
    /// its log (`take_published`), each named by `SystemEvent::name` and encoded by
    /// `wire::encode_system_event`. The outcome's `published` must be that log exactly — the same
    /// events, in publication order, byte for byte the same payloads — and each name must be the
    /// one its encoding carries.
    ///
    /// The served path answers the served body beside `kept`: what the dispatch left on the log
    /// and in the component's outbox, which must be nothing. Its body carries `outcome`,
    /// `published`, and the declared `error` and its `payload`.
    fn served(
        &self,
        observation: &str,
        answer: serde_json::Value,
    ) -> Result<serde_json::Value, TargetError> {
        let Some(status) = answer.get("status").and_then(serde_json::Value::as_u64) else {
            if answer.get("failure").is_some() {
                return Ok(answer);
            }
            let body = answer["answer"].clone();
            if body.get("undeclared").is_some() {
                return Ok(body);
            }
            let log = answer["log"].as_array().cloned().unwrap_or_default();
            let encoded: Vec<serde_json::Value> =
                log.iter().map(|entry| entry["encoded"].clone()).collect();
            for entry in &log {
                assert_eq!(
                    entry["name"], entry["encoded"]["event"],
                    "`SystemEvent::name` and `encode_system_event` name one event: {answer}"
                );
                self.logged.borrow_mut().insert(
                    entry["name"]
                        .as_str()
                        .expect("a logged event has a name")
                        .to_owned(),
                );
            }
            assert_eq!(
                body.get("published"),
                Some(&serde_json::Value::Array(encoded)),
                "the outcome lists exactly what the system published: {answer}"
            );
            return Ok(body);
        };
        assert_eq!(
            answer["kept"],
            serde_json::json!(0),
            "the served dispatch keeps nothing on the log or in an outbox: {answer}"
        );
        if status == 501 {
            return Ok(serde_json::json!({"undeclared": answer["answer"]["refused"]}));
        }
        // The standard refusal for an actor no grant admits (beyond10x/ess#265).
        if status == 403 && answer["answer"]["refused"] == "not granted" {
            return Err(TargetError::not_granted(answer["answer"]["actor"].as_str()));
        }
        let body = &answer["answer"];
        if body.get("outcome").is_none() {
            return Err(failure(observation, &answer));
        }
        let mut read = serde_json::json!({
            "outcome": body["outcome"],
            "published": body["published"],
        });
        if let Some(error) = body.get("error") {
            let mut refusal = serde_json::json!({"error": error});
            if let Some(payload) = body.get("payload") {
                refusal["payload"] = payload.clone();
            }
            read["refusal"] = refusal;
        }
        Ok(read)
    }

    fn tick(&self) -> u64 {
        let mut sequence = self.sequence.borrow_mut();
        *sequence += 1;
        *sequence
    }
}

impl Drop for Harnessed {
    fn drop(&mut self) {
        let _ = self.child.borrow_mut().kill();
        let _ = self.child.borrow_mut().wait();
    }
}

/// A suite value as JSON, a number in its exact spelling (`1`, never `1.0`).
fn json_of(node: &Node) -> serde_json::Value {
    match node {
        Node::Null => serde_json::Value::Null,
        Node::Bool(value) => serde_json::Value::Bool(*value),
        Node::Number(number) => {
            serde_json::from_str(&number.to_string()).expect("a number's spelling is JSON")
        }
        Node::Text(text) => serde_json::Value::String(text.clone()),
        Node::Seq(items) => serde_json::Value::Array(items.iter().map(json_of).collect()),
        Node::Map(members) => serde_json::Value::Object(
            members
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect(),
        ),
    }
}

/// A wire value as a suite value, with absent members left out.
fn node_of(value: &serde_json::Value) -> Node {
    serde_json::from_value(value.clone()).expect("the wire writes JSON a node reads")
}

fn failure(observation: &str, answer: &serde_json::Value) -> TargetError {
    TargetError::unavailable(observation, answer.to_string())
}

impl ConformanceTarget for Harnessed {
    fn identity(&self) -> Result<ImplementationIdentity, TargetError> {
        Ok(ImplementationIdentity::new(
            "declared-behaviour-generated",
            env!("CARGO_PKG_VERSION"),
        ))
    }

    fn begin_scenario(&self, _scenario: &ScenarioContext) -> Result<(), TargetError> {
        let answer = self.ask(&serde_json::json!({"op": "reset"}));
        if answer["ok"] != serde_json::json!(true) {
            return Err(failure("opening a scenario", &answer));
        }
        self.published.borrow_mut().clear();
        *self.forced.borrow_mut() = None;
        *self.sequence.borrow_mut() = 0;
        Ok(())
    }

    fn execute_command(
        &self,
        request: SemanticCommandRequest,
    ) -> Result<SemanticCommandResult, TargetError> {
        let observation = format!("invoking `{}`", request.command);
        let pending = self.forced.borrow_mut().take();
        let force = match pending {
            Some(forced) if forced.command == request.command => Some(forced.outcome.to_string()),
            other => {
                *self.forced.borrow_mut() = other;
                None
            }
        };
        let input: serde_json::Map<String, serde_json::Value> = request
            .input
            .iter()
            .map(|(name, value)| (name.clone(), json_of(value)))
            .collect();
        let caller = request.caller.as_ref().map(|caller| {
            caller
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect::<serde_json::Map<_, _>>()
        });
        let body = serde_json::Value::Object(input.clone()).to_string();
        let answer = self.ask(&serde_json::json!({
            "op": "command",
            "command": request.command.to_string(),
            "actor": request.actor.as_ref().map(ToString::to_string),
            "input": input,
            "body": body,
            "caller": caller,
            "force": force,
        }));
        let answer = self.served(&observation, answer)?;
        if answer.get("undeclared").is_some() {
            return Ok(SemanticCommandResult::undeclared());
        }
        let Some(outcome) = answer["outcome"].as_str() else {
            return Err(failure(&observation, &answer));
        };
        let outcome = OutcomeRef::new(
            CommandRef::new(request.command.name().clone()),
            outcome
                .parse()
                .map_err(|_| failure(&observation, &answer))?,
        );
        let error = match answer.get("refusal") {
            Some(refusal) => {
                let name: ErrorRef = refusal["error"]
                    .as_str()
                    .and_then(|name| name.parse().ok())
                    .ok_or_else(|| failure(&observation, &answer))?;
                let mut declared = DeclaredErrorValue::new(name);
                if let Some(serde_json::Value::Object(payload)) = refusal.get("payload") {
                    for (field, value) in payload {
                        if !value.is_null() {
                            declared = declared.with(field.clone(), node_of(value));
                        }
                    }
                }
                Some(declared)
            }
            None => None,
        };
        let mut direct_events = Vec::new();
        for published in answer["published"].as_array().into_iter().flatten() {
            let name = published["event"]
                .as_str()
                .ok_or_else(|| failure(&observation, &answer))?;
            let reference: EventRef = name.parse().map_err(|_| failure(&observation, &answer))?;
            let mut event = ObservedEvent::new(reference);
            if let Some(serde_json::Value::Object(payload)) = published.get("payload") {
                for (field, value) in payload {
                    let optional = self
                        .optional_fields
                        .get(name)
                        .is_some_and(|fields| fields.contains(field));
                    if value.is_null() && optional {
                        continue;
                    }
                    event = event.with(field.clone(), node_of(value));
                }
            }
            let event = event
                .in_activity(request.correlation.clone())
                .at(self.tick());
            self.published.borrow_mut().push(event.clone());
            direct_events.push(event);
        }
        // Every declared outcome names the state it leaves, a refusal included: the suite reads a
        // view no older than the command it just sent, whichever branch that command took.
        let consistency = Some(
            ConsistencyToken::new(format!("seq:{}", self.tick()))
                .map_err(|why| TargetError::unavailable(observation.clone(), why.to_string()))?,
        );
        Ok(SemanticCommandResult {
            outcome: Some(outcome),
            error,
            consistency,
            direct_events,
            response: None,
        })
    }

    fn query_view(&self, request: SemanticViewRequest) -> Result<SemanticViewResult, TargetError> {
        let observation = format!("reading `{}`", request.view);
        let answer = self.ask(&serde_json::json!({"op": "view", "view": request.view.to_string()}));
        let answer = match answer.get("status") {
            Some(_) => answer["answer"].clone(),
            None => answer,
        };
        let Some(rows) = answer["rows"].as_array() else {
            return Err(failure(&observation, &answer));
        };
        let optional = self
            .optional_fields
            .get(&request.view.to_string())
            .cloned()
            .unwrap_or_default();
        Ok(SemanticViewResult::of(rows.iter().map(|row| {
            // The wire leaves an absent optional field out; the row holds it as `null`.
            let mut read: ViewRow = row
                .as_object()
                .into_iter()
                .flatten()
                .map(|(field, value)| (field.clone(), node_of(value)))
                .collect();
            for field in &optional {
                read.entry(field.clone()).or_insert(Node::Null);
            }
            read
        })))
    }

    fn observe_events(
        &self,
        request: EventObservationRequest,
    ) -> Result<Vec<ObservedEvent>, TargetError> {
        Ok(self
            .published
            .borrow()
            .iter()
            .filter(|event| event.event == request.event)
            .cloned()
            .collect())
    }

    fn configure_external_outcome(
        &self,
        request: ExternalOutcomeControl,
    ) -> Result<(), TargetError> {
        *self.forced.borrow_mut() = Some(request.force);
        Ok(())
    }

    fn redeliver_event(&self, request: RedeliveryRequest) -> Result<(), TargetError> {
        Err(TargetError::unsupported(
            format!("delivering `{}` again", request.event),
            "the fixture declares no binding",
        ))
    }

    fn end_scenario(&self, _scenario: &ScenarioContext) -> Result<(), TargetError> {
        self.published.borrow_mut().clear();
        *self.forced.borrow_mut() = None;
        Ok(())
    }
}
