//! A fully declared command's behaviour is generated over storage and context ports
//! (`story:generated-behaviour-for-declared-commands`).
//!
//! The fixture under `tests/fixtures/declared-behaviour/` declares every construct the story names
//! as expressible: `when:`, `when_subject:`, `when_subject_state:`, `unknown_instance:`,
//! `wrong_state:`, a default, `external:` with and without an input guard; `creates:`, `moves:`,
//! `updates:`, `deletes:`; `sets:` from input, a literal, `{increment:}`, `{cleared}`, the caller and
//! `{generated: true}`; payloads from input, subject fields, the caller and generated values. Its
//! Rust workspace is synthesized, the in-memory port implementation in
//! `tests/fixtures/declared-behaviour-harness/` is placed beside it (outside the generated bytes,
//! holding no command behaviour), and the suite the same specification synthesizes runs against
//! the generated behaviours through that harness.

use std::cell::RefCell;
use std::collections::BTreeMap;
use std::io::{BufRead, BufReader, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, ChildStdout, Command, Stdio};

use ess_compiler::ir::EssIr;
use ess_compiler::resolve::compile_locating;
use ess_compiler::source::SourceMap;
use ess_conformance::report::Status;
use ess_conformance::scenario::{CommandRef, ErrorRef, EventRef, OutcomeRef};
use ess_conformance::target::{
    ConformanceTarget, DeclaredErrorValue, EventObservationRequest, ExternalOutcomeControl,
    ImplementationIdentity, ObservedEvent, RedeliveryRequest, ScenarioContext,
    SemanticCommandRequest, SemanticCommandResult, SemanticViewRequest, SemanticViewResult,
    TargetError, ViewRow,
};
use ess_conformance::{AdmittedSuite, Runner};
use ess_domain::spec::{RawSpecFile, Specification};
use ess_domain::system::Source;
use ess_primitives::consistency::ConsistencyToken;
use ess_primitives::node::Node;
use ess_synth::{synthesize_for, CapabilityKind, SynthesisDisposition, SynthesisPlan, Target};

/// The fixture directory.
fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/declared-behaviour")
}

/// A specification directory, compiled where it lives.
fn compile_directory(base: &Path) -> EssIr {
    let mut labels = Vec::new();
    let mut pending = vec![base.to_path_buf()];
    while let Some(directory) = pending.pop() {
        for entry in std::fs::read_dir(&directory).expect("the fixture is readable") {
            let path = entry.expect("an entry").path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|it| it == "yaml") {
                labels.push(
                    path.strip_prefix(base)
                        .expect("inside the fixture")
                        .display()
                        .to_string(),
                );
            }
        }
    }
    labels.sort();
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for label in &labels {
        let text = std::fs::read_to_string(base.join(label)).expect("readable");
        let raw = RawSpecFile::parse(&text)
            .unwrap_or_else(|error| panic!("{label} is well formed: {error}"));
        sources.insert(label.clone(), text);
        parsed.push((Source::new(label.clone()), raw));
    }
    let specification = Specification::assemble(parsed)
        .unwrap_or_else(|errors| panic!("the fixture validates:\n{errors}"));
    compile_locating(&specification, &sources, &labels)
        .unwrap_or_else(|diagnostics| panic!("the fixture resolves:\n{diagnostics}"))
}

/// One YAML document, compiled.
fn compile_text(text: &str) -> EssIr {
    let raw = RawSpecFile::parse(text).unwrap_or_else(|error| panic!("well formed: {error}"));
    let specification = Specification::assemble([(Source::new("model.yaml"), raw)])
        .unwrap_or_else(|errors| panic!("validates:\n{errors}"));
    let mut sources = SourceMap::new();
    sources.insert("model.yaml".to_owned(), text.to_owned());
    compile_locating(&specification, &sources, &["model.yaml".to_owned()])
        .unwrap_or_else(|diagnostics| panic!("resolves:\n{diagnostics}"))
}

#[test]
fn the_plan_generates_every_fully_declared_command_and_keeps_the_view_owed() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes");
    for command in ir.commands().keys() {
        assert_eq!(
            synthesis
                .plan
                .disposition_of(CapabilityKind::CommandBehavior, &command.to_string()),
            Some(&SynthesisDisposition::Generated),
            "`{command}` is fully declared, so its behaviour is generated"
        );
    }
    assert!(matches!(
        synthesis
            .plan
            .disposition_of(CapabilityKind::ViewQuery, "desk.ticket.Tickets"),
        Some(SynthesisDisposition::Obligation(_))
    ));
    let behaviour = synthesis
        .artifacts
        .get("crates/desk-types/src/behaviour.rs")
        .expect("the types crate carries the generated behaviours");
    for port in [
        "pub trait TicketStorage",
        "pub trait Context",
        "pub struct Generated<P>",
        "fn external(&mut self, command: &'static str, outcome: &'static str) -> bool;",
        "fn caller_agent_id(&self) -> Option<crate::ticket::AgentId>;",
        "fn generate_desk_ticket_ticket_id(&mut self) -> crate::ticket::TicketId;",
    ] {
        assert!(
            behaviour.contents.contains(port),
            "`{port}` missing:\n{}",
            behaviour.contents
        );
    }
    assert!(
        !behaviour.contents.contains("impl Unimplemented")
            && !synthesis
                .artifacts
                .values()
                .any(|artifact| artifact.contents.contains("impl TicketStorage for")),
        "ess generates the storage trait, never a store"
    );
    let domain = &synthesis.artifacts["crates/desk-types/src/ticket.rs"].contents;
    assert!(
        !domain.contains("impl OpenTicketBehavior for Unimplemented"),
        "a generated behaviour is not stubbed as owed"
    );
    assert!(domain.contains("pub trait OpenTicketBehavior"), "{domain}");
}

#[test]
fn a_moved_or_written_entity_is_checked_against_its_invariants_before_it_is_stored() {
    let ir = compile_directory(&fixture_root());
    let with_invariant = fixture_with_invariant();
    let plain = synthesize_for(&ir, Target::Rust).expect("synthesizes");
    let checked = synthesize_for(&with_invariant, Target::Rust).expect("synthesizes");
    let behaviour = |synthesis: &ess_synth::Synthesis| {
        synthesis.artifacts["crates/desk-types/src/behaviour.rs"]
            .contents
            .clone()
    };
    assert!(
        !behaviour(&plain).contains("broken_invariant"),
        "an entity declaring no invariant has no check to call"
    );
    let text = behaviour(&checked);
    // Every write of the entity — the create, both moves, the three updates — is preceded by the
    // check.
    let puts = text.matches("TicketStorage::put(").count();
    let checks = text.matches(".broken_invariant()").count();
    assert_eq!(puts, 6, "{text}");
    assert_eq!(checks, puts, "{text}");
    for (position, _) in text.match_indices("TicketStorage::put(") {
        let before = &text[..position];
        let check = before
            .rfind(".broken_invariant()")
            .expect("a check before the write");
        let previous_put = before.rfind("TicketStorage::put(").unwrap_or(0);
        assert!(
            check > previous_put,
            "the check precedes its own write:\n{text}"
        );
    }
}

/// The fixture with `estimate >= 0` declared on the ticket.
fn fixture_with_invariant() -> EssIr {
    let base = fixture_root();
    let mut labels = vec![
        "components.yaml".to_owned(),
        "domains/ticket.yaml".to_owned(),
        "system.yaml".to_owned(),
    ];
    labels.sort();
    let mut sources = SourceMap::new();
    let mut parsed = Vec::new();
    for label in &labels {
        let mut text = std::fs::read_to_string(base.join(label)).expect("readable");
        if label == "domains/ticket.yaml" {
            text = text.replace(
                "      - {name: note, type: Optional<String>}\n    lifecycle:",
                "      - {name: note, type: Optional<String>}\n    invariants:\n      - estimate >= 0\n    lifecycle:",
            );
        }
        let raw = RawSpecFile::parse(&text).expect("well formed");
        sources.insert(label.clone(), text);
        parsed.push((Source::new(label.clone()), raw));
    }
    let specification = Specification::assemble(parsed).expect("validates");
    compile_locating(&specification, &sources, &labels).expect("resolves")
}

/// A command that uses one construct the story keeps an obligation, beside a sibling that is fully
/// declared, and the phrase its obligation must name.
struct Kept {
    model: &'static str,
    command: &'static str,
    names: &'static str,
}

#[test]
fn every_construct_the_story_keeps_owed_keeps_its_whole_command_an_obligation() {
    let cases = [
        Kept {
            model: RELATED_GUARD,
            command: "kept.shop.PlaceOrder",
            names: "`when_related:`",
        },
        Kept {
            model: RELATED_SET,
            command: "kept.shop.PlaceOrder",
            names: "`{related:}`",
        },
        Kept {
            model: STATE_AND_EXTERNAL,
            command: "kept.shop.Ship",
            names: "`when_subject_state:` beside `external:`",
        },
        Kept {
            model: MOVE_OR_UPDATE,
            command: "kept.shop.Ship",
            names: "a subject predicate choosing between a move and an update",
        },
        Kept {
            model: NO_UNKNOWN_ANSWER,
            command: "kept.shop.Ship",
            names: "an unknown identity",
        },
        Kept {
            model: SET_OUTCOME,
            command: "kept.shop.ShipAll",
            names: "`instances:`",
        },
        Kept {
            model: AFFECTS,
            command: "kept.shop.Ship",
            names: "`affects:`",
        },
        Kept {
            model: UNDETERMINED_ERROR,
            command: "kept.shop.PlaceOrder",
            names: "the fields of error `kept.shop.TooMany`",
        },
        Kept {
            model: UNDETERMINED_FIELD,
            command: "kept.shop.PlaceOrder",
            names: "`creates:` leaving the required field `quantity`",
        },
    ];
    for case in cases {
        let ir = compile_text(case.model);
        // The plan, not a target: `instances:` and `affects:` are refused by the Rust target as a
        // whole, and the plan still names the construct that keeps the command owed.
        let plan = SynthesisPlan::of(&ir);
        match plan.disposition_of(CapabilityKind::CommandBehavior, case.command) {
            Some(SynthesisDisposition::Obligation(obligation)) => {
                let why = obligation.reason.describes();
                assert!(
                    why.contains(case.names),
                    "`{}` names `{}` as what kept it owed, not: {why}",
                    case.command,
                    case.names
                );
            }
            other => panic!("`{}` stays an obligation, not {other:?}", case.command),
        }
        let markdown = plan.to_markdown();
        assert!(markdown.contains(case.names), "{markdown}");
        // The sibling in each model is fully declared and generated: the line is per command.
        assert_eq!(
            plan.disposition_of(CapabilityKind::CommandBehavior, "kept.shop.OpenShop"),
            Some(&SynthesisDisposition::Generated),
            "{}",
            case.command
        );
    }
}

const RELATED_GUARD: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: no-shop
        when_related: {via: input.shop_id, exists: false}
        error: kept.shop.NoShop
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id, quantity: input.quantity}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

const RELATED_SET: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets:
          shop_id: input.shop_id
          quantity: input.quantity
          region: {related: {via: input.shop_id, field: region}}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

const STATE_AND_EXTERNAL: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: already-shipped
        when_subject_state: Shipped
        error: kept.shop.Conflict
      - name: carrier-refused
        external: the carrier refuses the parcel
        error: kept.shop.Refused
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
"
);

const MOVE_OR_UPDATE: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: shipped
        when_subject: {predicate: quantity > 0}
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - name: topped-up
        updates: kept.shop.Order
        instance: order_id
        sets: {quantity: \"1\"}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
      - {name: already-shipped, wrong_state: true, error: kept.shop.Conflict}
"
);

const NO_UNKNOWN_ANSWER: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: already-shipped
        when_subject_state: Shipped
        error: kept.shop.Conflict
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
"
);

const SET_OUTCOME: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.ShipAll
    input: [{name: shop_id, type: kept.shop.ShopId}]
    outcomes:
      - name: shipped
        moves: kept.shop.Order.ship
        instances: {where: shop_id == input.shop_id}
        emits: [kept.shop.ShopOpened]
        payload:
          kept.shop.ShopOpened: {shop_id: input.shop_id}
"
);

const AFFECTS: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.Ship
    input: [{name: order_id, type: kept.shop.OrderId}]
    outcomes:
      - name: shipped
        moves: kept.shop.Order.ship
        instance: order_id
        affects:
          - entity: kept.shop.Order
            where: shop_id == subject.shop_id
            sets: {region: {cleared: true}}
        emits: [kept.shop.OrderShipped]
        payload:
          kept.shop.OrderShipped: {order_id: input.order_id}
      - {name: no-such-order, unknown_instance: true, error: kept.shop.Conflict}
      - {name: already-shipped, wrong_state: true, error: kept.shop.Conflict}
"
);

const UNDETERMINED_ERROR: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
      - {name: quantity, type: Integer}
    outcomes:
      - name: too-many
        when: quantity > 10
        error: kept.shop.TooMany
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id, quantity: input.quantity}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

const UNDETERMINED_FIELD: &str = concat!(
    include_str!("fixtures/declared-behaviour-kept/head.yaml"),
    "  - name: kept.shop.PlaceOrder
    input:
      - {name: shop_id, type: kept.shop.ShopId}
    outcomes:
      - name: placed
        creates: kept.shop.Order
        instance: order_id
        sets: {shop_id: input.shop_id}
        emits: [kept.shop.OrderPlaced]
        payload:
          kept.shop.OrderPlaced: {order_id: {generated: true}}
"
);

#[test]
fn the_go_target_emits_a_generated_behaviour_as_a_seam_and_says_so() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Go).expect("the fixture synthesizes to Go");
    let report = synthesis.target.expect("Go reports what it weakens");
    assert!(
        report.weakenings.iter().any(|weakening| weakening
            .affects
            .contains(&CapabilityKind::CommandBehavior)
            && weakening.instead.contains("seam")),
        "{report:#?}"
    );
}

// ---- the generated workspace, built and run against its own suite ------------------------------

/// A scratch directory under this test binary's target, removed when dropped.
struct Scratch(PathBuf);

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// Writes every artifact of a synthesis under `root`.
fn write_tree(root: &Path, synthesis: &ess_synth::Synthesis) {
    for artifact in synthesis.artifacts.values() {
        let path = root.join(&artifact.path);
        std::fs::create_dir_all(path.parent().expect("a file has a parent")).expect("mkdir");
        std::fs::write(&path, &artifact.contents).expect("write");
    }
}

/// Runs cargo offline in `directory`, with warnings denied, returning its combined output.
fn cargo(directory: &Path, target: &Path, arguments: &[&str]) -> (bool, String) {
    let output = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args(arguments)
        .arg("--offline")
        .current_dir(directory)
        .env("CARGO_TARGET_DIR", target)
        .env("RUSTFLAGS", "-D warnings")
        .env("CARGO_INCREMENTAL", "0")
        .env_remove("RUSTC_WRAPPER")
        .output()
        .expect("cargo runs");
    (
        output.status.success(),
        format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ),
    )
}

/// The harness crate's manifest, pointing into the generated workspace beside it.
const HARNESS_MANIFEST: &str = "[package]
name = \"declared-behaviour-harness\"
version = \"0.0.0\"
edition = \"2021\"
publish = false

[workspace]

[[bin]]
name = \"harness\"
path = \"src/main.rs\"

[dependencies]
desk-types = { path = \"../desk/crates/desk-types\" }
desk-server = { path = \"../desk/crates/desk-server\" }
desk-service = { path = \"../desk/crates/desk-service\" }
";

#[test]
fn the_generated_behaviours_build_with_warnings_denied_and_pass_their_own_suite() {
    let ir = compile_directory(&fixture_root());
    let synthesis = synthesize_for(&ir, Target::Rust).expect("the fixture synthesizes");

    let scratch = Scratch(
        Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join(format!("declared-behaviour-{}", std::process::id())),
    );
    let _ = std::fs::remove_dir_all(&scratch.0);
    let tree = scratch.0.join("desk");
    write_tree(&tree, &synthesis);
    let harness = scratch.0.join("harness");
    std::fs::create_dir_all(harness.join("src")).expect("mkdir");
    std::fs::write(harness.join("Cargo.toml"), HARNESS_MANIFEST).expect("write");
    std::fs::copy(
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/declared-behaviour-harness/main.rs"),
        harness.join("src/main.rs"),
    )
    .expect("copy the harness");
    let target = scratch.0.join("target");

    let (built, log) = cargo(&tree, &target, &["check", "--workspace", "--all-targets"]);
    assert!(
        built,
        "the generated workspace builds with -D warnings:\n{log}"
    );
    let (built, log) = cargo(&harness, &target, &["build"]);
    assert!(
        built,
        "the harness builds against the generated ports:\n{log}"
    );

    let suite = ess_conformance::synthesize(&ir).suite;
    let admitted = AdmittedSuite::from_suite(&suite).unwrap_or_else(|error| panic!("{error}"));
    let target = Harnessed::start(&target.join("debug/harness"), &ir);
    let report = Runner::for_suite(&suite)
        .run_admitted(&admitted, &target)
        .into_report();
    let failed: Vec<String> = report
        .scenarios
        .iter()
        .filter(|scenario| scenario.status != Status::Passed)
        .map(|scenario| format!("{scenario:#?}"))
        .collect();
    assert!(
        failed.is_empty(),
        "{} of {} scenarios did not pass:\n{}",
        failed.len(),
        report.scenarios.len(),
        failed.join("\n")
    );
    eprintln!(
        "{} of {} scenarios passed against the generated behaviours",
        report.scenarios.len(),
        suite.scenarios.len()
    );
    assert_eq!(report.scenarios.len(), suite.scenarios.len());
    assert!(report.scenarios.len() >= 21, "{}", report.scenarios.len());
    drop(target);
    drop(scratch);
}

// ---- the adapter: the suite's requests, over the harness's line protocol ----------------------

/// The harness process, one scenario's published events, and the pending forced branch.
struct Harnessed {
    child: RefCell<Child>,
    stdin: RefCell<ChildStdin>,
    stdout: RefCell<BufReader<ChildStdout>>,
    published: RefCell<Vec<ObservedEvent>>,
    forced: RefCell<Option<OutcomeRef>>,
    sequence: RefCell<u64>,
    optional_fields: BTreeMap<String, Vec<String>>,
}

impl Harnessed {
    fn start(binary: &Path, ir: &EssIr) -> Self {
        let mut child = Command::new(binary)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .spawn()
            .expect("the harness starts");
        let stdin = child.stdin.take().expect("piped");
        let stdout = BufReader::new(child.stdout.take().expect("piped"));
        let optional = |fields: &[ess_compiler::ir::ResolvedField]| -> Vec<String> {
            fields
                .iter()
                .filter(|field| field.type_ref.is_optional())
                .map(|field| field.name.clone())
                .collect()
        };
        let optional_fields = ir
            .events()
            .values()
            .map(|event| (event.name.to_string(), optional(&event.fields)))
            .chain(
                ir.views()
                    .values()
                    .map(|view| (view.name.to_string(), optional(&view.fields))),
            )
            .collect();
        Self {
            child: RefCell::new(child),
            stdin: RefCell::new(stdin),
            stdout: RefCell::new(stdout),
            published: RefCell::default(),
            forced: RefCell::default(),
            sequence: RefCell::new(0),
            optional_fields,
        }
    }

    /// One request line out, one answer line back.
    fn ask(&self, request: &serde_json::Value) -> serde_json::Value {
        let mut stdin = self.stdin.borrow_mut();
        writeln!(stdin, "{request}").expect("the harness reads");
        stdin.flush().expect("the harness reads");
        let mut line = String::new();
        self.stdout
            .borrow_mut()
            .read_line(&mut line)
            .expect("the harness answers");
        if std::env::var_os("DECLARED_BEHAVIOUR_TRACE").is_some() {
            eprintln!("> {request}\n< {}", line.trim_end());
        }
        serde_json::from_str(&line).unwrap_or_else(|error| panic!("`{line}`: {error}"))
    }

    fn tick(&self) -> u64 {
        let mut sequence = self.sequence.borrow_mut();
        *sequence += 1;
        *sequence
    }
}

impl Drop for Harnessed {
    fn drop(&mut self) {
        let _ = self.child.borrow_mut().kill();
        let _ = self.child.borrow_mut().wait();
    }
}

/// A suite value as JSON, a number in its exact spelling (`1`, never `1.0`).
fn json_of(node: &Node) -> serde_json::Value {
    match node {
        Node::Null => serde_json::Value::Null,
        Node::Bool(value) => serde_json::Value::Bool(*value),
        Node::Number(number) => {
            serde_json::from_str(&number.to_string()).expect("a number's spelling is JSON")
        }
        Node::Text(text) => serde_json::Value::String(text.clone()),
        Node::Seq(items) => serde_json::Value::Array(items.iter().map(json_of).collect()),
        Node::Map(members) => serde_json::Value::Object(
            members
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect(),
        ),
    }
}

/// A wire value as a suite value, with absent members left out.
fn node_of(value: &serde_json::Value) -> Node {
    serde_json::from_value(value.clone()).expect("the wire writes JSON a node reads")
}

fn failure(observation: &str, answer: &serde_json::Value) -> TargetError {
    TargetError::unavailable(observation, answer.to_string())
}

impl ConformanceTarget for Harnessed {
    fn identity(&self) -> Result<ImplementationIdentity, TargetError> {
        Ok(ImplementationIdentity::new(
            "declared-behaviour-generated",
            env!("CARGO_PKG_VERSION"),
        ))
    }

    fn begin_scenario(&self, _scenario: &ScenarioContext) -> Result<(), TargetError> {
        let answer = self.ask(&serde_json::json!({"op": "reset"}));
        if answer["ok"] != serde_json::json!(true) {
            return Err(failure("opening a scenario", &answer));
        }
        self.published.borrow_mut().clear();
        *self.forced.borrow_mut() = None;
        *self.sequence.borrow_mut() = 0;
        Ok(())
    }

    fn execute_command(
        &self,
        request: SemanticCommandRequest,
    ) -> Result<SemanticCommandResult, TargetError> {
        let observation = format!("invoking `{}`", request.command);
        let pending = self.forced.borrow_mut().take();
        let force = match pending {
            Some(forced) if forced.command == request.command => Some(forced.outcome.to_string()),
            other => {
                *self.forced.borrow_mut() = other;
                None
            }
        };
        let input: serde_json::Map<String, serde_json::Value> = request
            .input
            .iter()
            .map(|(name, value)| (name.clone(), json_of(value)))
            .collect();
        let caller = request.caller.as_ref().map(|caller| {
            caller
                .iter()
                .map(|(name, value)| (name.clone(), json_of(value)))
                .collect::<serde_json::Map<_, _>>()
        });
        let answer = self.ask(&serde_json::json!({
            "op": "command",
            "command": request.command.to_string(),
            "input": input,
            "caller": caller,
            "force": force,
        }));
        if answer.get("undeclared").is_some() {
            return Ok(SemanticCommandResult::undeclared());
        }
        let Some(outcome) = answer["outcome"].as_str() else {
            return Err(failure(&observation, &answer));
        };
        let outcome = OutcomeRef::new(
            CommandRef::new(request.command.name().clone()),
            outcome
                .parse()
                .map_err(|_| failure(&observation, &answer))?,
        );
        let error = match answer.get("refusal") {
            Some(refusal) => {
                let name: ErrorRef = refusal["error"]
                    .as_str()
                    .and_then(|name| name.parse().ok())
                    .ok_or_else(|| failure(&observation, &answer))?;
                let mut declared = DeclaredErrorValue::new(name);
                if let Some(serde_json::Value::Object(payload)) = refusal.get("payload") {
                    for (field, value) in payload {
                        if !value.is_null() {
                            declared = declared.with(field.clone(), node_of(value));
                        }
                    }
                }
                Some(declared)
            }
            None => None,
        };
        let mut direct_events = Vec::new();
        for published in answer["published"].as_array().into_iter().flatten() {
            let name = published["event"]
                .as_str()
                .ok_or_else(|| failure(&observation, &answer))?;
            let reference: EventRef = name.parse().map_err(|_| failure(&observation, &answer))?;
            let mut event = ObservedEvent::new(reference);
            if let Some(serde_json::Value::Object(payload)) = published.get("payload") {
                for (field, value) in payload {
                    let optional = self
                        .optional_fields
                        .get(name)
                        .is_some_and(|fields| fields.contains(field));
                    if value.is_null() && optional {
                        continue;
                    }
                    event = event.with(field.clone(), node_of(value));
                }
            }
            let event = event
                .in_activity(request.correlation.clone())
                .at(self.tick());
            self.published.borrow_mut().push(event.clone());
            direct_events.push(event);
        }
        // Every declared outcome names the state it leaves, a refusal included: the suite reads a
        // view no older than the command it just sent, whichever branch that command took.
        let consistency = Some(
            ConsistencyToken::new(format!("seq:{}", self.tick()))
                .map_err(|why| TargetError::unavailable(observation.clone(), why.to_string()))?,
        );
        Ok(SemanticCommandResult {
            outcome: Some(outcome),
            error,
            consistency,
            direct_events,
            response: None,
        })
    }

    fn query_view(&self, request: SemanticViewRequest) -> Result<SemanticViewResult, TargetError> {
        let observation = format!("reading `{}`", request.view);
        let answer = self.ask(&serde_json::json!({"op": "view", "view": request.view.to_string()}));
        let Some(rows) = answer["rows"].as_array() else {
            return Err(failure(&observation, &answer));
        };
        let optional = self
            .optional_fields
            .get(&request.view.to_string())
            .cloned()
            .unwrap_or_default();
        Ok(SemanticViewResult::of(rows.iter().map(|row| {
            // The wire leaves an absent optional field out; the row holds it as `null`.
            let mut read: ViewRow = row
                .as_object()
                .into_iter()
                .flatten()
                .map(|(field, value)| (field.clone(), node_of(value)))
                .collect();
            for field in &optional {
                read.entry(field.clone()).or_insert(Node::Null);
            }
            read
        })))
    }

    fn observe_events(
        &self,
        request: EventObservationRequest,
    ) -> Result<Vec<ObservedEvent>, TargetError> {
        Ok(self
            .published
            .borrow()
            .iter()
            .filter(|event| event.event == request.event)
            .cloned()
            .collect())
    }

    fn configure_external_outcome(
        &self,
        request: ExternalOutcomeControl,
    ) -> Result<(), TargetError> {
        *self.forced.borrow_mut() = Some(request.force);
        Ok(())
    }

    fn redeliver_event(&self, request: RedeliveryRequest) -> Result<(), TargetError> {
        Err(TargetError::unsupported(
            format!("delivering `{}` again", request.event),
            "the fixture declares no binding",
        ))
    }

    fn end_scenario(&self, _scenario: &ScenarioContext) -> Result<(), TargetError> {
        self.published.borrow_mut().clear();
        *self.forced.borrow_mut() = None;
        Ok(())
    }
}
