//! Compiler-admitted models must produce a usable Rust workspace or an explicit target refusal.

use ess_compiler::ir::EssIr;
use ess_compiler::resolve::compile_locating;
use ess_compiler::source::SourceMap;
use ess_domain::spec::{RawSpecFile, Specification};
use ess_domain::system::Source;
use ess_synth::{synthesize, synthesize_for, Synthesis, SynthesisPlan, Target};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicUsize, Ordering};

static FIXTURE_SEQUENCE: AtomicUsize = AtomicUsize::new(0);

fn fixture(documents: &[(&str, &str)]) -> EssIr {
    let mut sources = SourceMap::new();
    let mut labels = Vec::new();
    let mut parsed = Vec::new();
    for (label, text) in documents {
        let raw = RawSpecFile::parse(text).expect("the fixture parses");
        sources.insert((*label).to_owned(), (*text).to_owned());
        labels.push((*label).to_owned());
        parsed.push((Source::new((*label).to_owned()), raw));
    }
    let specification = Specification::assemble(parsed)
        .unwrap_or_else(|errors| panic!("the source is valid ESS: {errors}"));
    compile_locating(&specification, &sources, &labels)
        .unwrap_or_else(|errors| panic!("the source resolves: {errors}"))
}

fn core(body: &str, wiring: &str) -> EssIr {
    fixture(&[
        (
            "system.yaml",
            "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.core\n",
        ),
        ("core.yaml", &format!("domain: demo.core\n{body}")),
        (
            "wiring.yaml",
            if wiring.is_empty() {
                "components: []\n"
            } else {
                wiring
            },
        ),
    ])
}

#[test]
fn binary64_is_refused_even_when_no_component_consumes_the_type() {
    let ir = fixture(&[("sparse.yaml", "format: ess/2\nsystem: demo\nversion: v1\ndomains: [demo.core]\ndomain: demo.core\ntypes:\n  - {name: demo.core.Ratio, kind: newtype, of: Binary64}\n")]);
    let plan = SynthesisPlan::of(&ir);
    for (target, label, format) in [
        (Target::Rust, "rust", "ess-target-failure/1"),
        (Target::Web, "web", "ess-target-failure/1"),
        (Target::Go, "go", "ess-target-failure/2"),
        (Target::Clap, "clap", "ess-target-failure/2"),
    ] {
        let failure = synthesize_for(&ir, target)
            .err()
            .expect("finite codec refusal");
        assert_eq!(failure.target(), label);
        let json: serde_json::Value = serde_json::from_str(&failure.to_canonical_json()).unwrap();
        assert_eq!(json["format"], format);
        assert_eq!(failure.causes().len(), 1);
        assert_ne!(failure.causes()[0].sources().len(), 0);
        assert!(failure.causes()[0].detail().contains("Binary64"));
        let direct = match target {
            Target::Rust => {
                ess_synth::rust::workspace(&ir, &plan).expect_err("finite codec refusal")
            }
            Target::Go => ess_synth::go::workspace(&ir, &plan)
                .err()
                .expect("finite codec refusal"),
            Target::Web => ess_synth::web::workspace(&ir, &plan)
                .err()
                .expect("finite codec refusal"),
            Target::Clap => ess_synth::clap::workspace(&ir, &plan)
                .err()
                .expect("finite codec refusal"),
        };
        assert_eq!(direct.to_canonical_json(), failure.to_canonical_json());
    }
}

fn scratch(name: &str) -> PathBuf {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..");
    let directory = root
        .join("target/review-boundaries-5/compiler-fixtures")
        .join(format!(
            "{name}-{}-{}",
            std::process::id(),
            FIXTURE_SEQUENCE.fetch_add(1, Ordering::Relaxed)
        ));
    std::fs::create_dir_all(&directory).expect("create an isolated fixture inside the unit target");
    directory
}

fn write_emission(directory: &Path, synthesis: &Synthesis) {
    for (relative, artifact) in &synthesis.artifacts {
        let destination = directory.join(relative);
        std::fs::create_dir_all(destination.parent().expect("artifact parent"))
            .expect("create generated directories");
        std::fs::write(&destination, &artifact.contents).expect("write exact generated bytes");
    }
}

fn cargo(directory: &Path, lane: &str, arguments: &[&str]) -> std::process::Output {
    let mut command =
        Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"));
    command
        .current_dir(directory)
        .env_remove("CARGO_TARGET_DIR");
    command.args(arguments);
    std::fs::write(
        directory.join(format!("{lane}.command")),
        format!("{command:?}\n"),
    )
    .expect("record compiler command");
    let output = command
        .output()
        .expect("the offline Rust compiler lane must be available");
    std::fs::write(directory.join(format!("{lane}.stdout")), &output.stdout)
        .expect("retain compiler stdout");
    std::fs::write(directory.join(format!("{lane}.stderr")), &output.stderr)
        .expect("retain compiler stderr");
    std::fs::write(
        directory.join(format!("{lane}.exit")),
        output.status.to_string(),
    )
    .expect("retain compiler exit");
    eprintln!(
        "{command:?}\n{}\n{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
        output.status
    );
    output
}

fn check_generated(directory: &Path) {
    check_generated_for(directory, None);
}

fn check_generated_for(directory: &Path, target: Option<&str>) {
    let before = generated_bytes(directory);
    let lock = cargo(
        directory,
        "lock",
        &[
            "generate-lockfile",
            "--offline",
            "--manifest-path",
            "Cargo.toml",
        ],
    );
    assert!(
        lock.status.success(),
        "fixture lock resolution failed; not a skipped compiler lane"
    );
    let mut arguments = vec![
        "check",
        "--locked",
        "--offline",
        "--workspace",
        "--all-targets",
        "--manifest-path",
        "Cargo.toml",
        "--target-dir",
        "target",
    ];
    if let Some(target) = target {
        arguments.extend(["--target", target]);
    }
    let checked = cargo(directory, "check", &arguments);
    assert!(
        checked.status.success(),
        "fresh generated workspace failed compilation; see {}",
        directory.display()
    );
    assert_eq!(
        before,
        generated_bytes(directory),
        "Cargo must not rewrite generated source or manifests"
    );
}

fn generated_bytes(directory: &Path) -> std::collections::BTreeMap<PathBuf, Vec<u8>> {
    fn visit(
        root: &Path,
        directory: &Path,
        bytes: &mut std::collections::BTreeMap<PathBuf, Vec<u8>>,
    ) {
        for entry in std::fs::read_dir(directory).unwrap() {
            let path = entry.unwrap().path();
            if path.file_name().is_some_and(|name| name == "target") {
                continue;
            }
            if path.is_dir() {
                visit(root, &path, bytes);
            } else if path
                .extension()
                .is_some_and(|ext| ext == "rs" || ext == "toml")
            {
                bytes.insert(
                    path.strip_prefix(root).unwrap().to_path_buf(),
                    std::fs::read(path).unwrap(),
                );
            }
        }
    }
    let mut bytes = std::collections::BTreeMap::new();
    visit(directory, directory, &mut bytes);
    bytes
}

fn refusal(ir: &EssIr, rule: &str, lane: &str) {
    fn transferable_error<T: std::error::Error + Send + Sync + 'static>() {}
    transferable_error::<ess_synth::TargetFailure>();
    let plan = SynthesisPlan::of(ir);
    let failure = match synthesize(ir) {
        Err(failure) => failure,
        Ok(synthesis) => {
            let directory = scratch(lane);
            write_emission(&directory, &synthesis);
            check_generated(&directory);
            panic!("the target claimed a workspace instead of {rule}");
        }
    };
    assert_eq!(failure.target(), "rust");
    let value: serde_json::Value = serde_json::from_str(&failure.to_canonical_json()).unwrap();
    assert_eq!(value["format"], "ess-target-failure/1");
    assert_eq!(value.as_object().unwrap().len(), 4);
    assert!(
        value["causes"]
            .as_array()
            .unwrap()
            .iter()
            .any(|cause| cause["code"] == rule),
        "missing {rule}: {failure:?}"
    );
    assert!(failure
        .causes()
        .iter()
        .all(|cause| !cause.sources().is_empty() && !cause.detail().is_empty()));
    assert_eq!(failure.plan().to_canonical_json(), plan.to_canonical_json());
    assert_eq!(failure.plan().to_markdown(), plan.to_markdown());
    assert_eq!(
        failure.to_canonical_json(),
        synthesize(ir)
            .err()
            .expect("repeat refusal")
            .to_canonical_json()
    );
    assert_eq!(
        failure.to_canonical_json(),
        ess_synth::rust::workspace(ir, &plan)
            .expect_err("direct checked API")
            .to_canonical_json()
    );
    let web = ess_synth::web::workspace(ir, &plan)
        .err()
        .expect("Web checks its Rust prerequisite");
    assert_eq!(web.target(), "web");
    assert_eq!(web.plan().to_canonical_json(), plan.to_canonical_json());
    assert_eq!(web.causes(), failure.causes());
    assert_eq!(
        web.to_canonical_json(),
        synthesize_for(ir, Target::Web)
            .err()
            .expect("checked Web facade")
            .to_canonical_json()
    );
    // The independent semantic catalog remains available for target-infeasible source models.
    assert!(ess_synth::web::browser_catalog(ir, &plan)
        .into_json()
        .contains("ess-browser-catalog/1"));
}

#[test]
fn normalized_type_collisions_refuse_before_returning_rust() {
    refusal(&core("types:\n  - name: demo.core.FooBar\n    kind: newtype\n    of: String\n  - name: demo.core.Foo_Bar\n    kind: newtype\n    of: String\n", ""), "symbol-collision", "type-collision");
}

/// An entity beside a view named for that entity's lifecycle state.
///
/// `demo.core.Call` derives the state enum `demo.core.Call.State`, and the authored view
/// `demo.core.CallState` flattens to the same Rust identifier. One of them has to move, and
/// `alias` is the author saying which.
fn state_view_fixture(alias: Option<&str>) -> EssIr {
    let naming = alias.map_or_else(String::new, |code| {
        format!("    naming:\n      code: {code}\n")
    });
    let body = format!(
        "entities:\n  - name: demo.core.Call\n    identity: {{name: id, type: String}}\n    fields:\n      - {{name: marker, type: String}}\n    lifecycle:\n      initial: Active\n      states: [Active]\n      terminal: [Active]\nviews:\n  - name: demo.core.CallState\n{naming}    source: demo.core.Call\n    consistency: eventual\n    fields:\n      - {{name: id, type: String}}\n      - {{name: marker, type: String}}\n"
    );
    core(&body, "")
}

#[test]
fn a_view_named_for_a_state_refuses_and_says_how_to_resolve_it() {
    let ir = state_view_fixture(None);
    let Err(failure) = synthesize(&ir) else {
        panic!("the derived state enum and the view want one identifier");
    };
    let detail = failure
        .causes()
        .iter()
        .map(|cause| cause.detail().to_owned())
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        detail.contains("`CallState` is allocated 2 times"),
        "{detail}"
    );
    // The refusal has to carry the remedy. A reader who did not write `demo.core.Call.State` cannot
    // otherwise tell that one of the two colliding names is a target's and not theirs.
    assert!(detail.contains("naming: { code: … }"), "{detail}");
}

#[test]
fn go_moves_the_derived_state_enum_not_the_authored_view() {
    // Go does not refuse a collision, it repairs one — and it repaired this one backwards. The
    // derived `demo.core.Call.State` sorts before the authored `demo.core.CallState`, so the sweep
    // handed the identifier to the enum nobody wrote and renamed the author's view `CallState_`.
    // `allocate_names` states the opposite rule in its own doc comment: "a declared type's name
    // comes from the specification and a derived one is this emitter's to move."
    let ir = state_view_fixture(None);
    let go = synthesize_for(&ir, Target::Go).expect("go repairs rather than refusing");
    let source = &go.artifacts["types/core/core.go"].contents;
    assert!(
        source.contains("type CallState struct {"),
        "the authored view keeps its name: {source}"
    );
    assert!(
        source.contains("CallState_"),
        "the derived enum is the one that moved: {source}"
    );
}

#[test]
fn an_authored_code_alias_resolves_the_collision() {
    let ir = state_view_fixture(Some("CallStateView"));
    let synthesis = synthesize(&ir).expect("an authored code alias moves the view out of the way");
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    // The author's view took the name the author chose; the derived enum kept the one nobody wrote.
    assert!(source.contains("pub struct CallStateView {"), "{source}");
    assert!(source.contains("pub enum CallState {"), "{source}");
    assert!(!source.contains("pub struct CallState {"), "{source}");
    assert_eq!(synthesis.plan, SynthesisPlan::of(&ir));

    // The other flattening target must agree. Go had the same collision and repaired it the wrong
    // way round: `demo.core.Call.State` sorts before `demo.core.CallState`, so the derived enum
    // took the identifier and the author's view was renamed `CallState_` — silently, with nothing
    // asserting it. Both emitters now read the same authored alias.
    let go = synthesize_for(&ir, Target::Go).expect("go honours the same alias");
    let go_source = &go.artifacts["types/core/core.go"].contents;
    assert!(
        go_source.contains("type CallStateView struct {"),
        "{go_source}"
    );
    assert!(!go_source.contains("CallState_"), "{go_source}");

    let directory = scratch("authored-code-alias");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn a_code_alias_is_reserved_against_every_other_allocation() {
    // The alias takes a name an entity boundary would otherwise have had, so the boundary must move
    // instead of colliding with it. Before `entity_snapshots` reserved the chosen names, the two
    // repairs could both land on `CallSnapshot`.
    let ir = state_view_fixture(Some("CallSnapshot"));
    let synthesis =
        synthesize(&ir).expect("an alias is part of the namespace it is allocated into");
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    assert!(source.contains("pub struct CallSnapshot {"), "{source}");
    assert!(
        source.contains("pub struct CallEntitySnapshot {"),
        "{source}"
    );
    let directory = scratch("code-alias-reserved");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

fn snapshot_view_fixture(reverse: bool, occupied_fallback: bool) -> EssIr {
    let mut names = vec!["ApprovalCheckpoint", "ContextPin", "Workbench"];
    if reverse {
        names.reverse();
    }
    let mut body = String::from("entities:\n");
    for name in &names {
        writeln!(body, "  - name: demo.core.{name}\n    identity: {{name: id, type: String}}\n    fields:\n      - {{name: marker, type: String}}\n    lifecycle:\n      initial: Active\n      states: [Active]\n      terminal: [Active]").unwrap();
    }
    body.push_str("views:\n");
    for name in &names {
        writeln!(body, "  - name: demo.core.{name}Snapshot\n    source: demo.core.{name}\n    consistency: read_your_writes\n    fields:\n      - {{name: id, type: String}}\n      - {{name: marker, type: String}}").unwrap();
    }
    if occupied_fallback {
        body.push_str("types:\n  - {name: demo.core.ContextPinEntitySnapshot, kind: newtype, of: String}\n  - {name: demo.core.ContextPinEntitySnapshot2, kind: newtype, of: String}\n");
    }
    core(&body, "")
}

#[test]
fn entity_snapshot_names_preserve_authored_view_records() {
    let ir = snapshot_view_fixture(false, false);
    let synthesis = synthesize(&ir).expect("entity helpers must not consume authored view names");
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    for name in ["ApprovalCheckpoint", "ContextPin", "Workbench"] {
        assert!(source.contains(&format!("pub struct {name}Snapshot {{")));
        assert!(source.contains(&format!("pub struct {name}EntitySnapshot {{")));
        assert!(source.contains(&format!("pub fn snapshot(self) -> {name}EntitySnapshot")));
        assert!(source.contains(&format!("impl {name}EntitySnapshot {{")));
    }
    let reordered = synthesize(&snapshot_view_fixture(true, false)).unwrap();
    assert_eq!(synthesis.artifacts, reordered.artifacts);
    assert_eq!(synthesis.plan, SynthesisPlan::of(&ir));
    let directory = scratch("authored-snapshot-views");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn entity_snapshot_names_avoid_occupied_fallbacks() {
    let synthesis = synthesize(&snapshot_view_fixture(false, true))
        .expect("fallbacks share the domain's authored declaration namespace");
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    assert!(source.contains("pub struct ContextPinEntitySnapshot3 {"));
    assert!(source.contains("pub struct ContextPinSnapshot {"));
    assert!(source.contains("pub struct ContextPinEntitySnapshot("));
    assert!(source.contains("pub struct ContextPinEntitySnapshot2("));
    let directory = scratch("occupied-snapshot-fallbacks");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn entity_snapshot_names_reserve_other_entities_ordinary_boundaries() {
    let ir = core("entities:\n  - name: demo.core.Pin\n    identity: {name: id, type: String}\n    fields: []\n    lifecycle: {initial: Active, states: [Active], terminal: [Active]}\n  - name: demo.core.PinEntity\n    identity: {name: id, type: String}\n    fields: []\n    lifecycle: {initial: Active, states: [Active], terminal: [Active]}\ntypes:\n  - {name: demo.core.PinSnapshot, kind: newtype, of: String}\n", "");
    let synthesis = synthesize(&ir).unwrap();
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    assert!(source.contains("pub struct PinEntitySnapshot {"));
    assert!(source.contains("pub struct PinEntitySnapshot2 {"));
    assert!(source.contains("pub struct PinSnapshot("));
    let directory = scratch("reserved-ordinary-snapshots");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn entity_snapshot_names_allocate_per_domain() {
    let entity = "entities:\n  - name: demo.DOMAIN.Pin\n    identity: {name: id, type: String}\n    fields: []\n    lifecycle: {initial: Active, states: [Active], terminal: [Active]}\n";
    let ir = fixture(&[
        ("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ndomains: [demo.alpha, demo.beta]\n"),
        ("alpha.yaml", &format!("domain: demo.alpha\n{}types:\n  - {{name: demo.alpha.PinSnapshot, kind: newtype, of: String}}\n", entity.replace("DOMAIN", "alpha"))),
        ("beta.yaml", &format!("domain: demo.beta\n{}", entity.replace("DOMAIN", "beta"))),
    ]);
    let synthesis = synthesize(&ir).unwrap();
    assert!(synthesis.artifacts["crates/demo-types/src/alpha.rs"]
        .contents
        .contains("pub struct PinEntitySnapshot {"));
    let beta = &synthesis.artifacts["crates/demo-types/src/beta.rs"].contents;
    assert!(beta.contains("pub struct PinSnapshot {"));
    assert!(!beta.contains("PinEntitySnapshot"));
}

#[test]
fn entity_snapshot_names_keep_uncontested_boundary_names() {
    let ir = core("entities:\n  - name: demo.core.ContextPin\n    identity: {name: id, type: String}\n    fields: []\n    lifecycle:\n      initial: Active\n      states: [Active]\n      terminal: [Active]\n", "");
    let synthesis = synthesize(&ir).unwrap();
    let source = &synthesis.artifacts["crates/demo-types/src/core.rs"].contents;
    assert!(source.contains("pub struct ContextPinSnapshot {"));
    assert!(source.contains("pub fn snapshot(self) -> ContextPinSnapshot"));
    assert!(!source.contains("ContextPinEntitySnapshot"));
}

#[test]
fn normalized_fields_share_their_actual_struct_scope() {
    refusal(&core("types:\n  - name: demo.core.Value\n    kind: struct\n    fields:\n      - name: fooBar\n        type: String\n      - name: foo_bar\n        type: String\n", ""), "symbol-collision", "field-collision");
}

#[test]
fn path_keyword_repairs_cannot_merge_fields() {
    refusal(&core("types:\n  - name: demo.core.Value\n    kind: struct\n    fields:\n      - name: self\n        type: String\n      - name: self_\n        type: String\n", ""), "symbol-collision", "path-keyword-fields");
}

#[test]
fn generated_outcome_names_share_the_domain_type_scope() {
    refusal(&core("types:\n  - name: demo.core.FireOutcome\n    kind: newtype\n    of: String\nevents:\n  - name: demo.core.Fired\ncommands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits:\n          - demo.core.Fired\n", ""), "symbol-collision", "outcome-name");
}

#[test]
fn variant_names_are_checked_after_pascal_normalization() {
    refusal(
        &core(
            "types:\n  - name: demo.core.Value\n    kind: enum\n    variants: [foo-bar, foo_bar]\n",
            "",
        ),
        "symbol-collision",
        "variant-name",
    );
}

#[test]
fn a_type_cannot_capture_the_primitive_string_reference() {
    refusal(&core("types:\n  - name: demo.core.String\n    kind: struct\n    fields:\n      - name: text\n        type: String\n", ""), "symbol-collision", "primitive-shadow");
}

#[test]
fn a_reserved_type_spelling_is_a_target_limitation() {
    refusal(
        &core(
            "types:\n  - name: demo.core.Self\n    kind: newtype\n    of: String\n",
            "",
        ),
        "invalid-identifier",
        "self-type",
    );
}

#[test]
fn raw_module_identifiers_must_resolve_the_emitted_filename() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.type\n"), ("type.yaml", "domain: demo.type\ntypes:\n  - name: demo.type.Code\n    kind: newtype\n    of: String\n")]);
    refusal(&ir, "path-collision", "raw-module");
}

#[test]
fn reserved_module_repairs_are_checked_as_a_final_set() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.primitives\n  - demo.primitives_domain\n"), ("one.yaml", "domain: demo.primitives\ntypes:\n  - name: demo.primitives.Code\n    kind: newtype\n    of: String\n"), ("two.yaml", "domain: demo.primitives_domain\ntypes:\n  - name: demo.primitives_domain.Name\n    kind: newtype\n    of: String\n")]);
    refusal(&ir, "path-collision", "repaired-modules");
}

#[test]
fn fixed_system_fields_are_reserved_only_in_the_system_scope() {
    refusal(&core("events:\n  - name: demo.core.Fired\n", "components:\n  - component: published\n    publishes:\n      events:\n        - demo.core.Fired\n"), "symbol-collision", "system-field");
}

#[test]
fn collection_indirection_and_acyclic_optionals_compile() {
    let ir = core("types:\n  - name: demo.core.Tree\n    kind: struct\n    fields:\n      - name: children\n        type: List<demo.core.Tree>\n      - name: named\n        type: Map<String, demo.core.Tree>\n      - name: note\n        type: Optional<Optional<String>>\n", "");
    let synthesis = synthesize(&ir).expect("admitted Rust");
    assert!(synthesis.target.is_none());
    let directory = scratch("collection-recursion");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn optional_identity_and_omission_bindings_compile() {
    for (name, source, mapped) in [
        ("identity", "Optional<String>", true),
        ("omitted", "String", false),
    ] {
        let ir = binding(source, "Optional<String>", mapped);
        let synthesis = synthesize(&ir).expect("admitted Rust");
        assert!(synthesis.target.is_none());
        let directory = scratch(name);
        write_emission(&directory, &synthesis);
        check_generated(&directory);
    }
}

fn strict_binding_model(input: &str, mapping: &str) -> EssIr {
    let model = format!(
        "format: ess/4
system: demo
version: v1
domain: demo.core
events:
  - name: demo.core.Fired
    fields:
      - {{name: value, type: String}}
  - name: demo.core.Handled
commands:
  - name: demo.core.Handle
    input: {input}
    outcomes:
      - name: done
        emits: [demo.core.Handled]
components:
  - component: worker
    owns: {{domains: [demo.core]}}
    accepts: {{commands: [demo.core.Handle]}}
    publishes: {{events: [demo.core.Fired, demo.core.Handled]}}
bindings:
  - id: handle-fired
    when: {{event: demo.core.Fired}}
    invoke: {{command: demo.core.Handle}}
    mapping: {mapping}
    delivery: at_least_once
    on_failure: drop
"
    );
    fixture(&[("binding.yaml", &model)])
}

/// Compile untouched emitted sources under strict warnings, then actually deliver a binding.
/// Each case and layout gets a fresh generated target, so equal package names cannot reuse a
/// different model's executable.
fn strict_binding(input: &str, mapping: &str, expected: &str) {
    let ir = strict_binding_model(input, mapping);
    for layout in [
        ess_synth::OutputLayout::Workspace,
        ess_synth::OutputLayout::Crate,
    ] {
        let synthesis = ess_synth::synthesize_laid_out(&ir, Target::Rust, layout)
            .expect("the binding is fully determined");
        let directory = scratch("strict-binding");
        write_emission(&directory, &synthesis);
        let (test_directory, imports) = match layout {
            ess_synth::OutputLayout::Workspace => (
                directory.join("crates/demo-system/tests"),
                "use demo_system as system; use demo_types::{core, behaviour::Generated}; use worker::Worker;",
            ),
            ess_synth::OutputLayout::Crate => (
                directory.join("tests"),
                "use demo::{system, core, behaviour::Generated, ports::worker::Worker};",
            ),
        };
        std::fs::create_dir_all(&test_directory).unwrap();
        let harness = format!(
            r#"{imports}
#[test]
fn binding_invokes_with_declared_input() {{
    let mut system = system::System::new(Worker::new(Generated::new(())));
    for value in ["first", "second"] {{
        let event = core::Fired {{ value: value.to_owned() }};
        let expected = core::Handle {{ {expected} }};
        assert_eq!(system::handle_fired(&event), expected);
        system.redeliver(&system::SystemEvent::Fired(event)).expect("binding delivers");
        assert_eq!(system.invocations().last(), Some(&system::BindingInvocation::HandleFired(expected)));
    }}
    assert_eq!(system.invocations().len(), 2);
    assert_eq!(system.published().len(), 2);
    assert!(system.published().iter().all(|event| matches!(event, system::SystemEvent::Handled(_))));
}}
"#
        );
        std::fs::write(test_directory.join("binding.rs"), harness).unwrap();
        let before = generated_bytes(&directory);
        let output = Command::new(std::env::var_os("CARGO").expect("Cargo executable"))
            .current_dir(&directory)
            .args([
                "test",
                "--offline",
                "--workspace",
                "--test",
                "binding",
                "--",
                "--nocapture",
            ])
            .env_remove("CARGO_TARGET_DIR")
            .env_remove("CARGO_ENCODED_RUSTFLAGS")
            .env("RUSTFLAGS", "-D warnings")
            .env("CARGO_INCREMENTAL", "0")
            .output()
            .expect("strict generated test executes");
        std::fs::write(directory.join("strict.stdout"), &output.stdout).unwrap();
        std::fs::write(directory.join("strict.stderr"), &output.stderr).unwrap();
        std::fs::write(directory.join("strict.exit"), output.status.to_string()).unwrap();
        eprintln!(
            "strict generated fixture {}\n{}\n{}",
            directory.display(),
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            output.status.success(),
            "strict generated binding failed: {}",
            directory.display()
        );
        assert!(String::from_utf8_lossy(&output.stdout).contains("1 passed; 0 failed"));
        assert_eq!(
            before,
            generated_bytes(&directory),
            "generated source is unchanged"
        );
    }
}

#[test]
fn strict_rust_binding_inputless_compiles_and_invokes() {
    strict_binding("[]", "{}", "");
}

#[test]
fn strict_rust_binding_literal_only_compiles_and_invokes() {
    strict_binding(
        "[{name: value, type: String}]",
        "{value: fixed}",
        "value: \"fixed\".to_owned()",
    );
}

#[test]
fn strict_rust_binding_optional_only_compiles_and_invokes() {
    strict_binding(
        "[{name: value, type: Optional<String>}]",
        "{}",
        "value: None",
    );
}

#[test]
fn strict_rust_binding_event_mapping_still_reads_payload() {
    strict_binding(
        "[{name: value, type: String}]",
        "{value: event.value}",
        "value: value.to_owned()",
    );
}

#[test]
fn mandatory_self_recursion_is_rejected_before_synthesis() {
    for optional in [
        "",
        "      - {name: optional, type: Optional<demo.core.Link>}\n",
    ] {
        let text = format!("format: ess/1\nsystem: demo\nversion: v1\ndomain: demo.core\ntypes:\n  - name: demo.core.Link\n    kind: struct\n    fields:\n      - {{name: next, type: demo.core.Link}}\n{optional}");
        let raw = RawSpecFile::parse(&text).unwrap();
        let error = Specification::assemble([(Source::new("mandatory.yaml"), raw)])
            .expect_err("mandatory recursion has no finite value");
        assert!(error.to_string().contains("[self_reference]"));
    }
}

#[test]
fn an_optional_self_edge_does_not_admit_other_recursive_edges() {
    for (label, extra, sibling) in [
        ("nested", "      - {name: nested, type: Optional<Optional<demo.core.Link>>}\n", ""),
        ("mutual", "      - {name: peer, type: demo.core.Other}\n", "  - name: demo.core.Other\n    kind: struct\n    fields:\n      - {name: back, type: Optional<demo.core.Link>}\n"),
    ] {
        let body = format!("types:\n  - name: demo.core.Link\n    kind: struct\n    fields:\n      - {{name: next, type: Optional<demo.core.Link>}}\n{extra}{sibling}");
        refusal(&core(&body, ""), "recursive-layout", label);
    }
}

#[test]
fn mutual_recursion_is_a_size_cycle() {
    refusal(&core("types:\n  - name: demo.core.Left\n    kind: struct\n    fields:\n      - name: right\n        type: demo.core.Right\n  - name: demo.core.Right\n    kind: newtype\n    of: Optional<demo.core.Left>\n", ""), "recursive-layout", "mutual-recursion");
}

fn binding(source: &str, target: &str, mapped: bool) -> EssIr {
    let body = format!("events:\n  - name: demo.core.Fired\n    fields:\n      - name: value\n        type: {source}\n  - name: demo.core.Handled\ncommands:\n  - name: demo.core.Handle\n    input:\n      - name: value\n        type: {target}\n    outcomes:\n      - name: done\n        emits:\n          - demo.core.Handled\n");
    let mapping = if mapped {
        "    mapping:\n      value: event.value\n"
    } else {
        "    mapping: {}\n"
    };
    let wiring = format!("components:\n  - component: worker\n    owns:\n      domains:\n        - demo.core\n    accepts:\n      commands:\n        - demo.core.Handle\n    publishes:\n      events:\n        - demo.core.Fired\n        - demo.core.Handled\nbindings:\n  - id: handle-fired\n    when:\n      event: demo.core.Fired\n    invoke:\n      command: demo.core.Handle\n{mapping}    delivery: at_least_once\n    on_failure: drop\n");
    core(&body, &wiring)
}

#[test]
fn required_to_optional_binding_assignment_is_not_a_plain_clone() {
    refusal(
        &binding("String", "Optional<String>", true),
        "binding-assignment",
        "optional-binding",
    );
}

#[test]
fn system_types_receive_a_target_result_instead_of_a_missing_owner_panic() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ntypes:\n  - name: demo.Code\n    kind: newtype\n    of: String\ndomains:\n  - demo.core\n"), ("core.yaml", "domain: demo.core\n")]);
    refusal(&ir, "missing-type-owner", "system-type");
}

#[test]
fn a_web_system_with_no_delivery_compiles_with_its_actual_rust_prerequisite() {
    let ir = core("events:\n  - name: demo.core.Fired\n    fields:\n      - name: value\n        type: String\ncommands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits:\n          - demo.core.Fired\n", "components:\n  - component: worker\n    owns:\n      domains:\n        - demo.core\n    accepts:\n      commands:\n        - demo.core.Fire\n    publishes:\n      events:\n        - demo.core.Fired\n");
    let directory = scratch("zero-delivery-web");
    let rust = directory.join("generated/rust/demo");
    let web = directory.join("generated/web/demo");
    write_emission(&rust, &synthesize(&ir).expect("admitted Rust"));
    write_emission(
        &web,
        &synthesize_for(&ir, Target::Web).expect("admitted Web"),
    );
    check_generated(&rust);
    check_generated_for(&web, Some("wasm32-unknown-unknown"));
    replay_probe(&directory);
}

fn replay_probe(directory: &Path) {
    let harness = directory.join("replay-harness");
    std::fs::create_dir_all(harness.join("src")).unwrap();
    std::fs::write(
        harness.join("Cargo.toml"),
        r#"[workspace]
resolver = "2"
[package]
name = "replay-proof"
version = "0.0.0"
edition = "2021"
[lib]
crate-type = ["cdylib"]
[dependencies]
demo-web = { path = "../generated/web/demo/crates/demo-web" }
demo-types = { path = "../generated/rust/demo/crates/demo-types" }
demo-system = { path = "../generated/rust/demo/crates/demo-system" }
worker = { path = "../generated/rust/demo/crates/worker" }
"#,
    )
    .unwrap();
    std::fs::write(
        harness.join("src/lib.rs"),
        r#"use demo_web::{Bound, BridgeError};
use demo_types::core::{Fire, FireOutcome, Fired};
struct Behavior;
impl demo_types::core::obligations::FireBehavior for Behavior {
    fn fire(&mut self, _: Fire) -> Result<FireOutcome, demo_types::obligation::UnmetObligation> {
        Ok(FireOutcome::Done { fired: Fired { value: "retained".to_owned() } })
    }
}
#[no_mangle]
pub extern "C" fn replay_proof() -> u32 {
    let mut system = demo_system::System::new(worker::Worker::new(Behavior));
    system.worker.fire(Fire {}).unwrap();
    system.pump().unwrap();
    assert_eq!(system.published().len(), 1);
    let before = system.published().to_vec();
    assert_eq!(Bound::replay(&mut system, 0), Ok(()));
    assert_eq!(system.published(), before);
    assert_eq!(Bound::replay(&mut system, 1), Err(BridgeError::NoSuchOccurrence(1)));
    assert_eq!(system.published(), before);
    73
}
"#,
    )
    .unwrap();
    let before_rust = generated_bytes(&directory.join("generated/rust/demo"));
    let before_web = generated_bytes(&directory.join("generated/web/demo"));
    let lock = cargo(&harness, "lock", &["generate-lockfile", "--offline"]);
    assert!(lock.status.success());
    let build = cargo(
        &harness,
        "wasm-build",
        &[
            "build",
            "--locked",
            "--offline",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
            "target",
        ],
    );
    assert!(
        build.status.success(),
        "the independent WASM replay harness compiles"
    );
    let mut command = Command::new("node");
    command.current_dir(&harness).args(["-e", "const fs=require('node:fs'); WebAssembly.instantiate(fs.readFileSync('target/wasm32-unknown-unknown/debug/replay_proof.wasm'),{}).then(({instance})=>{const answer=instance.exports.replay_proof(); if(answer!==73) throw Error(String(answer)); console.log('replay existing occurrence: no delivery; missing occurrence: NoSuchOccurrence; log unchanged');}).catch(e=>{console.error(e);process.exit(1);});"]);
    std::fs::write(harness.join("node.command"), format!("{command:?}\n")).unwrap();
    let output = command
        .output()
        .expect("Node is a required local WASM validation prerequisite");
    std::fs::write(harness.join("node.stdout"), &output.stdout).unwrap();
    std::fs::write(harness.join("node.stderr"), &output.stderr).unwrap();
    std::fs::write(harness.join("node.exit"), output.status.to_string()).unwrap();
    eprintln!(
        "{command:?}\n{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(
        output.status.success(),
        "the real generated Bound::replay must execute under WASM"
    );
    assert_eq!(
        before_rust,
        generated_bytes(&directory.join("generated/rust/demo"))
    );
    assert_eq!(
        before_web,
        generated_bytes(&directory.join("generated/web/demo"))
    );
}

#[test]
fn additional_optional_wrappers_and_union_size_cycles_refuse() {
    refusal(
        &binding("Optional<String>", "Optional<Optional<String>>", true),
        "binding-assignment",
        "nested-optional",
    );
    refusal(&core("types:\n  - name: demo.core.Loop\n    kind: union\n    tag: kind\n    variants:\n      again: Optional<demo.core.Loop>\n", ""), "recursive-layout", "union-cycle");
}

#[test]
fn generated_entity_names_and_markers_use_their_own_scopes() {
    let entity = "entities:\n  - name: demo.core.Item\n    identity:\n      name: id\n      type: String\n    lifecycle:\n      initial: Active\n      states: [Active]\n      terminal: [Active]\n";
    refusal(
        &core(
            &format!(
                "types:\n  - name: demo.core.ItemData\n    kind: newtype\n    of: String\n{entity}"
            ),
            "",
        ),
        "symbol-collision",
        "entity-data",
    );
    refusal(
        &core(&entity.replace("Active", "Marker"), ""),
        "symbol-collision",
        "entity-marker",
    );
}

#[test]
fn generated_port_methods_cannot_capture_a_constructor() {
    refusal(&core("events:\n  - name: demo.core.Fired\ncommands:\n  - name: demo.core.New\n    outcomes:\n      - name: done\n        emits:\n          - demo.core.Fired\n", "components:\n  - component: worker\n    accepts:\n      commands:\n        - demo.core.New\n"), "symbol-collision", "port-method");
}

#[test]
fn system_level_types_refuse_even_when_referenced() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ntypes:\n  - name: demo.Code\n    kind: newtype\n    of: String\ndomains:\n  - demo.core\n"), ("core.yaml", "domain: demo.core\ntypes:\n  - name: demo.core.Record\n    kind: struct\n    fields:\n      - name: code\n        type: demo.Code\n")]);
    refusal(&ir, "missing-type-owner", "referenced-system-type");
}

#[test]
fn duplicate_wire_aliases_are_refused_before_target_selection() {
    let body = "types:\n  - name: demo.core.Pair\n    kind: struct\n    fields:\n      - name: first\n        type: String\n        wire: same\n      - name: second\n        type: String\n        wire: same\n";
    let source = format!(
        "format: ess/1\nsystem: demo\nversion: v1\ndomains: [demo.core]\ndomain: demo.core\n{body}"
    );
    let errors = Specification::assemble([(
        Source::new("wire.yaml"),
        RawSpecFile::parse(&source).expect("the fixture parses"),
    )])
    .expect_err("duplicate JSON keys are invalid before selecting any target");
    assert_eq!(errors.len(), 1);
    let error = &errors.as_slice()[0];
    assert_eq!(error.code.to_string(), "duplicate_declaration");
    assert_eq!(error.location, "types.demo.core.Pair.fields[1]");
    assert!(error.message.contains("same"));
}

#[test]
fn independent_names_and_existing_package_repairs_compile() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.one\n  - demo.two\n"), ("one.yaml", "domain: demo.one\ntypes:\n  - name: demo.one.String\n    kind: newtype\n    of: Integer\n"), ("two.yaml", "domain: demo.two\ntypes:\n  - name: demo.two.String\n    kind: newtype\n    of: Integer\n"), ("wiring.yaml", "components:\n  - component: demo-types\n    owns:\n      domains:\n        - demo.one\n  - component: demo-types-component\n    owns:\n      domains:\n        - demo.two\n")]);
    let synthesis = synthesize(&ir).expect("independent scopes and established suffix allocation");
    let directory = scratch("independent-names");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn distinct_wire_overrides_and_value_union_tag_compile() {
    let ir = core("types:\n  - name: demo.core.Pair\n    kind: struct\n    fields:\n      - name: first\n        type: String\n        wire: left\n      - name: second\n        type: Optional<String>\n        wire: right\n  - name: demo.core.Choice\n    kind: union\n    tag: value\n    variants:\n      pair: demo.core.Pair\n      text: String\n", "");
    let directory = scratch("distinct-wire");
    let rust = directory.join("generated/rust/demo");
    let web = directory.join("generated/web/demo");
    write_emission(&rust, &synthesize(&ir).expect("valid Rust types"));
    write_emission(
        &web,
        &synthesize_for(&ir, Target::Web).expect("unambiguous wire surface"),
    );
    check_generated(&rust);
    check_generated_for(&web, Some("wasm32-unknown-unknown"));
    let before = generated_bytes(&web);
    let build = cargo(
        &web,
        "catalog-wasm-build",
        &[
            "build",
            "--locked",
            "--offline",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
            "target",
        ],
    );
    assert!(build.status.success());
    let mut node = Command::new("node");
    node.current_dir(&web).args(["-e", r"const fs=require('node:fs');
WebAssembly.instantiate(fs.readFileSync('target/wasm32-unknown-unknown/debug/demo_web.wasm'),{}).then(({instance})=>{
 const e=instance.exports;
 function send(request){const input=Buffer.from(JSON.stringify(request));const p=e.ess_input_reserve(input.length);new Uint8Array(e.memory.buffer,p,input.length).set(input);const out=e.ess_dispatch();return JSON.parse(Buffer.from(e.memory.buffer,out,e.ess_output_len()).toString());}
 const catalog=send({request:'catalog'});if(!catalog.ok||catalog.catalog.format!=='ess-browser-catalog/1')throw Error('catalog unavailable');
 const replay=send({request:'replay',occurrence:0});if(replay.ok||replay.error.kind!=='unknown-request')throw Error('invented interaction');
 console.log('catalog served through actual exports; catalog-only replay remains unknown-request');
}).catch(e=>{console.error(e);process.exit(1);});"]);
    std::fs::write(web.join("catalog-node.command"), format!("{node:?}\n")).unwrap();
    let output = node.output().expect("required local Node lane");
    std::fs::write(web.join("catalog-node.stdout"), &output.stdout).unwrap();
    std::fs::write(web.join("catalog-node.stderr"), &output.stderr).unwrap();
    std::fs::write(web.join("catalog-node.exit"), output.status.to_string()).unwrap();
    eprintln!(
        "{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(output.status.success());
    assert_eq!(before, generated_bytes(&web));
}

#[test]
fn codec_fragments_are_checked_as_one_final_function_set() {
    let ir = fixture(&[("system.yaml", "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.foo\n  - demo.foo_bar\n"), ("one.yaml", "domain: demo.foo\ntypes:\n  - name: demo.foo.BarValue\n    kind: newtype\n    of: String\n"), ("two.yaml", "domain: demo.foo_bar\ntypes:\n  - name: demo.foo_bar.Value\n    kind: newtype\n    of: String\n")]);
    let rust = synthesize(&ir).expect("independent domain names are legal Rust");
    let directory = scratch("codec-fragments-rust");
    write_emission(&directory, &rust);
    check_generated(&directory);
    let error = synthesize_for(&ir, Target::Web)
        .err()
        .expect("global codecs cannot share flattened names");
    assert!(error
        .causes()
        .iter()
        .any(|cause| cause.code() == ess_synth::TargetFailureCode::WireCollision));
}

#[test]
fn a_mechanical_conversion_cannot_capture_the_from_trait() {
    refusal(&core("types:\n  - name: demo.core.From\n    kind: newtype\n    of: String\n  - name: demo.core.Code\n    kind: newtype\n    of: String\nconversions:\n  - from: demo.core.From\n    to: demo.core.Code\n    because: same declared representation\n", ""), "symbol-collision", "from-helper");
}

#[test]
fn component_type_parameters_do_not_shadow_their_port() {
    refusal(
        &core(
            "types:\n  - name: demo.core.Code\n    kind: newtype\n    of: String\n",
            "components:\n  - component: b\n    owns:\n      domains:\n        - demo.core\n",
        ),
        "symbol-collision",
        "port-generic",
    );
}

#[test]
fn neutral_refused_deliveries_keep_the_partial_web_report_and_compile() {
    let ir = core("events:\n  - name: demo.core.Fired\n  - name: demo.core.Handled\ncommands:\n  - name: demo.core.Handle\n    outcomes:\n      - name: done\n        emits:\n          - demo.core.Handled\n", "components:\n  - component: worker\n    owns:\n      domains:\n        - demo.core\n    publishes:\n      events:\n        - demo.core.Fired\nbindings:\n  - id: handle-fired\n    when:\n      event: demo.core.Fired\n    invoke:\n      command: demo.core.Handle\n    mapping: {}\n    delivery: at_least_once\n    on_failure: drop\n");
    let directory = scratch("neutral-refused-web");
    let rust = synthesize(&ir).expect("neutral refusal still has a valid Rust tree");
    let web = synthesize_for(&ir, Target::Web).expect("partial Web report remains successful");
    assert!(rust.target.is_none());
    assert_ne!(web.target.as_ref().unwrap().refusals.len(), 0);
    assert_eq!(rust.plan, web.plan);
    assert!(!rust
        .plan
        .is_generated(ess_synth::CapabilityKind::BindingDelivery, "handle-fired"));
    write_emission(&directory.join("generated/rust/demo"), &rust);
    write_emission(&directory.join("generated/web/demo"), &web);
    check_generated(&directory.join("generated/rust/demo"));
    check_generated_for(
        &directory.join("generated/web/demo"),
        Some("wasm32-unknown-unknown"),
    );
}

#[test]
fn dependency_helpers_are_reserved_only_where_the_target_uses_them() {
    for component in ["gen", "result", "core"] {
        let ir = core("types:\n  - name: demo.core.Code\n    kind: newtype\n    of: String\n", &format!("components:\n  - component: {component}\n    owns:\n      domains:\n        - demo.core\n"));
        let directory = scratch(component);
        let rust =
            synthesize(&ir).expect("these pure Rust layouts use no conflicting dependency helper");
        write_emission(&directory, &rust);
        check_generated(&directory);
    }
    // The measured std dependency shadows Rust's automatically imported standard prelude, even
    // without an explicit std:: path in the system source (dependency-helper-red.log).
    refusal(
        &core(
            "types:\n  - name: demo.core.Code\n    kind: newtype\n    of: String\n",
            "components:\n  - component: std\n    owns:\n      domains:\n        - demo.core\n",
        ),
        "symbol-collision",
        "standard-prelude",
    );
}

fn disk_fixture(directory: &Path) -> EssIr {
    let mut paths = Vec::new();
    let mut pending = vec![directory.to_path_buf()];
    while let Some(dir) = pending.pop() {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|ext| ext == "yaml") {
                paths.push(path);
            }
        }
    }
    paths.sort();
    let documents = paths
        .iter()
        .map(|path| {
            (
                path.strip_prefix(directory).unwrap().display().to_string(),
                std::fs::read_to_string(path).unwrap(),
            )
        })
        .collect::<Vec<_>>();
    fixture(
        &documents
            .iter()
            .map(|(path, text)| (path.as_str(), text.as_str()))
            .collect::<Vec<_>>(),
    )
}

#[test]
fn complete_committed_valid_artifact_maps_are_unchanged_and_compile() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../..");
    for example in ["billing", "gatepass"] {
        let ir = disk_fixture(&root.join("examples").join(example));
        let directory = scratch(example);
        for target in if example == "billing" {
            &[Target::Rust, Target::Web][..]
        } else {
            &[Target::Rust][..]
        } {
            let target = *target;
            let synthesis = synthesize_for(&ir, target).expect("committed valid realization");
            let relative = format!("generated/{}/{example}", target.name());
            let committed = root.join(&relative);
            let mut pending = vec![committed.clone()];
            let mut observed = std::collections::BTreeSet::new();
            while let Some(dir) = pending.pop() {
                for entry in std::fs::read_dir(dir).unwrap() {
                    let entry = entry.unwrap();
                    let path = entry.path();
                    // The CLI's settled ownership ledger is local operational state, not a
                    // synthesis artifact. Every other path still participates in exact equality.
                    if path == committed.join(".ess-output") && entry.file_type().unwrap().is_dir()
                    {
                        continue;
                    }
                    if path.is_dir() {
                        pending.push(path);
                    } else {
                        let relative = path.strip_prefix(&committed).unwrap().display().to_string();
                        assert_eq!(
                            std::fs::read(&path).unwrap(),
                            synthesis.artifacts[&relative].contents.as_bytes(),
                            "historical bytes: {}",
                            path.display()
                        );
                        observed.insert(relative);
                    }
                }
            }
            assert_eq!(observed, synthesis.artifacts.keys().cloned().collect());
            assert_eq!(
                synthesis.plan.to_canonical_json(),
                SynthesisPlan::of(&ir).to_canonical_json()
            );
            write_emission(&directory.join(&relative), &synthesis);
            check_generated_for(
                &directory.join(&relative),
                (target == Target::Web).then_some("wasm32-unknown-unknown"),
            );
        }
    }
}

#[test]
fn an_empty_domain_cannot_overwrite_the_rust_crate_root() {
    let ir = fixture(&[
        (
            "system.yaml",
            "format: ess/1\nsystem: demo\nversion: v1\ndomains:\n  - demo.lib\n",
        ),
        ("lib.yaml", "domain: demo.lib\n"),
    ]);
    let plan = SynthesisPlan::of(&ir);
    assert_eq!(plan.generated().count(), 0);
    eprintln!(
        "compiler admitted zero-capability source\n{}",
        ir.to_canonical_json()
    );
    eprintln!("neutral plan\n{}", plan.to_canonical_json());
    refusal(&ir, "path-collision", "zero-capabilities");
}

fn web_module_dependency(component: &str) {
    let ir = core("events:\n  - name: demo.core.Fired\ncommands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits: [demo.core.Fired]\n", &format!("components:\n  - component: {component}\n    owns:\n      domains: [demo.core]\n    accepts:\n      commands: [demo.core.Fire]\n    publishes:\n      events: [demo.core.Fired]\n"));
    let directory = scratch(component);
    let rust = synthesize(&ir).expect("a Web-only module must not restrict pure Rust");
    write_emission(&directory.join("generated/rust/demo"), &rust);
    check_generated(&directory.join("generated/rust/demo"));
    let failure = match synthesize_for(&ir, Target::Web) {
        Err(failure) => failure,
        Ok(web) => {
            let path = directory.join("generated/web/demo");
            write_emission(&path, &web);
            check_generated_for(&path, Some("wasm32-unknown-unknown"));
            panic!("the Web root module captures the component dependency");
        }
    };
    assert_eq!(failure.target(), "web");
    assert_eq!(failure.plan(), &rust.plan);
    assert!(failure.causes().iter().any(|cause| {
        cause.code() == ess_synth::TargetFailureCode::SymbolCollision
            && cause.sources().iter().any(|source| source == component)
    }));
}

#[test]
fn web_catalog_module_cannot_capture_a_component_dependency() {
    web_module_dependency("catalog");
}

#[test]
fn web_wire_module_cannot_capture_a_component_dependency() {
    web_module_dependency("wire");
}

fn outcome_locals(events: &[&str]) -> EssIr {
    let mut declarations = String::new();
    for event in events {
        writeln!(declarations, "  - name: demo.core.{event}").unwrap();
    }
    let names = events
        .iter()
        .map(|event| format!("demo.core.{event}"))
        .collect::<Vec<_>>()
        .join(", ");
    core(&format!("events:\n{declarations}commands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits: [{names}]\n"), &format!("components:\n  - component: worker\n    owns:\n      domains: [demo.core]\n    accepts:\n      commands: [demo.core.Fire]\n    publishes:\n      events: [{names}]\n    reached_by: network\n"))
}

#[test]
fn outcome_bindings_cannot_capture_an_encoder_called_in_the_same_arm() {
    refusal(
        &outcome_locals(&["Fired", "EncodeEventDemoCoreFired"]),
        "symbol-collision",
        "outcome-encoder-capture",
    );
}

#[test]
fn outcome_bindings_in_other_namespaces_or_unused_helpers_compile() {
    let ir = outcome_locals(&["Value", "Json", "EncodeEventDemoCoreAbsent"]);
    let directory = scratch("outcome-locals-positive");
    let rust = synthesize(&ir).expect("these local bindings capture no used value");
    write_emission(&directory.join("generated/rust/demo"), &rust);
    check_generated(&directory.join("generated/rust/demo"));
    let web = synthesize_for(&ir, Target::Web).expect("the shared codec keeps separate namespaces");
    write_emission(&directory.join("generated/web/demo"), &web);
    check_generated_for(
        &directory.join("generated/web/demo"),
        Some("wasm32-unknown-unknown"),
    );
}

#[test]
fn a_web_system_without_any_published_event_has_an_empty_observation() {
    let ir = core(
        "types:\n  - name: demo.core.Code\n    kind: newtype\n    of: String\n",
        "components:\n  - component: worker\n    owns:\n      domains: [demo.core]\n",
    );
    let directory = scratch("empty-event-web");
    let rust = synthesize(&ir).expect("no source event is required for a component");
    let web = synthesize_for(&ir, Target::Web).expect("an empty log is a valid Web observation");
    assert_eq!(rust.plan, web.plan);
    let rust_path = directory.join("generated/rust/demo");
    let web_path = directory.join("generated/web/demo");
    write_emission(&rust_path, &rust);
    write_emission(&web_path, &web);
    check_generated(&rust_path);
    check_generated_for(&web_path, Some("wasm32-unknown-unknown"));
    let before_rust = generated_bytes(&rust_path);
    let before_web = generated_bytes(&web_path);
    let build = cargo(
        &web_path,
        "empty-log-build",
        &[
            "build",
            "--locked",
            "--offline",
            "--target",
            "wasm32-unknown-unknown",
            "--target-dir",
            "target",
        ],
    );
    assert!(
        build.status.success(),
        "the actual generated Web module builds"
    );
    let mut node = Command::new("node");
    node.current_dir(&web_path).args(["-e", r"const fs=require('node:fs');
WebAssembly.instantiate(fs.readFileSync('target/wasm32-unknown-unknown/debug/demo_web.wasm'),{}).then(({instance})=>{
 const e=instance.exports;
 function send(request){const input=Buffer.from(JSON.stringify(request));const p=e.ess_input_reserve(input.length);new Uint8Array(e.memory.buffer,p,input.length).set(input);const out=e.ess_dispatch();return JSON.parse(Buffer.from(e.memory.buffer,out,e.ess_output_len()).toString());}
 const before=send({request:'observe'});if(!before.ok||JSON.stringify(before.log)!=='[]'||JSON.stringify(before.invocations)!=='[]')throw Error('nonempty observation');
 const replay=send({request:'redeliver',occurrence:0});if(replay.ok||replay.error.kind!=='no-such-occurrence')throw Error('invented occurrence');
 if(JSON.stringify(send({request:'observe'}))!==JSON.stringify(before))throw Error('observation changed');
 console.log('empty-event system: log []; invocations []; redelivery reports no-such-occurrence; observation unchanged');
}).catch(e=>{console.error(e);process.exit(1);});"]);
    std::fs::write(
        web_path.join("empty-log-node.command"),
        format!("{node:?}\n"),
    )
    .unwrap();
    let output = node.output().expect("required local Node/WASM execution");
    std::fs::write(web_path.join("empty-log-node.stdout"), &output.stdout).unwrap();
    std::fs::write(web_path.join("empty-log-node.stderr"), &output.stderr).unwrap();
    std::fs::write(
        web_path.join("empty-log-node.exit"),
        output.status.to_string(),
    )
    .unwrap();
    eprintln!(
        "{node:?}\n{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(output.status.success());
    assert_eq!(before_rust, generated_bytes(&rust_path));
    assert_eq!(before_web, generated_bytes(&web_path));
}

#[test]
fn web_module_dependencies_are_checked_even_without_commands() {
    for component in ["catalog", "json", "wire"] {
        let ir = core(
            "",
            &format!(
                "components:\n  - component: {component}\n    owns:\n      domains: [demo.core]\n"
            ),
        );
        let rust = synthesize(&ir).expect("these names do not collide in pure Rust");
        let directory = scratch(&format!("web-module-{component}-pure-rust"));
        write_emission(&directory, &rust);
        check_generated(&directory);
        let failure = synthesize_for(&ir, Target::Web)
            .err()
            .expect("the installation references every component dependency");
        assert_eq!(failure.plan(), &rust.plan);
        assert_eq!(failure.target(), "web");
        assert!(failure.causes().iter().any(|cause| {
            cause.code() == ess_synth::TargetFailureCode::SymbolCollision
                && cause.sources().iter().any(|source| source == component)
                && cause.detail().contains("web root")
        }));
    }
}

#[test]
fn web_outcome_codec_checks_the_same_output_binding_as_http() {
    let ir = core(
        "events:\n  - name: demo.core.Out\ncommands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits: [demo.core.Out, demo.core.Out]\n",
        "components:\n  - component: worker\n    owns:\n      domains: [demo.core]\n    accepts:\n      commands: [demo.core.Fire]\n    publishes:\n      events: [demo.core.Out]\n",
    );
    let rust = synthesize(&ir).expect("pure Rust has no outcome codec output binding");
    let failure = synthesize_for(&ir, Target::Web)
        .err()
        .expect("the presented Web command has the conflicting pattern binding");
    assert_eq!(failure.plan(), &rust.plan);
    let collisions = failure
        .causes()
        .iter()
        .filter(|cause| cause.detail().contains("outcome codec:demo.core.Fire.done"))
        .collect::<Vec<_>>();
    assert_eq!(
        collisions.len(),
        1,
        "the repeated event's out_2 is not a collision"
    );
    assert_eq!(
        collisions[0].code(),
        ess_synth::TargetFailureCode::SymbolCollision
    );
    assert!(collisions[0]
        .sources()
        .iter()
        .any(|source| source == "demo.core.Out"));
    assert!(collisions[0].detail().contains("`out`"));
}

#[test]
fn an_unpresented_web_command_has_no_outcome_codec_binding_scope() {
    let ir = core(
        "events:\n  - name: demo.core.Out\ncommands:\n  - name: demo.core.Fire\n    outcomes:\n      - name: done\n        emits: [demo.core.Out]\n",
        "",
    );
    let web = synthesize_for(&ir, Target::Web)
        .expect("a catalogue-only target emits no command outcome codec");
    let directory = scratch("unpresented-outcome");
    write_emission(
        &directory.join("generated/rust/demo"),
        &synthesize(&ir).unwrap(),
    );
    write_emission(&directory.join("generated/web/demo"), &web);
    check_generated_for(
        &directory.join("generated/web/demo"),
        Some("wasm32-unknown-unknown"),
    );
}

fn optional_recursive_model() -> EssIr {
    fixture(&[(
        "recursive.yaml",
        r"format: ess/19
system: demo
version: v1
domain: demo.core
types:
  - name: demo.core.DocumentFormat
    kind: enum
    variants:
      - name: DocumentV1
        wire: demo.document/1
  - name: demo.core.Link
    kind: struct
    fields:
      - {name: format, type: demo.core.DocumentFormat}
      - {name: label, type: String}
      - {name: next, type: Optional<demo.core.Link>}
  - name: demo.core.Envelope
    kind: struct
    fields:
      - {name: root, type: demo.core.Link}
      - {name: list, type: 'List<demo.core.Link>'}
      - {name: map, type: 'Map<String, demo.core.Link>'}
events:
  - name: demo.core.Arrived
    fields:
      - {name: root, type: demo.core.Link}
  - name: demo.core.Done
    fields:
      - {name: built, type: Optional<demo.core.Link>}
commands:
  - name: demo.core.Receive
    input:
      - {name: root, type: demo.core.Link}
      - {name: child, type: Optional<demo.core.Link>}
      - {name: label, type: Optional<String>}
    outcomes:
      - name: accepted
        emits: [demo.core.Done]
        payload:
          demo.core.Done:
            built:
              format: DocumentV1
              label: built
              next: input.child
components:
  - component: worker
    owns:
      domains: [demo.core]
    accepts:
      commands: [demo.core.Receive]
    publishes:
      events: [demo.core.Arrived, demo.core.Done]
    reached_by: network
bindings:
  - id: project
    when:
      event: demo.core.Arrived
    invoke:
      command: demo.core.Receive
    mapping:
      root: event.root
      child: event.root.next
      label: event.root.next.label
    delivery: at_most_once
    on_failure: drop
",
    )])
}

const RECURSIVE_HARNESS: &str = r##"
use demo_server::{json, wire};
use demo_types::core::{Arrived, DocumentFormat, Envelope, Link};
use demo_types::core::obligations::ReceiveBehavior;

#[test]
fn recursive_json_and_accessor() {
    let leaf = Link { format: DocumentFormat::DocumentV1, label: "leaf".into(), next: None };
    let root = Link { format: DocumentFormat::DocumentV1, label: "root".into(), next: Some(Box::new(leaf.clone())) };
    let mut encoded = String::new();
    wire::encode_demo_core_link(&root, &mut encoded);
    assert_eq!(encoded, r#"{"format":"demo.document/1","label":"root","next":{"format":"demo.document/1","label":"leaf"}}"#);
    let value = json::parse(&encoded).unwrap();
    assert_eq!(wire::decode_demo_core_link(&value, "$").unwrap(), root);
    let absent = json::parse(r#"{"format":"demo.document/1","label":"leaf","next":null}"#).unwrap();
    assert_eq!(wire::decode_demo_core_link(&absent, "$").unwrap(), leaf);
    let mut envelope = Envelope { root: Box::new(root.clone()), list: vec![Box::new(leaf.clone())], map: Default::default() };
    envelope.map.insert("child".into(), Box::new(leaf.clone()));
    encoded.clear();
    wire::encode_demo_core_envelope(&envelope, &mut encoded);
    let value = json::parse(&encoded).unwrap();
    assert_eq!(wire::decode_demo_core_envelope(&value, "$").unwrap(), envelope);
    let input = demo_system::project(&Arrived { root: Box::new(root.clone()) });
    assert_eq!(input.root.as_ref(), &root);
    assert_eq!(input.child.as_deref(), Some(&leaf));
    assert_eq!(input.label.as_deref(), Some("leaf"));
    let demo_types::core::ReceiveOutcome::Accepted { done } = demo_types::behaviour::Generated::new(()).receive(input).unwrap();
    let built = done.built.unwrap();
    assert_eq!(built.label, "built");
    assert_eq!(built.next.as_deref(), Some(&leaf));
    let input = demo_system::project(&Arrived { root: Box::new(leaf) });
    assert!(input.child.is_none());
    assert!(input.label.is_none());
}
"##;

#[test]
fn optional_recursive_structs_compile_and_roundtrip_in_both_layouts() {
    use ess_synth::{synthesize_laid_out, OutputLayout};
    let ir = optional_recursive_model();
    for (label, layout) in [
        ("workspace", OutputLayout::Workspace),
        ("crate", OutputLayout::Crate),
    ] {
        let synthesis = synthesize_laid_out(&ir, Target::Rust, layout)
            .expect("optional recursive structs are representable");
        assert_eq!(
            synthesis.artifacts,
            synthesize_laid_out(&ir, Target::Rust, layout)
                .unwrap()
                .artifacts
        );
        let root = scratch(&format!("recursive-{label}"));
        let generated = root.join("generated");
        write_emission(&generated, &synthesis);
        let harness = root.join("harness");
        std::fs::create_dir_all(harness.join("src")).unwrap();
        let (dependencies, source) = if layout == OutputLayout::Workspace {
            ("demo-types = {path = '../generated/crates/demo-types'}\ndemo-server = {path = '../generated/crates/demo-server'}\ndemo-system = {path = '../generated/crates/demo-system'}\n", RECURSIVE_HARNESS.to_owned())
        } else {
            (
                "demo = {path = '../generated', features = ['server']}\n",
                RECURSIVE_HARNESS
                    .replace("demo_server::", "demo::server::")
                    .replace("demo_types::", "demo::")
                    .replace("demo_system::", "demo::system::"),
            )
        };
        std::fs::write(harness.join("Cargo.toml"), format!("[workspace]\n[package]\nname = 'recursive-witness'\nversion = '0.0.0'\nedition = '2021'\n[dependencies]\n{dependencies}")).unwrap();
        std::fs::write(harness.join("src/lib.rs"), source).unwrap();
        let lock = cargo(&harness, "lock", &["generate-lockfile", "--offline"]);
        assert!(lock.status.success());
        let run = cargo(&harness, "test", &["test", "--offline", "--locked"]);
        assert!(
            run.status.success(),
            "fresh recursive {label} witness failed"
        );
    }
}

#[test]
fn optional_recursive_structs_compile_in_the_shared_web_codec() {
    let ir = optional_recursive_model();
    let root = scratch("recursive-web");
    let rust = synthesize(&ir).expect("recursive Rust prerequisite");
    write_emission(&root.join("generated/rust/demo"), &rust);
    let web = synthesize_for(&ir, Target::Web).expect("shared recursive Web codec");
    let directory = root.join("generated/web/demo");
    write_emission(&directory, &web);
    check_generated_for(&directory, Some("wasm32-unknown-unknown"));
}

fn check_multiline_prose(line_ending: &str) {
    let documents = [
        ("system.yaml", "format: ess/19\nsystem: demo\nversion: v1\nsummary: \"System first.\\nSystem second.\"\ndomains: [demo.core]\n"),
        ("core.yaml", r#"domain: demo.core
naming:
  display: "Domain first\nDomain second"
summary: "Domain paragraph one.\n\nDomain paragraph two."
types:
  - name: demo.core.Code
    kind: newtype
    of: String
    naming:
      display: "Code first\nCode second"
      summary: "Code summary first.\nCode summary second."
  - name: demo.core.Payload
    kind: struct
    naming:
      display: "Payload first\nPayload second"
      summary: "Payload summary first.\nPayload summary second."
    fields:
      - {name: code, type: demo.core.Code}
entities:
  - name: demo.core.Record
    naming:
      display: "Record first\nRecord second"
    identity: {name: id, type: demo.core.Code}
    lifecycle:
      initial: Held
      states: [Held]
      terminal: [Held]
events:
  - name: demo.core.Done
    naming:
      display: "Event first\nEvent second"
      summary: "Event summary first.\nEvent summary second."
commands:
  - name: demo.core.Receive
    naming:
      display: "Command first\nCommand second"
      summary: "Command summary first.\nCommand summary second."
    input:
      - {name: value, type: demo.core.Payload}
    outcomes:
      - name: accepted
        summary: "Outcome first.\nOutcome second."
        emits: [demo.core.Done]
"#),
        ("components.yaml", r#"components:
  - component: worker
    naming:
      display: "Component first\nComponent second"
      summary: "Component summary first.\nComponent summary second."
    owns:
      domains: [demo.core]
    accepts:
      commands: [demo.core.Receive]
    publishes:
      events: [demo.core.Done]
"#),
    ];
    let documents = documents
        .iter()
        .map(|(label, source)| (*label, source.replace("\\n", line_ending)))
        .collect::<Vec<_>>();
    let borrowed = documents
        .iter()
        .map(|(label, source)| (*label, source.as_str()))
        .collect::<Vec<_>>();
    let ir = fixture(&borrowed);
    let synthesis = synthesize(&ir).expect("prose is valid source");
    let expected_summary = match line_ending {
        "\\n" => "System first.\n//! System second.",
        "\\r\\n" => "System first.\r\n//! System second.",
        "\\r" => "System first.\\rSystem second.",
        "\\nMiddle.\\r" => "System first.\n//! Middle.\\rSystem second.",
        _ => unreachable!("the fixture enumerates the supported line endings"),
    };
    assert!(synthesis.artifacts["crates/demo-types/src/lib.rs"]
        .contents
        .contains(expected_summary));
    let directory = scratch("multiline-prose");
    write_emission(&directory, &synthesis);
    check_generated(&directory);
}

#[test]
fn multiline_authored_prose_stays_inside_rust_doc_comments() {
    check_multiline_prose("\\n");
}

#[test]
fn carriage_returns_in_authored_prose_are_safe_rust_doc_comments() {
    check_multiline_prose("\\r");
    check_multiline_prose("\\nMiddle.\\r");
}

#[test]
fn crlf_in_authored_prose_is_safe_rust_doc_comments() {
    check_multiline_prose("\\r\\n");
}
