//! What a served command answers, and what a long-running server keeps between answers
//! (`story:generated-server-publishes-and-reads-headers`).
//!
//! A command's served answer lists what it published, `{"event": <qualified name>, "payload": …}`
//! per event in publication order, and the contract the server serves at `/openapi.json` admits
//! exactly that answer. Behind the answer, the served dispatch pumps — every binding that reacts to
//! what the command published is delivered first — and then takes the delivered events and the
//! record of what the bindings invoked off the system, so nothing accumulates from one request to
//! the next: not on the log, not in the record, not in a component's outbox.
//!
//! The model is one served component with a binding that reacts to the event a command publishes
//! by invoking a second command, and escalates when that command refuses. Every behaviour is
//! generated; the harness below, outside the generated bytes, supplies the one context port (which
//! external branch is taken) and the escalation the specification leaves owed, and counts what
//! the binding made happen. Both layouts, each built with warnings denied.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use ess_compiler::{resolve::compile, source::SourceMap, EssIr};
use ess_domain::{spec::RawSpecFile, system::Source, Specification};
use ess_gen::http::{self, Served};
use ess_synth::{synthesize_laid_out, OutputLayout, Synthesis, Target};

/// One served component; `ops.core.Opened` invokes `ops.core.Note` through a binding, and a busy
/// notebook escalates into `ops.core.NoteDropped`.
const MODEL: &str = "format: ess/15
system: ops
version: v1
domain: ops.core
events:
  - name: ops.core.Opened
    fields:
      - {name: id, type: String}
  - name: ops.core.Noted
    fields:
      - {name: id, type: String}
  - name: ops.core.NoteDropped
    fields:
      - {name: id, type: String}
commands:
  - name: ops.core.Open
    input:
      - {name: id, type: String}
    outcomes:
      - name: opened
        emits: [ops.core.Opened]
        payload:
          ops.core.Opened: {id: input.id}
      - name: closed
        external: the desk is closed
        error: ops.core.Closed
  - name: ops.core.Note
    input:
      - {name: id, type: String}
    outcomes:
      - name: noted
        emits: [ops.core.Noted]
        payload:
          ops.core.Noted: {id: input.id}
      - name: busy
        external: the notebook is full
        error: ops.core.Busy
errors:
  - name: ops.core.Closed
  - name: ops.core.Busy
components:
  - component: ops-service
    owns: {domains: [ops.core]}
    accepts: {commands: [ops.core.Open, ops.core.Note]}
    publishes: {events: [ops.core.Opened, ops.core.Noted, ops.core.NoteDropped]}
    reached_by: network
bindings:
  - id: note-on-open
    when:
      event: ops.core.Opened
    invoke:
      command: ops.core.Note
    mapping:
      id: event.id
    delivery: at_least_once
    on_failure:
      escalate:
        emits: ops.core.NoteDropped
";

/// The harness. Its arguments are the route table, `name method path` per construct.
///
/// It runs `ops.core.Open` six times, alternating the HTTP dispatcher and the transport-free
/// `handle`, with the notebook busy on the last two, then `ops.core.Note` once and the one
/// document route. After each answer it prints what the system kept — log, binding record and
/// outbox — and how often the binding's command ran and escalated so far.
const HARNESS: &str = r#"use std::cell::RefCell;
use std::rc::Rc;

use ops_server::ops_service as surface;
use ops_server::{http, json};
use ops_types::behaviour::{Context, ExternalCommand, Generated};
use ops_types::core;
use ops_types::obligation::UnmetObligation;

#[derive(Default)]
struct State {
    busy: bool,
    notes: usize,
    escalated: usize,
}

#[derive(Clone, Default)]
struct Desk(Rc<RefCell<State>>);

impl Context for Desk {
    fn external(&mut self, command: ExternalCommand<'_>, outcome: &'static str) -> bool {
        let command = command.name();
        let mut state = self.0.borrow_mut();
        if command == "ops.core.Note" && outcome == "busy" {
            state.notes += 1;
            return state.busy;
        }
        false
    }
}

impl ops_system::obligations::NoteOnOpenEscalation for Desk {
    fn note_on_open_escalation(&self, failed: &core::Note) -> Result<core::NoteDropped, UnmetObligation> {
        self.0.borrow_mut().escalated += 1;
        Ok(core::NoteDropped { id: failed.id.clone() })
    }
}

type System = ops_system::System<Generated<Desk>, Desk>;

fn route<'a>(routes: &'a [(String, String, String)], name: &str) -> &'a (String, String, String) {
    routes
        .iter()
        .find(|(declared, _, _)| declared == name)
        .unwrap_or_else(|| panic!("`{name}` is a route"))
}

fn kept(system: &mut System) -> usize {
    system.published().len()
        + system.invocations().len()
        + system.ops_service.drain_outbox().len()
}

fn main() {
    let arguments: Vec<String> = std::env::args().skip(1).collect();
    let routes: Vec<(String, String, String)> = arguments
        .chunks(3)
        .map(|row| (row[0].clone(), row[1].clone(), row[2].clone()))
        .collect();
    let desk = Desk::default();
    let mut system: System = ops_system::System::new(
        ops_service::OpsService::new(Generated::new(desk.clone())),
        desk.clone(),
    );

    for round in 0..6 {
        desk.0.borrow_mut().busy = round >= 4;
        let input = format!("{{\"id\":\"t{round}\"}}");
        let answer = if round % 2 == 0 {
            let (_, method, path) = route(&routes, "ops.core.Open");
            let request = http::Request {
                method: method.clone(),
                path: path.clone(),
                query: String::new(),
                headers: vec![("authorization".to_owned(), "Bearer ops".to_owned())],
                body: input.into_bytes(),
            };
            let answered = surface::dispatch(&mut system, &request);
            format!("served {} {}", answered.status, answered.body)
        } else {
            let handled = surface::handle(
                &mut system,
                "ops.core.Open",
                json::parse(&input).expect("JSON"),
            );
            let published = match &handled {
                Ok(value) => match value.member("published") {
                    Some(json::Value::Array(items)) => items.len(),
                    _ => usize::MAX,
                },
                Err(_) => usize::MAX,
            };
            format!("handled published={published}")
        };
        let kept = kept(&mut system);
        let state = desk.0.borrow();
        println!(
            "open {round} {answer} kept={kept} notes={} escalated={}",
            state.notes, state.escalated
        );
    }

    desk.0.borrow_mut().busy = false;
    let (_, method, path) = route(&routes, "ops.core.Note");
    let request = http::Request {
        method: method.clone(),
        path: path.clone(),
        query: String::new(),
        headers: Vec::new(),
        body: b"{\"id\":\"n\"}".to_vec(),
    };
    let answered = surface::dispatch(&mut system, &request);
    println!("note served {} {} kept={}", answered.status, answered.body, kept(&mut system));

    let request = http::Request {
        method: "GET".to_owned(),
        path: "/openapi.json".to_owned(),
        query: String::new(),
        headers: Vec::new(),
        body: Vec::new(),
    };
    let contract = surface::dispatch(&mut system, &request);
    println!("contract {}", contract.body.replace('\n', " "));
}
"#;

fn ir() -> EssIr {
    let spec = Specification::assemble([(
        Source::new("spec.yaml"),
        RawSpecFile::parse(MODEL).expect("well formed"),
    )])
    .unwrap_or_else(|errors| panic!("validates: {errors}"));
    let mut sources = SourceMap::new();
    sources.insert("spec.yaml", MODEL);
    compile(&spec, &sources).unwrap_or_else(|errors| panic!("compiles: {errors}"))
}

/// The route table as the harness's arguments.
fn route_table(ir: &EssIr) -> Vec<String> {
    let component = ir.components().values().next().expect("one component");
    let mut table = Vec::new();
    for route in http::routes(ir, component) {
        let name = match route.serves {
            Served::Command(handle) => ir.command(handle).name.to_string(),
            Served::View(handle) => ir.view(handle).name.to_string(),
        };
        table.extend([name, route.method.as_str().to_owned(), route.path]);
    }
    table
}

fn write(synthesis: &Synthesis, directory: &Path) {
    let _ = std::fs::remove_dir_all(directory);
    for (relative, artifact) in &synthesis.artifacts {
        let destination = directory.join(relative);
        std::fs::create_dir_all(destination.parent().expect("a parent")).expect("mkdir");
        std::fs::write(&destination, &artifact.contents).expect("write");
    }
}

/// Cargo with every warning an error.
fn cargo(directory: &Path, arguments: &[String]) -> Output {
    let output = Command::new(std::env::var_os("CARGO").expect("Cargo supplies its executable"))
        .args(arguments)
        .current_dir(directory)
        .env_remove("CARGO_TARGET_DIR")
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env("RUSTFLAGS", "-D warnings")
        .env("CARGO_INCREMENTAL", "0")
        .output()
        .expect("cargo runs");
    eprintln!(
        "cargo {arguments:?} in {}\n{}",
        directory.display(),
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

/// Synthesizes the model in `layout`, builds it and the harness with warnings denied, runs the
/// harness, and answers its output lines.
fn run(label: &str, layout: OutputLayout) -> Vec<String> {
    let ir = ir();
    let synthesis = synthesize_laid_out(&ir, Target::Rust, layout).expect("the model synthesizes");
    let root = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("served-publication-{label}-{}", std::process::id()));
    let generated = root.join("ops");
    write(&synthesis, &generated);
    let harness = root.join("harness");
    std::fs::create_dir_all(harness.join("src")).expect("mkdir");
    let (dependencies, source) = match layout {
        OutputLayout::Crate => (
            "ops = { path = \"../ops\", features = [\"server\"] }\n".to_owned(),
            HARNESS
                .replace("ops_server::", "ops::server::")
                .replace("ops_system::", "ops::system::")
                .replace("ops_service::", "ops::ports::ops_service::")
                .replace("ops_types::", "ops::"),
        ),
        OutputLayout::Workspace => (
            ["ops-server", "ops-system", "ops-service", "ops-types"]
                .iter()
                .fold(String::new(), |mut out, name| {
                    let _ = writeln!(out, "{name} = {{ path = \"../ops/crates/{name}\" }}");
                    out
                }),
            HARNESS.to_owned(),
        ),
    };
    std::fs::write(
        harness.join("Cargo.toml"),
        format!(
            "[package]\nname = \"served-publication-harness\"\nversion = \"0.0.0\"\nedition = \
             \"2021\"\n\n[dependencies]\n{dependencies}\n[workspace]\n"
        ),
    )
    .expect("write");
    std::fs::write(harness.join("src/main.rs"), source).expect("write");
    let target = root.join("target");
    let mut arguments: Vec<String> = [
        "run",
        "--offline",
        "--quiet",
        "--target-dir",
        target.to_str().expect("UTF-8"),
        "--",
    ]
    .iter()
    .map(|argument| (*argument).to_owned())
    .collect();
    arguments.extend(route_table(&ir));
    let ran = cargo(&harness, &arguments);
    let stdout = String::from_utf8_lossy(&ran.stdout).into_owned();
    let _ = std::fs::remove_dir_all(&root);
    assert!(
        ran.status.success(),
        "the {label} harness builds with -D warnings and runs"
    );
    stdout.lines().map(str::to_owned).collect()
}

/// What the harness prints for the six `Open`s and the one `Note`: each served answer lists what
/// that command published and nothing a binding published after it, nothing is kept afterwards,
/// and the binding ran once per `Open` — escalating exactly when the notebook was busy.
const EXPECTED: &[&str] = &[
    "open 0 served 202 {\"outcome\":\"opened\",\"published\":[{\"event\":\"ops.core.Opened\",\
     \"payload\":{\"id\":\"t0\"}}]} kept=0 notes=1 escalated=0",
    "open 1 handled published=1 kept=0 notes=2 escalated=0",
    "open 2 served 202 {\"outcome\":\"opened\",\"published\":[{\"event\":\"ops.core.Opened\",\
     \"payload\":{\"id\":\"t2\"}}]} kept=0 notes=3 escalated=0",
    "open 3 handled published=1 kept=0 notes=4 escalated=0",
    "open 4 served 202 {\"outcome\":\"opened\",\"published\":[{\"event\":\"ops.core.Opened\",\
     \"payload\":{\"id\":\"t4\"}}]} kept=0 notes=5 escalated=1",
    "open 5 handled published=1 kept=0 notes=6 escalated=2",
    "note served 202 {\"outcome\":\"noted\",\"published\":[{\"event\":\"ops.core.Noted\",\
     \"payload\":{\"id\":\"n\"}}]} kept=0",
];

fn assert_answers(lines: &[String]) {
    let answers: Vec<&str> = lines
        .iter()
        .filter(|line| !line.starts_with("contract "))
        .map(String::as_str)
        .collect();
    assert_eq!(answers, EXPECTED);
}

#[test]
fn a_served_command_answers_what_it_published_and_the_server_keeps_nothing() {
    assert_answers(&run("workspace", OutputLayout::Workspace));
}

#[test]
fn the_single_crate_server_answers_what_it_published_and_keeps_nothing() {
    assert_answers(&run("crate", OutputLayout::Crate));
}

/// Every served command answer the harness printed validates against the response schema the
/// same server serves at `/openapi.json` for that path and status — `published` included, under
/// `additionalProperties: false`.
#[test]
fn every_served_answer_validates_against_the_contract_the_server_serves() {
    let lines = run("contract", OutputLayout::Workspace);
    let contract: serde_json::Value = serde_json::from_str(
        lines
            .iter()
            .find_map(|line| line.strip_prefix("contract "))
            .expect("the harness printed the served contract"),
    )
    .expect("the served contract is JSON");
    let ir = ir();
    let paths: Vec<(String, String)> = route_table(&ir)
        .chunks(3)
        .map(|row| (row[0].clone(), row[2].clone()))
        .collect();
    let path_of = |command: &str| {
        paths
            .iter()
            .find(|(name, _)| name == command)
            .map(|(_, path)| path.clone())
            .expect("a route")
    };
    let mut validated = 0;
    for line in &lines {
        let (command, rest) = if let Some(rest) = line.strip_prefix("note served ") {
            ("ops.core.Note", rest)
        } else if let Some((_, rest)) = line.split_once(" served ") {
            ("ops.core.Open", rest)
        } else {
            continue;
        };
        let (status, rest) = rest.split_once(' ').expect("a status");
        let body = rest.rsplit_once(" kept=").expect("a kept count").0;
        let answer: serde_json::Value = serde_json::from_str(body).expect("the answer is JSON");
        let schema_at = &contract["paths"][path_of(command)]["post"]["responses"][status]
            ["content"]["application/json"]["schema"];
        assert!(
            schema_at.is_object(),
            "the contract declares `{command}` answering {status}"
        );
        let mut schema = contract.clone();
        schema["$ref"] = schema_at["$ref"].clone();
        if schema_at.get("$ref").is_none() {
            schema["oneOf"] = schema_at["oneOf"].clone();
        }
        let validator = jsonschema::draft202012::new(&schema)
            .unwrap_or_else(|error| panic!("the served contract compiles as a schema: {error}"));
        let errors: Vec<String> = validator
            .iter_errors(&answer)
            .map(|error| format!("{error} at {}", error.instance_path()))
            .collect();
        assert!(
            errors.is_empty(),
            "`{command}` {status} {answer} does not validate against the served contract: \
             {errors:?}"
        );
        validated += 1;
    }
    assert_eq!(validated, 4, "every served command answer was validated");

    // The other direction: an answer that lists an event the branch does not publish, or drops
    // `published`, is refused by the same schema — the contract states the list, not just a key.
    let opened = &contract["components"]["schemas"]["ops.core.Open.opened.Response"];
    assert_eq!(
        opened["required"],
        serde_json::json!(["outcome", "published"])
    );
    let mut schema = contract.clone();
    schema["$ref"] = serde_json::json!("#/components/schemas/ops.core.Open.opened.Response");
    let validator = jsonschema::draft202012::new(&schema).expect("compiles");
    for wrong in [
        serde_json::json!({"outcome": "opened"}),
        serde_json::json!({"outcome": "opened", "published": []}),
        serde_json::json!({"outcome": "opened", "published": [
            {"event": "ops.core.Noted", "payload": {"id": "t"}}
        ]}),
    ] {
        assert!(!validator.is_valid(&wrong), "the contract refuses {wrong}");
    }
}
