//! The suite as a Go test package.
//!
//! `ess conform run` drives a target written in Rust, which is every implementation this workspace
//! can reach and none of the implementations adopters have. So an adopter's suite is regenerated on
//! every model change and has never executed — which is the "generated tests are green" failure one
//! step further back: not a suite that checks less than it claims, a suite that checks nothing
//! because nothing can run it.
//!
//! # What is generated, and what is not
//!
//! The suite is data and the runner is not. `suite.json` is the same canonical document
//! `--target ir` writes, and the three `.go` files beside it are byte-identical for every
//! specification — they are checked into this repository as `.go` and copied out, so they are read
//! and reviewed as Go rather than as strings inside a Rust emitter.
//!
//! That split is the whole design. A generator that built the runner line by line would put the
//! semantics of three-valued evaluation, ordering and scenario isolation into `format!` calls,
//! where nothing type-checks them and no Go tool ever looks at them.
//!
//! # Embedded rather than inlined
//!
//! `suite.json` is a file the package embeds with `go:embed`, not a string constant. A generated
//! purpose reads `` `acd.backend.ConnectAgent` answers `requested` `` — backticks — so a Go raw
//! string literal cannot hold it, and an interpreted literal would need the whole document escaped
//! into one unreadable line. As a file it stays diffable, and `git diff` on a model change shows
//! which scenarios moved.

use crate::ConformanceSuite;

/// One file of the emitted package.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct GoArtifact {
    /// Where it goes, relative to the output directory.
    pub path: String,
    /// What it holds.
    pub contents: String,
}

/// The package directory every artifact is written under.
///
/// Named for what it is rather than for the system, so an adopter's import path does not change
/// when the specification's name does.
pub const PACKAGE: &str = "essconform";

/// The suite as a Go test package: the runner, the evaluator, and the suite it runs.
///
/// Deterministic: the same suite produces the same bytes, because the three Go files are constants
/// and the fourth is the suite's own canonical JSON.
pub fn emit(suite: &ConformanceSuite) -> Vec<GoArtifact> {
    let file = |name: &str, contents: String| GoArtifact {
        path: format!("{PACKAGE}/{name}"),
        contents,
    };

    vec![
        file("runtime.go", include_str!("runtime.go").to_owned()),
        file("predicate.go", include_str!("predicate.go").to_owned()),
        file("suite.go", SUITE_GO.to_owned()),
        file("suite.json", suite.to_canonical_json()),
        file("README.md", readme(suite)),
    ]
}

/// The one file that exists only to embed the other one.
const SUITE_GO: &str = r#"// The suite this package runs.
//
// Generated by `ess conform synthesize --target go`. Do not edit: change the specification and
// regenerate.
package essconform

import _ "embed"

// suiteJSON is the canonical suite document, embedded so the package needs no working directory
// and no build tag to find it.
//
//go:embed suite.json
var suiteJSON string
"#;

/// How to wire the package up, written against this suite's own numbers.
fn readme(suite: &ConformanceSuite) -> String {
    let provenance = &suite.provenance;
    let scope = match &provenance.component {
        None => String::new(),
        Some(component) => format!(
            "\nScoped to the component `{component}`: only the scenarios whose every command, event \
             and view it accepts, publishes or owns. The scenarios the specification obliges of \
             another component are listed by `ess conform synthesize --component {component}` as \
             `outside:`, and belong in that component's suite.\n"
        ),
    };
    format!(
        r#"# `{PACKAGE}`

{count} scenario(s) synthesized from `{system} {version}`, spec digest `{digest}`.
{scope}
Generated by `ess conform synthesize --target go`. Nothing in this directory is written by hand,
and re-running the command after a change to the specification is the only way to update it.

## Wiring it up

Implement `Target` — nine methods, each answering a question some construct in the specification
asks — and hand it over from one test:

```go
package acd_test

import (
    "testing"

    "example.com/acd/{PACKAGE}"
)

func TestConformance(t *testing.T) {{
    {PACKAGE}.Run(t, func() {PACKAGE}.Target {{ return newTarget() }})
}}
```

`Run` builds one target per scenario, because scenario isolation is the suite's requirement and a
shared target would make it your discipline instead.

## What to return when you cannot answer

`ErrUnsupported`, not an error. A scenario whose semantic the implementation does not expose is
reported as skipped, which is a different fact from a failed one — `ObserveInvocations` is the
method most often in that position, and the specification explicitly does not require it.

Every method may say it, `ExecuteCommand` included: a command whose actor is the implementation
itself has no caller a target can be, and answering for it would be the target deciding its own
verdict. Wrapping the sentinel (`fmt.Errorf("...: %w", essconform.ErrUnsupported)`) is read the
same way, so the reason can carry which command it was.

## What this does not check

Whatever the synthesis refused. Read the refusal list `ess conform synthesize` prints: a suite that
quietly holds fewer checks than the specification requires is the failure this whole thing exists
to rule out, and unlike a refusal, nothing about it is visible in a passing run.

## The report

Set `ESS_REPORT_OUT` to a file path and `Run` writes an `ess-conformance-report/1` there when the
last scenario has finished — the same closed document the Rust runner writes, so
`aep artifact evidence --from <that file>` records the run against the specification artifact
without anybody typing a count. `passed` means every scenario passed; a skipped scenario makes the
run `inconclusive`, because a target that could not answer a question has not shown the answer.

```console
ESS_REPORT_OUT=$PWD/report.json go test ./...
```
"#,
        count = suite.len(),
        system = provenance.system,
        version = provenance.specification_version,
        digest = provenance.spec_digest,
    )
}

#[cfg(test)]
mod tests {
    use ess_primitives::evidence::SpecDigest;

    use super::*;
    use crate::scenario::{SuiteFormat, SuiteProvenance};

    /// An empty suite, which is all these two tests need: what they check is that the runner does
    /// not move when the model does.
    fn suite() -> ConformanceSuite {
        let digest = |value: &str| SpecDigest::new(value).expect("a digest");
        ConformanceSuite::new(SuiteProvenance {
            suite_version: SuiteFormat::CURRENT,
            system: "billing".to_owned(),
            specification_version: "v3".to_owned(),
            spec_digest: digest("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"),
            contract_digest: digest(
                "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
            ),
            component: None,
        })
    }

    /// The emitted package is the same bytes twice, and the Go files do not depend on the model.
    #[test]
    fn the_runner_is_a_constant_and_only_the_suite_moves() {
        let suite = suite();
        let first = emit(&suite);
        let second = emit(&suite);
        assert_eq!(first, second);

        let paths: Vec<&str> = first.iter().map(|file| file.path.as_str()).collect();
        assert_eq!(
            paths,
            vec![
                "essconform/runtime.go",
                "essconform/predicate.go",
                "essconform/suite.go",
                "essconform/suite.json",
                "essconform/README.md",
            ]
        );
    }

    /// Every emitted Go file declares the package the README tells an adopter to import.
    #[test]
    fn every_go_file_is_in_the_package_the_readme_names() {
        for file in emit(&suite()) {
            if std::path::Path::new(&file.path)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("go"))
            {
                assert!(
                    file.contents.contains(&format!("package {PACKAGE}")),
                    "{} does not declare the package",
                    file.path
                );
            }
        }
    }
}
