//! `website/docs/reference/diagnostics.md`, rendered from the catalogues the owning crates export.
//!
//! Every diagnostic `ess` prints has a code a reader can look up, and until this page existed most
//! of them had nowhere to be looked up: three of thirty-seven `ESS-AUTHOR` codes and seven of
//! eighteen `ESS-SYNTH` codes were explained in the published documentation, and the compiler's
//! class numbers and the dotted history refusals not at all.
//!
//! The text is not written here. Each crate that emits a diagnostic exports a catalogue, and a test
//! in that crate fails when a code is missing from it: in `ess-conformance` the catalogue and the
//! exhaustive match that derives each refusal's code are one macro expansion, so a refusal cannot
//! be emitted without an entry; the category enums of realization, composition and deployment are
//! held to their catalogues by reading the enum's declaration; and the compiler's classes and
//! families are held to `class::ALL` and `family::ALL`. This module only lays the entries out.
//! `--check` holds the committed page to that rendering byte for byte, so a code added in a crate
//! and not on the page fails the gate, and it refuses any entry whose meaning or repair is empty.

use anyhow::{bail, Result};
use ess_compiler::diagnostic::{CatalogueEntry, Code};
use ess_compiler::resolve::{class_of, codes};
use ess_composition::CompositionCode;
use ess_conformance::authored::Cause;
use ess_conformance::history::HistoryRefusal;
use ess_conformance::mutate::{self, MutateCode};
use ess_conformance::synthesize::RefusalCause;
use ess_deployment::DiagnosticCode;
use ess_primitives::error::ValidationCode;
use ess_realization::RealizationCode;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// The rendered page, relative to the repository root.
pub const PAGE: &str = "website/docs/reference/diagnostics.md";

const BEGIN: &str = "[ess-diagnostics-begin]: # (generated by cargo xtask diagnostics from the \
                     catalogue each crate exports; change the catalogue, then run the command)";
const END: &str = "[ess-diagnostics-end]: #";

/// One row of a code table.
struct Row {
    code: String,
    meaning: &'static str,
    repair: &'static str,
}

/// Rows for a numbered family, `ESS-<family>-<nnn>`, in code order.
fn numbered(family: &'static str, entries: &[CatalogueEntry<u16>]) -> Vec<Row> {
    let mut entries: Vec<&CatalogueEntry<u16>> = entries.iter().collect();
    entries.sort_by_key(|entry| entry.key);
    entries
        .into_iter()
        .map(|entry| Row {
            code: format!("`{}`", Code::new(family, entry.key)),
            meaning: entry.meaning,
            repair: entry.repair,
        })
        .collect()
}

/// Rows for a family whose key is printed as `name` renders it, in catalogue order.
fn named<K>(entries: &[CatalogueEntry<K>], name: impl Fn(&K) -> String) -> Vec<Row> {
    entries
        .iter()
        .map(|entry| Row {
            code: name(&entry.key),
            meaning: entry.meaning,
            repair: entry.repair,
        })
        .collect()
}

/// A category's name as a JSON report spells it.
fn wire<K: serde::Serialize>(key: &K) -> String {
    match serde_json::to_value(key) {
        Ok(serde_json::Value::String(name)) => name,
        other => panic!("a diagnostic category serializes as a string, not {other:?}"),
    }
}

/// One sentence as a table cell: trimmed, its first letter upper case, ending in a full stop.
fn sentence(text: &str) -> String {
    let text = text.trim();
    let mut characters = text.chars();
    let mut out = match characters.next() {
        Some(first) => first.to_uppercase().chain(characters).collect(),
        None => String::new(),
    };
    if !out.ends_with('.') {
        out.push('.');
    }
    cell(&out)
}

/// Escapes text for a Markdown table cell that MDX also reads.
///
/// Outside a code span, `<`, `>`, `{` and `}` start JSX in MDX, so they become entities there. A
/// `|` ends a table cell anywhere, code span included, so it is escaped everywhere.
fn cell(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for (index, segment) in text.split('`').enumerate() {
        if index > 0 {
            out.push('`');
        }
        let in_code = index % 2 == 1;
        for character in segment.chars() {
            match character {
                '|' => out.push_str("\\|"),
                '\n' => out.push(' '),
                '<' if !in_code => out.push_str("&lt;"),
                '>' if !in_code => out.push_str("&gt;"),
                '{' if !in_code => out.push_str("&#123;"),
                '}' if !in_code => out.push_str("&#125;"),
                other => out.push(other),
            }
        }
    }
    out
}

fn table(out: &mut String, code_header: &str, rows: &[Row]) {
    let _ = writeln!(out, "| {code_header} | Meaning | Repair |");
    out.push_str("|---|---|---|\n");
    for row in rows {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            row.code,
            sentence(row.meaning),
            sentence(row.repair)
        );
    }
    out.push('\n');
}

/// A section after the compiler's, in reading order.
struct Section {
    heading: &'static str,
    intro: &'static str,
    code_header: &'static str,
    rows: Vec<Row>,
}

fn sections() -> Vec<Section> {
    vec![
        Section {
            heading: "Authored scenarios: `ESS-AUTHOR`",
            intro: "An authored scenario file that cannot become a scenario is refused with one \
                    of these codes: by `ess specify validate` for a specification's `scenarios:` \
                    list, and by `ess verify conform synthesize` for the files it reads. \
                    The refusal names the file, and the scenario where the file said enough to name \
                    one:\n\n\
                    ```text\n\
                    refusal[ESS-AUTHOR-012]: `billing.invoice/authored/a-scenario` in a.yaml\n\
                    \x20 `billing.invoice.AllInvoices` is not a view this specification declares\n\
                    \x20 help: name a view the specification declares\n\
                    ```",
            code_header: "Code",
            rows: numbered(Cause::FAMILY, Cause::CATALOGUE),
        },
        Section {
            heading: "Synthesis: `ESS-SYNTH`",
            intro: "`ess verify conform synthesize` reports a construct it could build no \
                    scenario for with one of these codes, beside the suite rather than instead \
                    of it. The `help:` line can be more specific than the repair below, because \
                    some refusals carry the reason that decides it:\n\n\
                    ```text\n\
                    refusal[ESS-SYNTH-011]: entity billing.invoice.Invoice has no scenario `…`\n\
                    \x20 `reminder_count >= 0` reads what no view of `billing.invoice.Invoice` publishes\n\
                    \x20   - `reminder_count` is published by no view of the entity\n\
                    \x20 help: publish the fields the invariant reads in a view of this entity, or state the invariant over what one already publishes\n\
                    ```",
            code_header: "Code",
            rows: numbered(RefusalCause::FAMILY, RefusalCause::CATALOGUE),
        },
        Section {
            heading: "Mutation audit: `ESS-MUTATE`",
            intro: "`ess verify conform mutate` reports an audit it cannot run, or a mutant it \
                    cannot score, with one of these codes. `ESS-MUTATE-001` and \
                    `ESS-MUTATE-003` refuse the whole audit and exit 3; the others are the \
                    verdict on one mutant.",
            code_header: "Code",
            rows: numbered(mutate::FAMILY, MutateCode::CATALOGUE),
        },
        Section {
            heading: "Recorded histories: `history.*`",
            intro: "`ess verify conform check-history` and `ess verify conform import-history` \
                    refuse an `ess-history/1` document they cannot admit under one of these \
                    names, before any operation is checked. The message is the name, a colon \
                    and the detail:\n\n\
                    ```text\n\
                    history.no-clients: `clients` is 0\n\
                    ```",
            code_header: "Name",
            rows: named(HistoryRefusal::CATALOGUE, |name| format!("`{name}`")),
        },
        Section {
            heading: "Realization",
            intro: "The `ess specify realization` commands refuse a realization document with \
                    one of these categories, each at the path in the document it concerns:\n\n\
                    ```text\n\
                    - UnresolvedReference at components: component `ledger` is not declared by the ESS\n\
                    ```\n\n\
                    A JSON report spells the category in snake case, shown second.",
            code_header: "Category",
            rows: named(RealizationCode::CATALOGUE, |code| {
                format!("`{code:?}` (`{}`)", wire(code))
            }),
        },
        Section {
            heading: "Build, release, stack and deployment",
            intro: "The build, component, release, stack and deployment commands under \
                    `ess generate` share one set of categories. Each diagnostic also names the \
                    stage that has to resolve it:\n\n\
                    ```text\n\
                    [missing_binding:Deployment] …\n\
                    ```",
            code_header: "Category",
            rows: named(DiagnosticCode::CATALOGUE, |code| format!("`{code}`")),
        },
        Section {
            heading: "Composition",
            intro: "`ess specify compose` refuses a composition document with one of these \
                    categories:\n\n\
                    ```text\n\
                    [unknown_component] …\n\
                    ```",
            code_header: "Category",
            rows: named(CompositionCode::CATALOGUE, |code| format!("`{code}`")),
        },
    ]
}

/// Every catalogued entry whose meaning or repair is empty.
fn empty_summaries(sections: &[Section]) -> Vec<String> {
    let mut problems = Vec::new();
    for section in sections {
        for row in &section.rows {
            if row.meaning.trim().is_empty() {
                problems.push(format!("{}: {} has no meaning", section.heading, row.code));
            }
            if row.repair.trim().is_empty() {
                problems.push(format!("{}: {} has no repair", section.heading, row.code));
            }
        }
    }
    for class in codes::class::CATALOGUE {
        if class.meaning.trim().is_empty() || class.repair.trim().is_empty() {
            problems.push(format!(
                "compiler class {:03} has an empty summary",
                class.number
            ));
        }
    }
    for family in codes::family::CATALOGUE {
        if family.applies_to.trim().is_empty() {
            problems.push(format!(
                "compiler family {} has an empty summary",
                family.name
            ));
        }
    }
    problems
}

/// The class a number names, for the validation table.
fn class_name(number: u16) -> &'static str {
    codes::class::CATALOGUE
        .iter()
        .find(|class| class.number == number)
        .map_or("", |class| class.name)
}

fn render_sections(sections: &[Section]) -> String {
    let mut out = String::new();
    out.push_str(
        "---\n\
         title: Diagnostics\n\
         description: Every code and refusal name the ess specification, conformance, realization, composition and deployment commands print, what it means, and how to repair it.\n\
         ---\n\n\
         # Diagnostics\n\n",
    );
    out.push_str(BEGIN);
    out.push_str(
        "\n\n\
         Every diagnostic `ess` prints for a specification, a scenario, a suite, a history, a \
         realization, a composition or a deployment carries a stable code or name, and this page \
         lists each one with what it means and how to repair it. A harness matches on the code. \
         The sentence after it and the `help:` line are for the reader, and may be reworded \
         between releases. The `ess infra` commands report their own findings and are not listed \
         here.\n\n\
         ## Specification diagnostics: `ESS-<FAMILY>-<NNN>`\n\n\
         `ess specify validate` reports a defect in a specification twice: \
         once under its validation name in brackets, and once as a compiler diagnostic \
         with a code, a location and a repair hint:\n\n\
         ```text\n\
         \x20 - [undeclared_reference] command.billing.invoice.CreateInvoice.outcomes.accepted.emits: `billing.invoice.InvoiceRaised` is not a declared event (hint: …)\n\
         \x20 - error[ESS-COMMAND-001]: `billing.invoice.InvoiceRaised` is not a declared event\n\
         ```\n\n\
         The code has two parts. The family says which part of the specification the defect is \
         in, and the number says what kind of defect it is. A number means the same thing in \
         every family: `ESS-BINDING-002` and `ESS-VIEW-002` are both type mismatches, one in a \
         binding and one in a view. Any family can carry any class, so the two tables below \
         cover every code.\n\n\
         ### Classes\n\n\
         | Number | Class | Meaning | Repair |\n\
         |---|---|---|---|\n",
    );
    for class in codes::class::CATALOGUE {
        let _ = writeln!(
            out,
            "| `{:03}` | `{}` | {} | {} |",
            class.number,
            class.name,
            sentence(class.meaning),
            sentence(class.repair)
        );
    }
    out.push_str("\n### Families\n\n| Family | Where it applies |\n|---|---|\n");
    for family in codes::family::CATALOGUE {
        let _ = writeln!(
            out,
            "| `{}` | {} |",
            family.name,
            sentence(family.applies_to)
        );
    }
    out.push_str(
        "\n### Validation names\n\n\
         Each bracketed validation name is reported under the class below. Its family is the \
         construct the defect is in.\n\n\
         | Validation name | Class |\n\
         |---|---|\n",
    );
    for code in ValidationCode::ALL {
        let number = class_of(*code);
        let _ = writeln!(
            out,
            "| `{}` | `{number:03}` `{}` |",
            code.as_str(),
            class_name(number)
        );
    }
    out.push('\n');
    for section in sections {
        let _ = write!(out, "## {}\n\n{}\n\n", section.heading, section.intro);
        table(&mut out, section.code_header, &section.rows);
    }
    out.push_str(END);
    out.push('\n');
    out
}

/// The whole page, or every entry with an empty summary.
pub fn render() -> Result<String> {
    let sections = sections();
    let problems = empty_summaries(&sections);
    if !problems.is_empty() {
        bail!(
            "a catalogued diagnostic has no summary; write it in the crate's catalogue:\n  {}",
            problems.join("\n  ")
        );
    }
    Ok(render_sections(&sections))
}

/// Writes the page, or with `check` compares the committed one with it.
pub fn run(root: &Path, check: bool) -> Result<String> {
    let rendered = render()?;
    let path = root.join(PAGE);
    if !check {
        fs::write(&path, &rendered)?;
        return Ok(format!("{PAGE}: written\n"));
    }
    let committed = fs::read_to_string(&path).unwrap_or_default();
    if committed != rendered {
        bail!(
            "{PAGE} is not what the diagnostic catalogues render to; run `cargo xtask \
             diagnostics`. A diagnostic was added, removed or reworded in a crate and the page \
             was left behind."
        );
    }
    Ok(format!(
        "{PAGE}: byte-identical to the diagnostic catalogues\n"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_cell_escapes_what_mdx_and_a_table_would_read() {
        assert_eq!(
            cell("declare `Optional<T>` or {x} | y <z>"),
            "declare `Optional<T>` or &#123;x&#125; \\| y &lt;z&gt;"
        );
        assert_eq!(cell("`a|b`"), "`a\\|b`");
        assert_eq!(sentence(" name a view"), "Name a view.");
        assert_eq!(
            sentence("`drop` is unobservable."),
            "`drop` is unobservable."
        );
    }

    #[test]
    fn the_page_has_a_row_for_every_code_the_story_names() {
        let page = render().expect("every catalogued diagnostic has a summary");
        for number in 1..=37 {
            assert!(
                page.contains(&format!("| `ESS-AUTHOR-{number:03}` |")),
                "AUTHOR {number}"
            );
        }
        for number in 1..=18 {
            assert!(
                page.contains(&format!("| `ESS-SYNTH-{number:03}` |")),
                "SYNTH {number}"
            );
            assert!(
                page.contains(&format!("| `{number:03}` |")),
                "class {number}"
            );
        }
        for number in 1..=5 {
            assert!(
                page.contains(&format!("| `ESS-MUTATE-{number:03}` |")),
                "MUTATE {number}"
            );
        }
        for family in codes::family::ALL {
            assert!(page.contains(&format!("| `{family}` |")), "family {family}");
        }
        assert_eq!(
            page.matches("| `history.").count(),
            15,
            "the dotted refusals"
        );
        for code in ValidationCode::ALL {
            assert!(
                page.contains(&format!("| `{}` |", code.as_str())),
                "{code:?}"
            );
        }
    }

    #[test]
    fn an_empty_summary_is_refused_by_name() {
        let sections = vec![Section {
            heading: "Test",
            intro: "",
            code_header: "Code",
            rows: vec![Row {
                code: "`X-1`".to_owned(),
                meaning: " ",
                repair: "fix it",
            }],
        }];
        assert_eq!(empty_summaries(&sections), ["Test: `X-1` has no meaning"]);
    }
}
