//! The `ess/` table of `website/docs/reference/spec-versions.md`, rendered from `FORMAT_HISTORY`.
//!
//! What each `ess/N` added used to be written twice: in this table by hand, and nowhere the `ess`
//! binary could read it. `FORMAT_HISTORY` in `ess-domain` is now the one record, `ess specify
//! formats` prints it, and this renders the table between two marker lines. `--check` holds the
//! committed table to that rendering byte for byte, so an `added` item changed in the catalogue
//! and not on the page, or a row edited on the page by hand, fails `projection-check`. The prose
//! paragraphs under the table stay hand-written.

use anyhow::{bail, Context, Result};
use ess_domain::system::{FormatHistoryEntry, FORMAT_HISTORY};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// The page whose `ess/` table is generated.
pub const PAGE: &str = "website/docs/reference/spec-versions.md";

/// The line that opens the generated table.
const BEGIN: &str = "[ess-format-history-begin]: # (generated by cargo xtask format-history from \
                     FORMAT_HISTORY in crates/specify/ess-domain/src/system.rs; change the \
                     catalogue, then run the command)";

/// The line that closes the generated table.
const END: &str = "[ess-format-history-end]: #";

/// The "Introduced in" cell: a reference link to the release, or `unreleased`.
pub fn release_cell(release: Option<&str>) -> String {
    match release {
        Some(release) => format!("[{release}][{}]", reference_label(release)),
        None => "unreleased".to_owned(),
    }
}

/// The page's reference label for a release.
///
/// `0.NN.0` keeps the page's existing `rNN`. Every other release is `rMAJOR-MINOR-PATCH`: the
/// hyphens keep it apart from every `rNN`, and its three numbers apart from every other release,
/// so two releases never share a label (`1.0.0` and `0.10.0` would both read `r10` without them).
fn reference_label(release: &str) -> String {
    match release.split('.').collect::<Vec<_>>().as_slice() {
        ["0", minor, "0"] => format!("r{minor}"),
        _ => format!("r{}", release.replace('.', "-")),
    }
}

/// Escapes text for a Markdown table cell that MDX also reads.
///
/// Outside a code span, `<`, `>`, `{` and `}` start JSX in MDX, so they become entities there. A
/// `|` ends a table cell anywhere, code span included, so it is escaped everywhere.
pub fn cell(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for (index, segment) in text.split('`').enumerate() {
        if index > 0 {
            out.push('`');
        }
        let in_code = index % 2 == 1;
        for character in segment.chars() {
            match character {
                '|' => out.push_str("\\|"),
                '\n' => out.push(' '),
                '<' if !in_code => out.push_str("&lt;"),
                '>' if !in_code => out.push_str("&gt;"),
                '{' if !in_code => out.push_str("&#123;"),
                '}' if !in_code => out.push_str("&#125;"),
                other => out.push(other),
            }
        }
    }
    out
}

/// The generated table: one row per format, what it added and then what reads differently.
pub fn render(history: &[FormatHistoryEntry]) -> String {
    let mut out = String::from("| Version | Introduced in | What changed |\n|---|---|---|\n");
    for entry in history {
        let changed: Vec<&str> = entry.added.iter().chain(entry.stricter).copied().collect();
        let _ = writeln!(
            out,
            "| `ess/{}` | {} | {} |",
            entry.major,
            release_cell(entry.release),
            cell(&changed.join(" "))
        );
    }
    out.push('\n');
    out
}

/// Every release label the table links that the page defines no reference for.
pub fn undefined_references(page: &str, history: &[FormatHistoryEntry]) -> Vec<String> {
    let mut missing: Vec<String> = Vec::new();
    for release in history.iter().filter_map(|entry| entry.release) {
        let label = reference_label(release);
        let defined = page
            .lines()
            .any(|line| line.starts_with(&format!("[{label}]: ")));
        if !defined && !missing.contains(&label) {
            missing.push(label);
        }
    }
    missing
}

/// Refuses a page whose generated table is not `block`, naming the first line that differs.
pub fn compare(page: &str, block: &str) -> Result<()> {
    let expected = splice(page, block)?;
    if expected == page {
        return Ok(());
    }
    let found: Vec<&str> = page.lines().collect();
    let wanted: Vec<&str> = expected.lines().collect();
    let line = (0..found.len().max(wanted.len()))
        .find(|&line| found.get(line) != wanted.get(line))
        .unwrap_or(0);
    bail!(
        "{PAGE}:{}: the `ess/` table differs from FORMAT_HISTORY\n\
         expected: {}\n   found: {}\n\
         Change the catalogue in crates/specify/ess-domain/src/system.rs, not the page, and run \
         `cargo xtask format-history`.",
        line + 1,
        wanted.get(line).unwrap_or(&"<end of page>"),
        found.get(line).unwrap_or(&"<end of page>"),
    )
}

/// `page` with the text between its markers replaced by `block`; everything else byte for byte.
fn splice(page: &str, block: &str) -> Result<String> {
    let mut begins = Vec::new();
    let mut ends = Vec::new();
    let mut offset = 0;
    for line in page.split_inclusive('\n') {
        match line.strip_suffix('\n').unwrap_or(line) {
            BEGIN => begins.push(offset + line.len()),
            END => ends.push(offset),
            _ => {}
        }
        offset += line.len();
    }
    let ([begin], [end]) = (begins.as_slice(), ends.as_slice()) else {
        bail!(
            "{PAGE}: needs exactly one `{BEGIN}` line and one `{END}` line; found {} and {}",
            begins.len(),
            ends.len()
        );
    };
    if begin > end || !page[..*begin].ends_with('\n') {
        bail!("{PAGE}: `{END}` must follow `{BEGIN}` on a line of its own");
    }
    Ok(format!("{}\n{block}{}", &page[..*begin], &page[*end..]))
}

/// Writes, or with `check` compares, the generated `ess/` table of [`PAGE`].
pub fn run(root: &Path, check: bool) -> Result<String> {
    let path = root.join(PAGE);
    let page = fs::read_to_string(&path).with_context(|| format!("reading {PAGE}"))?;
    let missing = undefined_references(&page, FORMAT_HISTORY);
    if !missing.is_empty() {
        bail!(
            "{PAGE}: FORMAT_HISTORY links releases the page defines no reference for: {}",
            missing.join(", ")
        );
    }
    let block = render(FORMAT_HISTORY);
    if check {
        compare(&page, &block)?;
        return Ok(format!(
            "{PAGE}: the `ess/` table is byte-identical to FORMAT_HISTORY\n"
        ));
    }
    let updated = splice(&page, &block)?;
    if updated == page {
        return Ok(format!("{PAGE}: already current\n"));
    }
    fs::write(&path, updated).with_context(|| format!("writing {PAGE}"))?;
    Ok(format!("{PAGE}: `ess/` table regenerated\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn committed() -> String {
        let root = crate::workspace_root().expect("workspace root");
        fs::read_to_string(root.join(PAGE)).expect("the version history page")
    }

    #[test]
    fn spec_versions_ess_table_is_rendered_from_the_catalogue() {
        let page = committed();
        compare(&page, &render(FORMAT_HISTORY)).expect("the committed table is the rendering");
    }

    #[test]
    fn an_added_item_edited_in_the_catalogue_and_not_on_the_page_is_refused() {
        let mut history: Vec<FormatHistoryEntry> = FORMAT_HISTORY.to_vec();
        history[0].added = &["A first format nobody wrote down."];
        let error = compare(&committed(), &render(&history)).expect_err("the page fell behind");
        assert!(
            error.to_string().contains("cargo xtask format-history"),
            "{error}"
        );
    }

    #[test]
    fn a_hand_edited_table_is_refused() {
        let page = committed();
        let row = page
            .lines()
            .find(|line| line.starts_with("| `ess/1` |"))
            .expect("an ess/1 row");
        let edited = page.replace(row, &format!("{row} Edited by hand."));
        assert!(compare(&edited, &render(FORMAT_HISTORY)).is_err());
        let dropped = page.replace(&format!("{row}\n"), "");
        assert!(compare(&dropped, &render(FORMAT_HISTORY)).is_err());
    }

    #[test]
    fn a_page_without_exactly_one_pair_of_markers_is_refused() {
        let block = render(FORMAT_HISTORY);
        assert!(compare("no markers\n", &block).is_err());
        let page = committed();
        let doubled = format!("{page}\n{BEGIN}\n{END}\n");
        assert!(compare(&doubled, &block).is_err());
    }

    #[test]
    fn every_release_cell_links_a_reference_the_page_defines() {
        let page = committed();
        assert_eq!(
            undefined_references(&page, FORMAT_HISTORY),
            Vec::<String>::new()
        );
        let missing = page.replace("[r1]: https://", "[r0]: https://");
        assert_eq!(undefined_references(&missing, FORMAT_HISTORY), ["r1"]);
    }

    #[test]
    fn a_cell_escapes_what_mdx_and_a_table_would_read() {
        assert_eq!(
            cell("`{fact, add|subtract}` or {x} <y>"),
            "`{fact, add\\|subtract}` or &#123;x&#125; &lt;y&gt;"
        );
        assert_eq!(release_cell(Some("0.46.1")), "[0.46.1][r0-46-1]");
        assert_eq!(release_cell(Some("1.0.0")), "[1.0.0][r1-0-0]");
        assert_eq!(release_cell(Some("0.20.0")), "[0.20.0][r20]");
        assert_eq!(release_cell(None), "unreleased");
    }
}
