//! The data the product landing page renders: recorded `ess` sessions and the billing domain graph.
//!
//! `website/product.json` names files under `website/data/`, and the docs-system product-site
//! plugin reads them at build time. Every one of them is produced here by running the real `ess`
//! binary on a copy of [`EXAMPLE`]: the terminal sessions are `b10x-terminal/1` documents holding
//! the commands and what they printed, and the domain graphs are `b10x-domain-graph/1` documents
//! derived from `ess specify compile --format json`. Nothing in them is typed by hand, and
//! `--check` refuses a committed file that differs from a fresh recording.
//!
//! The commands run in a scratch directory holding only `examples/billing`, so the paths they
//! print are the relative paths a reader would type, and the files they write land nowhere in the
//! repository.

use anyhow::{bail, ensure, Context, Result};
use serde::Serialize;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Stdio;

/// The specification every recording runs on.
const EXAMPLE: &str = "examples/billing";

/// Where the generated files land, relative to the repository root.
const DATA: &str = "website/data";

/// Recorded in each document, since JSON carries no comment.
const RECORDED_WITH: &str =
    "ess built from this repository, recorded by `cargo xtask site-data` on a copy of examples/billing";

/// Recorded in each domain graph's `domain.source`.
const GRAPH_SOURCE: &str =
    "examples/billing, compiled by `ess specify compile`; generated by `cargo xtask site-data`";

/// One command of a recorded session.
struct Step {
    /// The arguments after `ess`.
    args: &'static [&'static str],
    /// Keep only the last lines of standard output, as `| tail -n N` would.
    tail: Option<usize>,
}

/// One recorded session: its file, its title and its commands, in order.
struct Session {
    file: &'static str,
    title: &'static str,
    steps: &'static [Step],
}

const SESSIONS: &[Session] = &[
    Session {
        file: "ess.terminal.json",
        title: "ess / the billing example",
        steps: &[
            Step {
                args: &["specify", "validate", "--path", EXAMPLE],
                tail: None,
            },
            Step {
                args: &["specify", "compile", "--path", EXAMPLE],
                tail: None,
            },
            Step {
                args: &[
                    "verify",
                    "conform",
                    "synthesize",
                    "--path",
                    EXAMPLE,
                    "--out",
                    "suite.json",
                ],
                tail: None,
            },
            Step {
                args: &[
                    "verify",
                    "conform",
                    "run",
                    "--suite",
                    "suite.json",
                    "--target",
                    "billing",
                ],
                tail: Some(1),
            },
        ],
    },
    Session {
        file: "generate.terminal.json",
        title: "ess / generate and synthesize",
        steps: &[
            Step {
                args: &[
                    "generate",
                    "generate",
                    "--path",
                    EXAMPLE,
                    "--kind",
                    "openapi",
                    "--out",
                    "generated",
                ],
                tail: None,
            },
            Step {
                args: &[
                    "generate",
                    "synthesize",
                    "--path",
                    EXAMPLE,
                    "--target",
                    "rust",
                    "--out",
                    "billing-rust",
                ],
                tail: None,
            },
        ],
    },
];

#[derive(Serialize)]
struct Terminal {
    format: &'static str,
    title: &'static str,
    entries: Vec<Entry>,
    #[serde(rename = "recordedWith")]
    recorded_with: &'static str,
    #[serde(skip_serializing_if = "BTreeMap::is_empty")]
    tones: BTreeMap<String, &'static str>,
}

#[derive(Serialize)]
struct Entry {
    command: String,
    output: String,
    #[serde(rename = "exitCode")]
    exit_code: i32,
}

/// Writes, or with `check` compares, every file under [`DATA`].
pub(super) fn run(root: &Path, check: bool, ess: Option<&Path>) -> Result<String> {
    let ess = match ess {
        Some(path) => path.to_path_buf(),
        None => build_ess(root)?,
    };
    let files = render(root, &ess)?;
    let directory = root.join(DATA);
    let mut report = String::new();
    let mut stale = Vec::new();
    for (name, contents) in &files {
        let path = directory.join(name);
        let current = fs::read_to_string(&path).ok();
        if current.as_deref() == Some(contents.as_str()) {
            continue;
        }
        if check {
            stale.push(format!("{DATA}/{name}"));
        } else {
            fs::create_dir_all(&directory).with_context(|| format!("creating {DATA}"))?;
            fs::write(&path, contents).with_context(|| format!("writing {DATA}/{name}"))?;
            writeln!(report, "{DATA}/{name}: regenerated")?;
        }
    }
    if !stale.is_empty() {
        bail!(
            "these files differ from a fresh recording of `ess`: {}. Run `cargo xtask site-data` \
             and commit the result; never edit them by hand.",
            stale.join(", ")
        );
    }
    if report.is_empty() {
        report = format!(
            "{DATA}: {} file(s) agree with a fresh recording of `ess`\n",
            files.len()
        );
    }
    Ok(report)
}

/// Builds the `ess` binary from this workspace and returns its path.
fn build_ess(root: &Path) -> Result<PathBuf> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let output = std::process::Command::new(&cargo)
        .args([
            "build",
            "--quiet",
            "--locked",
            "--offline",
            "--package",
            "ess-cli",
            "--bin",
            "ess",
            "--message-format",
            "json",
        ])
        .current_dir(root)
        .stderr(Stdio::inherit())
        .output()
        .with_context(|| format!("running {cargo:?} build for ess"))?;
    ensure!(output.status.success(), "building `ess` failed");
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        let Ok(message) = serde_json::from_str::<Value>(line) else {
            continue;
        };
        if message["reason"] == "compiler-artifact" && message["target"]["name"] == "ess" {
            if let Some(executable) = message["executable"].as_str() {
                return Ok(PathBuf::from(executable));
            }
        }
    }
    bail!("`cargo build` reported no `ess` executable")
}

/// Every generated file, keyed by its name under [`DATA`].
fn render(root: &Path, ess: &Path) -> Result<BTreeMap<String, String>> {
    let scratch = Scratch::new()?;
    copy_tree(&root.join(EXAMPLE), &scratch.0.join(EXAMPLE))?;
    let mut files = BTreeMap::new();
    for session in SESSIONS {
        let mut entries = Vec::new();
        for step in session.steps {
            entries.push(record(ess, &scratch.0, step)?);
        }
        let tones = tones(entries.iter().map(|entry| entry.output.as_str()));
        let document = Terminal {
            format: "b10x-terminal/1",
            title: session.title,
            entries,
            recorded_with: RECORDED_WITH,
            tones,
        };
        files.insert(session.file.to_owned(), pretty(&document)?);
    }
    let compiled = std::process::Command::new(ess)
        .args(["specify", "compile", "--path", EXAMPLE, "--format", "json"])
        .current_dir(&scratch.0)
        .output()
        .with_context(|| format!("running {}", ess.display()))?;
    ensure!(
        compiled.status.success(),
        "`ess specify compile` refused the example: {}",
        String::from_utf8_lossy(&compiled.stderr)
    );
    let model: Value =
        serde_json::from_slice(&compiled.stdout).context("reading the compiled model")?;
    for graph in domain_graphs(&model)? {
        let name = format!("{}.domain-graph.json", graph.domain.id.replace('.', "-"));
        files.insert(name, pretty(&graph)?);
    }
    Ok(files)
}

/// Runs one step and records it as a reader would see it in a terminal.
fn record(ess: &Path, directory: &Path, step: &Step) -> Result<Entry> {
    let mut command = format!("ess {}", step.args.join(" "));
    let mut process = std::process::Command::new(ess);
    process.args(step.args).current_dir(directory);
    let (output, status) = match step.tail {
        // One file for both streams, so a note on standard error stays where it was printed.
        None => {
            let log = directory.join(".site-data-output");
            let file = fs::File::create(&log).context("creating the output capture")?;
            let status = process
                .stdout(file.try_clone().context("sharing the output capture")?)
                .stderr(file)
                .status()
                .with_context(|| format!("running `{command}`"))?;
            let output = fs::read_to_string(&log).context("reading the output capture")?;
            fs::remove_file(&log).context("removing the output capture")?;
            (output, status)
        }
        Some(lines) => {
            let output = process
                .output()
                .with_context(|| format!("running `{command}`"))?;
            ensure!(
                output.stderr.is_empty(),
                "`{command}` wrote to standard error, which `| tail` would not hide: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            write!(command, " | tail -n {lines}")?;
            let stdout = String::from_utf8(output.stdout).context("non-UTF-8 output")?;
            let all: Vec<&str> = stdout.lines().collect();
            let kept = all[all.len().saturating_sub(lines)..].join("\n");
            (kept, output.status)
        }
    };
    let exit_code = status
        .code()
        .with_context(|| format!("`{command}` ended without an exit status"))?;
    ensure!(exit_code == 0, "`{command}` failed:\n{output}");
    Ok(Entry {
        command,
        output: output.trim_end_matches('\n').to_owned(),
        exit_code,
    })
}

/// The `tones` of a recorded session: what each verdict word in its output means.
///
/// The renderer colours every occurrence of a key, so a bare `failed` would paint the `failed` of
/// `0 failed` as a failure. A counted verdict is therefore keyed with its count: `32 passed` is
/// true, `2 failed` or `1 error` false, and `0 failed` or `0 error` muted. `valid` and `compiled`
/// stand alone. Only words the output actually printed become keys.
fn tones<'a>(outputs: impl Iterator<Item = &'a str>) -> BTreeMap<String, &'static str> {
    let mut found = BTreeMap::new();
    for output in outputs {
        for line in output.lines() {
            let words: Vec<&str> = line
                .split(|c: char| c.is_whitespace() || c == ',' || c == ':')
                .filter(|word| !word.is_empty())
                .collect();
            for (index, word) in words.iter().enumerate() {
                match *word {
                    "valid" | "compiled" => {
                        found.insert((*word).to_owned(), "true");
                    }
                    "passed" | "failed" | "error" => {
                        let Some(count) = index
                            .checked_sub(1)
                            .and_then(|previous| words[previous].parse::<u64>().ok())
                        else {
                            continue;
                        };
                        let tone = match (*word, count) {
                            (_, 0) => "muted",
                            ("passed", _) => "true",
                            _ => "false",
                        };
                        found.insert(format!("{count} {word}"), tone);
                    }
                    _ => {}
                }
            }
        }
    }
    found
}

fn pretty(value: &impl Serialize) -> Result<String> {
    Ok(serde_json::to_string_pretty(value)? + "\n")
}

/// A directory removed when dropped.
struct Scratch(PathBuf);

impl Scratch {
    fn new() -> Result<Self> {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .context("system clock precedes the Unix epoch")?
            .as_nanos();
        let path =
            std::env::temp_dir().join(format!("ess-site-data-{}-{nonce}", std::process::id()));
        fs::create_dir_all(&path).with_context(|| format!("creating {}", path.display()))?;
        Ok(Self(path))
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn copy_tree(from: &Path, to: &Path) -> Result<()> {
    fs::create_dir_all(to).with_context(|| format!("creating {}", to.display()))?;
    for entry in fs::read_dir(from).with_context(|| format!("reading {}", from.display()))? {
        let entry = entry?;
        let target = to.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_tree(&entry.path(), &target)?;
        } else {
            fs::copy(entry.path(), &target)
                .with_context(|| format!("copying {}", entry.path().display()))?;
        }
    }
    Ok(())
}

#[derive(Serialize)]
struct DomainGraph {
    format: &'static str,
    domain: Domain,
    entities: Vec<Entity>,
    relations: Vec<Relation>,
}

#[derive(Serialize)]
struct Domain {
    id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    display: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    summary: Option<String>,
    system: String,
    source: &'static str,
}

#[derive(Serialize)]
struct Entity {
    id: String,
    name: String,
    identity: Field,
    fields: Vec<Field>,
    #[serde(rename = "createdBy", skip_serializing_if = "Vec::is_empty")]
    created_by: Vec<String>,
    lifecycle: Lifecycle,
}

#[derive(Serialize, PartialEq, Eq, Debug)]
struct Field {
    name: String,
    #[serde(rename = "type")]
    type_name: String,
}

#[derive(Serialize)]
struct Lifecycle {
    initial: String,
    states: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    terminal: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    transitions: Vec<Transition>,
}

#[derive(Serialize)]
struct Transition {
    name: String,
    from: Vec<String>,
    to: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    commands: Vec<String>,
}

#[derive(Serialize)]
struct Relation {
    from: String,
    to: String,
    name: String,
    kind: String,
    cardinality: String,
    via: String,
}

fn text<'a>(value: &'a Value, key: &str) -> Result<&'a str> {
    value[key]
        .as_str()
        .with_context(|| format!("compiled model: `{key}` is not a string in {value}"))
}

fn texts(value: &Value) -> Result<Vec<String>> {
    value
        .as_array()
        .with_context(|| format!("compiled model: expected a list of names, found {value}"))?
        .iter()
        .map(|item| {
            item.as_str()
                .map(ToOwned::to_owned)
                .with_context(|| format!("compiled model: expected a name, found {item}"))
        })
        .collect()
}

/// The last segment of a fully qualified name.
fn short(name: &str) -> &str {
    name.rsplit('.').next().unwrap_or(name)
}

/// A resolved type reference as the graph shows it: `InvoiceId`, `Optional<string>`,
/// `Map<string, string>` — the compiler's own rendering, with declared names shortened.
fn type_name(reference: &Value) -> Result<String> {
    Ok(match text(reference, "kind")? {
        "primitive" => text(reference, "name")?.to_owned(),
        "declared" => short(text(reference, "name")?).to_owned(),
        "optional" => format!("Optional<{}>", type_name(&reference["of"])?),
        "list" => format!("List<{}>", type_name(&reference["of"])?),
        "map" => format!(
            "Map<{}, {}>",
            text(reference, "key")?,
            type_name(&reference["value"])?
        ),
        other => bail!("compiled model: unknown type reference kind `{other}`"),
    })
}

fn field(value: &Value) -> Result<Field> {
    Ok(Field {
        name: text(value, "name")?.to_owned(),
        type_name: type_name(&value["type_ref"])?,
    })
}

/// The commands whose outcomes create each entity, and those that move it along each transition.
#[derive(Default)]
struct Effects {
    creates: BTreeMap<String, BTreeSet<String>>,
    moves: BTreeMap<(String, String), BTreeSet<String>>,
}

fn effects(model: &Value) -> Result<Effects> {
    let mut found = Effects::default();
    let commands = model["commands"]
        .as_object()
        .context("compiled model has no commands")?;
    for (command, declared) in commands {
        for outcome in declared["outcomes"].as_array().into_iter().flatten() {
            let subject = &outcome["subject"];
            if subject.is_null() {
                continue;
            }
            let entity = text(subject, "entity")?.to_owned();
            match text(subject, "effect")? {
                "creates" => {
                    found
                        .creates
                        .entry(entity)
                        .or_default()
                        .insert(command.clone());
                }
                "moves" => {
                    let transition = text(&subject["transition"], "name")?.to_owned();
                    found
                        .moves
                        .entry((entity, transition))
                        .or_default()
                        .insert(command.clone());
                }
                _ => {}
            }
        }
    }
    Ok(found)
}

/// One `b10x-domain-graph/1` document per domain that declares an entity, in domain order.
fn domain_graphs(model: &Value) -> Result<Vec<DomainGraph>> {
    let system = text(model, "system")?.to_owned();
    let effects = effects(model)?;
    let domains = model["domains"]
        .as_object()
        .context("compiled model has no domains")?;
    let mut graphs = Vec::new();
    for (id, declared) in domains {
        let mut names = texts(&declared["entities"])?;
        if names.is_empty() {
            continue;
        }
        names.sort();
        let members: BTreeSet<&str> = names.iter().map(String::as_str).collect();
        let mut entities = Vec::new();
        let mut relations = Vec::new();
        for name in &names {
            let entity = &model["entities"][name.as_str()];
            ensure!(
                entity.is_object(),
                "compiled model: domain {id} lists {name}, which is not an entity"
            );
            let lifecycle = &entity["lifecycle"];
            let transitions = lifecycle["transitions"]
                .as_array()
                .into_iter()
                .flatten()
                .map(|transition| {
                    let transition_name = text(transition, "name")?.to_owned();
                    let commands = effects
                        .moves
                        .get(&(name.clone(), transition_name.clone()))
                        .map(|set| set.iter().cloned().collect())
                        .unwrap_or_default();
                    Ok(Transition {
                        name: transition_name,
                        from: texts(&transition["from"])?,
                        to: text(transition, "to")?.to_owned(),
                        commands,
                    })
                })
                .collect::<Result<Vec<_>>>()?;
            entities.push(Entity {
                id: name.clone(),
                name: short(name).to_owned(),
                identity: field(&entity["identity"])?,
                fields: entity["fields"]
                    .as_array()
                    .into_iter()
                    .flatten()
                    .map(field)
                    .collect::<Result<_>>()?,
                created_by: effects
                    .creates
                    .get(name)
                    .map(|set| set.iter().cloned().collect())
                    .unwrap_or_default(),
                lifecycle: Lifecycle {
                    initial: text(lifecycle, "initial")?.to_owned(),
                    states: texts(&lifecycle["states"])?,
                    terminal: if lifecycle["terminal"].is_null() {
                        Vec::new()
                    } else {
                        texts(&lifecycle["terminal"])?
                    },
                    transitions,
                },
            });
            for relation in entity["relations"].as_array().into_iter().flatten() {
                let target = text(relation, "target")?;
                // A graph draws one domain, and its renderer refuses an edge to an entity it does
                // not hold. Dropping the edge would draw a domain with fewer relations than it
                // has, so the recording refuses instead.
                ensure!(
                    members.contains(target),
                    "{name}.{} relates to {target}, outside domain {id}; a domain graph cannot \
                     draw it",
                    text(relation, "name")?
                );
                relations.push(Relation {
                    from: name.clone(),
                    to: target.to_owned(),
                    name: text(relation, "name")?.to_owned(),
                    kind: text(relation, "kind")?.to_owned(),
                    cardinality: text(relation, "cardinality")?.to_owned(),
                    via: text(relation, "via")?.to_owned(),
                });
            }
        }
        let naming = &declared["naming"];
        graphs.push(DomainGraph {
            format: "b10x-domain-graph/1",
            domain: Domain {
                id: id.clone(),
                display: naming["display"].as_str().map(ToOwned::to_owned),
                summary: naming["summary"].as_str().map(ToOwned::to_owned),
                system: system.clone(),
                source: GRAPH_SOURCE,
            },
            entities,
            relations,
        });
    }
    Ok(graphs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn model() -> Value {
        json!({
            "system": "shop",
            "domains": {
                "shop.notify": {"naming": {}, "entities": []},
                "shop.order": {
                    "naming": {"display": "Orders", "summary": "Taking orders."},
                    "entities": ["shop.order.Order", "shop.order.Customer"]
                }
            },
            "entities": {
                "shop.order.Customer": {
                    "identity": {"name": "customer_id", "type_ref": {"kind": "declared", "name": "shop.order.CustomerId"}},
                    "fields": [{"name": "tags", "type_ref": {"kind": "map", "key": "string", "value": {"kind": "list", "of": {"kind": "primitive", "name": "string"}}}}],
                    "lifecycle": {"states": ["Active"], "initial": "Active", "terminal": ["Active"]},
                    "relations": [{"name": "orders", "kind": "owns", "target": "shop.order.Order", "cardinality": "many", "via": "customer_id"}]
                },
                "shop.order.Order": {
                    "identity": {"name": "order_id", "type_ref": {"kind": "declared", "name": "shop.order.OrderId"}},
                    "fields": [{"name": "note", "type_ref": {"kind": "optional", "of": {"kind": "primitive", "name": "string"}}}],
                    "lifecycle": {"states": ["Open", "Shipped"], "initial": "Open", "terminal": ["Shipped"],
                        "transitions": [{"name": "ship", "from": ["Open"], "to": "Shipped"}]}
                }
            },
            "commands": {
                "shop.order.Place": {"outcomes": [
                    {"name": "placed", "subject": {"entity": "shop.order.Order", "effect": "creates"}},
                    {"name": "refused", "subject": null}
                ]},
                "shop.order.Ship": {"outcomes": [
                    {"name": "shipped", "subject": {"entity": "shop.order.Order", "effect": "moves", "transition": {"name": "ship"}}}
                ]}
            }
        })
    }

    #[test]
    fn a_domain_with_entities_becomes_one_sorted_graph() {
        let graphs = domain_graphs(&model()).unwrap();
        assert_eq!(graphs.len(), 1, "a domain without entities draws nothing");
        let graph = &graphs[0];
        assert_eq!(graph.domain.id, "shop.order");
        assert_eq!(graph.domain.display.as_deref(), Some("Orders"));
        let ids: Vec<_> = graph
            .entities
            .iter()
            .map(|entity| entity.id.as_str())
            .collect();
        assert_eq!(ids, ["shop.order.Customer", "shop.order.Order"]);
        let customer = &graph.entities[0];
        assert_eq!(customer.identity.type_name, "CustomerId");
        assert_eq!(customer.fields[0].type_name, "Map<string, List<string>>");
        assert_eq!(customer.created_by.len(), 0);
        let order = &graph.entities[1];
        assert_eq!(order.fields[0].type_name, "Optional<string>");
        assert_eq!(order.created_by, ["shop.order.Place"]);
        assert_eq!(order.lifecycle.transitions[0].commands, ["shop.order.Ship"]);
        assert_eq!(graph.relations.len(), 1);
        assert_eq!(graph.relations[0].via, "customer_id");
    }

    #[test]
    fn a_relation_leaving_the_domain_is_refused_rather_than_dropped() {
        let mut model = model();
        model["entities"]["shop.order.Customer"]["relations"][0]["target"] =
            json!("shop.billing.Invoice");
        let error = domain_graphs(&model).err().unwrap().to_string();
        assert!(error.contains("outside domain shop.order"), "{error}");
    }

    #[test]
    fn verdict_words_become_tones_and_a_zero_count_is_muted() {
        let found = tones(
            [
                "billing v3 — 5 file(s), valid",
                "billing v3 — 5 file(s), 26 declaration(s), compiled",
                "  32 scenarios: 31 passed, 1 failed, 0 error, 0 unsupported",
                "48 capabilities: 40 generated, 4 obligation(s), 4 refused",
            ]
            .into_iter(),
        );
        let expected: BTreeMap<String, &str> = [
            ("valid", "true"),
            ("compiled", "true"),
            ("31 passed", "true"),
            ("1 failed", "false"),
            ("0 error", "muted"),
        ]
        .into_iter()
        .map(|(word, tone)| (word.to_owned(), tone))
        .collect();
        assert_eq!(found, expected);
        assert_eq!(
            tones(["a scenario failed", "error: nothing"].into_iter()).len(),
            0
        );
    }

    #[test]
    fn an_unknown_type_reference_is_refused() {
        assert!(type_name(&json!({"kind": "tuple"})).is_err());
    }

    #[test]
    fn the_serialized_graph_has_the_renderer_field_names() {
        let graph = &domain_graphs(&model()).unwrap()[0];
        let value: Value = serde_json::from_str(&pretty(graph).unwrap()).unwrap();
        assert_eq!(value["format"], "b10x-domain-graph/1");
        assert_eq!(value["entities"][1]["createdBy"][0], "shop.order.Place");
        assert_eq!(value["entities"][1]["identity"]["type"], "OrderId");
        assert!(value["entities"][0].get("createdBy").is_none());
    }
}
