//! Required target capabilities, extracted without changing the SDK's disposition encoding.

use ess_synth::{CapabilityKind, SynthesisDisposition, SynthesisPlan};
use std::fmt;

/// Whether a required semantic capability is generated or needs an explicit implementation.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
#[serde(tag = "disposition", rename_all = "snake_case", deny_unknown_fields)]
pub enum RequiredDisposition {
    /// Fully generated by ESS synthesis.
    Generated,
    /// An implementation is required against this exact ESS contract.
    Obligation {
        /// Stable human-readable ESS reason.
        reason: String,
        /// Exact ESS obligation contract.
        contract: String,
    },
}

impl<'de> serde::Deserialize<'de> for RequiredDisposition {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // Serde's internally tagged unit variant ignores extra fields even with
        // deny_unknown_fields. An empty struct variant enforces the promised boundary.
        #[derive(serde::Deserialize)]
        #[serde(tag = "disposition", rename_all = "snake_case", deny_unknown_fields)]
        enum Wire {
            Generated {},
            Obligation { reason: String, contract: String },
        }
        match Wire::deserialize(deserializer)? {
            Wire::Generated {} => Ok(Self::Generated),
            Wire::Obligation { reason, contract } => Ok(Self::Obligation { reason, contract }),
        }
    }
}

/// The required capability is absent, duplicated, or explicitly refused.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CapabilityError {
    /// Resolution requires exactly one capability for this kind and source.
    Cardinality {
        /// Required capability kind.
        kind: CapabilityKind,
        /// Exact semantic source spelling.
        source: String,
        /// Number of matching capabilities observed.
        found: usize,
    },
    /// The supplied target plan refuses this capability.
    Refused {
        /// Required capability kind.
        kind: CapabilityKind,
        /// Exact semantic source spelling.
        source: String,
        /// The target's original refusal detail.
        detail: String,
    },
}

/// Resolves exactly one required capability, preserving explicit obligations and refusals.
///
/// The caller must separately bind the plan's provenance to its compiler model and enforce
/// runtime-specific policy. This function does not authenticate or reconstruct a synthesis plan.
pub fn required_disposition(
    plan: &SynthesisPlan,
    kind: CapabilityKind,
    source: &str,
) -> Result<RequiredDisposition, CapabilityError> {
    let matches: Vec<_> = plan
        .capabilities
        .iter()
        .filter(|planned| planned.capability.kind == kind && planned.capability.source == source)
        .collect();
    let [planned] = matches.as_slice() else {
        return Err(CapabilityError::Cardinality {
            kind,
            source: source.to_owned(),
            found: matches.len(),
        });
    };
    match &planned.disposition {
        SynthesisDisposition::Generated => Ok(RequiredDisposition::Generated),
        SynthesisDisposition::Obligation(obligation) => Ok(RequiredDisposition::Obligation {
            reason: obligation.reason.describes(),
            contract: obligation.contract.clone(),
        }),
        SynthesisDisposition::Refused(refusal) => Err(CapabilityError::Refused {
            kind,
            source: source.to_owned(),
            detail: refusal.detail.clone(),
        }),
    }
}

impl fmt::Display for CapabilityError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Cardinality {
                kind,
                source,
                found,
            } => write!(
                f,
                "expected exactly one {kind:?} synthesis capability for {source}, found {found}"
            ),
            Self::Refused {
                kind,
                source,
                detail,
            } => write!(f, "ESS synthesis refused {kind:?} for {source}: {detail}"),
        }
    }
}

impl std::error::Error for CapabilityError {}
