// Package essconform runs a synthesized ESS conformance suite against an implementation.
//
// Generated by `ess conform synthesize --target go`. Do not edit: change the specification and
// regenerate. The suite it runs is in suite.go beside this file.
//
// # What you write
//
// One type satisfying Target, and one test that hands it over:
//
//	func TestConformance(t *testing.T) {
//	    essconform.Run(t, func() essconform.Target { return newTarget() })
//	}
//
// Nothing else. Every scenario, every assertion and every diagnostic below is derived from the
// specification, so adding a command or an invariant to the model adds checks here without anybody
// editing a test.
//
// # The runner owns every source of variation
//
// There is no clock read, no random number and no identifier minted anywhere except in Harness,
// which the runner constructs and hands to the target in each request. A target that needs a
// correlation id or a deadline is given one. This is what makes two runs over one specification
// produce the same report on any machine, at any load, on any day.
//
// Nothing sleeps. An `eventually` step asks the target again and hands it the deadline; the waiting
// happens inside the target, which is the only layer that knows what it is waiting for.
package essconform

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// ---- what an implementation offers ------------------------------------------------------------

// Node is one specification value: nil, bool, float64, string, []Node or map[string]Node.
//
// Deliberately not `any` with a comment: these six are what the model's types project to, and a
// target returning anything else has returned something the specification cannot describe.
type Node = any

// Row is one row of a view: a value per projected field name.
type Row = map[string]Node

// Target is an implementation a conformance suite can be run against.
//
// Every method answers a question some ESS construct asks. There is no assertion among them and no
// reset beyond the isolation ScenarioContext requires: a target reports what it observed, and the
// runner decides whether the specification is satisfied. A method that answered a question the
// suite is supposed to ask would make the suite ask the implementation for its own verdict.
type Target interface {
	// Identity names the implementation under test, for the report.
	Identity() (Identity, error)

	// BeginScenario and EndScenario bracket each scenario. Observations from one scenario may not
	// satisfy another, and this is where a target makes that true.
	BeginScenario(scenario ScenarioContext) error
	EndScenario(scenario ScenarioContext) error

	// ExecuteCommand invokes one command and reports the branch it took, the error it declared and
	// the events it emitted directly.
	ExecuteCommand(request CommandRequest) (CommandResult, error)

	// QueryView reads one view at the consistency the request demands. A read_your_writes view must
	// show the command that just returned, and the target blocks until it can.
	QueryView(request ViewRequest) (ViewResult, error)

	// ObserveEvents reports the events seen for this activity, away from the command that caused
	// them, until the deadline.
	ObserveEvents(request EventObservationRequest) ([]ObservedEvent, error)

	// ConfigureExternalOutcome forces an outcome declared `external:` to take a named branch.
	ConfigureExternalOutcome(control ExternalOutcomeControl) error

	// RedeliverEvent delivers an event a second time. The only way to perform the claim
	// `delivery: at_least_once` makes.
	RedeliverEvent(request RedeliveryRequest) error

	// ObserveInvocations reports the commands one binding invoked and what it passed.
	//
	// Return ErrUnsupported where the implementation cannot expose this; the scenario is reported
	// as unsupported rather than failed, which is a different fact.
	ObserveInvocations(request InvocationObservationRequest) ([]Invocation, error)
}

// ErrUnsupported is what a target returns for a semantic it cannot expose.
//
// Distinct from a failure: a suite that counted "the implementation cannot show me this" as "the
// implementation is wrong" would report a defect nobody can fix.
var ErrUnsupported = fmt.Errorf("the target does not expose this")

// Identity names the implementation under test.
type Identity struct {
	Name    string
	Version string
}

// ScenarioContext is what a target is told about the scenario it is bracketing.
type ScenarioContext struct {
	// Scenario is the scenario id, as the suite writes it.
	Scenario string
	// Correlation is this run's activity id, minted by the runner.
	Correlation string
}

// CommandRequest is one command invocation.
type CommandRequest struct {
	Command     string
	Actor       string
	Input       map[string]Node
	Correlation string
}

// CommandResult is what one command did.
type CommandResult struct {
	// Outcome is the branch it took, empty when it refused.
	Outcome string
	// Error is the declared error it refused with, empty when it did not.
	Error string
	// Consistency is a token a later read_your_writes query may demand, empty when the target has
	// no such token.
	Consistency string
	// DirectEvents are the events emitted as part of the command returning.
	DirectEvents []ObservedEvent
}

// ObservedEvent is one event and what it carried.
type ObservedEvent struct {
	Event   string
	Payload map[string]Node
}

// EventObservationRequest asks for the events of one activity.
type EventObservationRequest struct {
	Event       string
	Correlation string
	Deadline    Deadline
}

// RedeliveryRequest asks for one event to be delivered again.
type RedeliveryRequest struct {
	Event       string
	Correlation string
}

// ViewRequest reads one view.
type ViewRequest struct {
	View string
	// AtLeast is the consistency token the read must reflect, empty for a current read.
	AtLeast     string
	Correlation string
	Deadline    Deadline
}

// ViewResult is what a view holds.
type ViewResult struct {
	Rows []Row
}

// InvocationObservationRequest asks what one binding invoked.
type InvocationObservationRequest struct {
	Binding     string
	Command     string
	Correlation string
	Deadline    Deadline
}

// Invocation is one command a binding invoked, and what it passed.
type Invocation struct {
	Command string
	Input   map[string]Node
}

// ExternalOutcomeControl forces an external outcome to a branch.
type ExternalOutcomeControl struct {
	Command     string
	Outcome     string
	Correlation string
}

// Deadline is when the target may stop waiting, on the runner's clock.
//
// A budget rather than an instant, and there is no poll interval: a poll interval is a fixed delay
// spelled as configuration, which is the same test of the machine it runs on repeated in a loop.
type Deadline struct {
	// Attempts is how many more times the runner will ask.
	Attempts int
}

// ---- the harness ------------------------------------------------------------------------------

// Harness owns every source of variation: the ids handed to a target, and how many times an
// `eventually` step asks before giving up.
//
// Constructed per run, so "the same runner produces the same report" is not a discipline anybody
// has to keep — two identically-constructed harnesses cannot diverge.
type Harness struct {
	system   string
	sequence int
	attempts int
}

// NewHarness returns the harness a run uses, seeded from the specification's own system name.
func NewHarness(system string) *Harness {
	return &Harness{system: reduce(system), attempts: 8}
}

// Correlation mints the next activity id.
func (h *Harness) Correlation() string {
	h.sequence++
	return fmt.Sprintf("%s-%06d", h.system, h.sequence)
}

// Deadline is the budget an `eventually` step is given.
func (h *Harness) Deadline() Deadline {
	return Deadline{Attempts: h.attempts}
}

// reduce turns a system name into something usable as an identifier segment.
func reduce(system string) string {
	var parts []string
	for _, word := range strings.FieldsFunc(system, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9')
	}) {
		parts = append(parts, word)
	}
	if len(parts) == 0 {
		return "ess"
	}
	return strings.Join(parts, "-")
}

// ---- the suite --------------------------------------------------------------------------------

// Suite is a synthesized conformance suite.
type Suite struct {
	Provenance Provenance          `json:"provenance"`
	Scenarios  map[string]Scenario `json:"scenarios"`
}

// Provenance says which specification this suite came from.
//
// SpecDigest is the field that makes a passing run worth anything: without it a report says that
// some implementation passed some suite.
type Provenance struct {
	SuiteVersion         string `json:"suite_version"`
	System               string `json:"system"`
	SpecificationVersion string `json:"specification_version"`
	SpecDigest           string `json:"spec_digest"`
	ContractDigest       string `json:"contract_digest"`
}

// Scenario is one thing the specification obliges an implementation to do.
type Scenario struct {
	Purpose string `json:"purpose"`
	Steps   []Step `json:"steps"`
}

// Step is one step of a scenario. Which fields are set depends on Step.
type Step struct {
	Step        string           `json:"step"`
	Command     string           `json:"command,omitempty"`
	Actor       string           `json:"actor,omitempty"`
	Input       map[string]Value `json:"input,omitempty"`
	Outcome     *OutcomeRef      `json:"outcome,omitempty"`
	Force       *OutcomeRef      `json:"force,omitempty"`
	Event string `json:"event,omitempty"`
	// Payload is plain values, not Value: an event's fields are compared against what the
	// specification declared them to be, and there is nothing earlier in the scenario for them to
	// refer to. `input` and a view expectation's `fields` are the ones that can refer back.
	Payload map[string]Node `json:"payload,omitempty"`
	Shape       map[string]Held  `json:"shape,omitempty"`
	Error       string           `json:"error,omitempty"`
	View        string           `json:"view,omitempty"`
	Expectation *Expectation     `json:"expectation,omitempty"`
	Binding     string           `json:"binding,omitempty"`
	Instance    string           `json:"instance,omitempty"`
	Entity      string           `json:"entity,omitempty"`
	Field       string           `json:"field,omitempty"`
}

// Held is what one declared payload field must hold.
//
// Separate from a value match because the two are different kinds of claim, and only one of them is
// free: a value is assertable only where some construct says where it comes from, and a type is
// declared outright.
type Held struct {
	Holds string `json:"holds"`
	Kind  string `json:"kind,omitempty"`
}

// OutcomeRef names one branch of one command.
type OutcomeRef struct {
	Command string `json:"command"`
	Outcome string `json:"outcome"`
}

// Value is one value a step carries: written down, captured earlier, or read from an event.
type Value struct {
	Kind     string `json:"kind"`
	Value    Node   `json:"value,omitempty"`
	Instance string `json:"instance,omitempty"`
	Event    string `json:"event,omitempty"`
	Field    string `json:"field,omitempty"`
}

// Expectation is what must hold of a view.
//
// AtLeast and AtMost are pointers because absent and zero are different answers: a floor of zero
// requires nothing, and a suite that wrote neither bound is asking nothing at all — which is a
// generator defect this runner reports rather than passes.
type Expectation struct {
	Expect    string           `json:"expect"`
	Fields    map[string]Value `json:"fields,omitempty"`
	Predicate json.RawMessage  `json:"predicate,omitempty"`
	OrderBy   []string         `json:"order_by,omitempty"`
	AtLeast   *int             `json:"at_least,omitempty"`
	AtMost    *int             `json:"at_most,omitempty"`
}

// ---- running ----------------------------------------------------------------------------------

// Run executes every scenario of the embedded suite against a freshly built target.
//
// One target per scenario, because scenario isolation is the suite's own requirement and a shared
// target makes it the adopter's discipline instead.
func Run(t *testing.T, newTarget func() Target) {
	t.Helper()

	var suite Suite
	if err := json.Unmarshal([]byte(suiteJSON), &suite); err != nil {
		t.Fatalf("the embedded suite does not parse, which is a generator defect: %v", err)
	}

	// Sorted, so the order scenarios run in is the order they are written in the report, on every
	// machine. Go randomises map iteration on purpose and a suite that reported in that order would
	// be unreadable across two runs.
	ids := make([]string, 0, len(suite.Scenarios))
	for id := range suite.Scenarios {
		ids = append(ids, id)
	}
	sort.Strings(ids)

	t.Logf(
		"%s %s, %d scenario(s), spec digest %s",
		suite.Provenance.System,
		suite.Provenance.SpecificationVersion,
		len(ids),
		suite.Provenance.SpecDigest,
	)

	harness := NewHarness(suite.Provenance.System)
	for _, id := range ids {
		scenario := suite.Scenarios[id]
		t.Run(id, func(t *testing.T) {
			run := &run{
				t:           t,
				target:      newTarget(),
				harness:     harness,
				correlation: harness.Correlation(),
				instances:   map[string]Node{},
				observed:    map[string][]ObservedEvent{},
			}
			run.execute(id, scenario)
		})
	}
}

// run is one scenario in flight, and everything it has bound.
type run struct {
	t           *testing.T
	target      Target
	harness     *Harness
	correlation string

	// instances are what `capture_instance` bound, by name.
	instances map[string]Node
	// observed are the events the last command published, by event name. Cleared per command,
	// because every `expect_no_event` is a claim about *that* invocation.
	observed map[string][]ObservedEvent
	// seen are the events observed anywhere in this scenario so far, in the order they arrived.
	//
	// A second record rather than the same one, because the two answer different questions. A
	// negative event assertion asks what this command published; a value written `observed` asks
	// what some earlier step in this scenario published, which is what the suite means by it — and
	// a scenario that arranges further instances after the branch would otherwise lose the branch's
	// own occurrence the moment the next command ran.
	seen []ObservedEvent
	// last is what the most recent command did, for the assertions that read it.
	last CommandResult
	// consistency is the token the last command returned, for a read_your_writes query.
	consistency string
	// lastView is what the last query_view returned, for the expect_view after it.
	lastView ViewResult
	// queried is which view lastView came from.
	queried string
}

func (r *run) execute(id string, scenario Scenario) {
	context := ScenarioContext{Scenario: id, Correlation: r.correlation}
	if err := r.target.BeginScenario(context); err != nil {
		if err == ErrUnsupported {
			r.t.Skipf("the target does not support this scenario: %v", err)
		}
		r.t.Fatalf("begin: %v", err)
	}
	defer func() {
		if err := r.target.EndScenario(context); err != nil {
			r.t.Errorf("end: %v", err)
		}
	}()

	if scenario.Purpose != "" {
		r.t.Log(scenario.Purpose)
	}
	for index, step := range scenario.Steps {
		if !r.step(index, step) {
			return
		}
	}
}

// step performs one step, reporting whether the scenario should continue.
//
// A failed assertion stops the scenario: the steps after it were written assuming this one held,
// and running them produces a second failure about the first one's cause.
func (r *run) step(index int, step Step) bool {
	switch step.Step {
	case "execute_command":
		return r.executeCommand(index, step)
	case "expect_outcome":
		return r.expectOutcome(index, step)
	case "expect_error":
		return r.expectError(index, step)
	case "expect_event":
		return r.expectEvent(index, step)
	case "expect_no_event":
		return r.expectNoEvent(index, step)
	case "eventually_event":
		return r.eventuallyEvent(index, step)
	case "capture_instance":
		return r.captureInstance(index, step)
	case "query_view":
		return r.queryView(index, step)
	case "expect_view":
		return r.expectView(index, step, false)
	case "eventually_view":
		return r.expectView(index, step, true)
	case "expect_invocation":
		return r.expectInvocation(index, step)
	case "redeliver_event":
		return r.redeliver(index, step)
	case "configure_external_outcome":
		return r.configure(index, step)
	default:
		// A step this build does not know is a suite written by a newer generator. Reporting it as
		// a failure would blame the implementation for the tool's age.
		r.t.Skipf("step %d is `%s`, which this generated runner does not implement", index, step.Step)
		return false
	}
}

func (r *run) executeCommand(index int, step Step) bool {
	input, ok := r.resolveAll(index, step.Input)
	if !ok {
		return false
	}
	result, err := r.target.ExecuteCommand(CommandRequest{
		Command:     step.Command,
		Actor:       step.Actor,
		Input:       input,
		Correlation: r.correlation,
	})
	if err != nil {
		return r.fail(index, "executing `%s`: %v", step.Command, err)
	}
	r.consistency = result.Consistency
	r.last = result
	// Cleared, not accumulated. Every `expect_no_event` in a scenario is a claim about *this*
	// command — a scenario that creates an invoice and then pays it asserts that paying emitted no
	// `InvoiceCreated`, which would be false against everything seen so far.
	r.observed = map[string][]ObservedEvent{}
	for _, event := range result.DirectEvents {
		r.observed[event.Event] = append(r.observed[event.Event], event)
		r.remember(event)
	}
	return true
}

// remember records an occurrence for the whole scenario, without recording one twice.
func (r *run) remember(event ObservedEvent) {
	for _, held := range r.seen {
		if held.Event == event.Event && equal(held.Payload, event.Payload) {
			return
		}
	}
	r.seen = append(r.seen, event)
}

func (r *run) expectOutcome(index int, step Step) bool {
	if step.Outcome == nil {
		return r.fail(index, "the suite names no outcome, which is a generator defect")
	}
	if r.last.Outcome != step.Outcome.Outcome {
		return r.fail(
			index,
			"`%s` took `%s`, and the specification says `%s`",
			step.Outcome.Command, orNone(r.last.Outcome), step.Outcome.Outcome,
		)
	}
	return true
}

func (r *run) expectError(index int, step Step) bool {
	if r.last.Error != step.Error {
		return r.fail(index, "refused with `%s`, and the specification says `%s`", orNone(r.last.Error), step.Error)
	}
	return true
}

func (r *run) expectEvent(index int, step Step) bool {
	seen := r.observed[step.Event]
	if len(seen) == 0 {
		return r.fail(index, "`%s` was not emitted", step.Event)
	}
	var mismatch string
	for _, event := range seen {
		if !matches(event.Payload, step.Payload) {
			continue
		}
		// The declared fields, and what each holds. Asserting only that the event arrived would
		// pass an implementation that published it empty.
		if reason := holds(event.Payload, step.Shape); reason != "" {
			mismatch = reason
			continue
		}
		return true
	}
	if mismatch != "" {
		return r.fail(index, "`%s` was emitted, and %s", step.Event, mismatch)
	}
	return r.fail(
		index,
		"`%s` was emitted, and no instance of it carried %s",
		step.Event,
		describe(step.Payload),
	)
}

func (r *run) expectNoEvent(index int, step Step) bool {
	if len(r.observed[step.Event]) > 0 {
		return r.fail(index, "`%s` was emitted, and this branch does not emit it", step.Event)
	}
	return true
}

func (r *run) eventuallyEvent(index int, step Step) bool {
	deadline := r.harness.Deadline()
	for attempt := 0; attempt < deadline.Attempts; attempt++ {
		events, err := r.target.ObserveEvents(EventObservationRequest{
			Event:       step.Event,
			Correlation: r.correlation,
			Deadline:    Deadline{Attempts: deadline.Attempts - attempt},
		})
		if err == ErrUnsupported {
			r.t.Skipf("step %d: the target cannot observe `%s`", index, step.Event)
			return false
		}
		if err != nil {
			return r.fail(index, "observing `%s`: %v", step.Event, err)
		}
		for _, event := range events {
			r.observed[event.Event] = append(r.observed[event.Event], event)
			r.remember(event)
		}
		if len(r.observed[step.Event]) > 0 {
			return true
		}
	}
	return r.fail(index, "`%s` was not observed within the run's budget", step.Event)
}

func (r *run) captureInstance(index int, step Step) bool {
	for _, event := range r.observed[step.Event] {
		if value, ok := event.Payload[step.Field]; ok {
			r.instances[step.Instance] = value
			return true
		}
	}
	return r.fail(
		index,
		"nothing bound `%s`: `%s` did not carry `%s`",
		step.Instance, step.Event, step.Field,
	)
}

func (r *run) queryView(index int, step Step) bool {
	result, err := r.target.QueryView(ViewRequest{
		View:        step.View,
		AtLeast:     r.consistency,
		Correlation: r.correlation,
		Deadline:    r.harness.Deadline(),
	})
	if err == ErrUnsupported {
		r.t.Skipf("step %d: the target does not expose `%s`", index, step.View)
		return false
	}
	if err != nil {
		return r.fail(index, "querying `%s`: %v", step.View, err)
	}
	r.lastView = result
	r.queried = step.View
	return true
}

func (r *run) expectView(index int, step Step, retry bool) bool {
	attempts := 1
	if retry {
		attempts = r.harness.Deadline().Attempts
	}
	var last string
	for attempt := 0; attempt < attempts; attempt++ {
		if retry || r.queried != step.View {
			result, err := r.target.QueryView(ViewRequest{
				View:        step.View,
				Correlation: r.correlation,
				Deadline:    Deadline{Attempts: attempts - attempt},
			})
			if err == ErrUnsupported {
				r.t.Skipf("step %d: the target does not expose `%s`", index, step.View)
				return false
			}
			if err != nil {
				return r.fail(index, "querying `%s`: %v", step.View, err)
			}
			r.lastView = result
			r.queried = step.View
		}
		held, reason, undecidable := r.decide(index, step)
		if undecidable {
			// Not retried, ever. A row that cannot answer the question is a defect in the
			// specification or in what the view publishes, and polling to the deadline reports it
			// as a timeout — the same defect in a slower, less legible costume.
			return r.fail(index, "%s", reason)
		}
		if held {
			return true
		}
		last = reason
	}
	return r.fail(index, "%s", last)
}

// decide answers whether the view expectation holds, why not, and whether it could be decided.
func (r *run) decide(index int, step Step) (bool, string, bool) {
	expectation := step.Expectation
	if expectation == nil {
		return false, "the suite names no expectation, which is a generator defect", true
	}
	switch expectation.Expect {
	case "contains", "excludes":
		want, ok := r.resolveAll(index, expectation.Fields)
		if !ok {
			return false, "a value the expectation names is not bound", true
		}
		found := false
		for _, row := range r.lastView.Rows {
			if matches(row, want) {
				found = true
				break
			}
		}
		if expectation.Expect == "excludes" {
			if found {
				return false, fmt.Sprintf("`%s` holds a row where %s, and it must not", step.View, describe(want)), false
			}
			return true, "", false
		}
		if !found {
			return false, fmt.Sprintf("`%s` holds no row where %s", step.View, describe(want)), false
		}
		return true, "", false
	case "satisfies":
		predicate, err := parsePredicate(expectation.Predicate)
		if err != nil {
			return false, fmt.Sprintf("the suite's predicate does not parse: %v", err), true
		}
		// "At least one row" is part of the assertion: every row of an empty view satisfies
		// everything, so a target that published nothing would otherwise pass.
		if len(r.lastView.Rows) == 0 {
			return false, fmt.Sprintf("`%s` holds no rows", step.View), false
		}
		for _, row := range r.lastView.Rows {
			switch predicate.evaluate(facts(row)) {
			case truthTrue:
			case truthFalse:
				return false, fmt.Sprintf("`%s` in %s", predicate, describeRow(row)), false
			default:
				return false, fmt.Sprintf(
					"`%s` cannot be decided against %s, which is a defect in the view or the specification",
					predicate, describeRow(row),
				), true
			}
		}
		return true, "", false
	case "counts":
		// A count and not a match: which rows they are is what `contains` asks, and asking both in
		// one assertion would report two different defects under one name.
		if expectation.AtLeast == nil && expectation.AtMost == nil {
			return false, "a count with neither `at_least` nor `at_most` requires nothing, which is a generator defect", true
		}
		held := len(r.lastView.Rows)
		if expectation.AtLeast != nil && held < *expectation.AtLeast {
			return false, fmt.Sprintf(
				"`%s` holds %d row(s) and the specification requires at least %d",
				step.View, held, *expectation.AtLeast,
			), false
		}
		if expectation.AtMost != nil && held > *expectation.AtMost {
			return false, fmt.Sprintf(
				"`%s` holds %d row(s) and the specification permits at most %d",
				step.View, held, *expectation.AtMost,
			), false
		}
		return true, "", false
	case "ranked":
		return ranked(step.View, expectation.OrderBy, r.lastView.Rows)
	default:
		return false, fmt.Sprintf("`%s` is an expectation this generated runner does not implement", expectation.Expect), true
	}
}

func (r *run) expectInvocation(index int, step Step) bool {
	invocations, err := r.target.ObserveInvocations(InvocationObservationRequest{
		Binding:     step.Binding,
		Command:     step.Command,
		Correlation: r.correlation,
		Deadline:    r.harness.Deadline(),
	})
	if err == ErrUnsupported {
		// The one method the model explicitly refuses to require. Unsupported is a fact about the
		// target, not a failure of the specification.
		r.t.Skipf("step %d: the target does not expose what `%s` invoked", index, step.Binding)
		return false
	}
	if err != nil {
		return r.fail(index, "observing `%s`: %v", step.Binding, err)
	}
	want, ok := r.resolveAll(index, step.Input)
	if !ok {
		return false
	}
	for _, invocation := range invocations {
		if invocation.Command == step.Command && matches(invocation.Input, want) {
			return true
		}
	}
	return r.fail(
		index,
		"`%s` did not invoke `%s` with %s",
		step.Binding, step.Command, describe(want),
	)
}

func (r *run) redeliver(index int, step Step) bool {
	err := r.target.RedeliverEvent(RedeliveryRequest{Event: step.Event, Correlation: r.correlation})
	if err == ErrUnsupported {
		r.t.Skipf("step %d: the target cannot redeliver `%s`, so `at_least_once` is unchecked", index, step.Event)
		return false
	}
	if err != nil {
		return r.fail(index, "redelivering `%s`: %v", step.Event, err)
	}
	return true
}

func (r *run) configure(index int, step Step) bool {
	if step.Force == nil {
		return r.fail(index, "the suite names no outcome to force, which is a generator defect")
	}
	err := r.target.ConfigureExternalOutcome(ExternalOutcomeControl{
		Command:     step.Force.Command,
		Outcome:     step.Force.Outcome,
		Correlation: r.correlation,
	})
	if err == ErrUnsupported {
		r.t.Skipf("step %d: the target cannot force `%s`", index, step.Force.Outcome)
		return false
	}
	if err != nil {
		return r.fail(index, "forcing `%s`: %v", step.Force.Outcome, err)
	}
	return true
}

// fail records one failed assertion and stops the scenario.
func (r *run) fail(index int, format string, args ...any) bool {
	r.t.Errorf("step %d: "+format, append([]any{index}, args...)...)
	return false
}

// resolveAll resolves every value a step carries against what this run has bound.
func (r *run) resolveAll(index int, values map[string]Value) (map[string]Node, bool) {
	resolved := make(map[string]Node, len(values))
	for field, value := range values {
		node, err := r.resolve(value)
		if err != nil {
			r.fail(index, "`%s`: %v", field, err)
			return nil, false
		}
		resolved[field] = node
	}
	return resolved, true
}

func (r *run) resolve(value Value) (Node, error) {
	switch value.Kind {
	case "literal":
		return value.Value, nil
	case "instance":
		bound, ok := r.instances[value.Instance]
		if !ok {
			return nil, fmt.Errorf("nothing bound the instance `%s`", value.Instance)
		}
		return bound, nil
	case "observed":
		// The whole scenario, and the first occurrence in it. `observed` means "what an earlier
		// step in this scenario published", so a later command that published nothing of this name
		// does not unbind it, and a neighbouring instance arranged afterwards does not take it over.
		for _, event := range r.seen {
			if event.Event != value.Event {
				continue
			}
			if field, ok := event.Payload[value.Field]; ok {
				return field, nil
			}
		}
		return nil, fmt.Errorf("`%s` was not observed carrying `%s`", value.Event, value.Field)
	default:
		return nil, fmt.Errorf("`%s` is a value kind this generated runner does not implement", value.Kind)
	}
}

// ---- comparisons ------------------------------------------------------------------------------

// matches reports whether every wanted field is present and equal.
//
// A subset, not an equality: a row carries what the view projects, and a scenario names the fields
// that identify the instance it is about.
func matches(row map[string]Node, want map[string]Node) bool {
	for field, expected := range want {
		actual, ok := row[field]
		if !ok || !equal(actual, expected) {
			return false
		}
	}
	return true
}

// equal compares two specification values structurally.
func equal(left, right Node) bool {
	switch left := left.(type) {
	case nil:
		return right == nil
	case bool:
		other, ok := right.(bool)
		return ok && left == other
	case float64:
		other, ok := asNumber(right)
		return ok && left == other
	case string:
		other, ok := right.(string)
		return ok && left == other
	case []any:
		other, ok := right.([]any)
		if !ok || len(left) != len(other) {
			return false
		}
		for index := range left {
			if !equal(left[index], other[index]) {
				return false
			}
		}
		return true
	case map[string]any:
		other, ok := right.(map[string]any)
		if !ok || len(left) != len(other) {
			return false
		}
		for key, value := range left {
			if !equal(value, other[key]) {
				return false
			}
		}
		return true
	default:
		return false
	}
}

func asNumber(value Node) (float64, bool) {
	switch value := value.(type) {
	case float64:
		return value, true
	case int:
		return float64(value), true
	case int64:
		return float64(value), true
	case json.Number:
		parsed, err := value.Float64()
		return parsed, err == nil
	default:
		return 0, false
	}
}

// describe renders a field match for a diagnostic, in a stable order.
func describe(fields map[string]Node) string {
	return describeRow(fields)
}

func describeRow(row map[string]Node) string {
	keys := make([]string, 0, len(row))
	for key := range row {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		parts = append(parts, fmt.Sprintf("%s = %s", key, render(row[key])))
	}
	return strings.Join(parts, ", ")
}

func render(value Node) string {
	switch value := value.(type) {
	case nil:
		return "null"
	case string:
		return strconv.Quote(value)
	case float64:
		return strconv.FormatFloat(value, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(value)
	default:
		encoded, err := json.Marshal(value)
		if err != nil {
			return fmt.Sprintf("%v", value)
		}
		return string(encoded)
	}
}

// holds reports why a payload does not carry what the specification declared, or "" when it does.
//
// A shape path is dotted — `amount.currency` — because a declared field may itself be a struct, and
// what is checked is the leaf that actually holds a value.
func holds(payload map[string]Node, shape map[string]Held) string {
	paths := make([]string, 0, len(shape))
	for path := range shape {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	for _, path := range paths {
		value, ok := lookup(payload, path)
		if !ok {
			return fmt.Sprintf("did not carry `%s`", path)
		}
		expected := shape[path]
		if expected.Holds != "primitive" {
			// Only primitives are checked. A list or a map is a shape this runner would have to
			// re-derive to compare, and re-deriving a decision the compiler already took is how two
			// answers to one question appear.
			continue
		}
		if reason := primitive(expected.Kind, value); reason != "" {
			return fmt.Sprintf("`%s` %s", path, reason)
		}
	}
	return ""
}

// lookup follows a dotted path into a payload.
func lookup(payload map[string]Node, path string) (Node, bool) {
	var current Node = payload
	for _, segment := range strings.Split(path, ".") {
		mapping, ok := current.(map[string]any)
		if !ok {
			return nil, false
		}
		current, ok = mapping[segment]
		if !ok {
			return nil, false
		}
	}
	return current, true
}

// primitive reports why a value is not of the declared kind, or "" when it is.
func primitive(kind string, value Node) string {
	switch kind {
	case "string", "uuid", "timestamp", "duration":
		if _, ok := value.(string); !ok {
			return fmt.Sprintf("holds %s and the specification declares a %s", render(value), kind)
		}
	case "integer", "decimal":
		if _, ok := asNumber(value); !ok {
			return fmt.Sprintf("holds %s and the specification declares a %s", render(value), kind)
		}
	case "boolean":
		if _, ok := value.(bool); !ok {
			return fmt.Sprintf("holds %s and the specification declares a boolean", render(value))
		}
	}
	return ""
}

// ---- ordering ---------------------------------------------------------------------------------

// ranked reports whether rows are in the declared order.
//
// Adjacent pairs, not a sort: re-sorting and comparing would ask whether these are the right rows,
// which they trivially are, and would pass a view that returned everything backwards.
//
// Fewer than two rows holds. There is no adjacent pair to be out of order, and demanding one would
// quietly make every ordering claim a non-emptiness claim as well.
func ranked(view string, orderBy []string, rows []Row) (bool, string, bool) {
	keys := make([][2]string, 0, len(orderBy))
	for _, written := range orderBy {
		parts := strings.Fields(written)
		if len(parts) == 0 {
			return false, "the suite writes an empty ranking key, which is a generator defect", true
		}
		direction := "asc"
		if len(parts) > 1 {
			direction = parts[1]
		}
		keys = append(keys, [2]string{parts[0], direction})
	}

	for index := 0; index+1 < len(rows); index++ {
		earlier, later := rows[index], rows[index+1]
		for _, key := range keys {
			left, hasLeft := earlier[key[0]]
			right, hasRight := later[key[0]]
			if !hasLeft || !hasRight {
				return false, fmt.Sprintf(
					"`%s` is ranked by `%s` and does not publish it, which is a defect in the view",
					view, key[0],
				), true
			}
			order, ok := compare(left, right)
			if !ok {
				return false, fmt.Sprintf(
					"`%s` holds values of two kinds in `%s`, which have no order between them",
					view, key[0],
				), true
			}
			if order == 0 {
				continue
			}
			wanted := -1
			if key[1] == "desc" || key[1] == "descending" {
				wanted = 1
			}
			if order == wanted {
				break
			}
			return false, fmt.Sprintf(
				"`%s` holds %s then %s, which is not `%s %s`",
				view, describeRow(earlier), describeRow(later), key[0], key[1],
			), false
		}
	}
	return true, "", false
}

// compare orders two row values, reporting false where nothing orders them.
func compare(left, right Node) (int, bool) {
	if leftNumber, ok := asNumber(left); ok {
		if rightNumber, ok := asNumber(right); ok {
			switch {
			case leftNumber < rightNumber:
				return -1, true
			case leftNumber > rightNumber:
				return 1, true
			default:
				return 0, true
			}
		}
		return 0, false
	}
	if leftText, ok := left.(string); ok {
		if rightText, ok := right.(string); ok {
			return strings.Compare(leftText, rightText), true
		}
		return 0, false
	}
	if leftBool, ok := left.(bool); ok {
		if rightBool, ok := right.(bool); ok {
			switch {
			case leftBool == rightBool:
				return 0, true
			case rightBool:
				return -1, true
			default:
				return 1, true
			}
		}
	}
	return 0, false
}

func orNone(value string) string {
	if value == "" {
		return "nothing"
	}
	return value
}
