//! The same test files, emitted as a Playwright spec for the generated React project, selecting
//! every node by `[data-ui-path="…"]`. The spec is generated text; no browser runs here.

use std::path::{Path, PathBuf};

fn example_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../examples/partner-portal")
}

fn spec() -> String {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let files: Vec<ess_ui_test::TestFile> = ["partners-list.yaml", "live.yaml", "stale.yaml"]
        .iter()
        .map(|name| ess_ui_test::load(&example_dir().join("tests").join(name)).expect("loads"))
        .collect();
    ess_ui_test::playwright(&files, &document)
}

#[test]
fn every_test_becomes_a_playwright_test() {
    let spec = spec();
    assert!(
        spec.starts_with("// Generated by `ess ui test --playwright`"),
        "{spec}"
    );
    assert!(
        spec.contains("import { test, expect } from \"@playwright/test\";"),
        "{spec}"
    );
    for name in [
        "the search narrows the partner list",
        "deleting a partner asks first and sends the command",
        "a live ticket lands in the filtered list",
        "stale_after marks a channel that stays reconnecting",
    ] {
        assert!(
            spec.contains(&format!("test(\"{name}\", async ({{ page }}) => {{")),
            "{name}\n{spec}"
        );
    }
    // Deterministic: the same files give the same bytes.
    assert_eq!(spec, self::spec());
}

#[test]
fn steps_select_by_node_path_and_open_pages_by_route() {
    let spec = spec();
    for wanted in [
        // open: the React route of the page.
        "await page.goto(\"/partners/list\");",
        // type into a filter bar's search.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/filters\"] input[type=\"search\"]').pressSequentially(\"cedar\");",
        // choose an option of a filter-bar choice.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/filters/choices/tier\"]').getByRole(\"button\", { name: \"gold\", exact: true }).click();",
        // act on a row action, addressed under its row.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003/row_actions/delete\"]').click();",
        // act on an overlay: its primary button.
        "await page.locator('[data-ui-path=\"pages/partners.list/overlays/delete\"] button.ui-tone-danger, [data-ui-path=\"pages/partners.list/overlays/delete\"] button.ui-tone-primary').last().click();",
        // expect text.
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003\"]')).toContainText(\"Cedar Partners\");",
        // expect rows, by key and in order.
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-row')).toHaveCount(1);",
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-row').nth(0)).toHaveAttribute(\"data-ui-path\", \"pages/partners.list/sections/list/rows/pt-003\");",
        // expect section state.
        "await expect(page.locator('[data-ui-path=\"pages/overview/sections/kpis\"] .ui-stale-badge')).toBeVisible();",
        "await expect(page.locator('[data-ui-path=\"pages/overview/sections/kpis\"]')).toHaveAttribute(\"data-status\", \"ready\");",
        // time is the page's clock.
        "await page.clock.install({ time: 0 });",
        "await page.clock.runFor(25000);",
        "await page.clock.runFor(500);",
    ] {
        assert!(spec.contains(wanted), "{wanted}\n\n{spec}");
    }
}

/// `select` of a row moves the focus the way the terminal's cursor does, without a pointer click
/// that could land on a link inside the row; `page` goes to an absolute page and waits for it.
#[test]
fn select_focuses_a_row_and_page_reaches_an_absolute_page() {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let text = "format: ess-ui-test/1\ndocument: ui.yaml\ntests:\n- name: s\n  steps:\n\
                \x20 - open: partners.list\n\
                \x20 - select: pages/partners.list/sections/list/rows/pt-003/row_actions/delete\n\
                \x20 - page: {at: pages/partners.list/sections/list, to: 2}\n";
    let file = ess_ui_test::parse_str(text, &example_dir().join("inline.yaml")).expect("parses");
    let spec = ess_ui_test::playwright(&[file], &document);
    let row = "page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003\"]')";
    for wanted in [
        format!("await {row}.dispatchEvent(\"click\");"),
        format!("await expect({row}).toHaveClass(/(^|\\s)ui-focused(\\s|$)/);"),
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-pager').locator(\"button\").last().click();".to_owned(),
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-pager').locator(\"span\")).toHaveText(\"Page 2\");".to_owned(),
    ] {
        assert!(spec.contains(&wanted), "{wanted}\n\n{spec}");
    }
    assert!(!spec.contains(&format!("await {row}.click();")), "{spec}");
}

#[test]
fn commands_and_fixture_overrides_go_through_the_http_adapter_routes() {
    let spec = spec();
    assert!(
        spec.contains("await page.route(\"**/commands/**\""),
        "{spec}"
    );
    assert!(
        spec.contains(
            "expect(commands).toContainEqual(expect.objectContaining({ command: \"partners.DeletePartner\", input: expect.objectContaining({\"id\":\"pt-003\"}) }));"
        ),
        "{spec}"
    );
    // The replaced view is routed by its exact path, not every view its name prefixes.
    assert!(
        spec.contains(
            "await page.route((url) => url.pathname.endsWith(\"/views/partners.Page\"), (route) => route.fulfill({ json: {"
        ),
        "{spec}"
    );
    assert!(!spec.contains("**/views/"), "{spec}");
    // Views derived from it follow it, as in the terminal: `same_as` answers the same data,
    // `by_id_from` narrows it to the asked key.
    assert!(
        spec.contains("await page.route((url) => url.pathname.endsWith(\"/views/partners.Top\"), (route) => route.fulfill({ json: {"),
        "{spec}"
    );
    assert!(
        spec.contains("await page.route((url) => url.pathname.endsWith(\"/views/partners.ById\"), (route) => { const params = JSON.parse("),
        "{spec}"
    );
    assert!(
        spec.contains(".filter((row) => [\"id\"].every((key) => String(row[key]) === String(params[key] ?? params.id)))"),
        "{spec}"
    );
    // A view no replaced view feeds is not routed.
    assert!(!spec.contains("/views/deals.ById"), "{spec}");
    // A test with neither routes nothing.
    let stale = spec
        .split("test(\"a stale channel marks its section until it is live again\"")
        .nth(1)
        .and_then(|rest| rest.split("\n  });\n").next())
        .expect("the stale test");
    assert!(!stale.contains("page.route"), "{stale}");
}

/// `choose` at a form field drives the field's own choice control, as it does a filter bar's.
#[test]
fn choose_at_a_form_choice_field_picks_in_its_choice_control() {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let text = "format: ess-ui-test/1\ndocument: ui.yaml\ntests:\n- name: c\n  steps:\n\
                \x20 - open: partners.list\n\
                \x20 - act: pages/partners.list/header/actions/create\n\
                \x20 - choose: {at: pages/partners.list/overlays/create/fields/tier, option: gold}\n\
                \x20 - choose: {at: pages/partners.list/overlays/create/fields/tier/choice, option: silver}\n";
    let file = ess_ui_test::parse_str(text, &example_dir().join("inline.yaml")).expect("parses");
    let spec = ess_ui_test::playwright(&[file], &document);
    for wanted in [
        "await page.locator('[data-ui-path=\"pages/partners.list/overlays/create/fields/tier\"]').locator(\"select\").selectOption({ label: \"gold\" });",
        "await page.locator('[data-ui-path=\"pages/partners.list/overlays/create/fields/tier/choice\"]').locator(\"select\").selectOption({ label: \"silver\" });",
    ] {
        assert!(spec.contains(wanted), "{wanted}\n\n{spec}");
    }
    assert!(!spec.contains("test.fixme"), "{spec}");
}

/// A number of four or more digits in expected text matches the browser's grouped spelling too,
/// as it does in the terminal; text without such a number stays a plain string.
#[test]
fn expected_text_matches_numbers_with_or_without_grouping() {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let text = "format: ess-ui-test/1\ndocument: ui.yaml\ntests:\n- name: n\n  steps:\n\
                \x20 - open: partners.list\n\
                \x20 - expect: {at: pages/partners.list/sections/list/rows/pt-003, text: '150,000 EUR (x)'}\n\
                \x20 - expect: {at: pages/partners.list/sections/list/rows/pt-003, not_text: '1840'}\n\
                \x20 - expect: {at: pages/partners.list/sections/list/rows/pt-003, text: 'Cedar 12'}\n";
    let file = ess_ui_test::parse_str(text, &example_dir().join("inline.yaml")).expect("parses");
    let spec = ess_ui_test::playwright(&[file], &document);
    let row = "page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003\"]')";
    for wanted in [
        format!("await expect({row}).toContainText(new RegExp(\"150[,\\\\u00a0\\\\u202f]?000 EUR \\\\(x\\\\)\"));"),
        format!("await expect({row}).not.toContainText(new RegExp(\"1[,\\\\u00a0\\\\u202f]?840\"));"),
        format!("await expect({row}).toContainText(\"Cedar 12\");"),
    ] {
        assert!(spec.contains(&wanted), "{wanted}\n\n{spec}");
    }
}
