//! The same test files, emitted as a Playwright spec for the generated React project, selecting
//! every node by `[data-ui-path="…"]`. The spec is generated text; no browser runs here.

use std::path::{Path, PathBuf};

fn example_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../examples/partner-portal")
}

fn spec() -> String {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let files: Vec<ess_ui_test::TestFile> = ["partners-list.yaml", "live.yaml", "stale.yaml"]
        .iter()
        .map(|name| ess_ui_test::load(&example_dir().join("tests").join(name)).expect("loads"))
        .collect();
    ess_ui_test::playwright(&files, &document)
}

#[test]
fn every_test_becomes_a_playwright_test() {
    let spec = spec();
    assert!(
        spec.starts_with("// Generated by `ess ui test --playwright`"),
        "{spec}"
    );
    assert!(
        spec.contains("import { test, expect } from \"@playwright/test\";"),
        "{spec}"
    );
    for name in [
        "the search narrows the partner list",
        "deleting a partner asks first and sends the command",
        "a live ticket lands in the filtered list",
        "stale_after marks a channel that stays reconnecting",
    ] {
        assert!(
            spec.contains(&format!("test(\"{name}\", async ({{ page }}) => {{")),
            "{name}\n{spec}"
        );
    }
    // Deterministic: the same files give the same bytes.
    assert_eq!(spec, self::spec());
}

#[test]
fn steps_select_by_node_path_and_open_pages_by_route() {
    let spec = spec();
    for wanted in [
        // open: the React route of the page.
        "await page.goto(\"/partners/list\");",
        // type into a filter bar's search.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/filters\"] input[type=\"search\"]').pressSequentially(\"cedar\");",
        // choose an option of a filter-bar choice.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/filters/choices/tier\"]').getByRole(\"button\", { name: \"gold\", exact: true }).click();",
        // act on a row action, addressed under its row.
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003/row_actions/delete\"]').click();",
        // act on an overlay: its primary button.
        "await page.locator('[data-ui-path=\"pages/partners.list/overlays/delete\"] button.ui-tone-danger, [data-ui-path=\"pages/partners.list/overlays/delete\"] button.ui-tone-primary').last().click();",
        // expect text.
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003\"]')).toContainText(\"Cedar Partners\");",
        // expect rows, by key and in order.
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-row')).toHaveCount(1);",
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-row').nth(0)).toHaveAttribute(\"data-ui-path\", \"pages/partners.list/sections/list/rows/pt-003\");",
        // expect section state.
        "await expect(page.locator('[data-ui-path=\"pages/overview/sections/kpis\"] .ui-stale-badge')).toBeVisible();",
        "await expect(page.locator('[data-ui-path=\"pages/overview/sections/kpis\"]')).toHaveAttribute(\"data-status\", \"ready\");",
        // time is the page's clock.
        "await page.clock.install({ time: 0 });",
        "await page.clock.runFor(25000);",
        "await page.clock.runFor(500);",
    ] {
        assert!(spec.contains(wanted), "{wanted}\n\n{spec}");
    }
}

/// `select` of a row moves the focus the way the terminal's cursor does, without a pointer click
/// that could land on a link inside the row; `page` goes to an absolute page and waits for it.
#[test]
fn select_focuses_a_row_and_page_reaches_an_absolute_page() {
    let document = ess_ui::load_path(&example_dir().join("ui.yaml")).expect("the example loads");
    let text = "format: ess-ui-test/1\ndocument: ui.yaml\ntests:\n- name: s\n  steps:\n\
                \x20 - open: partners.list\n\
                \x20 - select: pages/partners.list/sections/list/rows/pt-003/row_actions/delete\n\
                \x20 - page: {at: pages/partners.list/sections/list, to: 2}\n";
    let file = ess_ui_test::parse_str(text, &example_dir().join("inline.yaml")).expect("parses");
    let spec = ess_ui_test::playwright(&[file], &document);
    let row = "page.locator('[data-ui-path=\"pages/partners.list/sections/list/rows/pt-003\"]')";
    for wanted in [
        format!("await {row}.dispatchEvent(\"click\");"),
        format!("await expect({row}).toHaveClass(/(^|\\s)ui-focused(\\s|$)/);"),
        "await page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-pager').locator(\"button\").last().click();".to_owned(),
        "await expect(page.locator('[data-ui-path=\"pages/partners.list/sections/list\"] .ui-pager').locator(\"span\")).toHaveText(\"Page 2\");".to_owned(),
    ] {
        assert!(spec.contains(&wanted), "{wanted}\n\n{spec}");
    }
    assert!(!spec.contains(&format!("await {row}.click();")), "{spec}");
}

#[test]
fn commands_and_fixture_overrides_go_through_the_http_adapter_routes() {
    let spec = spec();
    assert!(
        spec.contains("await page.route(\"**/commands/**\""),
        "{spec}"
    );
    assert!(
        spec.contains(
            "expect(commands).toContainEqual(expect.objectContaining({ command: \"partners.DeletePartner\", input: expect.objectContaining({\"id\":\"pt-003\"}) }));"
        ),
        "{spec}"
    );
    // The replaced view is routed by its exact path, not every view its name prefixes.
    assert!(
        spec.contains(
            "await page.route((url) => url.pathname.endsWith(\"/views/partners.Page\"), (route) => route.fulfill({ json: {"
        ),
        "{spec}"
    );
    assert!(!spec.contains("**/views/"), "{spec}");
    // Views derived from it follow it, as in the terminal: `same_as` answers the same data,
    // `by_id_from` narrows it to the asked key.
    assert!(
        spec.contains("await page.route((url) => url.pathname.endsWith(\"/views/partners.Top\"), (route) => route.fulfill({ json: {"),
        "{spec}"
    );
    assert!(
        spec.contains("await page.route((url) => url.pathname.endsWith(\"/views/partners.ById\"), (route) => { const params = JSON.parse("),
        "{spec}"
    );
    assert!(
        spec.contains(".filter((row) => [\"id\"].every((key) => String(row[key]) === String(params[key] ?? params.id)))"),
        "{spec}"
    );
    // A view no replaced view feeds is not routed.
    assert!(!spec.contains("/views/deals.ById"), "{spec}");
    // A test with neither routes nothing.
    let stale = spec
        .split("test(\"a stale channel marks its section until it is live again\"")
        .nth(1)
        .and_then(|rest| rest.split("\n  });\n").next())
        .expect("the stale test");
    assert!(!stale.contains("page.route"), "{stale}");
}

/// A front desk over the gatepass surface, with a view derived by id from the expected list.
const DESK: &str = "format: ess-ui/1
app: desk
model: gatepass
placement_profile: fat
fixtures:
  derived:
    visit.VisitById: {by_id_from: visit.ExpectedVisits, key: id}
shells: {app: {regions: {main: {kind: page_outlet}}}}
navigation: {home: desk, sections: [{name: all, pages: [desk]}]}
pages:
  desk:
    kind: detail_page
    title: Desk
    sections:
      - name: expected
        component: collection
        reads: visit.ExpectedVisits
        actions: [{name: register, does: visit.RegisterVisit, label: Register}]
      - name: one
        component: record
        reads: {view: visit.VisitById, params: {id: \"'v-1'\"}}
";

/// The binding `ess_ui_check::binding` gives the desk, with a query parameter on `VisitById`
/// carried under another key than its name, so the routes below show which one they read.
const BINDING: &str = r#"{
  "system": "gatepass",
  "components": {
    "pass-service": {
      "views": {
        "gatepass.visit.ExpectedVisits": {"path": "/visits/views/expected", "params": []},
        "gatepass.visit.VisitById": {
          "path": "/visits/views/by-id",
          "params": [{"name": "id", "wire": "visit", "required": true, "scalar": "Uuid"}]
        }
      },
      "commands": {
        "gatepass.visit.RegisterVisit": {
          "path": "/visits/commands/register-visit",
          "body_required": true,
          "errors": {"gatepass.visit.InvalidVisitLength": {"status": 422, "display": "InvalidVisitLength"}}
        }
      }
    }
  },
  "names": {
    "visit.ExpectedVisits": "gatepass.visit.ExpectedVisits",
    "visit.RegisterVisit": "gatepass.visit.RegisterVisit",
    "visit.VisitById": "gatepass.visit.VisitById"
  }
}"#;

#[test]
fn commands_and_fixture_overrides_go_through_the_bound_routes() {
    let document = ess_ui::load_str(DESK).unwrap_or_else(|error| panic!("{error}"));
    let binding: ess_ui::binding::Binding =
        serde_json::from_str(BINDING).expect("the binding parses");
    let text = "format: ess-ui-test/1\ndocument: desk.yaml\ntests:\n\
                - name: registering sends the command\n  fixtures:\n    views:\n\
                \x20     visit.ExpectedVisits: {rows: [{id: v-1, visitor: Ada}]}\n  steps:\n\
                \x20 - open: desk\n\
                \x20 - act: pages/desk/sections/expected/actions/register\n\
                \x20 - expect_command: {command: visit.RegisterVisit, input: {visitor: Ada}}\n";
    // Named beside the crate; nothing is read from or written to that path.
    let file =
        ess_ui_test::parse_str(text, &example_dir().join("tests/desk.test.yaml")).expect("parses");
    let spec = ess_ui_test::playwright_bound(&[file], &document, &binding);
    for wanted in [
        // The command is routed at its bound path and answered as an accepted declared branch.
        "await page.route((url) => url.pathname.endsWith(\"/visits/commands/register-visit\"), async (route) => {",
        "  commands.push({ command: \"gatepass.visit.RegisterVisit\", input: route.request().postDataJSON() });",
        "  await route.fulfill({ status: 202, json: { outcome: \"accepted\", published: [] } });",
        // The expected command is the qualified name the route records.
        "expect(commands).toContainEqual(expect.objectContaining({ command: \"gatepass.visit.RegisterVisit\", input: expect.objectContaining({\"visitor\":\"Ada\"}) }));",
        // The replaced view at its bound path.
        "await page.route((url) => url.pathname.endsWith(\"/visits/views/expected\"), (route) => route.fulfill({ json: {",
        // The view derived from it at its own path, narrowed by the parameter under its query key.
        "await page.route((url) => url.pathname.endsWith(\"/visits/views/by-id\"), (route) => { const query = new URL(route.request().url()).searchParams; const params = Object.fromEntries([[\"id\",\"visit\"]].map(([name, wire]) => [name, query.get(wire)]));",
    ] {
        assert!(spec.contains(wanted), "{wanted}\n\n{spec}");
    }
    for unwanted in ["/views/visit.", "/commands/**", "\"params\""] {
        assert!(!spec.contains(unwanted), "{unwanted}\n\n{spec}");
    }
    // The plain spec of the same files is unchanged by the binding's existence.
    assert!(ess_ui_test::playwright(&[], &document).contains("route /views/…"));
}
