//! Native Rust records and explicit wire serialization from the shared structural plan.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use super::native::{nullable, string_values};

use super::{
    children, finding, Field, Finding, Node, Plan, Realization, Refused, Report, Shape,
    TargetConfiguration, UnionMode,
};

const DERIVE: &str =
    "#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]\n";
const HELPERS: &str = include_str!("rust_support.rs.txt");

pub(super) fn emit(plan: &Plan, package: &str) -> Result<Realization, Refused> {
    if !package_name(package) {
        return Err(Refused(vec![finding("/", "rust_package", "use a non-reserved lowercase Cargo package name containing letters, digits, underscores or hyphens")]));
    }
    let mut emitter = Emitter {
        plan,
        output: BTreeMap::new(),
        allocated: plan.names.values().cloned().collect(),
        anonymous: BTreeMap::new(),
        errors: BTreeSet::new(),
        report: plan.report(TargetConfiguration::Rust {
            package: package.to_owned(),
        }),
    };
    if emitter.allocated.contains("EssNever") {
        emitter.errors.insert(finding(
            "/",
            "rust_helper_collision",
            "EssNever is reserved by the Rust target",
        ));
    }
    for (name, node) in &plan.definitions {
        emitter.account(node);
        emitter.named(&plan.names[name], node);
    }
    if !emitter.errors.is_empty() {
        return Err(Refused(emitter.errors.into_iter().collect()));
    }
    let mut output = format!("// @generated by ESS {}; do not edit.\n// Source SHA-256: {}\n// {}\n// Structural serialization only; see types-report.json for runtime obligations.\n\n{HELPERS}\n",
        env!("CARGO_PKG_VERSION"), plan.source_digest, plan.input_comment());
    for declaration in emitter.output.values() {
        output.push_str(declaration);
        output.push('\n');
    }
    let manifest = format!("[package]\nname = {package:?}\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\npath = \"types.rs\"\n\n[dependencies]\nserde = {{ version = \"=1.0.229\", features = [\"derive\"] }}\nserde_json = {{ version = \"=1.0.151\", features = [\"arbitrary_precision\"] }}\n\n[workspace]\n");
    Ok(Realization {
        declarations: output,
        report: emitter.report,
        supporting: BTreeMap::from([("Cargo.toml".to_owned(), manifest)]),
    })
}

struct Emitter<'a> {
    plan: &'a Plan,
    output: BTreeMap<String, String>,
    allocated: BTreeSet<String>,
    anonymous: BTreeMap<String, String>,
    errors: BTreeSet<Finding>,
    report: Report,
}

impl Emitter<'_> {
    fn account(&mut self, node: &Node) {
        match &node.shape {
            Shape::Integer => {
                self.report.obligations.insert(finding(&node.pointer, "integer", "serde_json::Number retains exact JSON numbers but does not enforce integrality; validate the source constraint"));
            }
            Shape::Union { mode, .. } => {
                if matches!(mode, UnionMode::OneOf) {
                    self.report.obligations.insert(finding(
                        &node.pointer,
                        "oneOf",
                        "validate exclusive branch membership against the source schema",
                    ));
                }
                if matches!(mode, UnionMode::AnyOf | UnionMode::OneOf) {
                    self.report.obligations.insert(finding(&node.pointer, "untagged_selection", "native union decoding chooses the first structurally decodable alternative; it does not certify source branch constraints or external dispatch"));
                }
            }
            _ => {}
        }
        for child in children(node) {
            self.account(child);
        }
    }

    fn named(&mut self, name: &str, node: &Node) {
        let mut output = format!("// Source: {:?}\n", node.pointer);
        if !matches!(node.shape, Shape::Ref(_)) {
            if let Some(values) = string_values(node, self.plan, &mut BTreeSet::new()) {
                output.push_str(DERIVE);
                writeln!(output, "pub enum {name} {{").expect("String write");
                for (index, value) in values.iter().enumerate() {
                    writeln!(output, "    #[serde(rename = {value:?})]\n    V{index},")
                        .expect("String write");
                }
                output.push_str("}\n");
                self.output.insert(name.to_owned(), output);
                return;
            }
        }
        match &node.shape {
            Shape::Object { fields, additional } => {
                self.record(&mut output, name, fields, additional, &node.pointer);
            }
            Shape::Union { variants, .. } if nullable(variants).is_none() => {
                self.union(&mut output, name, variants);
            }
            Shape::Array {
                prefix,
                minimum,
                maximum,
                ..
            } if !prefix.is_empty() => {
                if *minimum != prefix.len() as u64
                    || *maximum != Some(*minimum)
                    || prefix.len() > 16
                {
                    self.errors.insert(finding(
                        &node.pointer,
                        "rust_prefix_layout",
                        "Rust currently requires an exact prefix tuple of at most 16 positions",
                    ));
                } else {
                    let items = prefix
                        .iter()
                        .map(|item| format!("pub {}", self.ty(item)))
                        .collect::<Vec<_>>();
                    output.push_str(DERIVE);
                    writeln!(output, "pub struct {name}({});", items.join(", "))
                        .expect("String write");
                }
            }
            Shape::Intersection(_) | Shape::Literal(_) => {
                self.errors.insert(finding(
                    &node.pointer,
                    "rust_intersection_or_literal",
                    "this native intersection or non-string literal needs an explicit Rust mapping",
                ));
            }
            _ => {
                let ty = self.ty(node);
                output.push_str(DERIVE);
                writeln!(
                    output,
                    "#[serde(transparent)]\npub struct {name}(pub {ty});"
                )
                .expect("String write");
            }
        }
        self.output.insert(name.to_owned(), output);
    }

    fn record(
        &mut self,
        out: &mut String,
        name: &str,
        fields: &BTreeMap<String, Field>,
        additional: &Node,
        pointer: &str,
    ) {
        out.push_str(DERIVE);
        let closed = matches!(additional.shape, Shape::Never);
        if closed {
            out.push_str("#[serde(deny_unknown_fields)]\n");
        }
        writeln!(out, "pub struct {name} {{").expect("String write");
        let mut allocated = BTreeSet::new();
        if !closed {
            allocated.insert("ess_extra".to_owned());
        }
        for (wire, field) in fields {
            let field_name = field_name(wire);
            if field_name.is_empty()
                || field_name.as_bytes()[0].is_ascii_digit()
                || !allocated.insert(field_name.clone())
            {
                self.errors.insert(finding(
                    &field.value.pointer,
                    "rust_field_collision",
                    "field name is invalid or collides after Rust normalization",
                ));
            }
            let ty = self.ty(&field.value);
            writeln!(out, "    #[serde(rename = {wire:?})]").expect("String write");
            if field.required {
                writeln!(out, "    #[serde(deserialize_with = \"ess_required\")]\n    pub {field_name}: {ty},").expect("String write");
            } else {
                writeln!(out, "    #[serde(default, skip_serializing_if = \"EssPresence::is_absent\")]\n    pub {field_name}: EssPresence<{ty}>,").expect("String write");
            }
        }
        if closed {
            out.push_str("}\n");
            return;
        }
        let extra = self.ty(additional);
        writeln!(out, "    #[serde(flatten, serialize_with = \"{name}::ess_serialize_extra\")]\n    pub ess_extra: ::std::collections::BTreeMap<::std::string::String, {extra}>,\n}}").expect("String write");
        writeln!(out, "impl {name} {{\n    fn ess_serialize_extra<S: ::serde::Serializer>(values: &::std::collections::BTreeMap<::std::string::String, {extra}>, serializer: S) -> Result<S::Ok, S::Error> {{").expect("String write");
        if !fields.is_empty() {
            let keys = fields
                .keys()
                .map(|key| format!("{key:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "        if [{keys}].iter().any(|key| values.contains_key(*key)) {{\n            return Err(::serde::ser::Error::custom(\"additional key collides with a declared field\"));\n        }}").expect("String write");
        }
        out.push_str("        ::serde::Serialize::serialize(values, serializer)\n    }\n}\n");
        self.report.obligations.insert(finding(pointer, "open_object_storage", "preserve ess_extra when constructing or transforming the record; serialization rejects declared-key collisions"));
    }

    fn union(&mut self, out: &mut String, name: &str, variants: &[Node]) {
        let types = variants
            .iter()
            .map(|variant| self.ty(variant))
            .collect::<Vec<_>>();
        writeln!(out, "#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]\n#[serde(untagged)]\npub enum {name} {{").expect("String write");
        for (index, ty) in types.iter().enumerate() {
            writeln!(out, "    V{index}({ty}),").expect("String write");
        }
        out.push_str("}\n");
        writeln!(out, "impl<'de> ::serde::Deserialize<'de> for {name} {{\n    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let value = <::serde_json::Value as ::serde::Deserialize>::deserialize(deserializer)?;").expect("String write");
        for (index, ty) in types.iter().enumerate() {
            writeln!(out, "        if let Ok(decoded) = ::serde_json::from_value::<{ty}>(value.clone()) {{\n            return Ok(Self::V{index}(decoded));\n        }}").expect("String write");
        }
        out.push_str("        Err(::serde::de::Error::custom(\"no structurally decodable union alternative\"))\n    }\n}\n");
    }

    fn ty(&mut self, node: &Node) -> String {
        match &node.shape {
            Shape::Json => "::serde_json::Value".to_owned(),
            Shape::Never => "EssNever".to_owned(),
            Shape::Null => "()".to_owned(),
            Shape::Boolean => "bool".to_owned(),
            Shape::String => "::std::string::String".to_owned(),
            Shape::Number | Shape::Integer => "::serde_json::Number".to_owned(),
            Shape::Ref(name) => format!("::std::boxed::Box<{}>", self.plan.names[name]),
            Shape::Array { prefix, items, .. } if prefix.is_empty() => {
                format!("::std::vec::Vec<{}>", self.ty(items))
            }
            Shape::Union { variants, .. } if nullable(variants).is_some() => {
                format!(
                    "::std::option::Option<{}>",
                    self.ty(nullable(variants).expect("nullable union"))
                )
            }
            _ => self.anonymous(node),
        }
    }

    fn anonymous(&mut self, node: &Node) -> String {
        let kind = match &node.shape {
            Shape::Object { .. } => "object",
            Shape::Array { .. } => "array",
            Shape::Union { .. } => "union",
            Shape::Intersection(_) => "intersection",
            Shape::Literal(_) => "literal",
            _ => "scalar",
        };
        let identity = format!("{}#{kind}", node.pointer);
        if let Some(name) = self.anonymous.get(&identity) {
            return name.clone();
        }
        let digest = crate::bundle::source_digest(&identity);
        let name = format!("EssShape{}", &digest[..16]);
        if !self.allocated.insert(name.clone()) {
            self.errors.insert(finding(
                &node.pointer,
                "rust_declaration_collision",
                "anonymous declaration collides with an allocated native name",
            ));
            return "EssNever".to_owned();
        }
        self.anonymous.insert(identity, name.clone());
        self.named(&name, node);
        name
    }
}

fn field_name(wire: &str) -> String {
    let mut result = String::new();
    let mut lower = false;
    for c in wire.chars() {
        if !c.is_ascii_alphanumeric() && c != '_' {
            if !result.ends_with('_') {
                result.push('_');
            }
            lower = false;
        } else {
            if c.is_ascii_uppercase() && lower {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
            lower = c.is_ascii_lowercase() || c.is_ascii_digit();
        }
    }
    let name = result.trim_matches('_');
    match name {
        "self" | "super" | "crate" => format!("{name}_value"),
        "as" | "async" | "await" | "break" | "const" | "continue" | "dyn" | "else" | "enum"
        | "extern" | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match"
        | "mod" | "move" | "mut" | "pub" | "ref" | "return" | "static" | "struct" | "trait"
        | "true" | "type" | "unsafe" | "use" | "where" | "while" | "abstract" | "become"
        | "box" | "do" | "final" | "macro" | "override" | "priv" | "typeof" | "unsized"
        | "virtual" | "yield" | "try" | "gen" => format!("r#{name}"),
        _ => name.to_owned(),
    }
}

pub(super) fn package_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name.as_bytes()[0].is_ascii_lowercase()
        && name
            .bytes()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == b'_' || c == b'-')
        && ![
            "self",
            "super",
            "crate",
            "std",
            "core",
            "alloc",
            "serde",
            "serde_json",
        ]
        .contains(&name)
}
