//! Native Rust records and explicit wire serialization from the shared structural plan.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use super::native::{nullable, string_values};

use super::{
    children, finding, Field, Finding, IntegerWidth, Node, Plan, Realization, Refused, Report,
    Shape, TargetConfiguration, UnionMode,
};

const DERIVE: &str =
    "#[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]\n";
const HELPERS: &str = include_str!("rust_support.rs.txt");
/// The default-on crate feature that turns on `serde_json/arbitrary_precision`, declared only
/// where a realized type holds JSON numbers in `serde_json` (beyond10x/ess#483).
const EXACT_NUMBERS: &str = "exact-numbers";
const EXACT_NUMBERS_RULE: &str = "rust_exact_numbers";
const EXACT_NUMBERS_DETAIL: &str = "this value holds JSON numbers in serde_json; the generated crate's default-on `exact-numbers` feature enables serde_json/arbitrary_precision, and a consumer that turns default features off gets these numbers as binary64";

pub(super) fn emit(plan: &Plan, package: &str) -> Result<Realization, Refused> {
    if !package_name(package) {
        return Err(Refused(vec![finding("/", "rust_package", "use a non-reserved lowercase Cargo package name containing letters, digits, underscores or hyphens")]));
    }
    let mut emitter = Emitter {
        plan,
        output: BTreeMap::new(),
        allocated: plan.names.values().cloned().collect(),
        anonymous: BTreeMap::new(),
        errors: BTreeSet::new(),
        exact: BTreeSet::new(),
        report: plan.report(TargetConfiguration::Rust {
            package: package.to_owned(),
        }),
    };
    if emitter.allocated.contains("EssNever") {
        emitter.errors.insert(finding(
            "/",
            "rust_helper_collision",
            "EssNever is reserved by the Rust target",
        ));
    }
    if plan.has_timestamp() && !emitter.allocated.insert("EssTimestamp".to_owned()) {
        emitter
            .errors
            .insert(finding("/", "rust_helper_collision", "EssTimestamp"));
    }
    if !plan.binary64.is_empty() {
        for helper in ["EssBinary64", "EssBinary64Error"] {
            if !emitter.allocated.insert(helper.to_owned()) {
                emitter
                    .errors
                    .insert(finding("/", "rust_helper_collision", helper));
            }
        }
    }
    for (name, node) in &plan.definitions {
        emitter.account(node);
        emitter.named(&plan.names[name], node);
    }
    if !emitter.errors.is_empty() {
        return Err(Refused(emitter.errors.into_iter().collect()));
    }
    for at in &emitter.exact {
        emitter
            .report
            .obligations
            .insert(finding(at, EXACT_NUMBERS_RULE, EXACT_NUMBERS_DETAIL));
    }
    let mut output = format!("// @generated by ESS {}; do not edit.\n// Source SHA-256: {}\n// {}\n// Structural serialization only; see types-report.json for runtime obligations.\n\n{HELPERS}\n",
        env!("CARGO_PKG_VERSION"), plan.source_digest, plan.input_comment());
    if plan.has_timestamp() {
        output.push_str(include_str!("rust_timestamp.rs.txt"));
        output.push('\n');
    }
    if !plan.binary64.is_empty() {
        output.push_str(include_str!("rust_binary64.rs.txt"));
        output.push('\n');
    }
    for declaration in emitter.output.values() {
        output.push_str(declaration);
        output.push('\n');
    }
    let raw_feature = if plan.binary64.is_empty() {
        ""
    } else {
        ", features = [\"raw_value\"]"
    };
    let time = if plan.has_timestamp() {
        "time = { version = \"=0.3.45\", features = [\"formatting\", \"parsing\"] }\n"
    } else {
        ""
    };
    // Cargo unifies features across a consumer's graph, so the dependency line never names
    // `arbitrary_precision`; the crate feature lets a consumer turn it off.
    let features = if emitter.exact.is_empty() {
        String::new()
    } else {
        format!("\n[features]\ndefault = [\"{EXACT_NUMBERS}\"]\n{EXACT_NUMBERS} = [\"serde_json/arbitrary_precision\"]\n")
    };
    let manifest = format!("[package]\nname = {package:?}\nversion = \"0.0.0\"\nedition = \"2021\"\npublish = false\n\n[lib]\npath = \"types.rs\"\n\n[dependencies]\nserde = {{ version = \"=1.0.229\", features = [\"derive\"] }}\nserde_json = {{ version = \"=1.0.151\"{raw_feature} }}\n{time}{features}\n[workspace]\n");
    Ok(Realization {
        declarations: output,
        report: emitter.report,
        supporting: BTreeMap::from([("Cargo.toml".to_owned(), manifest)]),
    })
}

struct Emitter<'a> {
    plan: &'a Plan,
    output: BTreeMap<String, String>,
    allocated: BTreeSet<String>,
    anonymous: BTreeMap<String, String>,
    errors: BTreeSet<Finding>,
    /// Source pointers whose emitted code holds JSON numbers in `serde_json::Number` or
    /// `serde_json::Value`, the values `arbitrary_precision` changes.
    exact: BTreeSet<String>,
    report: Report,
}

impl Emitter<'_> {
    fn account(&mut self, node: &Node) {
        match &node.shape {
            Shape::Integer => {
                self.report.obligations.insert(finding(&node.pointer, "integer", "serde_json::Number holds exact JSON numbers with the default `exact-numbers` feature and binary64 without it, and does not enforce integrality; validate the source constraint"));
            }
            Shape::Union { mode, .. } => {
                if matches!(mode, UnionMode::OneOf) {
                    self.report.obligations.insert(finding(
                        &node.pointer,
                        "oneOf",
                        "validate exclusive branch membership against the source schema",
                    ));
                }
                if matches!(mode, UnionMode::AnyOf | UnionMode::OneOf) {
                    self.report.obligations.insert(finding(&node.pointer, "untagged_selection", "native union decoding chooses the first structurally decodable alternative; it does not certify source branch constraints or external dispatch"));
                }
            }
            _ => {}
        }
        for child in children(node) {
            self.account(child);
        }
    }

    fn named(&mut self, name: &str, node: &Node) {
        let mut output = format!("// Source: {:?}\n", node.pointer);
        if !matches!(node.shape, Shape::Ref(_)) {
            if let Some(values) = string_values(node, self.plan, &mut BTreeSet::new()) {
                output.push_str(DERIVE);
                writeln!(output, "pub enum {name} {{").expect("String write");
                for (index, value) in values.iter().enumerate() {
                    writeln!(output, "    #[serde(rename = {value:?})]\n    V{index},")
                        .expect("String write");
                }
                output.push_str("}\n");
                if let Some(attributes) = self.plan.attributes.get(&node.pointer) {
                    accessors(&mut output, name, &values, attributes);
                }
                self.output.insert(name.to_owned(), output);
                return;
            }
        }
        match &node.shape {
            Shape::Object { fields, additional } => {
                self.record(&mut output, name, fields, additional, &node.pointer);
            }
            Shape::Union { variants, .. } if nullable(variants).is_none() => {
                self.union(&mut output, name, variants, &node.pointer);
            }
            Shape::Array {
                prefix,
                minimum,
                maximum,
                ..
            } if !prefix.is_empty() => {
                if *minimum != prefix.len() as u64
                    || *maximum != Some(*minimum)
                    || prefix.len() > 16
                {
                    self.errors.insert(finding(
                        &node.pointer,
                        "rust_prefix_layout",
                        "Rust currently requires an exact prefix tuple of at most 16 positions",
                    ));
                } else {
                    let items = prefix
                        .iter()
                        .map(|item| format!("pub {}", self.ty(item)))
                        .collect::<Vec<_>>();
                    output.push_str(DERIVE);
                    writeln!(output, "pub struct {name}({});", items.join(", "))
                        .expect("String write");
                }
            }
            Shape::Intersection(_) | Shape::Literal(_) => {
                self.errors.insert(finding(
                    &node.pointer,
                    "rust_intersection_or_literal",
                    "this native intersection or non-string literal needs an explicit Rust mapping",
                ));
            }
            _ => {
                let ty = self.ty(node);
                output.push_str(DERIVE);
                writeln!(
                    output,
                    "#[serde(transparent)]\npub struct {name}(pub {ty});"
                )
                .expect("String write");
                // A newtype fixed to one integer carries it, so no caller has to know it
                // (beyond10x/ess#408).
                if let Some(value) = self.plan.constants.get(&node.pointer) {
                    writeln!(
                        output,
                        "\nimpl {name} {{\n    /// The one value this type admits.\n    pub const VALUE: {ty} = {value};\n}}\n\nimpl ::std::default::Default for {name} {{\n    fn default() -> Self {{\n        Self(Self::VALUE)\n    }}\n}}"
                    )
                    .expect("String write");
                }
            }
        }
        self.output.insert(name.to_owned(), output);
    }

    fn record(
        &mut self,
        out: &mut String,
        name: &str,
        fields: &BTreeMap<String, Field>,
        additional: &Node,
        pointer: &str,
    ) {
        let raw_map = self.plan.reaches_binary64(additional);
        if raw_map && !fields.is_empty() {
            self.errors.insert(finding(&additional.pointer, "rust_binary64_open_record", "Binary64 additional values on a record with declared fields require raw-token object decoding, which this Rust target does not support"));
            return;
        }
        out.push_str(if raw_map {
            "#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]\n"
        } else {
            DERIVE
        });
        let closed = matches!(additional.shape, Shape::Never);
        if closed {
            out.push_str("#[serde(deny_unknown_fields)]\n");
        }
        writeln!(out, "pub struct {name} {{").expect("String write");
        let mut allocated = BTreeSet::new();
        if !closed {
            allocated.insert("ess_extra".to_owned());
        }
        for (wire, field) in fields {
            let field_name = field_name(wire);
            if field_name.is_empty()
                || field_name.as_bytes()[0].is_ascii_digit()
                || !allocated.insert(field_name.clone())
            {
                self.errors.insert(finding(
                    &field.value.pointer,
                    "rust_field_collision",
                    "field name is invalid or collides after Rust normalization",
                ));
            }
            let ty = self.ty(&field.value);
            writeln!(out, "    #[serde(rename = {wire:?})]").expect("String write");
            if field.required {
                writeln!(out, "    #[serde(deserialize_with = \"ess_required\")]\n    pub {field_name}: {ty},").expect("String write");
            } else {
                writeln!(out, "    #[serde(default, skip_serializing_if = \"EssPresence::is_absent\")]\n    pub {field_name}: EssPresence<{ty}>,").expect("String write");
            }
        }
        if closed {
            out.push_str("}\n");
            return;
        }
        let extra = self.ty(additional);
        writeln!(out, "    #[serde(flatten, serialize_with = \"{name}::ess_serialize_extra\")]\n    pub ess_extra: ::std::collections::BTreeMap<::std::string::String, {extra}>,\n}}").expect("String write");
        writeln!(out, "impl {name} {{\n    fn ess_serialize_extra<S: ::serde::Serializer>(values: &::std::collections::BTreeMap<::std::string::String, {extra}>, serializer: S) -> Result<S::Ok, S::Error> {{").expect("String write");
        if !fields.is_empty() {
            let keys = fields
                .keys()
                .map(|key| format!("{key:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(out, "        if [{keys}].iter().any(|key| values.contains_key(*key)) {{\n            return Err(::serde::ser::Error::custom(\"additional key collides with a declared field\"));\n        }}").expect("String write");
        }
        out.push_str("        ::serde::Serialize::serialize(values, serializer)\n    }\n}\n");
        if raw_map {
            writeln!(out, "impl<'de> ::serde::Deserialize<'de> for {name} {{\n    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let ess_extra = <::std::collections::BTreeMap<::std::string::String, {extra}> as ::serde::Deserialize>::deserialize(deserializer)?;\n        Ok(Self {{ ess_extra }})\n    }}\n}}").expect("String write");
        }
        self.report.obligations.insert(finding(pointer, "open_object_storage", "preserve ess_extra when constructing or transforming the record; serialization rejects declared-key collisions"));
    }

    fn union(&mut self, out: &mut String, name: &str, variants: &[Node], pointer: &str) {
        let types = variants
            .iter()
            .map(|variant| self.ty(variant))
            .collect::<Vec<_>>();
        writeln!(out, "#[derive(Debug, Clone, PartialEq, ::serde::Serialize)]\n#[serde(untagged)]\npub enum {name} {{").expect("String write");
        for (index, ty) in types.iter().enumerate() {
            writeln!(out, "    V{index}({ty}),").expect("String write");
        }
        out.push_str("}\n");
        let raw = variants
            .iter()
            .any(|variant| self.plan.reaches_binary64(variant));
        let value_type = if raw {
            "::std::boxed::Box<::serde_json::value::RawValue>"
        } else {
            // A number an alternative can hold passes through this `Value` first, and decodes
            // differently with and without `arbitrary_precision` (`-0` into an `i32`, for one).
            if variants
                .iter()
                .any(|variant| holds_number(self.plan, variant))
            {
                self.exact.insert(pointer.to_owned());
            }
            "::serde_json::Value"
        };
        writeln!(out, "impl<'de> ::serde::Deserialize<'de> for {name} {{\n    fn deserialize<D: ::serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let value = <{value_type} as ::serde::Deserialize>::deserialize(deserializer)?;").expect("String write");
        for (index, ty) in types.iter().enumerate() {
            let decode = if raw {
                format!("::serde_json::from_str::<{ty}>(value.get())")
            } else {
                format!("::serde_json::from_value::<{ty}>(value.clone())")
            };
            writeln!(out, "        if let Ok(decoded) = {decode} {{\n            return Ok(Self::V{index}(decoded));\n        }}").expect("String write");
        }
        out.push_str("        Err(::serde::de::Error::custom(\"no structurally decodable union alternative\"))\n    }\n}\n");
    }

    fn ty(&mut self, node: &Node) -> String {
        if self.plan.binary64.contains(&node.pointer) {
            return "EssBinary64".to_owned();
        }
        match &node.shape {
            Shape::Json => {
                self.exact.insert(node.pointer.clone());
                "::serde_json::Value".to_owned()
            }
            Shape::Never => "EssNever".to_owned(),
            Shape::Null => "()".to_owned(),
            Shape::Boolean => "bool".to_owned(),
            Shape::String => "::std::string::String".to_owned(),
            Shape::Timestamp => "EssTimestamp".to_owned(),
            Shape::Number | Shape::Integer => {
                self.exact.insert(node.pointer.clone());
                "::serde_json::Number".to_owned()
            }
            Shape::SizedInteger(IntegerWidth::I32) => "i32".to_owned(),
            Shape::SizedInteger(IntegerWidth::I64) => "i64".to_owned(),
            Shape::Ref(name) => format!("::std::boxed::Box<{}>", self.plan.names[name]),
            Shape::Array { prefix, items, .. } if prefix.is_empty() => {
                format!("::std::vec::Vec<{}>", self.ty(items))
            }
            Shape::Union { variants, .. } if nullable(variants).is_some() => {
                format!(
                    "::std::option::Option<{}>",
                    self.ty(nullable(variants).expect("nullable union"))
                )
            }
            _ => self.anonymous(node),
        }
    }

    fn anonymous(&mut self, node: &Node) -> String {
        let kind = match &node.shape {
            Shape::Object { .. } => "object",
            Shape::Array { .. } => "array",
            Shape::Union { .. } => "union",
            Shape::Intersection(_) => "intersection",
            Shape::Literal(_) => "literal",
            _ => "scalar",
        };
        let identity = format!("{}#{kind}", node.pointer);
        if let Some(name) = self.anonymous.get(&identity) {
            return name.clone();
        }
        let digest = crate::bundle::source_digest(&identity);
        let hashed = format!("EssShape{}", &digest[..16]);
        let name = self
            .plan
            .positional_name(&node.pointer)
            .filter(|positional| !self.allocated.contains(positional))
            .unwrap_or(hashed);
        if !self.allocated.insert(name.clone()) {
            self.errors.insert(finding(
                &node.pointer,
                "rust_declaration_collision",
                "anonymous declaration collides with an allocated native name",
            ));
            return "EssNever".to_owned();
        }
        self.anonymous.insert(identity, name.clone());
        self.named(&name, node);
        name
    }
}

/// Whether `node` can hold a JSON number at any depth, references followed: a `Number`, an
/// `Integer`, a native-width integer or unrestricted JSON (beyond10x/ess#483).
fn holds_number(plan: &Plan, node: &Node) -> bool {
    let mut pending = vec![node];
    let mut followed = BTreeSet::new();
    while let Some(node) = pending.pop() {
        match &node.shape {
            Shape::Json | Shape::Number | Shape::Integer | Shape::SizedInteger(_) => return true,
            Shape::Ref(name) => {
                if followed.insert(name) {
                    pending.push(&plan.definitions[name]);
                }
            }
            _ => pending.extend(children(node)),
        }
    }
    false
}

fn field_name(wire: &str) -> String {
    let mut result = String::new();
    let mut lower = false;
    for c in wire.chars() {
        if !c.is_ascii_alphanumeric() && c != '_' {
            if !result.ends_with('_') {
                result.push('_');
            }
            lower = false;
        } else {
            if c.is_ascii_uppercase() && lower {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
            lower = c.is_ascii_lowercase() || c.is_ascii_digit();
        }
    }
    let name = result.trim_matches('_');
    match name {
        "self" | "super" | "crate" => format!("{name}_value"),
        "as" | "async" | "await" | "break" | "const" | "continue" | "dyn" | "else" | "enum"
        | "extern" | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match"
        | "mod" | "move" | "mut" | "pub" | "ref" | "return" | "static" | "struct" | "trait"
        | "true" | "type" | "unsafe" | "use" | "where" | "while" | "abstract" | "become"
        | "box" | "do" | "final" | "macro" | "override" | "priv" | "typeof" | "unsized"
        | "virtual" | "yield" | "try" | "gen" => format!("r#{name}"),
        _ => name.to_owned(),
    }
}

pub(super) fn package_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name.as_bytes()[0].is_ascii_lowercase()
        && name
            .bytes()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == b'_' || c == b'-')
        && ![
            "self",
            "super",
            "crate",
            "std",
            "core",
            "alloc",
            "serde",
            "serde_json",
        ]
        .contains(&name)
}

/// One accessor per typed variant attribute of the enum `name` (`ess/23`, beyond10x/ess#450),
/// answering each variant's value: `bool`, `i64`, or the text — a `Decimal` as its decimal string —
/// and `Option` of these where a variant may leave the attribute unfilled.
fn accessors(
    output: &mut String,
    name: &str,
    values: &BTreeSet<String>,
    attributes: &[super::EnumAttribute],
) {
    writeln!(output, "\nimpl {name} {{").expect("String write");
    for attribute in attributes {
        let ty = match attribute.kind.as_str() {
            "boolean" => "bool",
            "integer" => "i64",
            _ => "&'static str",
        };
        let ty = if attribute.optional {
            format!("Option<{ty}>")
        } else {
            ty.to_owned()
        };
        writeln!(
            output,
            "    /// The `{}` each variant declares.\n    pub fn {}(&self) -> {ty} {{\n        match self {{",
            attribute.name,
            field_name(&attribute.name)
        )
        .expect("String write");
        for (index, wire) in values.iter().enumerate() {
            let value = attribute.values.get(wire).map(|value| match value {
                serde_json::Value::String(text) => format!("{text:?}"),
                other => other.to_string(),
            });
            let value = match (value, attribute.optional) {
                (Some(value), true) => format!("Some({value})"),
                (None, _) => "None".to_owned(),
                (Some(value), false) => value,
            };
            writeln!(output, "            Self::V{index} => {value},").expect("String write");
        }
        output.push_str("        }\n    }\n");
    }
    output.push_str("}\n");
}
