//! Structural TypeScript emission from the shared, checked type plan.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use serde_json::Value;

use super::{finding, Finding, Node, Plan, Realization, Shape, TargetConfiguration, UnionMode};

pub(super) fn emit(plan: &Plan) -> Realization {
    let mut report = plan.report(TargetConfiguration::Typescript);
    report.obligations.insert(finding("/", "typescript_compiler_options", "use strict and exactOptionalPropertyTypes; these declarations do not validate runtime JSON"));
    let mut output = format!(
        "// @generated by ESS {}; do not edit.\n// Source SHA-256: {}\n// {}\n// Runtime validation and target limitations: types-report.json.\n\n",
        env!("CARGO_PKG_VERSION"), plan.source_digest, plan.input_comment()
    );
    output.push_str("export type EssJsonValue = null | boolean | number | string | EssJsonValue[] | { [key: string]: EssJsonValue };\n\n");
    for (name, node) in &plan.definitions {
        let rendered = render(node, plan, &mut report.obligations);
        writeln!(output, "export type {} = {rendered};\n", plan.names[name]).expect("String write");
    }
    Realization {
        declarations: output,
        report,
        supporting: BTreeMap::new(),
    }
}

fn render(node: &Node, plan: &Plan, obligations: &mut BTreeSet<Finding>) -> String {
    match &node.shape {
        Shape::Json => {
            obligations.insert(finding(&node.pointer, "json_number_precision", "TypeScript number cannot retain arbitrary JSON numeric precision; validate representability before decoding"));
            "EssJsonValue".to_owned()
        }
        Shape::Never => "never".to_owned(),
        Shape::Null => "null".to_owned(),
        Shape::Boolean => "boolean".to_owned(),
        Shape::String => "string".to_owned(),
        Shape::Number | Shape::Integer => {
            obligations.insert(finding(&node.pointer, "json_number_precision", "TypeScript number cannot retain arbitrary JSON numeric precision; validate representability before decoding"));
            if matches!(node.shape, Shape::Integer) {
                obligations.insert(finding(
                    &node.pointer,
                    "integer",
                    "TypeScript number does not enforce integrality",
                ));
            }
            "number".to_owned()
        }
        Shape::Literal(value) => literal(value, &node.pointer, obligations),
        Shape::Ref(name) => plan.names[name].clone(),
        Shape::Union { mode, variants } => {
            if matches!(mode, UnionMode::OneOf) {
                obligations.insert(finding(&node.pointer, "oneOf", "a TypeScript union is inclusive; validate exclusive branch membership against the source schema"));
            }
            joined(variants, " | ", plan, obligations)
        }
        Shape::Intersection(terms) => joined(terms, " & ", plan, obligations),
        Shape::Object { fields, additional } => {
            let mut output = String::from("{\n");
            let mut known = BTreeSet::new();
            for (name, field) in fields {
                let rendered = render(&field.value, plan, obligations);
                known.insert(rendered.clone());
                let optional = if field.required { "" } else { "?" };
                writeln!(
                    output,
                    "  {}{optional}: {rendered};",
                    serde_json::to_string(name).expect("JSON key")
                )
                .expect("String write");
            }
            output.push('}');
            if matches!(additional.shape, Shape::Never) {
                obligations.insert(finding(&node.pointer, "closed_object", "TypeScript structural assignability does not enforce exact object keys; validate additionalProperties at runtime"));
                output
            } else {
                let extra = render(additional, plan, obligations);
                if !fields.is_empty() && !matches!(additional.shape, Shape::Json) {
                    obligations.insert(finding(&node.pointer, "additional_property_index", "TypeScript cannot exclude named keys from a string index; extra keys admit the union of named and additional value types until schema validation"));
                    known.insert(extra);
                    format!(
                        "({output} & {{ [key: string]: {}; }})",
                        known.into_iter().collect::<Vec<_>>().join(" | ")
                    )
                } else {
                    format!("({output} & {{ [key: string]: {extra}; }})")
                }
            }
        }
        Shape::Array {
            prefix,
            items,
            minimum,
            maximum,
        } => {
            if maximum.is_some_and(|maximum| maximum < *minimum) {
                return "never".to_owned();
            }
            if *maximum == Some(0) {
                return "[]".to_owned();
            }
            if prefix.is_empty() {
                return format!("({})[]", render(items, plan, obligations));
            }
            let mut slots = Vec::new();
            for (index, entry) in prefix.iter().enumerate() {
                if maximum.is_some_and(|maximum| index as u64 >= maximum) {
                    break;
                }
                let optional = if (index as u64) < *minimum { "" } else { "?" };
                slots.push(format!("({}){optional}", render(entry, plan, obligations)));
            }
            if matches!(items.shape, Shape::Never) {
                if *minimum > prefix.len() as u64 {
                    return "never".to_owned();
                }
            } else if maximum.is_none_or(|maximum| maximum > prefix.len() as u64) {
                slots.push(format!("...({})[]", render(items, plan, obligations)));
            }
            format!("[{}]", slots.join(", "))
        }
    }
}

fn joined(
    nodes: &[Node],
    separator: &str,
    plan: &Plan,
    obligations: &mut BTreeSet<Finding>,
) -> String {
    format!(
        "({})",
        nodes
            .iter()
            .map(|node| render(node, plan, obligations))
            .collect::<Vec<_>>()
            .join(separator)
    )
}

fn literal(value: &Value, pointer: &str, obligations: &mut BTreeSet<Finding>) -> String {
    match value {
        Value::Array(values) => format!(
            "[{}]",
            values
                .iter()
                .map(|value| literal(value, pointer, obligations))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        Value::Object(values) => {
            obligations.insert(finding(
                pointer,
                "literal_object_closure",
                "validate exact literal object membership against the source schema",
            ));
            format!(
                "{{ {} }}",
                values
                    .iter()
                    .map(|(name, value)| format!(
                        "{}: {};",
                        serde_json::to_string(name).expect("JSON key"),
                        literal(value, pointer, obligations)
                    ))
                    .collect::<Vec<_>>()
                    .join(" ")
            )
        }
        Value::Number(_) => {
            obligations.insert(finding(
                pointer,
                "numeric_literal_precision",
                "validate that the numeric literal is exactly representable by TypeScript number",
            ));
            value.to_string()
        }
        _ => value.to_string(),
    }
}
